libstdc++: __gnu_debug::basic_string< _CharT, _Traits, _Allocator > Class Template Reference
__gnu_debug::basic_string< _CharT, _Traits, _Allocator > Class Template Reference
Public Types
typedef _Allocator allocator_type
typedef
__gnu_debug::_Safe_iterator
< typename
_Base::const_iterator,
basic_string > const_iterator
typedef _Base::const_pointer const_pointer
typedef _Base::const_reference const_reference
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef _Base::difference_type difference_type
typedef
__gnu_debug::_Safe_iterator
< typename _Base::iterator,
basic_string > iterator
typedef _Base::pointer pointer
typedef _Base::reference reference
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef _Base::size_type size_type
typedef _Traits traits_type
typedef _Traits::char_type value_type
Public Member Functions
basic_string (const _Allocator &__a=_Allocator())
basic_string (const _Base &__base)
basic_string (const basic_string &__str)
basic_string (const basic_string &__str, size_type __pos, size_type __n=_Base::npos, const _Allocator &__a=_Allocator())
basic_string (const _CharT *__s, size_type __n, const _Allocator &__a=_Allocator())
basic_string (const _CharT *__s, const _Allocator &__a=_Allocator())
basic_string (size_type __n, _CharT __c, const _Allocator &__a=_Allocator())
template<typename _InputIterator > basic_string (_InputIterator __begin, _InputIterator __end, const _Allocator &__a=_Allocator())
basic_string (basic_string &&__str) noexcept
basic_string (std::initializer_list< _CharT > __l, const _Allocator &__a=_Allocator())
~basic_string () _GLIBCXX_NOEXCEPT
void _M_attach (_Safe_iterator_base *__it, bool __constant)
void _M_attach_single (_Safe_iterator_base *__it, bool __constant) throw ()
_Base & _M_base () _GLIBCXX_NOEXCEPT
const _Base & _M_base () const _GLIBCXX_NOEXCEPT
void _M_detach (_Safe_iterator_base *__it)
void _M_detach_single (_Safe_iterator_base *__it) throw ()
void _M_invalidate_all () const
void _M_invalidate_if (_Predicate __pred)
void _M_transfer_from_if (_Safe_sequence &__from, _Predicate __pred)
basic_string & append (const basic_string &__str)
basic_string & append (const basic_string &__str, size_type __pos, size_type __n)
basic_string & append (const _CharT *__s, size_type __n)
basic_string & append (const _CharT *__s)
basic_string & append (size_type __n, _CharT __c)
template<typename _InputIterator > basic_string & append (_InputIterator __first, _InputIterator __last)
basic_string & append (const basic_string &__str)
basic_string & append (const basic_string &__str, size_type __pos, size_type __n)
basic_string & append (initializer_list< _CharT > __l)
basic_string & assign (const basic_string &__x)
basic_string & assign (basic_string &&__x)
basic_string & assign (const basic_string &__str, size_type __pos, size_type __n)
basic_string & assign (const _CharT *__s, size_type __n)
basic_string & assign (const _CharT *__s)
basic_string & assign (size_type __n, _CharT __c)
template<typename _InputIterator > basic_string & assign (_InputIterator __first, _InputIterator __last)
basic_string & assign (std::initializer_list< _CharT > __l)
basic_string & assign (const basic_string &__str)
basic_string & assign (basic_string &&__str)
basic_string & assign (const basic_string &__str, size_type __pos, size_type __n)
const_reference at (size_type __n) const
reference at (size_type __n)
reference back ()
const_reference back () const
iterator begin () _GLIBCXX_NOEXCEPT
const_iterator begin () const _GLIBCXX_NOEXCEPT
const _CharT * c_str () const _GLIBCXX_NOEXCEPT
size_type capacity () const _GLIBCXX_NOEXCEPT
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () _GLIBCXX_NOEXCEPT
int compare (const basic_string &__str) const
int compare (size_type __pos1, size_type __n1, const basic_string &__str) const
int compare (size_type __pos1, size_type __n1, const basic_string &__str, size_type __pos2, size_type __n2) const
int compare (const _CharT *__s) const
int compare (size_type __pos1, size_type __n1, const _CharT *__s) const
int compare (size_type __pos1, size_type __n1, const _CharT *__s, size_type __n2) const
int compare (const basic_string &__str) const
int compare (size_type __pos, size_type __n, const basic_string &__str) const
int compare (size_type __pos1, size_type __n1, const basic_string &__str, size_type __pos2, size_type __n2) const
size_type copy (_CharT *__s, size_type __n, size_type __pos=0) const
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
const _CharT * data () const _GLIBCXX_NOEXCEPT
bool empty () const _GLIBCXX_NOEXCEPT
iterator end () _GLIBCXX_NOEXCEPT
const_iterator end () const _GLIBCXX_NOEXCEPT
basic_string & erase (size_type __pos=0, size_type __n=_Base::npos)
iterator erase (iterator __position)
iterator erase (iterator __first, iterator __last)
iterator erase (iterator __position)
iterator erase (iterator __first, iterator __last)
size_type find (const basic_string &__str, size_type __pos=0) const _GLIBCXX_NOEXCEPT
size_type find (const _CharT *__s, size_type __pos, size_type __n) const
size_type find (const _CharT *__s, size_type __pos=0) const
size_type find (_CharT __c, size_type __pos=0) const _GLIBCXX_NOEXCEPT
size_type find (const basic_string &__str, size_type __pos=0) const _GLIBCXX_NOEXCEPT
size_type find_first_not_of (const basic_string &__str, size_type __pos=0) const _GLIBCXX_NOEXCEPT
size_type find_first_not_of (const _CharT *__s, size_type __pos, size_type __n) const
size_type find_first_not_of (const _CharT *__s, size_type __pos=0) const
size_type find_first_not_of (_CharT __c, size_type __pos=0) const _GLIBCXX_NOEXCEPT
size_type find_first_not_of (const basic_string &__str, size_type __pos=0) const _GLIBCXX_NOEXCEPT
size_type find_first_of (const basic_string &__str, size_type __pos=0) const _GLIBCXX_NOEXCEPT
size_type find_first_of (const _CharT *__s, size_type __pos, size_type __n) const
size_type find_first_of (const _CharT *__s, size_type __pos=0) const
size_type find_first_of (_CharT __c, size_type __pos=0) const _GLIBCXX_NOEXCEPT
size_type find_first_of (const basic_string &__str, size_type __pos=0) const _GLIBCXX_NOEXCEPT
size_type find_last_not_of (const basic_string &__str, size_type __pos=_Base::npos) const _GLIBCXX_NOEXCEPT
size_type find_last_not_of (const _CharT *__s, size_type __pos, size_type __n) const
size_type find_last_not_of (const _CharT *__s, size_type __pos=_Base::npos) const
size_type find_last_not_of (_CharT __c, size_type __pos=_Base::npos) const _GLIBCXX_NOEXCEPT
size_type find_last_not_of (const basic_string &__str, size_type __pos=npos) const _GLIBCXX_NOEXCEPT
size_type find_last_of (const basic_string &__str, size_type __pos=_Base::npos) const _GLIBCXX_NOEXCEPT
size_type find_last_of (const _CharT *__s, size_type __pos, size_type __n) const
size_type find_last_of (const _CharT *__s, size_type __pos=_Base::npos) const
size_type find_last_of (_CharT __c, size_type __pos=_Base::npos) const _GLIBCXX_NOEXCEPT
size_type find_last_of (const basic_string &__str, size_type __pos=npos) const _GLIBCXX_NOEXCEPT
reference front ()
const_reference front () const
allocator_type get_allocator () const _GLIBCXX_NOEXCEPT
basic_string & insert (size_type __pos1, const basic_string &__str)
basic_string & insert (size_type __pos1, const basic_string &__str, size_type __pos2, size_type __n)
basic_string & insert (size_type __pos, const _CharT *__s, size_type __n)
basic_string & insert (size_type __pos, const _CharT *__s)
basic_string & insert (size_type __pos, size_type __n, _CharT __c)
iterator insert (iterator __p, _CharT __c)
void insert (iterator __p, size_type __n, _CharT __c)
template<typename _InputIterator > void insert (iterator __p, _InputIterator __first, _InputIterator __last)
void insert (iterator __p, std::initializer_list< _CharT > __l)
void insert (iterator __p, size_type __n, _CharT __c)
void insert (iterator __p, _InputIterator __beg, _InputIterator __end)
void insert (iterator __p, initializer_list< _CharT > __l)
basic_string & insert (size_type __pos1, const basic_string &__str)
basic_string & insert (size_type __pos1, const basic_string &__str, size_type __pos2, size_type __n)
iterator insert (iterator __p, _CharT __c)
size_type length () const _GLIBCXX_NOEXCEPT
size_type max_size () const _GLIBCXX_NOEXCEPT
basic_string & operator+= (const basic_string &__str)
basic_string & operator+= (const _CharT *__s)
basic_string & operator+= (_CharT __c)
basic_string & operator+= (std::initializer_list< _CharT > __l)
basic_string & operator+= (const basic_string &__str)
basic_string & operator= (const basic_string &__str)
basic_string & operator= (const _CharT *__s)
basic_string & operator= (_CharT __c)
basic_string & operator= (basic_string &&__str)
basic_string & operator= (std::initializer_list< _CharT > __l)
const_reference operator[] (size_type __pos) const
reference operator[] (size_type __pos)
void pop_back ()
void push_back (_CharT __c)
reverse_iterator rbegin () _GLIBCXX_NOEXCEPT
const_reverse_iterator rbegin () const _GLIBCXX_NOEXCEPT
reverse_iterator rend () _GLIBCXX_NOEXCEPT
const_reverse_iterator rend () const _GLIBCXX_NOEXCEPT
basic_string & replace (size_type __pos1, size_type __n1, const basic_string &__str)
basic_string & replace (size_type __pos1, size_type __n1, const basic_string &__str, size_type __pos2, size_type __n2)
basic_string & replace (size_type __pos, size_type __n1, const _CharT *__s, size_type __n2)
basic_string & replace (size_type __pos, size_type __n1, const _CharT *__s)
basic_string & replace (size_type __pos, size_type __n1, size_type __n2, _CharT __c)
basic_string & replace (iterator __i1, iterator __i2, const basic_string &__str)
basic_string & replace (iterator __i1, iterator __i2, const _CharT *__s, size_type __n)
basic_string & replace (iterator __i1, iterator __i2, const _CharT *__s)
basic_string & replace (iterator __i1, iterator __i2, size_type __n, _CharT __c)
template<typename _InputIterator > basic_string & replace (iterator __i1, iterator __i2, _InputIterator __j1, _InputIterator __j2)
basic_string & replace (iterator __i1, iterator __i2, std::initializer_list< _CharT > __l)
basic_string & replace (size_type __pos, size_type __n, const basic_string &__str)
basic_string & replace (size_type __pos1, size_type __n1, const basic_string &__str, size_type __pos2, size_type __n2)
basic_string & replace (iterator __i1, iterator __i2, const basic_string &__str)
basic_string & replace (iterator __i1, iterator __i2, const _CharT *__s, size_type __n)
basic_string & replace (iterator __i1, iterator __i2, const _CharT *__s)
basic_string & replace (iterator __i1, iterator __i2, size_type __n, _CharT __c)
basic_string & replace (iterator __i1, iterator __i2, _InputIterator __k1, _InputIterator __k2)
basic_string & replace (iterator __i1, iterator __i2, _CharT *__k1, _CharT *__k2)
basic_string & replace (iterator __i1, iterator __i2, const _CharT *__k1, const _CharT *__k2)
basic_string & replace (iterator __i1, iterator __i2, iterator __k1, iterator __k2)
basic_string & replace (iterator __i1, iterator __i2, initializer_list< _CharT > __l)
void reserve (size_type __res_arg=0)
void resize (size_type __n, _CharT __c)
void resize (size_type __n)
size_type rfind (const basic_string &__str, size_type __pos=_Base::npos) const _GLIBCXX_NOEXCEPT
size_type rfind (const _CharT *__s, size_type __pos, size_type __n) const
size_type rfind (const _CharT *__s, size_type __pos=_Base::npos) const
size_type rfind (_CharT __c, size_type __pos=_Base::npos) const _GLIBCXX_NOEXCEPT
size_type rfind (const basic_string &__str, size_type __pos=npos) const _GLIBCXX_NOEXCEPT
void shrink_to_fit ()
size_type size () const _GLIBCXX_NOEXCEPT
basic_string substr (size_type __pos=0, size_type __n=_Base::npos) const
void swap (basic_string< _CharT, _Traits, _Allocator > &__x)
void swap (basic_string &__s)
Public Attributes
_Safe_iterator_base * _M_const_iterators
_Safe_iterator_base * _M_iterators
unsigned int _M_version
Static Public Attributes
static const size_type npos
Protected Member Functions
void _M_detach_all ()
void _M_detach_singular ()
__gnu_cxx::__mutex & _M_get_mutex () throw ()
void _M_revalidate_singular ()
void _M_swap (_Safe_sequence_base &__x)
Detailed Description
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>>
class __gnu_debug::basic_string< _CharT, _Traits, _Allocator >
Class std::basic_string with safety/checking/debug instrumentation.
Definition at line 42 of file debug/string.
Constructor & Destructor Documentation
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::basic_string (const _Allocator & __a = _Allocator()) [inline, explicit]
Construct an empty string using allocator a.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 73 of file debug/string.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::basic_string (const _CharT * __s, size_type __n, const _Allocator & __a = _Allocator()) [inline]
Construct string initialized by a character array.
Parameters:
__s Source character array.
__n Number of characters to copy.
__a Allocator to use (default is default allocator).
NB: __s must have at least __n characters, '\0' has no special meaning.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 94 of file debug/string.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::basic_string (const _CharT * __s, const _Allocator & __a = _Allocator()) [inline]
Construct string as copy of a C string.
Parameters:
__s Source C string.
__a Allocator to use (default is default allocator).
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 99 of file debug/string.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::basic_string (size_type __n, _CharT __c, const _Allocator & __a = _Allocator()) [inline]
Construct string as multiple characters.
Parameters:
__n Number of characters.
__c Character to use.
__a Allocator to use (default is default allocator).
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 103 of file debug/string.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> template<typename _InputIterator > __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::basic_string (_InputIterator __beg, _InputIterator __end, const _Allocator & __a = _Allocator()) [inline]
Construct string as copy of a range.
Parameters:
__beg Start of range.
__end End of range.
__a Allocator to use (default is default allocator).
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 109 of file debug/string.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::basic_string (std::initializer_list< _CharT > __l, const _Allocator & __a = _Allocator()) [inline]
Construct string from an initializer list.
Parameters:
__l std::initializer_list of characters.
__a Allocator to use (default is default allocator).
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 121 of file debug/string.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::~basic_string () [inline]
Destroy the string instance.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 127 of file debug/string.
Member Function Documentation
void __gnu_debug::_Safe_sequence_base::_M_attach (_Safe_iterator_base * __it, bool __constant) [inherited]
Attach an iterator to this sequence.
void __gnu_debug::_Safe_sequence_base::_M_attach_single (_Safe_iterator_base * __it, bool __constant) throw () [inherited]
Likewise but not thread safe.
void __gnu_debug::_Safe_sequence_base::_M_detach (_Safe_iterator_base * __it) [inherited]
Detach an iterator from this sequence
void __gnu_debug::_Safe_sequence_base::_M_detach_all () [protected, inherited]
Detach all iterators, leaving them singular.
Reimplemented in __gnu_debug::_Safe_unordered_container_base.
Referenced by __gnu_debug::_Safe_sequence_base::~_Safe_sequence_base().
void __gnu_debug::_Safe_sequence_base::_M_detach_single (_Safe_iterator_base * __it) throw () [inherited]
Likewise but not thread safe.
void __gnu_debug::_Safe_sequence_base::_M_detach_singular () [protected, inherited]
Detach all singular iterators.
Postcondition:
for all iterators i attached to this sequence, i->_M_version == _M_version.
__gnu_cxx::__mutex& __gnu_debug::_Safe_sequence_base::_M_get_mutex () throw () [protected, inherited]
For use in _Safe_sequence.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
void __gnu_debug::_Safe_sequence_base::_M_invalidate_all () const [inline, inherited]
Invalidates all iterators.
Definition at line 234 of file safe_base.h.
References __gnu_debug::_Safe_sequence_base::_M_version.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::append(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::assign(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::c_str(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::clear(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::data(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::erase(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::insert(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator+=(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator=(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::pop_back(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::push_back(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::replace(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::resize(), and __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::shrink_to_fit().
void __gnu_debug::_Safe_sequence< basic_string< _CharT, _Traits, _Allocator > >::_M_invalidate_if (_Predicate __pred) [inherited]
Invalidates all iterators x that reference this sequence, are not singular, and for which __pred(x) returns true. __pred will be invoked with the normal iterators nested in the safe ones.
void __gnu_debug::_Safe_sequence_base::_M_revalidate_singular () [protected, inherited]
Revalidates all attached singular iterators. This method may be used to validate iterators that were invalidated before (but for some reason, such as an exception, need to become valid again).
void __gnu_debug::_Safe_sequence_base::_M_swap (_Safe_sequence_base & __x) [protected, inherited]
Swap this sequence with the given sequence. This operation also swaps ownership of the iterators, so that when the operation is complete all iterators that originally referenced one container now reference the other container.
void __gnu_debug::_Safe_sequence< basic_string< _CharT, _Traits, _Allocator > >::_M_transfer_from_if (_Safe_sequence< basic_string< _CharT, _Traits, _Allocator > > & __from, _Predicate __pred) [inherited]
Transfers all iterators x that reference from sequence, are not singular, and for which __pred(x) returns true. __pred will be invoked with the normal iterators nested in the safe ones.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::append (const _CharT * __s, size_type __n) [inline]
Append a C substring.
Parameters:
__s The C string to append.
__n The number of characters to append.
Returns:
Reference to this string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 356 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::append().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::append (const _CharT * __s) [inline]
Append a C string.
Parameters:
__s The C string to append.
Returns:
Reference to this string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 365 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::append().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::append (size_type __n, _CharT __c) [inline]
Append multiple characters.
Parameters:
__n The number of characters to append.
__c The character to use.
Returns:
Reference to this string.
Appends __n copies of __c to this string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 374 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::append().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> template<typename _InputIterator > basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::append (_InputIterator __first, _InputIterator __last) [inline]
Append a range of characters.
Parameters:
__first Iterator referencing the first character to append.
__last Iterator marking the end of the range.
Returns:
Reference to this string.
Appends characters in the range [__first,__last) to this string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 383 of file debug/string.
References __gnu_debug::__base(), __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::append().
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::append (const basic_string< _CharT, _Traits, _Allocator > & __str) [inherited]
Append a string to this string.
Parameters:
__str The string to append.
Returns:
Reference to this string.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::append().
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::append (const basic_string< _CharT, _Traits, _Allocator > & __str, size_type __pos, size_type __n) [inherited]
Append a substring.
Parameters:
__str The string to append.
__pos Index of the first character of str to append.
__n The number of characters to append.
Returns:
Reference to this string.
Exceptions:
std::out_of_range if __pos is not a valid index.
This function appends __n characters from __str starting at __pos to this string. If __n is is larger than the number of available characters in __str, the remainder of __str is appended.
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::append (initializer_list< _CharT > __l) [inline, inherited]
Append an initializer_list of characters.
Parameters:
__l The initializer_list of characters to append.
Returns:
Reference to this string.
Definition at line 1027 of file basic_string.h.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::assign (const _CharT * __s, size_type __n) [inline]
Set value to a C substring.
Parameters:
__s The C string to use.
__n Number of characters to use.
Returns:
Reference to this string.
This function sets the value of this string to the first __n characters of __s. If __n is is larger than the number of available characters in __s, the remainder of __s is used.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 428 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::assign().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::assign (const _CharT * __s) [inline]
Set value to contents of a C string.
Parameters:
__s The C string to use.
Returns:
Reference to this string.
This function sets the value of this string to the value of __s. The data is copied, so there is no dependence on __s once the function returns.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 437 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::assign().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::assign (size_type __n, _CharT __c) [inline]
Set value to multiple characters.
Parameters:
__n Length of the resulting string.
__c The character to use.
Returns:
Reference to this string.
This function sets the value of this string to __n copies of character __c.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 446 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::assign().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> template<typename _InputIterator > basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::assign (_InputIterator __first, _InputIterator __last) [inline]
Set value to a range of characters.
Parameters:
__first Iterator referencing the first character to append.
__last Iterator marking the end of the range.
Returns:
Reference to this string.
Sets value of string to characters in the range [__first,__last).
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 455 of file debug/string.
References __gnu_debug::__base(), __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::assign().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::assign (std::initializer_list< _CharT > __l) [inline]
Set value to an initializer_list of characters.
Parameters:
__l The initializer_list of characters to assign.
Returns:
Reference to this string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 466 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::assign().
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::assign (const basic_string< _CharT, _Traits, _Allocator > & __str) [inherited]
Set value to contents of another string.
Parameters:
__str Source string to use.
Returns:
Reference to this string.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::assign().
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::assign (basic_string< _CharT, _Traits, _Allocator > && __str) [inline, inherited]
Set value to contents of another string.
Parameters:
__str Source string to use.
Returns:
Reference to this string.
This function sets this string to the exact contents of __str. __str is a valid, but unspecified string.
Definition at line 1076 of file basic_string.h.
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::assign (const basic_string< _CharT, _Traits, _Allocator > & __str, size_type __pos, size_type __n) [inline, inherited]
Set value to a substring of a string.
Parameters:
__str The string to use.
__pos Index of the first character of str.
__n Number of characters to use.
Returns:
Reference to this string.
Exceptions:
std::out_of_range if pos is not a valid index.
This function sets this string to the substring of __str consisting of __n characters at __pos. If __n is is larger than the number of available characters in __str, the remainder of __str is used.
Definition at line 1097 of file basic_string.h.
const_reference std::basic_string< _CharT, _Traits, _Allocator >::at (size_type __n) const [inline, inherited]
Provides access to the data contained in the string.
Parameters:
__n The index of the character to access.
Returns:
Read-only (const) reference to the character.
Exceptions:
std::out_of_range If n is an invalid index.
This function provides for safer data access. The parameter is first checked that it is in the range of the string. The function throws out_of_range if the check fails.
Definition at line 861 of file basic_string.h.
reference std::basic_string< _CharT, _Traits, _Allocator >::at (size_type __n) [inline, inherited]
Provides access to the data contained in the string.
Parameters:
__n The index of the character to access.
Returns:
Read/write reference to the character.
Exceptions:
std::out_of_range If n is an invalid index.
This function provides for safer data access. The parameter is first checked that it is in the range of the string. The function throws out_of_range if the check fails. Success results in unsharing the string.
Definition at line 880 of file basic_string.h.
reference std::basic_string< _CharT, _Traits, _Allocator >::back () [inline, inherited]
Returns a read/write reference to the data at the last element of the string.
Definition at line 910 of file basic_string.h.
const_reference std::basic_string< _CharT, _Traits, _Allocator >::back () const [inline, inherited]
Returns a read-only (constant) reference to the data at the last element of the string.
Definition at line 918 of file basic_string.h.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> iterator __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::begin () [inline]
Returns a read/write iterator that points to the first character in the string. Unshares the string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 174 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::begin().
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::crend(), and __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::rend().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> const_iterator __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::begin () const [inline]
Returns a read-only (constant) iterator that points to the first character in the string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 178 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::begin().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> const _CharT* __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::c_str () const [inline]
Return const pointer to null-terminated contents.
This is a handle to internal data. Do not modify or dire things may happen.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 716 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::c_str().
size_type std::basic_string< _CharT, _Traits, _Allocator >::capacity () const [inline, inherited]
Returns the total number of characters that the string can hold before needing to allocate more memory.
Definition at line 773 of file basic_string.h.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::shrink_to_fit().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> const_iterator __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::cbegin () const [inline]
Returns a read-only (constant) iterator that points to the first character in the string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 207 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::begin().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> const_iterator __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::cend () const [inline]
Returns a read-only (constant) iterator that points one past the last character in the string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 211 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::end().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> void __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::clear () [inline]
Erases the string, making it empty.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 260 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::clear().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> int __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::compare (const _CharT * __s) const [inline]
Compare to a C string.
Parameters:
__s C string to compare against.
Returns:
Integer < 0, 0, or > 0.
Returns an integer < 0 if this string is ordered before __s, 0 if their values are equivalent, or > 0 if this string is ordered after __s. Determines the effective length rlen of the strings to compare as the smallest of size() and the length of a string constructed from __s. The function then compares the two strings by calling traits::compare(data(),s,rlen). If the result of the comparison is nonzero returns it, otherwise the shorter one is ordered first.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 893 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::compare().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> int __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::compare (size_type __pos, size_type __n1, const _CharT * __s) const [inline]
Compare substring to a C string.
Parameters:
__pos Index of first character of substring.
__n1 Number of characters in substring.
__s C string to compare against.
Returns:
Integer < 0, 0, or > 0.
Form the substring of this string from the __n1 characters starting at pos. Returns an integer < 0 if the substring is ordered before __s, 0 if their values are equivalent, or > 0 if the substring is ordered after __s. Determines the effective length rlen of the strings to compare as the smallest of the length of the substring and the length of a string constructed from __s. The function then compares the two string by calling traits::compare(substring.data(),__s,rlen). If the result of the comparison is nonzero returns it, otherwise the shorter one is ordered first.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 902 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::compare().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> int __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::compare (size_type __pos, size_type __n1, const _CharT * __s, size_type __n2) const [inline]
Compare substring against a character array.
Parameters:
__pos Index of first character of substring.
__n1 Number of characters in substring.
__s character array to compare against.
__n2 Number of characters of s.
Returns:
Integer < 0, 0, or > 0.
Form the substring of this string from the __n1 characters starting at __pos. Form a string from the first __n2 characters of __s. Returns an integer < 0 if this substring is ordered before the string from __s, 0 if their values are equivalent, or > 0 if this substring is ordered after the string from __s. Determines the effective length rlen of the strings to compare as the smallest of the length of the substring and __n2. The function then compares the two strings by calling traits::compare(substring.data(),s,rlen). If the result of the comparison is nonzero returns it, otherwise the shorter one is ordered first.
NB: s must have at least n2 characters, '\0' has no special meaning.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 911 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::compare().
int std::basic_string< _CharT, _Traits, _Allocator >::compare (const basic_string< _CharT, _Traits, _Allocator > & __str) const [inline, inherited]
Compare to a string.
Parameters:
__str String to compare against.
Returns:
Integer < 0, 0, or > 0.
Returns an integer < 0 if this string is ordered before __str, 0 if their values are equivalent, or > 0 if this string is ordered after __str. Determines the effective length rlen of the strings to compare as the smallest of size() and str.size(). The function then compares the two strings by calling traits::compare(data(), str.data(),rlen). If the result of the comparison is nonzero returns it, otherwise the shorter one is ordered first.
Definition at line 2222 of file basic_string.h.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::compare().
int std::basic_string< _CharT, _Traits, _Allocator >::compare (size_type __pos, size_type __n, const basic_string< _CharT, _Traits, _Allocator > & __str) const [inherited]
Compare substring to a string.
Parameters:
__pos Index of first character of substring.
__n Number of characters in substring.
__str String to compare against.
Returns:
Integer < 0, 0, or > 0.
Form the substring of this string from the __n characters starting at __pos. Returns an integer < 0 if the substring is ordered before __str, 0 if their values are equivalent, or > 0 if the substring is ordered after __str. Determines the effective length rlen of the strings to compare as the smallest of the length of the substring and __str.size(). The function then compares the two strings by calling traits::compare(substring.data(),str.data(),rlen). If the result of the comparison is nonzero returns it, otherwise the shorter one is ordered first.
int std::basic_string< _CharT, _Traits, _Allocator >::compare (size_type __pos1, size_type __n1, const basic_string< _CharT, _Traits, _Allocator > & __str, size_type __pos2, size_type __n2) const [inherited]
Compare substring to a substring.
Parameters:
__pos1 Index of first character of substring.
__n1 Number of characters in substring.
__str String to compare against.
__pos2 Index of first character of substring of str.
__n2 Number of characters in substring of str.
Returns:
Integer < 0, 0, or > 0.
Form the substring of this string from the __n1 characters starting at __pos1. Form the substring of __str from the __n2 characters starting at __pos2. Returns an integer < 0 if this substring is ordered before the substring of __str, 0 if their values are equivalent, or > 0 if this substring is ordered after the substring of __str. Determines the effective length rlen of the strings to compare as the smallest of the lengths of the substrings. The function then compares the two strings by calling traits::compare(substring.data(),str.substr(pos2,n2).data(),rlen). If the result of the comparison is nonzero returns it, otherwise the shorter one is ordered first.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::copy (_CharT * __s, size_type __n, size_type __pos = 0) const [inline]
Copy substring into C string.
Parameters:
__s C string to copy value into.
__n Number of characters to copy.
__pos Index of first character to copy.
Returns:
Number of characters actually copied
Exceptions:
std::out_of_range If __pos > size().
Copies up to __n characters starting at __pos into the C string __s. If __pos is greater than size(), out_of_range is thrown.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 699 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::copy().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> const_reverse_iterator __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::crbegin () const [inline]
Returns a read-only (constant) reverse iterator that points to the last character in the string. Iteration is done in reverse element order.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 215 of file debug/string.
References __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::end().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> const_reverse_iterator __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::crend () const [inline]
Returns a read-only (constant) reverse iterator that points to one before the first character in the string. Iteration is done in reverse element order.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 219 of file debug/string.
References __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::begin().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> const _CharT* __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::data () const [inline]
Return const pointer to contents.
This is a handle to internal data. Do not modify or dire things may happen.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 724 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::data().
bool std::basic_string< _CharT, _Traits, _Allocator >::empty () const [inline, inherited]
Returns true if the string is empty. Equivalent to *this == "".
Definition at line 808 of file basic_string.h.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> iterator __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::end () [inline]
Returns a read/write iterator that points one past the last character in the string. Unshares the string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 182 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::end().
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::crbegin(), and __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::rbegin().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> const_iterator __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::end () const [inline]
Returns a read-only (constant) iterator that points one past the last character in the string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 186 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::end().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::erase (size_type __pos = 0, size_type __n = _Base::npos) [inline]
Remove characters.
Parameters:
__pos Index of first character to remove (default 0).
__n Number of characters to remove (default remainder).
Returns:
Reference to this string.
Exceptions:
std::out_of_range If pos is beyond the end of this string.
Removes __n characters from this string starting at __pos. The length of the string is reduced by __n. If there are < __n characters to remove, the remainder of the string is truncated. If __p is beyond end of string, out_of_range is thrown. The value of the string doesn't change if an error is thrown.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 555 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::erase().
iterator std::basic_string< _CharT, _Traits, _Allocator >::erase (iterator __position) [inline, inherited]
Remove one character.
Parameters:
__position Iterator referencing the character to remove.
Returns:
iterator referencing same location after removal.
Removes the character at __position from this string. The value of the string doesn't change if an error is thrown.
Definition at line 1375 of file basic_string.h.
iterator std::basic_string< _CharT, _Traits, _Allocator >::erase (iterator __first, iterator __last) [inherited]
Remove a range of characters.
Parameters:
__first Iterator referencing the first character to remove.
__last Iterator referencing the end of the range.
Returns:
Iterator referencing location of first after removal.
Removes the characters in the range [first,last) from this string. The value of the string doesn't change if an error is thrown.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find (const _CharT * __s, size_type __pos, size_type __n) const [inline]
Find position of a C substring.
Parameters:
__s C string to locate.
__pos Index of character to search from.
__n Number of characters from s to search for.
Returns:
Index of start of first occurrence.
Starting from __pos, searches forward for the first __n characters in __s within this string. If found, returns the index where it begins. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 739 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find (const _CharT * __s, size_type __pos = 0) const [inline]
Find position of a C string.
Parameters:
__s C string to locate.
__pos Index of character to search from (default 0).
Returns:
Index of start of first occurrence.
Starting from __pos, searches forward for the value of __s within this string. If found, returns the index where it begins. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 746 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find (_CharT __c, size_type __pos = 0) const [inline]
Find position of a character.
Parameters:
__c Character to locate.
__pos Index of character to search from (default 0).
Returns:
Index of first occurrence.
Starting from __pos, searches forward for __c within this string. If found, returns the index where it was found. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 753 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find().
size_type std::basic_string< _CharT, _Traits, _Allocator >::find (const basic_string< _CharT, _Traits, _Allocator > & __str, size_type __pos = 0) const [inline, inherited]
Find position of a string.
Parameters:
__str String to locate.
__pos Index of character to search from (default 0).
Returns:
Index of start of first occurrence.
Starting from __pos, searches forward for value of __str within this string. If found, returns the index where it begins. If not found, returns npos.
Definition at line 1843 of file basic_string.h.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_first_not_of (const _CharT * __s, size_type __pos, size_type __n) const [inline]
Find position of a character not in C substring.
Parameters:
__s C string containing characters to avoid.
__pos Index of character to search from.
__n Number of characters from __s to consider.
Returns:
Index of first occurrence.
Starting from __pos, searches forward for a character not contained in the first __n characters of __s within this string. If found, returns the index where it was found. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 832 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find_first_not_of().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_first_not_of (const _CharT * __s, size_type __pos = 0) const [inline]
Find position of a character not in C string.
Parameters:
__s C string containing characters to avoid.
__pos Index of character to search from (default 0).
Returns:
Index of first occurrence.
Starting from __pos, searches forward for a character not contained in __s within this string. If found, returns the index where it was found. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 839 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find_first_not_of().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_first_not_of (_CharT __c, size_type __pos = 0) const [inline]
Find position of a different character.
Parameters:
__c Character to avoid.
__pos Index of character to search from (default 0).
Returns:
Index of first occurrence.
Starting from __pos, searches forward for a character other than __c within this string. If found, returns the index where it was found. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 846 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find_first_not_of().
size_type std::basic_string< _CharT, _Traits, _Allocator >::find_first_not_of (const basic_string< _CharT, _Traits, _Allocator > & __str, size_type __pos = 0) const [inline, inherited]
Find position of a character not in string.
Parameters:
__str String containing characters to avoid.
__pos Index of character to search from (default 0).
Returns:
Index of first occurrence.
Starting from __pos, searches forward for a character not contained in __str within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 2076 of file basic_string.h.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_first_not_of().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_first_of (const _CharT * __s, size_type __pos, size_type __n) const [inline]
Find position of a character of C substring.
Parameters:
__s String containing characters to locate.
__pos Index of character to search from.
__n Number of characters from s to search for.
Returns:
Index of first occurrence.
Starting from __pos, searches forward for one of the first __n characters of __s within this string. If found, returns the index where it was found. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 785 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find_first_of().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_first_of (const _CharT * __s, size_type __pos = 0) const [inline]
Find position of a character of C string.
Parameters:
__s String containing characters to locate.
__pos Index of character to search from (default 0).
Returns:
Index of first occurrence.
Starting from __pos, searches forward for one of the characters of __s within this string. If found, returns the index where it was found. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 792 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find_first_of().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_first_of (_CharT __c, size_type __pos = 0) const [inline]
Find position of a character.
Parameters:
__c Character to locate.
__pos Index of character to search from (default 0).
Returns:
Index of first occurrence.
Starting from __pos, searches forward for the character __c within this string. If found, returns the index where it was found. If not found, returns npos.
Note: equivalent to find(__c, __pos).
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 799 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find_first_of().
size_type std::basic_string< _CharT, _Traits, _Allocator >::find_first_of (const basic_string< _CharT, _Traits, _Allocator > & __str, size_type __pos = 0) const [inline, inherited]
Find position of a character of string.
Parameters:
__str String containing characters to locate.
__pos Index of character to search from (default 0).
Returns:
Index of first occurrence.
Starting from __pos, searches forward for one of the characters of __str within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 1949 of file basic_string.h.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_first_of().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_last_not_of (const _CharT * __s, size_type __pos, size_type __n) const [inline]
Find last position of a character not in C substring.
Parameters:
__s C string containing characters to avoid.
__pos Index of character to search back from.
__n Number of characters from s to consider.
Returns:
Index of last occurrence.
Starting from __pos, searches backward for a character not contained in the first __n characters of __s within this string. If found, returns the index where it was found. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 856 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find_last_not_of().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_last_not_of (const _CharT * __s, size_type __pos = _Base::npos) const [inline]
Find last position of a character not in C string.
Parameters:
__s C string containing characters to avoid.
__pos Index of character to search back from (default end).
Returns:
Index of last occurrence.
Starting from __pos, searches backward for a character not contained in __s within this string. If found, returns the index where it was found. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 863 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find_last_not_of().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_last_not_of (_CharT __c, size_type __pos = _Base::npos) const [inline]
Find last position of a different character.
Parameters:
__c Character to avoid.
__pos Index of character to search back from (default end).
Returns:
Index of last occurrence.
Starting from __pos, searches backward for a character other than __c within this string. If found, returns the index where it was found. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 870 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find_last_not_of().
size_type std::basic_string< _CharT, _Traits, _Allocator >::find_last_not_of (const basic_string< _CharT, _Traits, _Allocator > & __str, size_type __pos = npos) const [inline, inherited]
Find last position of a character not in string.
Parameters:
__str String containing characters to avoid.
__pos Index of character to search back from (default end).
Returns:
Index of last occurrence.
Starting from __pos, searches backward for a character not contained in __str within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 2139 of file basic_string.h.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_last_not_of().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_last_of (const _CharT * __s, size_type __pos, size_type __n) const [inline]
Find last position of a character of C substring.
Parameters:
__s C string containing characters to locate.
__pos Index of character to search back from.
__n Number of characters from s to search for.
Returns:
Index of last occurrence.
Starting from __pos, searches backward for one of the first __n characters of __s within this string. If found, returns the index where it was found. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 808 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find_last_of().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_last_of (const _CharT * __s, size_type __pos = _Base::npos) const [inline]
Find last position of a character of C string.
Parameters:
__s C string containing characters to locate.
__pos Index of character to search back from (default end).
Returns:
Index of last occurrence.
Starting from __pos, searches backward for one of the characters of __s within this string. If found, returns the index where it was found. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 815 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find_last_of().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_last_of (_CharT __c, size_type __pos = _Base::npos) const [inline]
Find last position of a character.
Parameters:
__c Character to locate.
__pos Index of character to search back from (default end).
Returns:
Index of last occurrence.
Starting from __pos, searches backward for __c within this string. If found, returns the index where it was found. If not found, returns npos.
Note: equivalent to rfind(__c, __pos).
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 822 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::find_last_of().
size_type std::basic_string< _CharT, _Traits, _Allocator >::find_last_of (const basic_string< _CharT, _Traits, _Allocator > & __str, size_type __pos = npos) const [inline, inherited]
Find last position of a character of string.
Parameters:
__str String containing characters to locate.
__pos Index of character to search back from (default end).
Returns:
Index of last occurrence.
Starting from __pos, searches backward for one of the characters of __str within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 2013 of file basic_string.h.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::find_last_of().
reference std::basic_string< _CharT, _Traits, _Allocator >::front () [inline, inherited]
Returns a read/write reference to the data at the first element of the string.
Definition at line 894 of file basic_string.h.
const_reference std::basic_string< _CharT, _Traits, _Allocator >::front () const [inline, inherited]
Returns a read-only (constant) reference to the data at the first element of the string.
Definition at line 902 of file basic_string.h.
allocator_type std::basic_string< _CharT, _Traits, _Allocator >::get_allocator () const [inline, inherited]
Return copy of allocator used to construct this string.
Definition at line 1814 of file basic_string.h.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::insert (size_type __pos, const _CharT * __s, size_type __n) [inline]
Insert a C substring.
Parameters:
__pos Iterator referencing location in string to insert at.
__s The C string to insert.
__n The number of characters to insert.
Returns:
Reference to this string.
Exceptions:
std::length_error If new length exceeds max_size().
std::out_of_range If __pos is beyond the end of this string.
Inserts the first __n characters of __s starting at __pos. If adding characters causes the length to exceed max_size(), length_error is thrown. If __pos is beyond end(), out_of_range is thrown. The value of the string doesn't change if an error is thrown.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 492 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::insert().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::insert (size_type __pos, const _CharT * __s) [inline]
Insert a C string.
Parameters:
__pos Iterator referencing location in string to insert at.
__s The C string to insert.
Returns:
Reference to this string.
Exceptions:
std::length_error If new length exceeds max_size().
std::out_of_range If pos is beyond the end of this string.
Inserts the first n characters of __s starting at __pos. If adding characters causes the length to exceed max_size(), length_error is thrown. If __pos is beyond end(), out_of_range is thrown. The value of the string doesn't change if an error is thrown.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 501 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::insert().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::insert (size_type __pos, size_type __n, _CharT __c) [inline]
Insert multiple characters.
Parameters:
__pos Index in string to insert at.
__n Number of characters to insert
__c The character to insert.
Returns:
Reference to this string.
Exceptions:
std::length_error If new length exceeds max_size().
std::out_of_range If __pos is beyond the end of this string.
Inserts __n copies of character __c starting at index __pos. If adding characters causes the length to exceed max_size(), length_error is thrown. If __pos > length(), out_of_range is thrown. The value of the string doesn't change if an error is thrown.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 510 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::insert().
void std::basic_string< _CharT, _Traits, _Allocator >::insert (iterator __p, size_type __n, _CharT __c) [inline, inherited]
Insert multiple characters.
Parameters:
__p Iterator referencing location in string to insert at.
__n Number of characters to insert
__c The character to insert.
Exceptions:
std::length_error If new length exceeds max_size().
Inserts __n copies of character __c starting at the position referenced by iterator __p. If adding characters causes the length to exceed max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1182 of file basic_string.h.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::insert().
void std::basic_string< _CharT, _Traits, _Allocator >::insert (iterator __p, _InputIterator __beg, _InputIterator __end) [inline, inherited]
Insert a range of characters.
Parameters:
__p Iterator referencing location in string to insert at.
__beg Start of range.
__end End of range.
Exceptions:
std::length_error If new length exceeds max_size().
Inserts characters in range [__beg,__end). If adding characters causes the length to exceed max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1199 of file basic_string.h.
void std::basic_string< _CharT, _Traits, _Allocator >::insert (iterator __p, initializer_list< _CharT > __l) [inline, inherited]
Insert an initializer_list of characters.
Parameters:
__p Iterator referencing location in string to insert at.
__l The initializer_list of characters to insert.
Exceptions:
std::length_error If new length exceeds max_size().
Definition at line 1210 of file basic_string.h.
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::insert (size_type __pos1, const basic_string< _CharT, _Traits, _Allocator > & __str) [inline, inherited]
Insert value of a string.
Parameters:
__pos1 Iterator referencing location in string to insert at.
__str The string to insert.
Returns:
Reference to this string.
Exceptions:
std::length_error If new length exceeds max_size().
Inserts value of __str starting at __pos1. If adding characters causes the length to exceed max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1230 of file basic_string.h.
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::insert (size_type __pos1, const basic_string< _CharT, _Traits, _Allocator > & __str, size_type __pos2, size_type __n) [inline, inherited]
Insert a substring.
Parameters:
__pos1 Iterator referencing location in string to insert at.
__str The string to insert.
__pos2 Start of characters in str to insert.
__n Number of characters to insert.
Returns:
Reference to this string.
Exceptions:
std::length_error If new length exceeds max_size().
std::out_of_range If pos1 > size() or __pos2 > str.size().
Starting at pos1, insert __n character of __str beginning with __pos2. If adding characters causes the length to exceed max_size(), length_error is thrown. If __pos1 is beyond the end of this string or __pos2 is beyond the end of __str, out_of_range is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1252 of file basic_string.h.
iterator std::basic_string< _CharT, _Traits, _Allocator >::insert (iterator __p, _CharT __c) [inline, inherited]
Insert one character.
Parameters:
__p Iterator referencing position in string to insert at.
__c The character to insert.
Returns:
Iterator referencing newly inserted char.
Exceptions:
std::length_error If new length exceeds max_size().
Inserts character __c at position referenced by __p. If adding character causes the length to exceed max_size(), length_error is thrown. If __p is beyond end of string, out_of_range is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1334 of file basic_string.h.
size_type std::basic_string< _CharT, _Traits, _Allocator >::length () const [inline, inherited]
Returns the number of characters in the string, not including any null-termination.
Definition at line 718 of file basic_string.h.
size_type std::basic_string< _CharT, _Traits, _Allocator >::max_size () const [inline, inherited]
Returns the size() of the largest possible string.
Definition at line 723 of file basic_string.h.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator+= (const _CharT * __s) [inline]
Append a C string.
Parameters:
__s The C string to append.
Returns:
Reference to this string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 313 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator+= (_CharT __c) [inline]
Append a character.
Parameters:
__c The character to append.
Returns:
Reference to this string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 322 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator+= (std::initializer_list< _CharT > __l) [inline]
Append an initializer_list of characters.
Parameters:
__l The initializer_list of characters to be appended.
Returns:
Reference to this string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 331 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all().
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::operator+= (const basic_string< _CharT, _Traits, _Allocator > & __str) [inline, inherited]
Append a string to this string.
Parameters:
__str The string to append.
Returns:
Reference to this string.
Definition at line 929 of file basic_string.h.
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator= (const _CharT * __s) [inline]
Copy contents of s into this string.
Parameters:
__s Source null-terminated string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 138 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator= (_CharT __c) [inline]
Set value to string of length 1.
Parameters:
__c Source character.
Assigning to a character makes this string length 1 and (*this)[0] == c.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 147 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator= (std::initializer_list< _CharT > __l) [inline]
Set value to string constructed from initializer list.
Parameters:
__l std::initializer_list.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 164 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> const_reference __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator[] (size_type __pos) const [inline]
Subscript access to the data contained in the string.
Parameters:
__pos The index of the character to access.
Returns:
Read-only (constant) reference to the character.
This operator allows for easy, array-style, data access. Note that data access with this operator is unchecked and out_of_range lookups are not defined. (For checked lookups see at().)
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 270 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::size().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> reference __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator[] (size_type __pos) [inline]
Subscript access to the data contained in the string.
Parameters:
__pos The index of the character to access.
Returns:
Read/write reference to the character.
This operator allows for easy, array-style, data access. Note that data access with this operator is unchecked and out_of_range lookups are not defined. (For checked lookups see at().) Unshares the string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 281 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::size().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> void __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::pop_back () [inline]
Remove the last character.
The string must be non-empty.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 585 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::pop_back().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> void __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::push_back (_CharT __c) [inline]
Append a single character.
Parameters:
__c Character to append.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 395 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::push_back().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> reverse_iterator __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::rbegin () [inline]
Returns a read/write reverse iterator that points to the last character in the string. Iteration is done in reverse element order. Unshares the string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 190 of file debug/string.
References __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::end().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> const_reverse_iterator __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::rbegin () const [inline]
Returns a read-only (constant) reverse iterator that points to the last character in the string. Iteration is done in reverse element order.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 194 of file debug/string.
References __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::end().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> reverse_iterator __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::rend () [inline]
Returns a read/write reverse iterator that points to one before the first character in the string. Iteration is done in reverse element order. Unshares the string.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 198 of file debug/string.
References __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::begin().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> const_reverse_iterator __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::rend () const [inline]
Returns a read-only (constant) reverse iterator that points to one before the first character in the string. Iteration is done in reverse element order.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 202 of file debug/string.
References __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::begin().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::replace (size_type __pos, size_type __n1, const _CharT * __s, size_type __n2) [inline]
Replace characters with value of a C substring.
Parameters:
__pos Index of first character to replace.
__n1 Number of characters to be replaced.
__s C string to insert.
__n2 Number of characters from s to use.
Returns:
Reference to this string.
Exceptions:
std::out_of_range If pos1 > size().
std::length_error If new length exceeds max_size().
Removes the characters in the range [__pos,__pos + __n1) from this string. In place, the first __n2 characters of __s are inserted, or all of __s if __n2 is too large. If __pos is beyond end of string, out_of_range is thrown. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 611 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::replace().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::replace (size_type __pos, size_type __n1, const _CharT * __s) [inline]
Replace characters with value of a C string.
Parameters:
__pos Index of first character to replace.
__n1 Number of characters to be replaced.
__s C string to insert.
Returns:
Reference to this string.
Exceptions:
std::out_of_range If pos > size().
std::length_error If new length exceeds max_size().
Removes the characters in the range [__pos,__pos + __n1) from this string. In place, the characters of __s are inserted. If __pos is beyond end of string, out_of_range is thrown. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 621 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::replace().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string& __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::replace (size_type __pos, size_type __n1, size_type __n2, _CharT __c) [inline]
Replace characters with multiple characters.
Parameters:
__pos Index of first character to replace.
__n1 Number of characters to be replaced.
__n2 Number of characters to insert.
__c Character to insert.
Returns:
Reference to this string.
Exceptions:
std::out_of_range If __pos > size().
std::length_error If new length exceeds max_size().
Removes the characters in the range [pos,pos + n1) from this string. In place, __n2 copies of __c are inserted. If __pos is beyond end of string, out_of_range is thrown. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 630 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::replace().
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::replace (size_type __pos, size_type __n, const basic_string< _CharT, _Traits, _Allocator > & __str) [inline, inherited]
Replace characters with value from another string.
Parameters:
__pos Index of first character to replace.
__n Number of characters to be replaced.
__str String to insert.
Returns:
Reference to this string.
Exceptions:
std::out_of_range If pos is beyond the end of this string.
std::length_error If new length exceeds max_size().
Removes the characters in the range [__pos,__pos+__n) from this string. In place, the value of __str is inserted. If __pos is beyond end of string, out_of_range is thrown. If the length of the result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1426 of file basic_string.h.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::replace().
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::replace (size_type __pos1, size_type __n1, const basic_string< _CharT, _Traits, _Allocator > & __str, size_type __pos2, size_type __n2) [inline, inherited]
Replace characters with value from another string.
Parameters:
__pos1 Index of first character to replace.
__n1 Number of characters to be replaced.
__str String to insert.
__pos2 Index of first character of str to use.
__n2 Number of characters from str to use.
Returns:
Reference to this string.
Exceptions:
std::out_of_range If __pos1 > size() or __pos2 > __str.size().
std::length_error If new length exceeds max_size().
Removes the characters in the range [__pos1,__pos1 + n) from this string. In place, the value of __str is inserted. If __pos is beyond end of string, out_of_range is thrown. If the length of the result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1448 of file basic_string.h.
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::replace (iterator __i1, iterator __i2, const basic_string< _CharT, _Traits, _Allocator > & __str) [inline, inherited]
Replace range of characters with string.
Parameters:
__i1 Iterator referencing start of range to replace.
__i2 Iterator referencing end of range to replace.
__str String value to insert.
Returns:
Reference to this string.
Exceptions:
std::length_error If new length exceeds max_size().
Removes the characters in the range [__i1,__i2). In place, the value of __str is inserted. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1535 of file basic_string.h.
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::replace (iterator __i1, iterator __i2, const _CharT * __s, size_type __n) [inline, inherited]
Replace range of characters with C substring.
Parameters:
__i1 Iterator referencing start of range to replace.
__i2 Iterator referencing end of range to replace.
__s C string value to insert.
__n Number of characters from s to insert.
Returns:
Reference to this string.
Exceptions:
std::length_error If new length exceeds max_size().
Removes the characters in the range [__i1,__i2). In place, the first __n characters of __s are inserted. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1554 of file basic_string.h.
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::replace (iterator __i1, iterator __i2, const _CharT * __s) [inline, inherited]
Replace range of characters with C string.
Parameters:
__i1 Iterator referencing start of range to replace.
__i2 Iterator referencing end of range to replace.
__s C string value to insert.
Returns:
Reference to this string.
Exceptions:
std::length_error If new length exceeds max_size().
Removes the characters in the range [__i1,__i2). In place, the characters of __s are inserted. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1575 of file basic_string.h.
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::replace (iterator __i1, iterator __i2, size_type __n, _CharT __c) [inline, inherited]
Replace range of characters with multiple characters.
Parameters:
__i1 Iterator referencing start of range to replace.
__i2 Iterator referencing end of range to replace.
__n Number of characters to insert.
__c Character to insert.
Returns:
Reference to this string.
Exceptions:
std::length_error If new length exceeds max_size().
Removes the characters in the range [__i1,__i2). In place, __n copies of __c are inserted. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1596 of file basic_string.h.
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::replace (iterator __i1, iterator __i2, _InputIterator __k1, _InputIterator __k2) [inline, inherited]
Replace range of characters with range.
Parameters:
__i1 Iterator referencing start of range to replace.
__i2 Iterator referencing end of range to replace.
__k1 Iterator referencing start of range to insert.
__k2 Iterator referencing end of range to insert.
Returns:
Reference to this string.
Exceptions:
std::length_error If new length exceeds max_size().
Removes the characters in the range [__i1,__i2). In place, characters in the range [__k1,__k2) are inserted. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1620 of file basic_string.h.
basic_string& std::basic_string< _CharT, _Traits, _Allocator >::replace (iterator __i1, iterator __i2, initializer_list< _CharT > __l) [inline, inherited]
Replace range of characters with initializer_list.
Parameters:
__i1 Iterator referencing start of range to replace.
__i2 Iterator referencing end of range to replace.
__l The initializer_list of characters to insert.
Returns:
Reference to this string.
Exceptions:
std::length_error If new length exceeds max_size().
Removes the characters in the range [__i1,__i2). In place, characters in the range [__k1,__k2) are inserted. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1689 of file basic_string.h.
void std::basic_string< _CharT, _Traits, _Allocator >::reserve (size_type __res_arg = 0) [inherited]
Attempt to preallocate enough memory for specified number of characters.
Parameters:
__res_arg Number of characters required.
Exceptions:
std::length_error If __res_arg exceeds max_size().
This function attempts to reserve enough memory for the string to hold the specified number of characters. If the number requested is more than max_size(), length_error is thrown.
The advantage of this function is that if optimal code is a necessity and the user can determine the string length that will be required, the user can reserve the memory in advance, and thus prevent a possible reallocation of memory and copying of string data.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::shrink_to_fit().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> void __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::resize (size_type __n, _CharT __c) [inline]
Resizes the string to the specified number of characters.
Parameters:
__n Number of characters the string should contain.
__c Character to fill any new elements.
This function will resize the string to the specified number of characters. If the number is smaller than the string's current size the string is truncated, otherwise the string is extended and new elements are set to __c.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 229 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and std::basic_string< _CharT, _Traits, _Allocator >::resize().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> void __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::resize (size_type __n) [inline]
Resizes the string to the specified number of characters.
Parameters:
__n Number of characters the string should contain.
This function will resize the string to the specified length. If the new size is smaller than the string's current size the string is truncated, otherwise the string is extended and new characters are default-constructed. For basic types such as char, this means setting them to 0.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 236 of file debug/string.
References __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::resize().
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::resize().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::rfind (const _CharT * __s, size_type __pos, size_type __n) const [inline]
Find last position of a C substring.
Parameters:
__s C string to locate.
__pos Index of character to search back from.
__n Number of characters from s to search for.
Returns:
Index of start of last occurrence.
Starting from __pos, searches backward for the first __n characters in __s within this string. If found, returns the index where it begins. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 762 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::rfind().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::rfind (const _CharT * __s, size_type __pos = _Base::npos) const [inline]
Find last position of a C string.
Parameters:
__s C string to locate.
__pos Index of character to start search at (default end).
Returns:
Index of start of last occurrence.
Starting from __pos, searches backward for the value of __s within this string. If found, returns the index where it begins. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 769 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::rfind().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> size_type __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::rfind (_CharT __c, size_type __pos = _Base::npos) const [inline]
Find last position of a character.
Parameters:
__c Character to locate.
__pos Index of character to search back from (default end).
Returns:
Index of last occurrence.
Starting from __pos, searches backward for __c within this string. If found, returns the index where it was found. If not found, returns npos.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 776 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::rfind().
size_type std::basic_string< _CharT, _Traits, _Allocator >::rfind (const basic_string< _CharT, _Traits, _Allocator > & __str, size_type __pos = npos) const [inline, inherited]
Find last position of a string.
Parameters:
__str String to locate.
__pos Index of character to search back from (default end).
Returns:
Index of start of last occurrence.
Starting from __pos, searches backward for value of __str within this string. If found, returns the index where it begins. If not found, returns npos.
Definition at line 1888 of file basic_string.h.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::rfind().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> void __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::shrink_to_fit () [inline]
A non-binding request to reduce capacity() to size().
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 241 of file debug/string.
References __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), std::basic_string< _CharT, _Traits, _Allocator >::capacity(), std::basic_string< _CharT, _Traits, _Allocator >::reserve(), and std::basic_string< _CharT, _Traits, _Allocator >::size().
size_type std::basic_string< _CharT, _Traits, _Allocator >::size () const [inline, inherited]
Returns the number of characters in the string, not including any null-termination.
Definition at line 712 of file basic_string.h.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator[](), and __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::shrink_to_fit().
template<typename _CharT, typename _Traits = std::char_traits<_CharT>, typename _Allocator = std::allocator<_CharT>> basic_string __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::substr (size_type __pos = 0, size_type __n = _Base::npos) const [inline]
Get a substring.
Parameters:
__pos Index of first character (default 0).
__n Number of characters in substring (default remainder).
Returns:
The new string.
Exceptions:
std::out_of_range If __pos > size().
Construct and return a new string using the __n characters starting at __pos. If the string is too short, use the remainder of the characters. If __pos is beyond the end of the string, out_of_range is thrown.
Reimplemented from std::basic_string< _CharT, _Traits, _Allocator >.
Definition at line 875 of file debug/string.
References std::basic_string< _CharT, _Traits, _Allocator >::basic_string(), and std::basic_string< _CharT, _Traits, _Allocator >::substr().
void std::basic_string< _CharT, _Traits, _Allocator >::swap (basic_string< _CharT, _Traits, _Allocator > & __s) [inherited]
Swap contents with another string.
Parameters:
__s String to swap with.
Exchanges the contents of this string with that of __s in constant time.
Member Data Documentation
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_const_iterators [inherited]
The list of constant iterators that reference this container.
Definition at line 185 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_iterators [inherited]
The list of mutable iterators that reference this container.
Definition at line 182 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
unsigned int __gnu_debug::_Safe_sequence_base::_M_version [mutable, inherited]
The container version number. This number may never be 0.
Definition at line 188 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
const size_type std::basic_string< _CharT, _Traits, _Allocator >::npos [static, inherited]
Value returned by various member functions when they fail.
Definition at line 282 of file basic_string.h.
The documentation for this class was generated from the following file:
debug/string