libstdc++: std::__debug::multimap< _Key, _Tp, _Compare, _Allocator > Class Template Reference
std::__debug::multimap< _Key, _Tp, _Compare, _Allocator > Class Template Reference
Public Types
typedef _Allocator allocator_type
typedef
__gnu_debug::_Safe_iterator
< _Base_const_iterator,
multimap > const_iterator
typedef _Base::const_pointer const_pointer
typedef _Base::const_reference const_reference
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef _Base::difference_type difference_type
typedef
__gnu_debug::_Safe_iterator
< _Base_iterator, multimap > iterator
typedef _Compare key_compare
typedef _Key key_type
typedef _Tp mapped_type
typedef _Base::pointer pointer
typedef _Base::reference reference
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef _Base::size_type size_type
typedef std::pair< const _Key,
_Tp > value_type
Public Member Functions
multimap (const _Compare &__comp=_Compare(), const _Allocator &__a=_Allocator())
template<typename _InputIterator > multimap (_InputIterator __first, _InputIterator __last, const _Compare &__comp=_Compare(), const _Allocator &__a=_Allocator())
multimap (const multimap &__x)
multimap (const _Base &__x)
multimap (multimap &&__x) noexcept(is_nothrow_copy_constructible< _Compare >
multimap (initializer_list< value_type > __l, const _Compare &__c=_Compare(), const allocator_type &__a=allocator_type())
void _M_attach (_Safe_iterator_base *__it, bool __constant)
void _M_attach_single (_Safe_iterator_base *__it, bool __constant) throw ()
_Base & _M_base () _GLIBCXX_NOEXCEPT
const _Base & _M_base () const _GLIBCXX_NOEXCEPT
void _M_detach (_Safe_iterator_base *__it)
void _M_detach_single (_Safe_iterator_base *__it) throw ()
void _M_invalidate_all () const
void _M_invalidate_if (_Predicate __pred)
void _M_transfer_from_if (_Safe_sequence &__from, _Predicate __pred)
iterator begin () _GLIBCXX_NOEXCEPT
const_iterator begin () const _GLIBCXX_NOEXCEPT
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () _GLIBCXX_NOEXCEPT
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
iterator end () _GLIBCXX_NOEXCEPT
const_iterator end () const _GLIBCXX_NOEXCEPT
std::pair< iterator, iterator > equal_range (const key_type &__x)
std::pair< const_iterator,
const_iterator > equal_range (const key_type &__x) const
iterator erase (const_iterator __position)
iterator erase (iterator __position)
size_type erase (const key_type &__x)
iterator erase (const_iterator __first, const_iterator __last)
iterator find (const key_type &__x)
const_iterator find (const key_type &__x) const
iterator insert (const value_type &__x)
template<typename _Pair , typename = typename std::enable_if<std::is_constructible<value_type, _Pair&&>::value>::type> iterator insert (_Pair &&__x)
void insert (std::initializer_list< value_type > __list)
iterator insert (const_iterator __position, const value_type &__x)
template<typename _Pair , typename = typename std::enable_if<std::is_constructible<value_type, _Pair&&>::value>::type> iterator insert (const_iterator __position, _Pair &&__x)
template<typename _InputIterator > void insert (_InputIterator __first, _InputIterator __last)
iterator lower_bound (const key_type &__x)
const_iterator lower_bound (const key_type &__x) const
multimap & operator= (const multimap &__x)
multimap & operator= (multimap &&__x)
multimap & operator= (initializer_list< value_type > __l)
reverse_iterator rbegin () _GLIBCXX_NOEXCEPT
const_reverse_iterator rbegin () const _GLIBCXX_NOEXCEPT
reverse_iterator rend () _GLIBCXX_NOEXCEPT
const_reverse_iterator rend () const _GLIBCXX_NOEXCEPT
void swap (multimap &__x)
iterator upper_bound (const key_type &__x)
const_iterator upper_bound (const key_type &__x) const
Public Attributes
_Safe_iterator_base * _M_const_iterators
_Safe_iterator_base * _M_iterators
unsigned int _M_version
Protected Member Functions
void _M_detach_all ()
void _M_detach_singular ()
__gnu_cxx::__mutex & _M_get_mutex () throw ()
void _M_revalidate_singular ()
void _M_swap (_Safe_sequence_base &__x)
Detailed Description
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Allocator = std::allocator<std::pair<const _Key, _Tp> >>
class std::__debug::multimap< _Key, _Tp, _Compare, _Allocator >
Class std::multimap with safety/checking/debug instrumentation.
Definition at line 44 of file debug/multimap.h.
Member Function Documentation
void __gnu_debug::_Safe_sequence_base::_M_attach (_Safe_iterator_base * __it, bool __constant) [inherited]
Attach an iterator to this sequence.
void __gnu_debug::_Safe_sequence_base::_M_attach_single (_Safe_iterator_base * __it, bool __constant) throw () [inherited]
Likewise but not thread safe.
void __gnu_debug::_Safe_sequence_base::_M_detach (_Safe_iterator_base * __it) [inherited]
Detach an iterator from this sequence
void __gnu_debug::_Safe_sequence_base::_M_detach_all () [protected, inherited]
Detach all iterators, leaving them singular.
Reimplemented in __gnu_debug::_Safe_unordered_container_base.
Referenced by __gnu_debug::_Safe_sequence_base::~_Safe_sequence_base().
void __gnu_debug::_Safe_sequence_base::_M_detach_single (_Safe_iterator_base * __it) throw () [inherited]
Likewise but not thread safe.
void __gnu_debug::_Safe_sequence_base::_M_detach_singular () [protected, inherited]
Detach all singular iterators.
Postcondition:
for all iterators i attached to this sequence, i->_M_version == _M_version.
__gnu_cxx::__mutex& __gnu_debug::_Safe_sequence_base::_M_get_mutex () throw () [protected, inherited]
For use in _Safe_sequence.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
void __gnu_debug::_Safe_sequence_base::_M_invalidate_all () const [inline, inherited]
Invalidates all iterators.
Definition at line 234 of file safe_base.h.
References __gnu_debug::_Safe_sequence_base::_M_version.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::append(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::assign(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::c_str(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::clear(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::data(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::erase(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::insert(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator+=(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator=(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::pop_back(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::push_back(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::replace(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::resize(), and __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::shrink_to_fit().
void __gnu_debug::_Safe_sequence< multimap< _Key, _Tp, _Compare, _Allocator > >::_M_invalidate_if (_Predicate __pred) [inherited]
Invalidates all iterators x that reference this sequence, are not singular, and for which __pred(x) returns true. __pred will be invoked with the normal iterators nested in the safe ones.
void __gnu_debug::_Safe_sequence_base::_M_revalidate_singular () [protected, inherited]
Revalidates all attached singular iterators. This method may be used to validate iterators that were invalidated before (but for some reason, such as an exception, need to become valid again).
void __gnu_debug::_Safe_sequence_base::_M_swap (_Safe_sequence_base & __x) [protected, inherited]
Swap this sequence with the given sequence. This operation also swaps ownership of the iterators, so that when the operation is complete all iterators that originally referenced one container now reference the other container.
void __gnu_debug::_Safe_sequence< multimap< _Key, _Tp, _Compare, _Allocator > >::_M_transfer_from_if (_Safe_sequence< multimap< _Key, _Tp, _Compare, _Allocator > > & __from, _Predicate __pred) [inherited]
Transfers all iterators x that reference from sequence, are not singular, and for which __pred(x) returns true. __pred will be invoked with the normal iterators nested in the safe ones.
Member Data Documentation
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_const_iterators [inherited]
The list of constant iterators that reference this container.
Definition at line 185 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_iterators [inherited]
The list of mutable iterators that reference this container.
Definition at line 182 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
unsigned int __gnu_debug::_Safe_sequence_base::_M_version [mutable, inherited]
The container version number. This number may never be 0.
Definition at line 188 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
The documentation for this class was generated from the following file:
debug/multimap.h