libstdc++: std::__debug::vector< _Tp, _Allocator > Class Template Reference
std::__debug::vector< _Tp, _Allocator > Class Template Reference
Public Types
typedef _Allocator allocator_type
typedef
__gnu_debug::_Safe_iterator
< _Base_const_iterator, vector > const_iterator
typedef _Base::const_pointer const_pointer
typedef _Base::const_reference const_reference
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef _Base::difference_type difference_type
typedef
__gnu_debug::_Safe_iterator
< _Base_iterator, vector > iterator
typedef _Base::pointer pointer
typedef _Base::reference reference
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef _Base::size_type size_type
typedef _Tp value_type
Public Member Functions
vector (const _Allocator &__a=_Allocator())
vector (size_type __n)
vector (size_type __n, const _Tp &__value, const _Allocator &__a=_Allocator())
template<class _InputIterator > vector (_InputIterator __first, _InputIterator __last, const _Allocator &__a=_Allocator())
vector (const vector &__x)
vector (const _Base &__x)
vector (vector &&__x) noexcept
vector (const vector &__x, const allocator_type &__a)
vector (vector &&__x, const allocator_type &__a)
vector (initializer_list< value_type > __l, const allocator_type &__a=allocator_type())
void _M_attach (_Safe_iterator_base *__it, bool __constant)
void _M_attach_single (_Safe_iterator_base *__it, bool __constant) throw ()
_Base & _M_base () _GLIBCXX_NOEXCEPT
const _Base & _M_base () const _GLIBCXX_NOEXCEPT
void _M_detach (_Safe_iterator_base *__it)
void _M_detach_single (_Safe_iterator_base *__it) throw ()
void _M_invalidate_all () const
void _M_invalidate_if (_Predicate __pred)
void _M_transfer_from_if (_Safe_sequence &__from, _Predicate __pred)
template<typename _InputIterator > void assign (_InputIterator __first, _InputIterator __last)
void assign (size_type __n, const _Tp &__u)
void assign (initializer_list< value_type > __l)
reference back ()
const_reference back () const
iterator begin () _GLIBCXX_NOEXCEPT
const_iterator begin () const _GLIBCXX_NOEXCEPT
size_type capacity () const _GLIBCXX_NOEXCEPT
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () _GLIBCXX_NOEXCEPT
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
template<typename... _Args> iterator emplace (iterator __position, _Args &&...__args)
template<typename... _Args> void emplace_back (_Args &&...__args)
iterator end () _GLIBCXX_NOEXCEPT
const_iterator end () const _GLIBCXX_NOEXCEPT
iterator erase (iterator __position)
iterator erase (iterator __first, iterator __last)
reference front ()
const_reference front () const
iterator insert (iterator __position, const _Tp &__x)
template<typename _Up = _Tp> __gnu_cxx::__enable_if
<!std::__are_same< _Up, bool >
::__value, iterator >::__type insert (iterator __position, _Tp &&__x)
void insert (iterator __position, initializer_list< value_type > __l)
void insert (iterator __position, size_type __n, const _Tp &__x)
template<class _InputIterator > void insert (iterator __position, _InputIterator __first, _InputIterator __last)
vector & operator= (const vector &__x)
vector & operator= (vector &&__x) noexcept(_Alloc_traits
vector & operator= (initializer_list< value_type > __l)
reference operator[] (size_type __n)
const_reference operator[] (size_type __n) const
void pop_back ()
void push_back (const _Tp &__x)
template<typename _Up = _Tp> __gnu_cxx::__enable_if
<!std::__are_same< _Up, bool >
::__value, void >::__type push_back (_Tp &&__x)
reverse_iterator rbegin () _GLIBCXX_NOEXCEPT
const_reverse_iterator rbegin () const _GLIBCXX_NOEXCEPT
reverse_iterator rend () _GLIBCXX_NOEXCEPT
const_reverse_iterator rend () const _GLIBCXX_NOEXCEPT
void reserve (size_type __n)
void resize (size_type __sz)
void resize (size_type __sz, const _Tp &__c)
void shrink_to_fit ()
void swap (vector &__x) noexcept(_Alloc_traits
Public Attributes
_Safe_iterator_base * _M_const_iterators
_Safe_iterator_base * _M_iterators
unsigned int _M_version
Protected Member Functions
void _M_detach_all ()
void _M_detach_singular ()
__gnu_cxx::__mutex & _M_get_mutex () throw ()
void _M_revalidate_singular ()
void _M_swap (_Safe_sequence_base &__x)
Detailed Description
template<typename _Tp, typename _Allocator = std::allocator<_Tp>>
class std::__debug::vector< _Tp, _Allocator >
Class std::vector with safety/checking/debug instrumentation.
Definition at line 45 of file debug/vector.
Constructor & Destructor Documentation
template<typename _Tp, typename _Allocator = std::allocator<_Tp>> std::__debug::vector< _Tp, _Allocator >::vector (const _Base & __x) [inline]
Construction from a release-mode vector.
Definition at line 111 of file debug/vector.
Member Function Documentation
void __gnu_debug::_Safe_sequence_base::_M_attach (_Safe_iterator_base * __it, bool __constant) [inherited]
Attach an iterator to this sequence.
void __gnu_debug::_Safe_sequence_base::_M_attach_single (_Safe_iterator_base * __it, bool __constant) throw () [inherited]
Likewise but not thread safe.
void __gnu_debug::_Safe_sequence_base::_M_detach (_Safe_iterator_base * __it) [inherited]
Detach an iterator from this sequence
void __gnu_debug::_Safe_sequence_base::_M_detach_all () [protected, inherited]
Detach all iterators, leaving them singular.
Reimplemented in __gnu_debug::_Safe_unordered_container_base.
Referenced by __gnu_debug::_Safe_sequence_base::~_Safe_sequence_base().
void __gnu_debug::_Safe_sequence_base::_M_detach_single (_Safe_iterator_base * __it) throw () [inherited]
Likewise but not thread safe.
void __gnu_debug::_Safe_sequence_base::_M_detach_singular () [protected, inherited]
Detach all singular iterators.
Postcondition:
for all iterators i attached to this sequence, i->_M_version == _M_version.
__gnu_cxx::__mutex& __gnu_debug::_Safe_sequence_base::_M_get_mutex () throw () [protected, inherited]
For use in _Safe_sequence.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
void __gnu_debug::_Safe_sequence_base::_M_invalidate_all () const [inline, inherited]
Invalidates all iterators.
Definition at line 234 of file safe_base.h.
References __gnu_debug::_Safe_sequence_base::_M_version.
Referenced by __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::append(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::assign(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::c_str(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::clear(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::data(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::erase(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::insert(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator+=(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::operator=(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::pop_back(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::push_back(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::replace(), __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::resize(), and __gnu_debug::basic_string< _CharT, _Traits, _Allocator >::shrink_to_fit().
void __gnu_debug::_Safe_sequence< vector< _Tp, _Allocator > >::_M_invalidate_if (_Predicate __pred) [inherited]
Invalidates all iterators x that reference this sequence, are not singular, and for which __pred(x) returns true. __pred will be invoked with the normal iterators nested in the safe ones.
void __gnu_debug::_Safe_sequence_base::_M_revalidate_singular () [protected, inherited]
Revalidates all attached singular iterators. This method may be used to validate iterators that were invalidated before (but for some reason, such as an exception, need to become valid again).
void __gnu_debug::_Safe_sequence_base::_M_swap (_Safe_sequence_base & __x) [protected, inherited]
Swap this sequence with the given sequence. This operation also swaps ownership of the iterators, so that when the operation is complete all iterators that originally referenced one container now reference the other container.
void __gnu_debug::_Safe_sequence< vector< _Tp, _Allocator > >::_M_transfer_from_if (_Safe_sequence< vector< _Tp, _Allocator > > & __from, _Predicate __pred) [inherited]
Transfers all iterators x that reference from sequence, are not singular, and for which __pred(x) returns true. __pred will be invoked with the normal iterators nested in the safe ones.
Member Data Documentation
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_const_iterators [inherited]
The list of constant iterators that reference this container.
Definition at line 185 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_iterators [inherited]
The list of mutable iterators that reference this container.
Definition at line 182 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
unsigned int __gnu_debug::_Safe_sequence_base::_M_version [mutable, inherited]
The container version number. This number may never be 0.
Definition at line 188 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence_base::_M_invalidate_all(), and __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
The documentation for this class was generated from the following file:
debug/vector