libstdc++: std Namespace Reference
std Namespace Reference
Namespaces
namespace __debug
namespace __detail
namespace __parallel
namespace __profile
namespace chrono
namespace decimal
namespace placeholders
namespace regex_constants
namespace rel_ops
namespace this_thread
namespace tr1
namespace tr2
Classes
struct __atomic_base
Base class for atomic integrals.
struct __atomic_base< _PTp * >
Partial specialization for pointer types.
struct __atomic_flag_base
Base type for atomic_flag.
class __codecvt_abstract_base
Common base for codecvt functions.
class __ctype_abstract_base
Common base for ctype facet.
class __has_iterator_category_helper
Traits class for iterators.
struct __is_location_invariant
struct __numeric_limits_base
Part of std::numeric_limits.
struct _Base_bitset
struct _Base_bitset< 0 >
struct _Base_bitset< 1 >
class _Deque_base
struct _Deque_iterator
A deque::iterator.
struct _Derives_from_binary_function
Determines if the type _Tp derives from binary_function.
struct _Derives_from_unary_function
Determines if the type _Tp derives from unary_function.
class _Function_base
Base class of all polymorphic function object wrappers.
struct _Fwd_list_base
Base class for forward_list.
struct _Fwd_list_const_iterator
A forward_list::const_iterator.
struct _Fwd_list_iterator
A forward_list::iterator.
struct _Fwd_list_node
A helper node class for forward_list. This is just a linked list with a data value in each node. There is a sorting utility method.
struct _Fwd_list_node_base
A helper basic node class for forward_list. This is just a linked list with nothing inside it. There are purely list shuffling utility methods here.
class _Hashtable
class _List_base
See bits/stl_deque.h's _Deque_base for an explanation.
struct _List_const_iterator
A list::const_iterator.
struct _List_iterator
A list::iterator.
struct _List_node
An actual node in the list.
struct _Maybe_get_result_type
If we have found a result_type, extract it.
struct _Maybe_unary_or_binary_function
struct _Maybe_unary_or_binary_function< _Res, _T1 >
Derives from unary_function, as appropriate.
struct _Maybe_unary_or_binary_function< _Res, _T1, _T2 >
Derives from binary_function, as appropriate.
struct _Maybe_wrap_member_pointer
struct _Maybe_wrap_member_pointer< _Tp _Class::* >
class _Mem_fn< _Res(_Class::*)(_ArgTypes...) const >
Implementation of mem_fn for const member function pointers.
class _Mem_fn< _Res(_Class::*)(_ArgTypes...) const volatile >
Implementation of mem_fn for const volatile member function pointers.
class _Mem_fn< _Res(_Class::*)(_ArgTypes...) volatile >
Implementation of mem_fn for volatile member function pointers.
class _Mem_fn< _Res(_Class::*)(_ArgTypes...)>
Implementation of mem_fn for member function pointers.
class _Mu< _Arg, false, false >
class _Mu< _Arg, false, true >
class _Mu< _Arg, true, false >
class _Mu< reference_wrapper< _Tp >, false, false >
struct _Placeholder
The type of placeholder objects defined by libstdc++.
struct _Reference_wrapper_base
struct _Safe_tuple_element
struct _Safe_tuple_element_impl
struct _Safe_tuple_element_impl< __i, _Tuple, false >
class _Temporary_buffer
struct _Tuple_impl< _Idx >
struct _Tuple_impl< _Idx, _Head, _Tail...>
struct _Vector_base
See bits/stl_deque.h's _Deque_base for an explanation.
struct _Weak_result_type
struct _Weak_result_type_impl
struct _Weak_result_type_impl< _Res(&)(_ArgTypes...)>
Retrieve the result type for a function reference.
struct _Weak_result_type_impl< _Res(*)(_ArgTypes...)>
Retrieve the result type for a function pointer.
struct _Weak_result_type_impl< _Res(_ArgTypes...)>
Retrieve the result type for a function type.
struct _Weak_result_type_impl< _Res(_Class::*)(_ArgTypes...) const >
Retrieve result type for a const member function pointer.
struct _Weak_result_type_impl< _Res(_Class::*)(_ArgTypes...) const volatile >
Retrieve result type for a const volatile member function pointer.
struct _Weak_result_type_impl< _Res(_Class::*)(_ArgTypes...) volatile >
Retrieve result type for a volatile member function pointer.
struct _Weak_result_type_impl< _Res(_Class::*)(_ArgTypes...)>
Retrieve result type for a member function pointer.
struct add_const
add_const
struct add_cv
add_cv
struct add_lvalue_reference
add_lvalue_reference
struct add_pointer
add_pointer
struct add_rvalue_reference
add_rvalue_reference
struct add_volatile
add_volatile
struct adopt_lock_t
Assume the calling thread has already obtained mutex ownership and manage it.
struct aligned_storage
Alignment type.
struct alignment_of
alignment_of
class allocator
The standard allocator, as per [20.4].
class allocator< void >
allocator<void> specialization.
struct allocator_arg_t
[allocator.tag]
struct allocator_traits
Uniform interface to all allocator types.
struct array
A standard container for storing a fixed size sequence of elements.
struct atomic
atomic 29.4.3, Generic atomic type, primary class template.
struct atomic< _Tp * >
Partial specialization for pointer types.
struct atomic< bool >
Explicit specialization for bool.
struct atomic< char >
Explicit specialization for char.
struct atomic< char16_t >
Explicit specialization for char16_t.
struct atomic< char32_t >
Explicit specialization for char32_t.
struct atomic< int >
Explicit specialization for int.
struct atomic< long >
Explicit specialization for long.
struct atomic< long long >
Explicit specialization for long long.
struct atomic< short >
Explicit specialization for short.
struct atomic< signed char >
Explicit specialization for signed char.
struct atomic< unsigned char >
Explicit specialization for unsigned char.
struct atomic< unsigned int >
Explicit specialization for unsigned int.
struct atomic< unsigned long >
Explicit specialization for unsigned long.
struct atomic< unsigned long long >
Explicit specialization for unsigned long long.
struct atomic< unsigned short >
Explicit specialization for unsigned short.
struct atomic< wchar_t >
Explicit specialization for wchar_t.
struct atomic_bool
atomic_bool
struct atomic_flag
atomic_flag
class auto_ptr
A simple smart pointer providing strict ownership semantics.
struct auto_ptr_ref
class back_insert_iterator
Turns assignment into insertion.
class bad_alloc
Exception possibly thrown by new.bad_alloc (or classes derived from it) is used to report allocation errors from the throwing forms of new.
class bad_cast
Thrown during incorrect typecasting.If you attempt an invalid dynamic_cast expression, an instance of this class (or something derived from this class) is thrown.
class bad_exception
class bad_function_call
Exception class thrown when class template function's operator() is called with an empty target.
class bad_typeid
Thrown when a NULL pointer in a typeid expression is used.
class bad_weak_ptr
Exception possibly thrown by shared_ptr.
class basic_filebuf
The actual work of input and output (for files).This class associates both its input and output sequence with an external disk file, and maintains a joint file position for both sequences. Many of its semantics are described in terms of similar behavior in the Standard C Library's FILE streams.
class basic_fstream
Controlling input and output for files.This class supports reading from and writing to named files, using the inherited functions from std::basic_iostream. To control the associated sequence, an instance of std::basic_filebuf is used, which this page refers to as sb.
class basic_ifstream
Controlling input for files.This class supports reading from named files, using the inherited functions from std::basic_istream. To control the associated sequence, an instance of std::basic_filebuf is used, which this page refers to as sb.
class basic_ios
Virtual base class for all stream classes.Most of the member functions called dispatched on stream objects (e.g., std::cout.foo(bar);) are consolidated in this class.
class basic_iostream
Template class basic_iostreamThis class multiply inherits from the input and output stream classes simply to provide a single interface.
class basic_istream
Template class basic_istream.This is the base class for all input streams. It provides text formatting of all builtin types, and communicates with any class derived from basic_streambuf to do the actual input.
class basic_istringstream
Controlling input for std::string.This class supports reading from objects of type std::basic_string, using the inherited functions from std::basic_istream. To control the associated sequence, an instance of std::basic_stringbuf is used, which this page refers to as sb.
class basic_ofstream
Controlling output for files.This class supports reading from named files, using the inherited functions from std::basic_ostream. To control the associated sequence, an instance of std::basic_filebuf is used, which this page refers to as sb.
class basic_ostream
Template class basic_ostream.This is the base class for all output streams. It provides text formatting of all builtin types, and communicates with any class derived from basic_streambuf to do the actual output.
class basic_ostringstream
Controlling output for std::string.This class supports writing to objects of type std::basic_string, using the inherited functions from std::basic_ostream. To control the associated sequence, an instance of std::basic_stringbuf is used, which this page refers to as sb.
class basic_regex
class basic_streambuf
The actual work of input and output (interface).This is a base class. Derived stream buffers each control a pair of character sequences: one for input, and one for output.
class basic_string
Managing sequences of characters and character-like objects.
class basic_stringbuf
The actual work of input and output (for std::string).This class associates either or both of its input and output sequences with a sequence of characters, which can be initialized from, or made available as, a std::basic_string. (Paraphrased from [27.7.1]/1.)
class basic_stringstream
Controlling input and output for std::string.This class supports reading from and writing to objects of type std::basic_string, using the inherited functions from std::basic_iostream. To control the associated sequence, an instance of std::basic_stringbuf is used, which this page refers to as sb.
class bernoulli_distribution
A Bernoulli random number distribution.
struct bidirectional_iterator_tag
Bidirectional iterators support a superset of forward iterator operations.
struct binary_function
class binary_negate
One of the negation functors.
class binder1st
One of the binder functors.
class binder2nd
One of the binder functors.
class binomial_distribution
A discrete binomial random number distribution.
class cauchy_distribution
A cauchy_distribution random number distribution.
struct char_traits
Basis for explicit traits specializations.
struct char_traits< __gnu_cxx::character< V, I, S > >
char_traits<__gnu_cxx::character> specialization.
struct char_traits< char >
21.1.3.1 char_traits specializations
struct char_traits< wchar_t >
21.1.3.2 char_traits specializations
class chi_squared_distribution
A chi_squared_distribution random number distribution.
class codecvt
Primary class template codecvt.NB: Generic, mostly useless implementation.
class codecvt< _InternT, _ExternT, encoding_state >
codecvt<InternT, _ExternT, encoding_state> specialization.
class codecvt< char, char, mbstate_t >
class codecvt<char, char, mbstate_t> specialization.
class codecvt< wchar_t, char, mbstate_t >
class codecvt<wchar_t, char, mbstate_t> specialization.
class codecvt_base
Empty base class for codecvt facet [22.2.1.5].
class codecvt_byname
class codecvt_byname [22.2.1.6].
class collate
Facet for localized string comparison.
class collate_byname
class collate_byname [22.2.4.2].
struct complex
struct complex< double >
26.2.3 complex specializations complex<double> specialization
struct complex< float >
26.2.3 complex specializations complex<float> specialization
struct complex< long double >
26.2.3 complex specializations complex<long double> specialization
class condition_variable
condition_variable
class condition_variable_any
condition_variable_any
struct conditional
Define a member typedef type to one of two argument types.
class const_mem_fun1_ref_t
One of the adaptors for member pointers.
class const_mem_fun1_t
One of the adaptors for member pointers.
class const_mem_fun_ref_t
One of the adaptors for member pointers.
class const_mem_fun_t
One of the adaptors for member pointers.
class ctype
Primary class template ctype facet.This template class defines classification and conversion functions for character sets. It wraps cctype functionality. Ctype gets used by streams for many I/O operations.
class ctype< char >
The ctype<char> specialization.This class defines classification and conversion functions for the char type. It gets used by char streams for many I/O operations. The char specialization provides a number of optimizations as well.
class ctype< wchar_t >
The ctype<wchar_t> specialization.This class defines classification and conversion functions for the wchar_t type. It gets used by wchar_t streams for many I/O operations. The wchar_t specialization provides a number of optimizations as well.
struct ctype_base
Base class for ctype.
class ctype_byname
class ctype_byname [22.2.1.2].
class ctype_byname< char >
22.2.1.4 Class ctype_byname specializations.
class decay
decay
struct default_delete
Primary template, default_delete.
struct default_delete< _Tp[]>
Specialization, default_delete.
struct defer_lock_t
Do not acquire ownership of the mutex.
class deque
A standard container using fixed-size memory allocation and constant-time manipulation of elements at either end.
class discard_block_engine
class discrete_distribution
A discrete_distribution random number distribution.
struct divides
One of the math functors.
class domain_error
struct enable_if
Define a member typedef type only if a boolean constant is true.
class enable_shared_from_this
Base class allowing use of member function shared_from_this.
struct equal_to
One of the comparison functors.
class error_category
error_category
struct error_code
error_code
struct error_condition
error_condition
class exception
Base class for all library exceptions.
class exponential_distribution
An exponential continuous distribution for random numbers.
struct extent
extent
class extreme_value_distribution
A extreme_value_distribution random number distribution.
class fisher_f_distribution
A fisher_f_distribution random number distribution.
struct forward_iterator_tag
Forward iterators support a superset of input iterator operations.
class forward_list
A standard container with linear time access to elements, and fixed time insertion/deletion at any point in the sequence.
class fpos
Class representing stream positions.
class front_insert_iterator
Turns assignment into insertion.
class function< _Res(_ArgTypes...)>
Primary class template for std::function.Polymorphic function wrapper.
class future_error
Exception type thrown by futures.
class gamma_distribution
A gamma continuous distribution for random numbers.
class geometric_distribution
A discrete geometric random number distribution.
struct greater
One of the comparison functors.
struct greater_equal
One of the comparison functors.
class gslice
Class defining multi-dimensional subset of an array.
class gslice_array
Reference to multi-dimensional subset of an array.
struct has_trivial_copy_assign
has_trivial_copy_assign
struct has_trivial_copy_constructor
has_trivial_copy_constructor
struct has_trivial_default_constructor
has_trivial_default_constructor
struct has_trivial_destructor
has_trivial_destructor
struct has_virtual_destructor
has_virtual_destructor
struct hash
Primary class template hash.
struct hash< __debug::bitset< _Nb > >
std::hash specialization for bitset.
struct hash< __debug::vector< bool, _Alloc > >
std::hash specialization for vector<bool>.
struct hash< __gnu_cxx::__u16vstring >
std::hash specialization for __u16vstring.
struct hash< __gnu_cxx::__u32vstring >
std::hash specialization for __u32vstring.
struct hash< __gnu_cxx::__vstring >
std::hash specialization for __vstring.
struct hash< __gnu_cxx::__wvstring >
std::hash specialization for __wvstring.
struct hash< __gnu_cxx::throw_value_limit >
Explicit specialization of std::hash for __gnu_cxx::throw_value_limit.
struct hash< __gnu_cxx::throw_value_random >
Explicit specialization of std::hash for __gnu_cxx::throw_value_limit.
struct hash< __profile::bitset< _Nb > >
std::hash specialization for bitset.
struct hash< __profile::vector< bool, _Alloc > >
std::hash specialization for vector<bool>.
struct hash< __shared_ptr< _Tp, _Lp > >
std::hash specialization for __shared_ptr.
struct hash< _Tp * >
Partial specializations for pointer types.
struct hash< bool >
Explicit specialization for bool.
struct hash< char >
Explicit specialization for char.
struct hash< char16_t >
Explicit specialization for char16_t.
struct hash< char32_t >
Explicit specialization for char32_t.
struct hash< double >
Specialization for double.
struct hash< error_code >
std::hash specialization for error_code.
struct hash< float >
Specialization for float.
struct hash< int >
Explicit specialization for int.
struct hash< long >
Explicit specialization for long.
struct hash< long double >
Specialization for long double.
struct hash< long long >
Explicit specialization for long long.
struct hash< shared_ptr< _Tp > >
std::hash specialization for shared_ptr.
struct hash< short >
Explicit specialization for short.
struct hash< signed char >
Explicit specialization for signed char.
struct hash< string >
std::hash specialization for string.
struct hash< thread::id >
std::hash specialization for thread::id.
struct hash< type_index >
std::hash specialization for type_index.
struct hash< u16string >
std::hash specialization for u16string.
struct hash< u32string >
std::hash specialization for u32string.
struct hash< unique_ptr< _Tp, _Dp > >
std::hash specialization for unique_ptr.
struct hash< unsigned char >
Explicit specialization for unsigned char.
struct hash< unsigned int >
Explicit specialization for unsigned int.
struct hash< unsigned long >
Explicit specialization for unsigned long.
struct hash< unsigned long long >
Explicit specialization for unsigned long long.
struct hash< unsigned short >
Explicit specialization for unsigned short.
struct hash< wchar_t >
Explicit specialization for wchar_t.
struct hash< wstring >
std::hash specialization for wstring.
struct hash<::bitset< _Nb > >
std::hash specialization for bitset.
struct hash<::vector< bool, _Alloc > >
std::hash specialization for vector<bool>.
class independent_bits_engine
class indirect_array
Reference to arbitrary subset of an array.
class initializer_list
initializer_list
struct input_iterator_tag
Marking input iterators.
class insert_iterator
Turns assignment into insertion.
struct integral_constant
integral_constant
class invalid_argument
class ios_base
The base of the I/O class hierarchy.This class defines everything that can be defined about I/O that does not depend on the type of characters being input or output. Most people will only see ios_base when they need to specify the full name of the various I/O flags (e.g., the openmodes).
struct is_abstract
is_abstract
struct is_arithmetic
is_arithmetic
struct is_array
is_array
struct is_assignable
is_assignable
struct is_base_of
is_base_of
struct is_bind_expression
Determines if the given type _Tp is a function object should be treated as a subexpression when evaluating calls to function objects returned by bind(). [TR1 3.6.1].
struct is_bind_expression< _Bind< _Signature > >
Class template _Bind is always a bind expression.
struct is_bind_expression< _Bind_result< _Result, _Signature > >
Class template _Bind_result is always a bind expression.
struct is_bind_expression< const _Bind< _Signature > >
Class template _Bind is always a bind expression.
struct is_bind_expression< const _Bind_result< _Result, _Signature > >
Class template _Bind_result is always a bind expression.
struct is_bind_expression< const volatile _Bind< _Signature > >
Class template _Bind is always a bind expression.
struct is_bind_expression< const volatile _Bind_result< _Result, _Signature > >
Class template _Bind_result is always a bind expression.
struct is_bind_expression< volatile _Bind< _Signature > >
Class template _Bind is always a bind expression.
struct is_bind_expression< volatile _Bind_result< _Result, _Signature > >
Class template _Bind_result is always a bind expression.
struct is_class
is_class
struct is_compound
is_compound
struct is_const
is_const
struct is_constructible
is_constructible
struct is_convertible
is_convertible
struct is_copy_assignable
is_copy_assignable
struct is_copy_constructible
is_copy_constructible
struct is_default_constructible
is_default_constructible
struct is_destructible
is_destructible
struct is_empty
is_empty
struct is_enum
is_enum
struct is_error_code_enum
is_error_code_enum
struct is_error_code_enum< future_errc >
Specialization.
struct is_error_condition_enum
is_error_condition_enum
struct is_explicitly_convertible
is_explicitly_convertible
struct is_floating_point
is_floating_point
struct is_function
is_function
struct is_fundamental
is_fundamental
struct is_integral
is_integral
struct is_literal_type
is_literal_type
struct is_lvalue_reference
is_lvalue_reference
struct is_member_function_pointer
is_member_function_pointer
struct is_member_object_pointer
is_member_object_pointer
struct is_member_pointer
is_member_pointer
struct is_move_assignable
is_move_assignable
struct is_move_constructible
is_move_constructible
struct is_nothrow_assignable
is_nothrow_assignable
struct is_nothrow_constructible
is_nothrow_constructible
struct is_nothrow_copy_assignable
is_nothrow_copy_assignable
struct is_nothrow_copy_constructible
is_nothrow_copy_constructible
struct is_nothrow_default_constructible
is_nothrow_default_constructible
struct is_nothrow_move_assignable
is_nothrow_move_assignable
struct is_nothrow_move_constructible
is_nothrow_move_constructible
struct is_object
is_object
struct is_placeholder
Determines if the given type _Tp is a placeholder in a bind() expression and, if so, which placeholder it is. [TR1 3.6.2].
struct is_placeholder< _Placeholder< _Num > >
struct is_pod
is_pod
struct is_pointer
is_pointer
struct is_polymorphic
is_polymorphic
struct is_reference
is_reference
struct is_rvalue_reference
is_rvalue_reference
struct is_same
is_same
struct is_scalar
is_scalar
struct is_signed
is_signed
struct is_standard_layout
is_standard_layout
struct is_trivial
is_trivial
struct is_union
is_union
struct is_unsigned
is_unsigned
struct is_void
is_void
struct is_volatile
is_volatile
class istream_iterator
Provides input iterator semantics for streams.
class istreambuf_iterator
Provides input iterator semantics for streambufs.
struct iterator
Common iterator class.
struct iterator_traits< _Tp * >
Partial specialization for pointer types.
struct iterator_traits< const _Tp * >
Partial specialization for const pointer types.
class length_error
struct less
One of the comparison functors.
struct less_equal
One of the comparison functors.
class linear_congruential_engine
A model of a linear congruential random number generator.
class list
A standard container with linear time access to elements, and fixed time insertion/deletion at any point in the sequence.
class locale
Container class for localization functionality.The locale class is first a class wrapper for C library locales. It is also an extensible container for user-defined localization. A locale is a collection of facets that implement various localization features such as money, time, and number printing.
class lock_guard
Scoped lock idiom.
class logic_error
One of two subclasses of exception.
struct logical_and
One of the Boolean operations functors.
struct logical_not
One of the Boolean operations functors.
struct logical_or
One of the Boolean operations functors.
class lognormal_distribution
A lognormal_distribution random number distribution.
struct make_signed
make_signed
struct make_unsigned
make_unsigned
class map
A standard container made up of (key,value) pairs, which can be retrieved based on a key, in logarithmic time.
class mask_array
Reference to selected subset of an array.
class match_results
The results of a match or search operation.
class mem_fun1_ref_t
One of the adaptors for member pointers.
class mem_fun1_t
One of the adaptors for member pointers.
class mem_fun_ref_t
One of the adaptors for member pointers.
class mem_fun_t
One of the adaptors for member pointers.
class mersenne_twister_engine
class messages
Primary class template messages.This facet encapsulates the code to retrieve messages from message catalogs. The only thing defined by the standard for this facet is the interface. All underlying functionality is implementation-defined.
struct messages_base
Messages facet base class providing catalog typedef.
class messages_byname
class messages_byname [22.2.7.2].
struct minus
One of the math functors.
struct modulus
One of the math functors.
class money_base
Money format ordering data.This class contains an ordered array of 4 fields to represent the pattern for formatting a money amount. Each field may contain one entry from the part enum. symbol, sign, and value must be present and the remaining field must contain either none or space.
class money_get
Primary class template money_get.This facet encapsulates the code to parse and return a monetary amount from a string.
class money_put
Primary class template money_put.This facet encapsulates the code to format and output a monetary amount.
class moneypunct
Primary class template moneypunct.This facet encapsulates the punctuation, grouping and other formatting features of money amount string representations.
class moneypunct_byname
class moneypunct_byname [22.2.6.4].
class move_iterator
class multimap
A standard container made up of (key,value) pairs, which can be retrieved based on a key, in logarithmic time.
struct multiplies
One of the math functors.
class multiset
A standard container made up of elements, which can be retrieved in logarithmic time.
class mutex
mutex
struct negate
One of the math functors.
class negative_binomial_distribution
A negative_binomial_distribution random number distribution.
class nested_exception
Exception class with exception_ptr data member.
class normal_distribution
A normal continuous distribution for random numbers.
struct not_equal_to
One of the comparison functors.
class num_get
Primary class template num_get.This facet encapsulates the code to parse and return a number from a string. It is used by the istream numeric extraction operators.
class num_put
Primary class template num_put.This facet encapsulates the code to convert a number to a string. It is used by the ostream numeric insertion operators.
struct numeric_limits
Properties of fundamental types.
struct numeric_limits< bool >
numeric_limits<bool> specialization.
struct numeric_limits< char >
numeric_limits<char> specialization.
struct numeric_limits< char16_t >
numeric_limits<char16_t> specialization.
struct numeric_limits< char32_t >
numeric_limits<char32_t> specialization.
struct numeric_limits< double >
numeric_limits<double> specialization.
struct numeric_limits< float >
numeric_limits<float> specialization.
struct numeric_limits< int >
numeric_limits<int> specialization.
struct numeric_limits< long >
numeric_limits<long> specialization.
struct numeric_limits< long double >
numeric_limits<long double> specialization.
struct numeric_limits< long long >
numeric_limits<long long> specialization.
struct numeric_limits< short >
numeric_limits<short> specialization.
struct numeric_limits< signed char >
numeric_limits<signed char> specialization.
struct numeric_limits< unsigned char >
numeric_limits<unsigned char> specialization.
struct numeric_limits< unsigned int >
numeric_limits<unsigned int> specialization.
struct numeric_limits< unsigned long >
numeric_limits<unsigned long> specialization.
struct numeric_limits< unsigned long long >
numeric_limits<unsigned long long> specialization.
struct numeric_limits< unsigned short >
numeric_limits<unsigned short> specialization.
struct numeric_limits< wchar_t >
numeric_limits<wchar_t> specialization.
class numpunct
Primary class template numpunct.This facet stores several pieces of information related to printing and scanning numbers, such as the decimal point character. It takes a template parameter specifying the char type. The numpunct facet is used by streams for many I/O operations involving numbers.
class numpunct_byname
class numpunct_byname [22.2.3.2].
struct once_flag
once_flag
class ostream_iterator
Provides output iterator semantics for streams.
class ostreambuf_iterator
Provides output iterator semantics for streambufs.
class out_of_range
struct output_iterator_tag
Marking output iterators.
class overflow_error
struct owner_less< shared_ptr< _Tp > >
Partial specialization of owner_less for shared_ptr.
struct owner_less< weak_ptr< _Tp > >
Partial specialization of owner_less for weak_ptr.
struct pair
Struct holding two objects of arbitrary type.
class piecewise_constant_distribution
A piecewise_constant_distribution random number distribution.
struct piecewise_construct_t
piecewise_construct_t
class piecewise_linear_distribution
A piecewise_linear_distribution random number distribution.
struct plus
One of the math functors.
class pointer_to_binary_function
One of the adaptors for function pointers.
class pointer_to_unary_function
One of the adaptors for function pointers.
struct pointer_traits
Uniform interface to all pointer-like types.
struct pointer_traits< _Tp * >
Partial specialization for built-in pointers.
class poisson_distribution
A discrete Poisson random number distribution.
class priority_queue
A standard container automatically sorting its contents.
class queue
A standard container giving FIFO behavior.
struct random_access_iterator_tag
Random-access iterators support a superset of bidirectional iterator operations.
class random_device
class range_error
struct rank
rank
struct ratio
Provides compile-time rational arithmetic.
struct ratio_divide
ratio_divide
struct ratio_equal
ratio_equal
struct ratio_multiply
ratio_multiply
struct ratio_not_equal
ratio_not_equal
class raw_storage_iterator
class recursive_mutex
recursive_mutex
class reference_wrapper
Primary class template for reference_wrapper.
class regex_error
A regular expression exception class.The regular expression library throws objects of this class on error.
class regex_iterator
class regex_token_iterator
struct regex_traits
Describes aspects of a regular expression.
struct remove_all_extents
remove_all_extents
struct remove_const
remove_const
struct remove_cv
remove_cv
struct remove_extent
remove_extent
struct remove_pointer
remove_pointer
struct remove_reference
remove_reference
struct remove_volatile
remove_volatile
class reverse_iterator
class runtime_error
One of two subclasses of exception.
class scoped_allocator_adaptor
Primary class template.
class seed_seq
The seed_seq class generates sequences of seeds for random number generators.
class set
A standard container made up of unique keys, which can be retrieved in logarithmic time.
class shared_ptr
A smart pointer with reference-counted copy semantics.
class shuffle_order_engine
Produces random numbers by combining random numbers from some base engine to produce random numbers with a specifies number of bits __w.
class slice
Class defining one-dimensional subset of an array.
class slice_array
Reference to one-dimensional subset of an array.
class stack
A standard container giving FILO behavior.
class student_t_distribution
A student_t_distribution random number distribution.
class sub_match
class system_error
Thrown to indicate error code of underlying system.
class thread
thread
class time_base
Time format ordering data.This class provides an enum representing different orderings of time: day, month, and year.
class time_get
Primary class template time_get.This facet encapsulates the code to parse and return a date or time from a string. It is used by the istream numeric extraction operators.
class time_get_byname
class time_get_byname [22.2.5.2].
class time_put
Primary class template time_put.This facet encapsulates the code to format and output dates and times according to formats used by strftime().
class time_put_byname
class time_put_byname [22.2.5.4].
struct try_to_lock_t
Try to acquire ownership of the mutex without blocking.
class tuple
Primary class template, tuple.
class tuple< _T1, _T2 >
Partial specialization, 2-element tuple. Includes construction and assignment from a pair.
struct tuple_element< 0, tuple< _Head, _Tail...> >
struct tuple_element< __i, tuple< _Head, _Tail...> >
struct tuple_size< tuple< _Elements...> >
class tuple_size
struct type_index
The class type_index provides a simple wrapper for type_info which can be used as an index type in associative containers (23.6) and in unordered associative containers (23.7).
class type_info
Part of RTTI.
struct unary_function
class unary_negate
One of the negation functors.
class underflow_error
struct underlying_type
The underlying type of an enum.
class uniform_int_distribution
Uniform discrete distribution for random numbers. A discrete random distribution on the range with equal probability throughout the range.
class uniform_real_distribution
Uniform continuous distribution for random numbers.
class unique_lock
unique_lock
class unique_ptr
20.7.12.2 unique_ptr for single objects.
class unique_ptr< _Tp[], _Dp >
20.7.12.3 unique_ptr for array objects with a runtime length
class unordered_map
A standard container composed of unique keys (containing at most one of each key value) that associates values of another type with the keys.
class unordered_multimap
A standard container composed of equivalent keys (possibly containing multiple of each key value) that associates values of another type with the keys.
class unordered_multiset
A standard container composed of equivalent keys (possibly containing multiple of each key value) in which the elements' keys are the elements themselves.
class unordered_set
A standard container composed of unique keys (containing at most one of each key value) in which the elements' keys are the elements themselves.
struct uses_allocator
[allocator.uses.trait]
struct uses_allocator< tuple< _Types...>, _Alloc >
Partial specialization for tuples.
class valarray
Smart array designed to support numeric processing.
class vector
A standard container which offers fixed time access to individual elements in any order.
class vector< bool, _Alloc >
A specialization of vector for booleans which offers fixed time access to individual elements in any order.
class weak_ptr
A smart pointer with weak semantics.
class weibull_distribution
A weibull_distribution random number distribution.
Typedefs
typedef unsigned char __atomic_flag_data_type
typedef FILE __c_file
typedef __locale_t __c_locale
typedef __gthread_mutex_t __c_lock
typedef unsigned long _Bit_type
typedef __atomic_base< char > atomic_char
typedef __atomic_base< char16_t > atomic_char16_t
typedef __atomic_base< char32_t > atomic_char32_t
typedef __atomic_base< int > atomic_int
typedef __atomic_base
< int_fast16_t > atomic_int_fast16_t
typedef __atomic_base
< int_fast32_t > atomic_int_fast32_t
typedef __atomic_base
< int_fast64_t > atomic_int_fast64_t
typedef __atomic_base
< int_fast8_t > atomic_int_fast8_t
typedef __atomic_base
< int_least16_t > atomic_int_least16_t
typedef __atomic_base
< int_least32_t > atomic_int_least32_t
typedef __atomic_base
< int_least64_t > atomic_int_least64_t
typedef __atomic_base
< int_least8_t > atomic_int_least8_t
typedef __atomic_base< intmax_t > atomic_intmax_t
typedef __atomic_base< intptr_t > atomic_intptr_t
typedef __atomic_base< long long > atomic_llong
typedef __atomic_base< long > atomic_long
typedef __atomic_base< ptrdiff_t > atomic_ptrdiff_t
typedef __atomic_base< signed
char > atomic_schar
typedef __atomic_base< short > atomic_short
typedef __atomic_base< size_t > atomic_size_t
typedef __atomic_base
< unsigned char > atomic_uchar
typedef __atomic_base
< unsigned int > atomic_uint
typedef __atomic_base
< uint_fast16_t > atomic_uint_fast16_t
typedef __atomic_base
< uint_fast32_t > atomic_uint_fast32_t
typedef __atomic_base
< uint_fast64_t > atomic_uint_fast64_t
typedef __atomic_base
< uint_fast8_t > atomic_uint_fast8_t
typedef __atomic_base
< uint_least16_t > atomic_uint_least16_t
typedef __atomic_base
< uint_least32_t > atomic_uint_least32_t
typedef __atomic_base
< uint_least64_t > atomic_uint_least64_t
typedef __atomic_base
< uint_least8_t > atomic_uint_least8_t
typedef __atomic_base< uintmax_t > atomic_uintmax_t
typedef __atomic_base< uintptr_t > atomic_uintptr_t
typedef __atomic_base
< unsigned long long > atomic_ullong
typedef __atomic_base
< unsigned long > atomic_ulong
typedef __atomic_base
< unsigned short > atomic_ushort
typedef __atomic_base< wchar_t > atomic_wchar_t
typedef match_results< const
char * > cmatch
typedef regex_iterator< const
char * > cregex_iterator
typedef regex_token_iterator
< const char * > cregex_token_iterator
typedef sub_match< const char * > csub_match
typedef minstd_rand0 default_random_engine
typedef integral_constant
< bool, false > false_type
typedef basic_filebuf< char > filebuf
typedef basic_fstream< char > fstream
typedef basic_ifstream< char > ifstream
typedef basic_ios< char > ios
typedef basic_iostream< char > iostream
typedef basic_istream< char > istream
typedef basic_istringstream< char > istringstream
typedef shuffle_order_engine
< minstd_rand0, 256 > knuth_b
typedef enum std::memory_order memory_order
typedef
linear_congruential_engine
< uint_fast32_t, 48271UL, 0UL, 2147483647UL > minstd_rand
typedef
linear_congruential_engine
< uint_fast32_t, 16807UL, 0UL, 2147483647UL > minstd_rand0
typedef
mersenne_twister_engine
< uint_fast32_t, 32, 624, 397, 31, 0x9908b0dfUL, 11, 0xffffffffUL, 7, 0x9d2c5680UL, 15, 0xefc60000UL, 18, 1812433253UL > mt19937
typedef
mersenne_twister_engine
< uint_fast64_t, 64, 312, 156, 31, 0xb5026f5aa96619e9ULL, 29, 0x5555555555555555ULL, 17, 0x71d67fffeda60000ULL, 37, 0xfff7eee000000000ULL, 43, 6364136223846793005ULL > mt19937_64
typedef void(* new_handler)()
typedef basic_ofstream< char > ofstream
typedef basic_ostream< char > ostream
typedef basic_ostringstream< char > ostringstream
typedef __PTRDIFF_TYPE__ ptrdiff_t
typedef discard_block_engine
< ranlux24_base, 223, 23 > ranlux24
typedef
subtract_with_carry_engine
< uint_fast32_t, 24, 10, 24 > ranlux24_base
typedef discard_block_engine
< ranlux48_base, 389, 11 > ranlux48
typedef
subtract_with_carry_engine
< uint_fast64_t, 48, 5, 12 > ranlux48_base
typedef basic_regex< char > regex
typedef __SIZE_TYPE__ size_t
typedef match_results
< string::const_iterator > smatch
typedef regex_iterator
< string::const_iterator > sregex_iterator
typedef regex_token_iterator
< string::const_iterator > sregex_token_iterator
typedef sub_match
< string::const_iterator > ssub_match
typedef basic_streambuf< char > streambuf
typedef long long streamoff
typedef fpos< mbstate_t > streampos
typedef ptrdiff_t streamsize
typedef basic_string< char > string
typedef basic_stringbuf< char > stringbuf
typedef basic_stringstream< char > stringstream
typedef void(* terminate_handler)()
typedef integral_constant
< bool, true > true_type
typedef fpos< mbstate_t > u16streampos
typedef basic_string< char16_t > u16string
typedef fpos< mbstate_t > u32streampos
typedef basic_string< char32_t > u32string
typedef void(* unexpected_handler)()
typedef match_results< const
wchar_t * > wcmatch
typedef regex_iterator< const
wchar_t * > wcregex_iterator
typedef regex_token_iterator
< const wchar_t * > wcregex_token_iterator
typedef sub_match< const
wchar_t * > wcsub_match
typedef basic_filebuf< wchar_t > wfilebuf
typedef basic_fstream< wchar_t > wfstream
typedef basic_ifstream< wchar_t > wifstream
typedef basic_ios< wchar_t > wios
typedef basic_iostream< wchar_t > wiostream
typedef basic_istream< wchar_t > wistream
typedef basic_istringstream
< wchar_t > wistringstream
typedef basic_ofstream< wchar_t > wofstream
typedef basic_ostream< wchar_t > wostream
typedef basic_ostringstream
< wchar_t > wostringstream
typedef basic_regex< wchar_t > wregex
typedef match_results
< wstring::const_iterator > wsmatch
typedef regex_iterator
< wstring::const_iterator > wsregex_iterator
typedef regex_token_iterator
< wstring::const_iterator > wsregex_token_iterator
typedef sub_match
< wstring::const_iterator > wssub_match
typedef basic_streambuf< wchar_t > wstreambuf
typedef fpos< mbstate_t > wstreampos
typedef basic_string< wchar_t > wstring
typedef basic_stringbuf< wchar_t > wstringbuf
typedef basic_stringstream
< wchar_t > wstringstream
Enumerations
enum { _S_threshold }
enum { _S_chunk_size }
enum { _S_word_bit }
enum _Ios_Fmtflags {
_S_boolalpha, _S_dec, _S_fixed, _S_hex,
_S_internal, _S_left, _S_oct, _S_right,
_S_scientific, _S_showbase, _S_showpoint, _S_showpos,
_S_skipws, _S_unitbuf, _S_uppercase, _S_adjustfield,
_S_basefield, _S_floatfield, _S_ios_fmtflags_end
}
enum _Ios_Iostate {
_S_goodbit, _S_badbit, _S_eofbit, _S_failbit,
_S_ios_iostate_end
}
enum _Ios_Openmode {
_S_app, _S_ate, _S_bin, _S_in,
_S_out, _S_trunc, _S_ios_openmode_end
}
enum _Ios_Seekdir { _S_beg, _S_cur, _S_end, _S_ios_seekdir_end }
enum _Manager_operation { __get_type_info, __get_functor_ptr, __clone_functor, __destroy_functor }
enum _Rb_tree_color { _S_red, _S_black }
enum cv_status { no_timeout, timeout }
enum errc {
address_family_not_supported, address_in_use, address_not_available, already_connected,
argument_list_too_long, argument_out_of_domain, bad_address, bad_file_descriptor,
broken_pipe, connection_aborted, connection_already_in_progress, connection_refused,
connection_reset, cross_device_link, destination_address_required, device_or_resource_busy,
directory_not_empty, executable_format_error, file_exists, file_too_large,
filename_too_long, function_not_supported, host_unreachable, illegal_byte_sequence,
inappropriate_io_control_operation, interrupted, invalid_argument, invalid_seek,
io_error, is_a_directory, message_size, network_down,
network_reset, network_unreachable, no_buffer_space, no_child_process,
no_lock_available, no_message, no_protocol_option, no_space_on_device,
no_such_device_or_address, no_such_device, no_such_file_or_directory, no_such_process,
not_a_directory, not_a_socket, not_connected, not_enough_memory,
operation_in_progress, operation_not_permitted, operation_not_supported, operation_would_block,
permission_denied, protocol_not_supported, read_only_file_system, resource_deadlock_would_occur,
resource_unavailable_try_again, result_out_of_range, timed_out, too_many_files_open_in_system,
too_many_files_open, too_many_links, too_many_symbolic_link_levels, wrong_protocol_type
}
enum float_denorm_style { denorm_indeterminate, denorm_absent, denorm_present }
enum float_round_style {
round_indeterminate, round_toward_zero, round_to_nearest, round_toward_infinity,
round_toward_neg_infinity
}
enum future_errc { future_already_retrieved, promise_already_satisfied, no_state, broken_promise }
enum future_status { ready, timeout, deferred }
enum launch { async, deferred }
enum memory_order {
memory_order_relaxed, memory_order_consume, memory_order_acquire, memory_order_release,
memory_order_acq_rel, memory_order_seq_cst
}
Functions
template<typename _CharT > _CharT * __add_grouping (_CharT *__s, _CharT __sep, const char *__gbeg, size_t __gsize, const _CharT *__first, const _CharT *__last)
template<typename _Tp > _Tp * __addressof (_Tp &__r) _GLIBCXX_NOEXCEPT
template<typename _RandomAccessIterator , typename _Distance , typename _Tp > void __adjust_heap (_RandomAccessIterator __first, _Distance __holeIndex, _Distance __len, _Tp __value)
template<typename _RandomAccessIterator , typename _Distance , typename _Tp , typename _Compare > void __adjust_heap (_RandomAccessIterator __first, _Distance __holeIndex, _Distance __len, _Tp __value, _Compare __comp)
template<typename _InputIterator , typename _Distance > void __advance (_InputIterator &__i, _Distance __n, input_iterator_tag)
template<typename _BidirectionalIterator , typename _Distance > void __advance (_BidirectionalIterator &__i, _Distance __n, bidirectional_iterator_tag)
template<typename _RandomAccessIterator , typename _Distance > void __advance (_RandomAccessIterator &__i, _Distance __n, random_access_iterator_tag)
template<typename _Alloc > void __alloc_on_copy (_Alloc &__one, const _Alloc &__two)
template<typename _Alloc > _Alloc __alloc_on_copy (const _Alloc &__a)
template<typename _Alloc > void __alloc_on_move (_Alloc &__one, _Alloc &__two)
template<typename _Alloc > void __alloc_on_swap (_Alloc &__one, _Alloc &__two)
template<typename _Tp , _Lock_policy _Lp, typename _Alloc , typename... _Args> __shared_ptr< _Tp, _Lp > __allocate_shared (const _Alloc &__a, _Args &&...__args)
template<typename _Callable , typename... _Args> _Bind_simple_helper< _Callable,
_Args...>::__type __bind_simple (_Callable &&__callable, _Args &&...__args)
template<typename _Functor > _Functor & __callable_functor (_Functor &__f)
template<typename _Member , typename _Class > _Mem_fn< _Member _Class::* > __callable_functor (_Member _Class::*&__p)
template<typename _Member , typename _Class > _Mem_fn< _Member _Class::* > __callable_functor (_Member _Class::*const &__p)
template<typename _Facet > const _Facet & __check_facet (const _Facet *__f)
template<typename _RandomAccessIterator , typename _Distance > void __chunk_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Distance __chunk_size)
template<typename _RandomAccessIterator , typename _Distance , typename _Compare > void __chunk_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Distance __chunk_size, _Compare __comp)
constexpr memory_order __cmpexch_failure_order (memory_order __m) noexcept
template<typename _Tp > _Tp __complex_abs (const complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > __complex_acos (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > __complex_acosh (const std::complex< _Tp > &__z)
template<typename _Tp > _Tp __complex_arg (const complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > __complex_asin (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > __complex_asinh (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > __complex_atan (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > __complex_atanh (const std::complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > __complex_cos (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > __complex_cosh (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > __complex_exp (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > __complex_log (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > __complex_pow (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > std::complex< _Tp > __complex_proj (const std::complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > __complex_sin (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > __complex_sinh (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > __complex_sqrt (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > __complex_tan (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > __complex_tanh (const complex< _Tp > &__z)
int __convert_from_v (const __c_locale &__cloc __attribute__((__unused__)), char *__out, const int __size __attribute__((__unused__)), const char *__fmt,...)
template<typename _Tp > void __convert_to_v (const char *, _Tp &, ios_base::iostate &, const __c_locale &) throw ()
template<> void __convert_to_v (const char *, float &, ios_base::iostate &, const __c_locale &) throw ()
template<> void __convert_to_v (const char *, double &, ios_base::iostate &, const __c_locale &) throw ()
template<> void __convert_to_v (const char *, long double &, ios_base::iostate &, const __c_locale &) throw ()
template<bool _IsMove, typename _II , typename _OI > _OI __copy_move_a (_II __first, _II __last, _OI __result)
template<bool _IsMove, typename _CharT > __gnu_cxx::__enable_if
< __is_char< _CharT >::__value,
ostreambuf_iterator< _CharT >
>::__type __copy_move_a2 (_CharT *__first, _CharT *__last, ostreambuf_iterator< _CharT > __result)
template<bool _IsMove, typename _CharT > __gnu_cxx::__enable_if
< __is_char< _CharT >::__value,
ostreambuf_iterator< _CharT >
>::__type __copy_move_a2 (const _CharT *__first, const _CharT *__last, ostreambuf_iterator< _CharT > __result)
template<bool _IsMove, typename _CharT > __gnu_cxx::__enable_if
< __is_char< _CharT >::__value,
_CharT * >::__type __copy_move_a2 (istreambuf_iterator< _CharT > __first, istreambuf_iterator< _CharT > __last, _CharT *__result)
template<bool _IsMove, typename _CharT > __gnu_cxx::__enable_if
< __is_char< _CharT >::__value,
ostreambuf_iterator< _CharT,
char_traits< _CharT >
> >::__type __copy_move_a2 (_CharT *, _CharT *, ostreambuf_iterator< _CharT, char_traits< _CharT > >)
template<bool _IsMove, typename _CharT > __gnu_cxx::__enable_if
< __is_char< _CharT >::__value,
ostreambuf_iterator< _CharT,
char_traits< _CharT >
> >::__type __copy_move_a2 (const _CharT *, const _CharT *, ostreambuf_iterator< _CharT, char_traits< _CharT > >)
template<bool _IsMove, typename _CharT > __gnu_cxx::__enable_if
< __is_char< _CharT >::__value,
_CharT * >::__type __copy_move_a2 (istreambuf_iterator< _CharT, char_traits< _CharT > >, istreambuf_iterator< _CharT, char_traits< _CharT > >, _CharT *)
template<bool _IsMove, typename _II , typename _OI > _OI __copy_move_a2 (_II __first, _II __last, _OI __result)
template<bool _IsMove, typename _BI1 , typename _BI2 > _BI2 __copy_move_backward_a (_BI1 __first, _BI1 __last, _BI2 __result)
template<bool _IsMove, typename _BI1 , typename _BI2 > _BI2 __copy_move_backward_a2 (_BI1 __first, _BI1 __last, _BI2 __result)
template<typename _InputIterator , typename _Size , typename _OutputIterator > _OutputIterator __copy_n (_InputIterator __first, _Size __n, _OutputIterator __result, input_iterator_tag)
template<typename _RandomAccessIterator , typename _Size , typename _OutputIterator > _OutputIterator __copy_n (_RandomAccessIterator __first, _Size __n, _OutputIterator __result, random_access_iterator_tag)
template<typename _CharT , typename _Traits > streamsize __copy_streambufs (basic_streambuf< _CharT, _Traits > *__sbin, basic_streambuf< _CharT, _Traits > *__sbout)
template<typename _CharT , typename _Traits > streamsize __copy_streambufs_eof (basic_streambuf< _CharT, _Traits > *, basic_streambuf< _CharT, _Traits > *, bool &)
template<> streamsize __copy_streambufs_eof (basic_streambuf< char > *__sbin, basic_streambuf< char > *__sbout, bool &__ineof)
template<> streamsize __copy_streambufs_eof (basic_streambuf< wchar_t > *__sbin, basic_streambuf< wchar_t > *__sbout, bool &__ineof)
size_t __deque_buf_size (size_t __size)
template<typename _InputIterator > iterator_traits
< _InputIterator >
::difference_type __distance (_InputIterator __first, _InputIterator __last, input_iterator_tag)
template<typename _RandomAccessIterator > iterator_traits
< _RandomAccessIterator >
::difference_type __distance (_RandomAccessIterator __first, _RandomAccessIterator __last, random_access_iterator_tag)
template<typename _Alloc > void __do_alloc_on_copy (_Alloc &__one, const _Alloc &__two, true_type)
template<typename _Alloc > void __do_alloc_on_move (_Alloc &__one, _Alloc &__two, true_type)
template<typename _Alloc > void __do_alloc_on_swap (_Alloc &__one, _Alloc &__two, true_type)
template<typename _Alloc > auto __do_outermost (_Alloc &__a, _Alloc *)-> decltype(__a.outer_allocator())
template<typename _Alloc > _Alloc & __do_outermost (_Alloc &__a,...)
auto &__a return __do_outermost (__a,&__a)
template<_Lock_policy _Lp, typename _Tp1 , typename _Tp2 > void __enable_shared_from_this_helper (const __shared_count< _Lp > &, const __enable_shared_from_this< _Tp1, _Lp > *, const _Tp2 *) noexcept
template<typename _Tp1 , typename _Tp2 > void __enable_shared_from_this_helper (const __shared_count<> &, const enable_shared_from_this< _Tp1 > *, const _Tp2 *) noexcept
template<_Lock_policy _Lp> void __enable_shared_from_this_helper (const __shared_count< _Lp > &,...) noexcept
template<typename _II1 , typename _II2 > bool __equal_aux (_II1 __first1, _II1 __last1, _II2 __first2)
template<typename _ForwardIterator , typename _Tp > __gnu_cxx::__enable_if
<!__is_scalar< _Tp >::__value,
void >::__type __fill_a (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _Tp > __gnu_cxx::__enable_if
< __is_byte< _Tp >::__value,
void >::__type __fill_a (_Tp *__first, _Tp *__last, const _Tp &__c)
void __fill_bvector (_Bit_iterator __first, _Bit_iterator __last, bool __x)
template<typename _OutputIterator , typename _Size , typename _Tp > __gnu_cxx::__enable_if
<!__is_scalar< _Tp >::__value,
_OutputIterator >::__type __fill_n_a (_OutputIterator __first, _Size __n, const _Tp &__value)
template<typename _Size , typename _Tp > __gnu_cxx::__enable_if
< __is_byte< _Tp >::__value,
_Tp * >::__type __fill_n_a (_Tp *__first, _Size __n, const _Tp &__c)
template<typename _RandomAccessIterator > void __final_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void __final_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _InputIterator , typename _Tp > _InputIterator __find (_InputIterator __first, _InputIterator __last, const _Tp &__val, input_iterator_tag)
template<typename _RandomAccessIterator , typename _Tp > _RandomAccessIterator __find (_RandomAccessIterator __first, _RandomAccessIterator __last, const _Tp &__val, random_access_iterator_tag)
template<typename _ForwardIterator1 , typename _ForwardIterator2 > _ForwardIterator1 __find_end (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, forward_iterator_tag, forward_iterator_tag)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate > _ForwardIterator1 __find_end (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, forward_iterator_tag, forward_iterator_tag, _BinaryPredicate __comp)
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 > _BidirectionalIterator1 __find_end (_BidirectionalIterator1 __first1, _BidirectionalIterator1 __last1, _BidirectionalIterator2 __first2, _BidirectionalIterator2 __last2, bidirectional_iterator_tag, bidirectional_iterator_tag)
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _BinaryPredicate > _BidirectionalIterator1 __find_end (_BidirectionalIterator1 __first1, _BidirectionalIterator1 __last1, _BidirectionalIterator2 __first2, _BidirectionalIterator2 __last2, bidirectional_iterator_tag, bidirectional_iterator_tag, _BinaryPredicate __comp)
template<typename _InputIterator , typename _Predicate > _InputIterator __find_if (_InputIterator __first, _InputIterator __last, _Predicate __pred, input_iterator_tag)
template<typename _RandomAccessIterator , typename _Predicate > _RandomAccessIterator __find_if (_RandomAccessIterator __first, _RandomAccessIterator __last, _Predicate __pred, random_access_iterator_tag)
template<typename _InputIterator , typename _Predicate > _InputIterator __find_if_not (_InputIterator __first, _InputIterator __last, _Predicate __pred, input_iterator_tag)
template<typename _RandomAccessIterator , typename _Predicate > _RandomAccessIterator __find_if_not (_RandomAccessIterator __first, _RandomAccessIterator __last, _Predicate __pred, random_access_iterator_tag)
template<typename _InputIterator , typename _Predicate > _InputIterator __find_if_not (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _InputIterator , typename _Predicate , typename _Distance > _InputIterator __find_if_not_n (_InputIterator __first, _Distance &__len, _Predicate __pred)
template<typename _EuclideanRingElement > _EuclideanRingElement __gcd (_EuclideanRingElement __m, _EuclideanRingElement __n)
template<std::size_t __i, typename _Head , typename... _Tail> constexpr __add_ref< _Head >::type __get_helper (_Tuple_impl< __i, _Head, _Tail...> &__t) noexcept
template<std::size_t __i, typename _Head , typename... _Tail> constexpr __add_c_ref< _Head >
::type __get_helper (const _Tuple_impl< __i, _Head, _Tail...> &__t) noexcept
template<typename _Ex > const nested_exception * __get_nested_exception (const _Ex &__ex)
mutex & __get_once_mutex ()
template<typename _RandomAccessIterator > void __heap_select (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void __heap_select (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, _Compare __comp)
template<typename _Tp > size_t __iconv_adaptor (size_t(*__func)(iconv_t, _Tp, size_t *, char **, size_t *), iconv_t __cd, char **__inbuf, size_t *__inbytes, char **__outbuf, size_t *__outbytes)
template<typename _ForwardIterator , typename _Predicate , typename _Distance > _ForwardIterator __inplace_stable_partition (_ForwardIterator __first, _Predicate __pred, _Distance __len)
template<typename _RandomAccessIterator > void __inplace_stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void __inplace_stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator > void __insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void __insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _CharT , typename _ValueT > int __int_to_char (_CharT *__bufend, _ValueT __v, const _CharT *__lit, ios_base::fmtflags __flags, bool __dec)
template<typename _RandomAccessIterator , typename _Size > void __introselect (_RandomAccessIterator __first, _RandomAccessIterator __nth, _RandomAccessIterator __last, _Size __depth_limit)
template<typename _RandomAccessIterator , typename _Size , typename _Compare > void __introselect (_RandomAccessIterator __first, _RandomAccessIterator __nth, _RandomAccessIterator __last, _Size __depth_limit, _Compare __comp)
template<typename _RandomAccessIterator , typename _Size > void __introsort_loop (_RandomAccessIterator __first, _RandomAccessIterator __last, _Size __depth_limit)
template<typename _RandomAccessIterator , typename _Size , typename _Compare > void __introsort_loop (_RandomAccessIterator __first, _RandomAccessIterator __last, _Size __depth_limit, _Compare __comp)
template<typename _RandomAccessIterator , typename _Distance > bool __is_heap (_RandomAccessIterator __first, _Distance __n)
template<typename _RandomAccessIterator , typename _Compare , typename _Distance > bool __is_heap (_RandomAccessIterator __first, _Compare __comp, _Distance __n)
template<typename _RandomAccessIterator > bool __is_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > bool __is_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Distance > _Distance __is_heap_until (_RandomAccessIterator __first, _Distance __n)
template<typename _RandomAccessIterator , typename _Distance , typename _Compare > _Distance __is_heap_until (_RandomAccessIterator __first, _Distance __n, _Compare __comp)
template<typename _Iter > iterator_traits< _Iter >
::iterator_category __iterator_category (const _Iter &)
template<typename _II1 , typename _II2 > bool __lexicographical_compare_aux (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2)
template<typename _Size > _Size __lg (_Size __n)
int __lg (int __n)
unsigned __lg (unsigned __n)
long __lg (long __n)
unsigned long __lg (unsigned long __n)
long long __lg (long long __n)
unsigned long long __lg (unsigned long long __n)
template<typename _Iterator , typename _ReturnType = typename conditional<__move_if_noexcept_cond <typename iterator_traits<_Iterator>::value_type>::value, _Iterator, move_iterator<_Iterator>>::type> _ReturnType __make_move_if_noexcept_iterator (_Iterator __i)
template<typename _Tp , _Lock_policy _Lp, typename... _Args> __shared_ptr< _Tp, _Lp > __make_shared (_Args &&...__args)
template<typename _BidirectionalIterator , typename _Distance , typename _Pointer > void __merge_adaptive (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Pointer __buffer, _Distance __buffer_size)
template<typename _BidirectionalIterator , typename _Distance , typename _Pointer , typename _Compare > void __merge_adaptive (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Pointer __buffer, _Distance __buffer_size, _Compare __comp)
template<typename _RandomAccessIterator1 , typename _RandomAccessIterator2 , typename _Distance > void __merge_sort_loop (_RandomAccessIterator1 __first, _RandomAccessIterator1 __last, _RandomAccessIterator2 __result, _Distance __step_size)
template<typename _RandomAccessIterator1 , typename _RandomAccessIterator2 , typename _Distance , typename _Compare > void __merge_sort_loop (_RandomAccessIterator1 __first, _RandomAccessIterator1 __last, _RandomAccessIterator2 __result, _Distance __step_size, _Compare __comp)
template<typename _RandomAccessIterator , typename _Pointer > void __merge_sort_with_buffer (_RandomAccessIterator __first, _RandomAccessIterator __last, _Pointer __buffer)
template<typename _RandomAccessIterator , typename _Pointer , typename _Compare > void __merge_sort_with_buffer (_RandomAccessIterator __first, _RandomAccessIterator __last, _Pointer __buffer, _Compare __comp)
template<typename _BidirectionalIterator , typename _Distance > void __merge_without_buffer (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2)
template<typename _BidirectionalIterator , typename _Distance , typename _Compare > void __merge_without_buffer (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Compare __comp)
template<typename _Iterator > _Miter_base< _Iterator >
::iterator_type __miter_base (_Iterator __it)
template<typename _Iterator > void __move_median_first (_Iterator __a, _Iterator __b, _Iterator __c)
template<typename _Iterator , typename _Compare > void __move_median_first (_Iterator __a, _Iterator __b, _Iterator __c, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator > _OutputIterator __move_merge (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare > _OutputIterator __move_merge (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator > void __move_merge_adaptive (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare > void __move_merge_adaptive (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _BidirectionalIterator3 > void __move_merge_adaptive_backward (_BidirectionalIterator1 __first1, _BidirectionalIterator1 __last1, _BidirectionalIterator2 __first2, _BidirectionalIterator2 __last2, _BidirectionalIterator3 __result)
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _BidirectionalIterator3 , typename _Compare > void __move_merge_adaptive_backward (_BidirectionalIterator1 __first1, _BidirectionalIterator1 __last1, _BidirectionalIterator2 __first2, _BidirectionalIterator2 __last2, _BidirectionalIterator3 __result, _Compare __comp)
template<typename _Iterator > _Niter_base< _Iterator >
::iterator_type __niter_base (_Iterator __it)
void __once_proxy (void)
template<typename _CharT , typename _Traits > void __ostream_fill (basic_ostream< _CharT, _Traits > &__out, streamsize __n)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & __ostream_insert (basic_ostream< _CharT, _Traits > &__out, const _CharT *__s, streamsize __n)
template<typename _CharT , typename _Traits > void __ostream_write (basic_ostream< _CharT, _Traits > &__out, const _CharT *__s, streamsize __n)
template<typename _Alloc > auto __outermost (_Alloc &__a)-> decltype(__do_outermost(__a
template<typename _ForwardIterator , typename _Predicate > _ForwardIterator __partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, forward_iterator_tag)
template<typename _BidirectionalIterator , typename _Predicate > _BidirectionalIterator __partition (_BidirectionalIterator __first, _BidirectionalIterator __last, _Predicate __pred, bidirectional_iterator_tag)
template<typename _RandomAccessIterator > void __pop_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _RandomAccessIterator __result)
template<typename _RandomAccessIterator , typename _Compare > void __pop_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _RandomAccessIterator __result, _Compare __comp)
template<typename _RandomAccessIterator , typename _Distance , typename _Tp > void __push_heap (_RandomAccessIterator __first, _Distance __holeIndex, _Distance __topIndex, _Tp __value)
template<typename _RandomAccessIterator , typename _Distance , typename _Tp , typename _Compare > void __push_heap (_RandomAccessIterator __first, _Distance __holeIndex, _Distance __topIndex, _Tp __value, _Compare __comp)
template<typename _BidirectionalIterator > void __reverse (_BidirectionalIterator __first, _BidirectionalIterator __last, bidirectional_iterator_tag)
template<typename _RandomAccessIterator > void __reverse (_RandomAccessIterator __first, _RandomAccessIterator __last, random_access_iterator_tag)
template<typename _ForwardIterator > void __rotate (_ForwardIterator __first, _ForwardIterator __middle, _ForwardIterator __last, forward_iterator_tag)
template<typename _BidirectionalIterator > void __rotate (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, bidirectional_iterator_tag)
template<typename _RandomAccessIterator > void __rotate (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, random_access_iterator_tag)
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _Distance > _BidirectionalIterator1 __rotate_adaptive (_BidirectionalIterator1 __first, _BidirectionalIterator1 __middle, _BidirectionalIterator1 __last, _Distance __len1, _Distance __len2, _BidirectionalIterator2 __buffer, _Distance __buffer_size)
template<typename _ForwardIterator , typename _Integer , typename _Tp > _ForwardIterator __search_n (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, const _Tp &__val, std::forward_iterator_tag)
template<typename _RandomAccessIter , typename _Integer , typename _Tp > _RandomAccessIter __search_n (_RandomAccessIter __first, _RandomAccessIter __last, _Integer __count, const _Tp &__val, std::random_access_iterator_tag)
template<typename _ForwardIterator , typename _Integer , typename _Tp , typename _BinaryPredicate > _ForwardIterator __search_n (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, const _Tp &__val, _BinaryPredicate __binary_pred, std::forward_iterator_tag)
template<typename _RandomAccessIter , typename _Integer , typename _Tp , typename _BinaryPredicate > _RandomAccessIter __search_n (_RandomAccessIter __first, _RandomAccessIter __last, _Integer __count, const _Tp &__val, _BinaryPredicate __binary_pred, std::random_access_iterator_tag)
void __set_once_functor_lock_ptr (unique_lock< mutex > *)
template<typename _ForwardIterator , typename _Pointer , typename _Predicate , typename _Distance > _ForwardIterator __stable_partition_adaptive (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, _Distance __len, _Pointer __buffer, _Distance __buffer_size)
template<typename _RandomAccessIterator , typename _Pointer , typename _Distance > void __stable_sort_adaptive (_RandomAccessIterator __first, _RandomAccessIterator __last, _Pointer __buffer, _Distance __buffer_size)
template<typename _RandomAccessIterator , typename _Pointer , typename _Distance , typename _Compare > void __stable_sort_adaptive (_RandomAccessIterator __first, _RandomAccessIterator __last, _Pointer __buffer, _Distance __buffer_size, _Compare __comp)
void __throw_bad_alloc (void) __attribute__((__noreturn__))
void __throw_bad_cast (void) __attribute__((__noreturn__))
void __throw_bad_exception (void) __attribute__((__noreturn__))
void __throw_bad_function_call () __attribute__((__noreturn__))
void __throw_bad_typeid (void) __attribute__((__noreturn__))
void __throw_bad_weak_ptr ()
void __throw_domain_error (const char *) __attribute__((__noreturn__))
void __throw_future_error (int) __attribute__((__noreturn__))
void __throw_invalid_argument (const char *) __attribute__((__noreturn__))
void __throw_ios_failure (const char *) __attribute__((__noreturn__))
void __throw_length_error (const char *) __attribute__((__noreturn__))
void __throw_logic_error (const char *) __attribute__((__noreturn__))
void __throw_out_of_range (const char *) __attribute__((__noreturn__))
void __throw_overflow_error (const char *) __attribute__((__noreturn__))
void __throw_range_error (const char *) __attribute__((__noreturn__))
void __throw_regex_error (regex_constants::error_type __ecode)
void __throw_runtime_error (const char *) __attribute__((__noreturn__))
void __throw_system_error (int) __attribute__((__noreturn__))
void __throw_underflow_error (const char *) __attribute__((__noreturn__))
template<typename _Ex > void __throw_with_nested (_Ex &&, const nested_exception *=0) __attribute__((__noreturn__))
template<typename _Ex > void __throw_with_nested (_Ex &&,...) __attribute__((__noreturn__))
template<typename _Lock > unique_lock< _Lock > __try_to_lock (_Lock &__l)
template<typename _RandomAccessIterator > void __unguarded_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void __unguarded_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator > void __unguarded_linear_insert (_RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void __unguarded_linear_insert (_RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Tp > _RandomAccessIterator __unguarded_partition (_RandomAccessIterator __first, _RandomAccessIterator __last, const _Tp &__pivot)
template<typename _RandomAccessIterator , typename _Tp , typename _Compare > _RandomAccessIterator __unguarded_partition (_RandomAccessIterator __first, _RandomAccessIterator __last, const _Tp &__pivot, _Compare __comp)
template<typename _RandomAccessIterator > _RandomAccessIterator __unguarded_partition_pivot (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > _RandomAccessIterator __unguarded_partition_pivot (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _ForwardIterator , typename _Tp > void __uninitialized_construct_buf (_ForwardIterator __first, _ForwardIterator __last, _Tp &__value)
template<typename _InputIterator , typename _ForwardIterator , typename _Allocator > _ForwardIterator __uninitialized_copy_a (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, _Allocator &__alloc)
template<typename _InputIterator , typename _ForwardIterator , typename _Tp > _ForwardIterator __uninitialized_copy_a (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, allocator< _Tp > &)
template<typename _InputIterator1 , typename _InputIterator2 , typename _ForwardIterator , typename _Allocator > _ForwardIterator __uninitialized_copy_move (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _ForwardIterator __result, _Allocator &__alloc)
template<typename _InputIterator , typename _Size , typename _ForwardIterator > _ForwardIterator __uninitialized_copy_n (_InputIterator __first, _Size __n, _ForwardIterator __result, input_iterator_tag)
template<typename _RandomAccessIterator , typename _Size , typename _ForwardIterator > _ForwardIterator __uninitialized_copy_n (_RandomAccessIterator __first, _Size __n, _ForwardIterator __result, random_access_iterator_tag)
template<typename _ForwardIterator > void __uninitialized_default (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Allocator > void __uninitialized_default_a (_ForwardIterator __first, _ForwardIterator __last, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Tp > void __uninitialized_default_a (_ForwardIterator __first, _ForwardIterator __last, allocator< _Tp > &)
template<typename _ForwardIterator , typename _Size > void __uninitialized_default_n (_ForwardIterator __first, _Size __n)
template<typename _ForwardIterator , typename _Size , typename _Allocator > void __uninitialized_default_n_a (_ForwardIterator __first, _Size __n, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Size , typename _Tp > void __uninitialized_default_n_a (_ForwardIterator __first, _Size __n, allocator< _Tp > &)
template<typename _ForwardIterator , typename _Tp , typename _Allocator > void __uninitialized_fill_a (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__x, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Tp , typename _Tp2 > void __uninitialized_fill_a (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__x, allocator< _Tp2 > &)
template<typename _ForwardIterator , typename _Tp , typename _InputIterator , typename _Allocator > _ForwardIterator __uninitialized_fill_move (_ForwardIterator __result, _ForwardIterator __mid, const _Tp &__x, _InputIterator __first, _InputIterator __last, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Size , typename _Tp , typename _Allocator > void __uninitialized_fill_n_a (_ForwardIterator __first, _Size __n, const _Tp &__x, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Size , typename _Tp , typename _Tp2 > void __uninitialized_fill_n_a (_ForwardIterator __first, _Size __n, const _Tp &__x, allocator< _Tp2 > &)
template<typename _InputIterator , typename _ForwardIterator , typename _Allocator > _ForwardIterator __uninitialized_move_a (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, _Allocator &__alloc)
template<typename _InputIterator1 , typename _InputIterator2 , typename _ForwardIterator , typename _Allocator > _ForwardIterator __uninitialized_move_copy (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _ForwardIterator __result, _Allocator &__alloc)
template<typename _InputIterator , typename _ForwardIterator , typename _Tp , typename _Allocator > void __uninitialized_move_fill (_InputIterator __first1, _InputIterator __last1, _ForwardIterator __first2, _ForwardIterator __last2, const _Tp &__x, _Allocator &__alloc)
template<typename _InputIterator , typename _ForwardIterator , typename _Allocator > _ForwardIterator __uninitialized_move_if_noexcept_a (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, _Allocator &__alloc)
template<typename _ForwardIterator , typename _OutputIterator > _OutputIterator __unique_copy (_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __result, forward_iterator_tag, output_iterator_tag)
template<typename _InputIterator , typename _OutputIterator > _OutputIterator __unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, input_iterator_tag, output_iterator_tag)
template<typename _InputIterator , typename _ForwardIterator > _ForwardIterator __unique_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, input_iterator_tag, forward_iterator_tag)
template<typename _ForwardIterator , typename _OutputIterator , typename _BinaryPredicate > _OutputIterator __unique_copy (_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred, forward_iterator_tag, output_iterator_tag)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryPredicate > _OutputIterator __unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred, input_iterator_tag, output_iterator_tag)
template<typename _InputIterator , typename _ForwardIterator , typename _BinaryPredicate > _ForwardIterator __unique_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, _BinaryPredicate __binary_pred, input_iterator_tag, forward_iterator_tag)
template<typename _Bi_iter > const sub_match< _Bi_iter > & __unmatched_sub ()
template<typename _Tp , typename _Alloc , typename... _Args> __uses_alloc_impl< _Tp, _Alloc,
_Args...> __use_alloc (const _Alloc &__a)
template<typename _Tp > void __valarray_copy (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void __valarray_copy (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp > void __valarray_copy (_Array< _Tp > __a, _Array< bool > __m, size_t __n, _Array< _Tp > __b, _Array< bool > __k)
template<typename _Tp , class _Dom > void __valarray_copy (const _Expr< _Dom, _Tp > &__e, size_t __n, _Array< _Tp > __a)
template<typename _Tp , class _Dom > void __valarray_copy (const _Expr< _Dom, _Tp > &__e, size_t __n, _Array< _Tp > __a, size_t __s)
template<typename _Tp , class _Dom > void __valarray_copy (const _Expr< _Dom, _Tp > &__e, size_t __n, _Array< _Tp > __a, _Array< size_t > __i)
template<typename _Tp > void __valarray_copy (_Array< _Tp > __e, _Array< size_t > __f, size_t __n, _Array< _Tp > __a, _Array< size_t > __i)
template<typename _Tp , class _Dom > void __valarray_copy (const _Expr< _Dom, _Tp > &__e, size_t __n, _Array< _Tp > __a, _Array< bool > __m)
template<typename _Tp > void __valarray_copy (const _Tp *__restrict__ __a, size_t __n, _Tp *__restrict__ __b)
template<typename _Tp > void __valarray_copy (const _Tp *__restrict__ __a, size_t __n, size_t __s, _Tp *__restrict__ __b)
template<typename _Tp > void __valarray_copy (const _Tp *__restrict__ __a, _Tp *__restrict__ __b, size_t __n, size_t __s)
template<typename _Tp > void __valarray_copy (const _Tp *__restrict__ __src, size_t __n, size_t __s1, _Tp *__restrict__ __dst, size_t __s2)
template<typename _Tp > void __valarray_copy (const _Tp *__restrict__ __a, const size_t *__restrict__ __i, _Tp *__restrict__ __b, size_t __n)
template<typename _Tp > void __valarray_copy (const _Tp *__restrict__ __a, size_t __n, _Tp *__restrict__ __b, const size_t *__restrict__ __i)
template<typename _Tp > void __valarray_copy (const _Tp *__restrict__ __src, size_t __n, const size_t *__restrict__ __i, _Tp *__restrict__ __dst, const size_t *__restrict__ __j)
template<typename _Tp > void __valarray_copy (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp > void __valarray_copy (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp > void __valarray_copy (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp > void __valarray_copy (_Array< _Tp > __a, size_t __n, size_t __s1, _Array< _Tp > __b, size_t __s2)
template<typename _Tp > void __valarray_copy (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void __valarray_copy (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp > void __valarray_copy (_Array< _Tp > __src, size_t __n, _Array< size_t > __i, _Array< _Tp > __dst, _Array< size_t > __j)
template<typename _Tp > void __valarray_copy_construct (const _Tp *__b, const _Tp *__e, _Tp *__restrict__ __o)
template<typename _Tp > void __valarray_copy_construct (const _Tp *__restrict__ __a, size_t __n, size_t __s, _Tp *__restrict__ __o)
template<typename _Tp > void __valarray_copy_construct (const _Tp *__restrict__ __a, const size_t *__restrict__ __i, _Tp *__restrict__ __o, size_t __n)
template<typename _Tp , class _Dom > void __valarray_copy_construct (const _Expr< _Dom, _Tp > &__e, size_t __n, _Array< _Tp > __a)
template<typename _Tp > void __valarray_copy_construct (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void __valarray_copy_construct (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void __valarray_copy_construct (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp > void __valarray_default_construct (_Tp *__b, _Tp *__e)
template<typename _Tp > void __valarray_destroy_elements (_Tp *__b, _Tp *__e)
template<typename _Tp > void __valarray_fill (_Array< _Tp > __a, size_t __n, _Array< bool > __m, const _Tp &__t)
template<typename _Tp > void __valarray_fill (_Tp *__restrict__ __a, size_t __n, const _Tp &__t)
template<typename _Tp > void __valarray_fill (_Tp *__restrict__ __a, size_t __n, size_t __s, const _Tp &__t)
template<typename _Tp > void __valarray_fill (_Tp *__restrict__ __a, const size_t *__restrict__ __i, size_t __n, const _Tp &__t)
template<typename _Tp > void __valarray_fill (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp > void __valarray_fill (_Array< _Tp > __a, size_t __n, size_t __s, const _Tp &__t)
template<typename _Tp > void __valarray_fill (_Array< _Tp > __a, _Array< size_t > __i, size_t __n, const _Tp &__t)
template<typename _Tp > void __valarray_fill_construct (_Tp *__b, _Tp *__e, const _Tp __t)
void * __valarray_get_memory (size_t __n)
template<typename _Tp > _Tp *__restrict__ __valarray_get_storage (size_t __n)
template<typename _Ta > _Ta::value_type __valarray_max (const _Ta &__a)
template<typename _Ta > _Ta::value_type __valarray_min (const _Ta &__a)
template<typename _Tp > _Tp __valarray_product (const _Tp *__f, const _Tp *__l)
void __valarray_release_memory (void *__p)
template<typename _Tp > _Tp __valarray_sum (const _Tp *__f, const _Tp *__l)
bool __verify_grouping (const char *__grouping, size_t __grouping_size, const string &__grouping_tmp) throw ()
template<std::size_t _Ind, typename... _Tp> auto __volget (volatile tuple< _Tp...> &__tuple)-> typename tuple_element< _Ind
typename _Tp auto __volget (const volatile tuple< _Tp...> &__tuple)-> typename tuple_element< _Ind
template<typename _CharT > ostreambuf_iterator< _CharT > __write (ostreambuf_iterator< _CharT > __s, const _CharT *__ws, int __len)
template<typename _CharT , typename _OutIter > _OutIter __write (_OutIter __s, const _CharT *__ws, int __len)
template<typename _Tp > void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp > void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom > void _Array_augmented___bitwise_and (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom > void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom > void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp , class _Dom > void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp > void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp > void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom > void _Array_augmented___bitwise_or (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom > void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom > void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom > void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp , class _Dom > void _Array_augmented___bitwise_xor (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom > void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom > void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom > void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp > void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp > void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp > void _Array_augmented___divides (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom > void _Array_augmented___divides (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___divides (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom > void _Array_augmented___divides (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___divides (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom > void _Array_augmented___divides (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp , class _Dom > void _Array_augmented___divides (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom > void _Array_augmented___minus (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp > void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom > void _Array_augmented___minus (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___minus (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom > void _Array_augmented___minus (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___minus (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp , class _Dom > void _Array_augmented___minus (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp > void _Array_augmented___minus (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp > void _Array_augmented___modulus (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom > void _Array_augmented___modulus (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___modulus (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom > void _Array_augmented___modulus (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp , class _Dom > void _Array_augmented___modulus (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___modulus (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom > void _Array_augmented___modulus (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom > void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp , class _Dom > void _Array_augmented___multiplies (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp > void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom > void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp , class _Dom > void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp > void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___plus (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom > void _Array_augmented___plus (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___plus (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom > void _Array_augmented___plus (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom > void _Array_augmented___plus (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp > void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp , class _Dom > void _Array_augmented___plus (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___plus (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp , class _Dom > void _Array_augmented___shift_left (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp , class _Dom > void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom > void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp , class _Dom > void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom > void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp > void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp , class _Dom > void _Array_augmented___shift_right (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp > void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp > void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp > void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp > void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp , class _Dom > void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom > void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _T1 , typename... _Args> void _Construct (_T1 *__p, _Args &&...__args)
template<typename _Tp > void _Destroy (_Tp *__pointer)
template<typename _ForwardIterator > void _Destroy (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Allocator > void _Destroy (_ForwardIterator __first, _ForwardIterator __last, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Tp > void _Destroy (_ForwardIterator __first, _ForwardIterator __last, allocator< _Tp > &)
size_t _Find_first () const _GLIBCXX_NOEXCEPT
size_t _Find_next (size_t __prev) const _GLIBCXX_NOEXCEPT
size_t _Fnv_hash_bytes (const void *__ptr, size_t __len, size_t __seed)
size_t _Hash_bytes (const void *__ptr, size_t __len, size_t __seed)
template<class _CharT , class _Traits > void _M_copy_from_ptr (const _CharT *, size_t, size_t, size_t, _CharT, _CharT)
template<class _CharT , class _Traits , class _Alloc > void _M_copy_from_string (const std::basic_string< _CharT, _Traits, _Alloc > &__s, size_t __pos, size_t __n, _CharT __zero, _CharT __one)
template<class _CharT , class _Traits , class _Alloc > void _M_copy_from_string (const std::basic_string< _CharT, _Traits, _Alloc > &__s, size_t __pos, size_t __n)
template<class _CharT , class _Traits , class _Alloc > void _M_copy_to_string (std::basic_string< _CharT, _Traits, _Alloc > &, _CharT, _CharT) const
template<class _CharT , class _Traits , class _Alloc > void _M_copy_to_string (std::basic_string< _CharT, _Traits, _Alloc > &__s) const
template<size_t _Nb> _M_do_and (__rhs)
unsigned int _Rb_tree_black_count (const _Rb_tree_node_base *__node, const _Rb_tree_node_base *__root) throw ()
_Rb_tree_node_base * _Rb_tree_decrement (_Rb_tree_node_base *__x) throw ()
const _Rb_tree_node_base * _Rb_tree_decrement (const _Rb_tree_node_base *__x) throw ()
_Rb_tree_node_base * _Rb_tree_increment (_Rb_tree_node_base *__x) throw ()
const _Rb_tree_node_base * _Rb_tree_increment (const _Rb_tree_node_base *__x) throw ()
void _Rb_tree_insert_and_rebalance (const bool __insert_left, _Rb_tree_node_base *__x, _Rb_tree_node_base *__p, _Rb_tree_node_base &__header) throw ()
_Rb_tree_node_base * _Rb_tree_rebalance_for_erase (_Rb_tree_node_base *const __z, _Rb_tree_node_base &__header) throw ()
void abort (void) throw ()
template<typename _Tp > _Tp abs (const complex< _Tp > &)
constexpr double abs (double __x)
constexpr float abs (float __x)
constexpr long double abs (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type abs (_Tp __x)
template<class _Dom > _Expr< _UnClos< _Abs, _Expr,
_Dom >, typename
_Dom::value_type > abs (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _UnClos< _Abs,
_ValArray, _Tp >, _Tp > abs (const valarray< _Tp > &__v)
template<typename _InputIterator , typename _Tp > _Tp accumulate (_InputIterator __first, _InputIterator __last, _Tp __init)
template<typename _InputIterator , typename _Tp , typename _BinaryOperation > _Tp accumulate (_InputIterator __first, _InputIterator __last, _Tp __init, _BinaryOperation __binary_op)
constexpr float acos (float __x)
constexpr long double acos (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type acos (_Tp __x)
template<class _Dom > _Expr< _UnClos< _Acos, _Expr,
_Dom >, typename
_Dom::value_type > acos (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _UnClos< _Acos,
_ValArray, _Tp >, _Tp > acos (const valarray< _Tp > &__v)
template<typename _Tp > std::complex< _Tp > acos (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > acosh (const std::complex< _Tp > &__z)
template<typename _Tp > _Tp * addressof (_Tp &__r) noexcept
template<typename _InputIterator , typename _OutputIterator > _OutputIterator adjacent_difference (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation > _OutputIterator adjacent_difference (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op)
template<typename _FIter > _FIter adjacent_find (_FIter, _FIter)
template<typename _FIter , typename _BinaryPredicate > _FIter adjacent_find (_FIter, _FIter, _BinaryPredicate)
template<typename _ForwardIterator > _ForwardIterator adjacent_find (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _BinaryPredicate > _ForwardIterator adjacent_find (_ForwardIterator __first, _ForwardIterator __last, _BinaryPredicate __binary_pred)
template<typename _InputIterator , typename _Distance > void advance (_InputIterator &__i, _Distance __n)
bool all () const _GLIBCXX_NOEXCEPT
template<typename _IIter , typename _Predicate > bool all_of (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate > bool all_of (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _Tp , typename _Alloc , typename... _Args> shared_ptr< _Tp > allocate_shared (const _Alloc &__a, _Args &&...__args)
bool any () const _GLIBCXX_NOEXCEPT
template<typename _IIter , typename _Predicate > bool any_of (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate > bool any_of (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _Tp > _Tp arg (const complex< _Tp > &)
template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type arg (_Tp __x)
constexpr float asin (float __x)
constexpr long double asin (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type asin (_Tp __x)
template<class _Dom > _Expr< _UnClos< _Asin, _Expr,
_Dom >, typename
_Dom::value_type > asin (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _UnClos< _Asin,
_ValArray, _Tp >, _Tp > asin (const valarray< _Tp > &__v)
template<typename _Tp > std::complex< _Tp > asin (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > asinh (const std::complex< _Tp > &__z)
template<typename _Fn , typename... _Args> future< typename result_of
< _Fn(_Args...)>::type > async (launch __policy, _Fn &&__fn, _Args &&...__args)
template<typename _Fn , typename... _Args> __async_sfinae_helper
< typename decay< _Fn >::type,
_Fn, _Args...>::type async (_Fn &&__fn, _Args &&...__args)
constexpr float atan (float __x)
constexpr long double atan (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type atan (_Tp __x)
template<class _Dom > _Expr< _UnClos< _Atan, _Expr,
_Dom >, typename
_Dom::value_type > atan (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _UnClos< _Atan,
_ValArray, _Tp >, _Tp > atan (const valarray< _Tp > &__v)
template<typename _Tp > std::complex< _Tp > atan (const std::complex< _Tp > &__z)
constexpr float atan2 (float __y, float __x)
constexpr long double atan2 (long double __y, long double __x)
template<typename _Tp , typename _Up > constexpr
__gnu_cxx::__promote_2< _Tp,
_Up >::__type atan2 (_Tp __y, _Up __x)
template<class _Dom > _Expr< _BinClos< _Atan2,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename _Dom::value_type > atan2 (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _BinClos< _Atan2,
_ValArray, _ValArray, _Tp, _Tp >
, _Tp > atan2 (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< _Atan2, _Expr,
_Expr, _Dom1, _Dom2 >
, typename _Dom1::value_type > atan2 (const _Expr< _Dom1, typename _Dom1::value_type > &__e1, const _Expr< _Dom2, typename _Dom2::value_type > &__e2)
template<class _Dom > _Expr< _BinClos< _Atan2, _Expr,
_ValArray, _Dom, typename
_Dom::value_type >, typename
_Dom::value_type > atan2 (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< _Atan2,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename _Dom::value_type > atan2 (const valarray< typename _Dom::valarray > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom > _Expr< _BinClos< _Atan2, _Expr,
_Constant, _Dom, typename
_Dom::value_type >, typename
_Dom::value_type > atan2 (const _Expr< _Dom, typename _Dom::value_type > &__e, const typename _Dom::value_type &__t)
template<typename _Tp > _Expr< _BinClos< _Atan2,
_Constant, _ValArray, _Tp, _Tp >
, _Tp > atan2 (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Tp > _Expr< _BinClos< _Atan2,
_ValArray, _Constant, _Tp, _Tp >
, _Tp > atan2 (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > std::complex< _Tp > atanh (const std::complex< _Tp > &__z)
int atexit (void(*)()) throw ()
template<typename _ITp > bool atomic_compare_exchange_strong (atomic< _ITp > *__a, _ITp *__i1, _ITp __i2) noexcept
template<typename _ITp > bool atomic_compare_exchange_strong (volatile atomic< _ITp > *__a, _ITp *__i1, _ITp __i2) noexcept
template<typename _ITp > bool atomic_compare_exchange_strong_explicit (atomic< _ITp > *__a, _ITp *__i1, _ITp __i2, memory_order __m1, memory_order __m2) noexcept
template<typename _ITp > bool atomic_compare_exchange_strong_explicit (volatile atomic< _ITp > *__a, _ITp *__i1, _ITp __i2, memory_order __m1, memory_order __m2) noexcept
template<typename _ITp > bool atomic_compare_exchange_weak (atomic< _ITp > *__a, _ITp *__i1, _ITp __i2) noexcept
template<typename _ITp > bool atomic_compare_exchange_weak (volatile atomic< _ITp > *__a, _ITp *__i1, _ITp __i2) noexcept
template<typename _ITp > bool atomic_compare_exchange_weak_explicit (atomic< _ITp > *__a, _ITp *__i1, _ITp __i2, memory_order __m1, memory_order __m2) noexcept
template<typename _ITp > bool atomic_compare_exchange_weak_explicit (volatile atomic< _ITp > *__a, _ITp *__i1, _ITp __i2, memory_order __m1, memory_order __m2) noexcept
template<typename _ITp > _ITp atomic_exchange (atomic< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > _ITp atomic_exchange (volatile atomic< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > _ITp atomic_exchange_explicit (atomic< _ITp > *__a, _ITp __i, memory_order __m) noexcept
template<typename _ITp > _ITp atomic_exchange_explicit (volatile atomic< _ITp > *__a, _ITp __i, memory_order __m) noexcept
template<typename _ITp > _ITp atomic_fetch_add (__atomic_base< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > _ITp atomic_fetch_add (volatile __atomic_base< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > _ITp * atomic_fetch_add (volatile atomic< _ITp * > *__a, ptrdiff_t __d) noexcept
template<typename _ITp > _ITp * atomic_fetch_add (atomic< _ITp * > *__a, ptrdiff_t __d) noexcept
template<typename _ITp > _ITp atomic_fetch_add_explicit (__atomic_base< _ITp > *__a, _ITp __i, memory_order __m) noexcept
template<typename _ITp > _ITp atomic_fetch_add_explicit (volatile __atomic_base< _ITp > *__a, _ITp __i, memory_order __m) noexcept
template<typename _ITp > _ITp * atomic_fetch_add_explicit (atomic< _ITp * > *__a, ptrdiff_t __d, memory_order __m) noexcept
template<typename _ITp > _ITp * atomic_fetch_add_explicit (volatile atomic< _ITp * > *__a, ptrdiff_t __d, memory_order __m) noexcept
template<typename _ITp > _ITp atomic_fetch_and (__atomic_base< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > _ITp atomic_fetch_and (volatile __atomic_base< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > _ITp atomic_fetch_and_explicit (__atomic_base< _ITp > *__a, _ITp __i, memory_order __m) noexcept
template<typename _ITp > _ITp atomic_fetch_and_explicit (volatile __atomic_base< _ITp > *__a, _ITp __i, memory_order __m) noexcept
template<typename _ITp > _ITp atomic_fetch_or (__atomic_base< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > _ITp atomic_fetch_or (volatile __atomic_base< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > _ITp atomic_fetch_or_explicit (__atomic_base< _ITp > *__a, _ITp __i, memory_order __m) noexcept
template<typename _ITp > _ITp atomic_fetch_or_explicit (volatile __atomic_base< _ITp > *__a, _ITp __i, memory_order __m) noexcept
template<typename _ITp > _ITp atomic_fetch_sub (__atomic_base< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > _ITp atomic_fetch_sub (volatile __atomic_base< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > _ITp * atomic_fetch_sub (volatile atomic< _ITp * > *__a, ptrdiff_t __d) noexcept
template<typename _ITp > _ITp * atomic_fetch_sub (atomic< _ITp * > *__a, ptrdiff_t __d) noexcept
template<typename _ITp > _ITp atomic_fetch_sub_explicit (__atomic_base< _ITp > *__a, _ITp __i, memory_order __m) noexcept
template<typename _ITp > _ITp atomic_fetch_sub_explicit (volatile __atomic_base< _ITp > *__a, _ITp __i, memory_order __m) noexcept
template<typename _ITp > _ITp * atomic_fetch_sub_explicit (volatile atomic< _ITp * > *__a, ptrdiff_t __d, memory_order __m) noexcept
template<typename _ITp > _ITp * atomic_fetch_sub_explicit (atomic< _ITp * > *__a, ptrdiff_t __d, memory_order __m) noexcept
template<typename _ITp > _ITp atomic_fetch_xor (__atomic_base< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > _ITp atomic_fetch_xor (volatile __atomic_base< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > _ITp atomic_fetch_xor_explicit (__atomic_base< _ITp > *__a, _ITp __i, memory_order __m) noexcept
template<typename _ITp > _ITp atomic_fetch_xor_explicit (volatile __atomic_base< _ITp > *__a, _ITp __i, memory_order __m) noexcept
void atomic_flag_clear (atomic_flag *__a) noexcept
void atomic_flag_clear (volatile atomic_flag *__a) noexcept
void atomic_flag_clear_explicit (atomic_flag *__a, memory_order __m) noexcept
void atomic_flag_clear_explicit (volatile atomic_flag *__a, memory_order __m) noexcept
bool atomic_flag_test_and_set (atomic_flag *__a) noexcept
bool atomic_flag_test_and_set (volatile atomic_flag *__a) noexcept
bool atomic_flag_test_and_set_explicit (atomic_flag *__a, memory_order __m) noexcept
bool atomic_flag_test_and_set_explicit (volatile atomic_flag *__a, memory_order __m) noexcept
template<typename _ITp > void atomic_init (atomic< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > void atomic_init (volatile atomic< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > bool atomic_is_lock_free (const atomic< _ITp > *__a) noexcept
template<typename _ITp > bool atomic_is_lock_free (const volatile atomic< _ITp > *__a) noexcept
template<typename _ITp > _ITp atomic_load (const atomic< _ITp > *__a) noexcept
template<typename _ITp > _ITp atomic_load (const volatile atomic< _ITp > *__a) noexcept
template<typename _ITp > _ITp atomic_load_explicit (const atomic< _ITp > *__a, memory_order __m) noexcept
template<typename _ITp > _ITp atomic_load_explicit (const volatile atomic< _ITp > *__a, memory_order __m) noexcept
void atomic_signal_fence (memory_order __m) noexcept
template<typename _ITp > void atomic_store (atomic< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > void atomic_store (volatile atomic< _ITp > *__a, _ITp __i) noexcept
template<typename _ITp > void atomic_store_explicit (atomic< _ITp > *__a, _ITp __i, memory_order __m) noexcept
template<typename _ITp > void atomic_store_explicit (volatile atomic< _ITp > *__a, _ITp __i, memory_order __m) noexcept
void atomic_thread_fence (memory_order __m) noexcept
template<typename _Container > back_insert_iterator< _Container > back_inserter (_Container &__x)
template<class _Container > auto begin (_Container &__cont)-> decltype(__cont.begin())
template<class _Container > auto begin (const _Container &__cont)-> decltype(__cont.begin())
template<class _Tp , size_t _Nm> _Tp * begin (_Tp(&__arr)[_Nm])
template<class _Tp > constexpr const _Tp * begin (initializer_list< _Tp > __ils) noexcept
template<class _Tp > _Tp * begin (valarray< _Tp > &__va)
template<class _Tp > const _Tp * begin (const valarray< _Tp > &__va)
template<typename _FIter , typename _Tp > bool binary_search (_FIter, _FIter, const _Tp &)
template<typename _FIter , typename _Tp , typename _Compare > bool binary_search (_FIter, _FIter, const _Tp &, _Compare)
template<typename _ForwardIterator , typename _Tp > bool binary_search (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val)
template<typename _ForwardIterator , typename _Tp , typename _Compare > bool binary_search (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
template<typename _Func , typename... _BoundArgs> _Bind_helper< __is_socketlike
< _Func >::value, _Func,
_BoundArgs...>::type bind (_Func &&__f, _BoundArgs &&...__args)
template<typename _Result , typename _Func , typename... _BoundArgs> _Bindres_helper< _Result,
_Func, _BoundArgs...>::type bind (_Func &&__f, _BoundArgs &&...__args)
template<typename _Operation , typename _Tp > binder1st< _Operation > bind1st (const _Operation &__fn, const _Tp &__x)
template<typename _Operation , typename _Tp > binder2nd< _Operation > bind2nd (const _Operation &__fn, const _Tp &__x)
ios_base & boolalpha (ios_base &__base)
template<typename _Callable , typename... _Args> void call_once (once_flag &__once, _Callable &&__f, _Args &&...__args)
constexpr float ceil (float __x)
constexpr long double ceil (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type ceil (_Tp __x)
template<typename _Tp > complex< _Tp > conj (const complex< _Tp > &)
template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type conj (_Tp __x)
template<typename _Tp , typename _Tp1 > shared_ptr< _Tp > const_pointer_cast (const shared_ptr< _Tp1 > &__r) noexcept
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp> __shared_ptr< _Tp, _Lp > const_pointer_cast (const __shared_ptr< _Tp1, _Lp > &__r) noexcept
template<typename _IIter , typename _OIter > _OIter copy (_IIter, _IIter, _OIter)
template<typename _CharT > __gnu_cxx::__enable_if
< __is_char< _CharT >::__value,
ostreambuf_iterator< _CharT >
>::__type copy (istreambuf_iterator< _CharT > __first, istreambuf_iterator< _CharT > __last, ostreambuf_iterator< _CharT > __result)
template<typename _Tp > _Deque_iterator< _Tp, _Tp
&, _Tp * > copy (_Deque_iterator< _Tp, _Tp &, _Tp * > __first, _Deque_iterator< _Tp, _Tp &, _Tp * > __last, _Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<typename _II , typename _OI > _OI copy (_II __first, _II __last, _OI __result)
template<typename _Tp > _Deque_iterator< _Tp, _Tp
&, _Tp * > copy (_Deque_iterator< _Tp, const _Tp &, const _Tp * > __first, _Deque_iterator< _Tp, const _Tp &, const _Tp * > __last, _Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<typename _BIter1 , typename _BIter2 > _BIter2 copy_backward (_BIter1, _BIter1, _BIter2)
template<typename _Tp > _Deque_iterator< _Tp, _Tp
&, _Tp * > copy_backward (_Deque_iterator< _Tp, _Tp &, _Tp * > __first, _Deque_iterator< _Tp, _Tp &, _Tp * > __last, _Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<typename _BI1 , typename _BI2 > _BI2 copy_backward (_BI1 __first, _BI1 __last, _BI2 __result)
template<typename _Tp > _Deque_iterator< _Tp, _Tp
&, _Tp * > copy_backward (_Deque_iterator< _Tp, const _Tp &, const _Tp * > __first, _Deque_iterator< _Tp, const _Tp &, const _Tp * > __last, _Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<typename _Ex > exception_ptr copy_exception (_Ex __ex) _GLIBCXX_USE_NOEXCEPT
template<typename _IIter , typename _OIter , typename _Predicate > _OIter copy_if (_IIter, _IIter, _OIter, _Predicate)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate > _OutputIterator copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred)
template<typename _IIter , typename _Size , typename _OIter > _OIter copy_n (_IIter, _Size, _OIter)
template<typename _InputIterator , typename _Size , typename _OutputIterator > _OutputIterator copy_n (_InputIterator __first, _Size __n, _OutputIterator __result)
template<typename _Tp > complex< _Tp > cos (const complex< _Tp > &)
constexpr float cos (float __x)
constexpr long double cos (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type cos (_Tp __x)
template<class _Dom > _Expr< _UnClos< _Cos, _Expr,
_Dom >, typename
_Dom::value_type > cos (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _UnClos< _Cos,
_ValArray, _Tp >, _Tp > cos (const valarray< _Tp > &__v)
template<typename _Tp > complex< _Tp > cosh (const complex< _Tp > &)
constexpr float cosh (float __x)
constexpr long double cosh (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type cosh (_Tp __x)
template<class _Dom > _Expr< _UnClos< _Cosh, _Expr,
_Dom >, typename
_Dom::value_type > cosh (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _UnClos< _Cosh,
_ValArray, _Tp >, _Tp > cosh (const valarray< _Tp > &__v)
template<typename _IIter , typename _Tp > iterator_traits< _IIter >
::difference_type count (_IIter, _IIter, const _Tp &)
size_t count () const _GLIBCXX_NOEXCEPT
template<typename _InputIterator , typename _Tp > iterator_traits
< _InputIterator >
::difference_type count (_InputIterator __first, _InputIterator __last, const _Tp &__value)
template<typename _IIter , typename _Predicate > iterator_traits< _IIter >
::difference_type count_if (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate > iterator_traits
< _InputIterator >
::difference_type count_if (_InputIterator __first, _InputIterator __last, _Predicate __pred)
exception_ptr current_exception () _GLIBCXX_USE_NOEXCEPT
ios_base & dec (ios_base &__base)
typedef decltype (nullptr) nullptr_t
template<typename _Tp > add_rvalue_reference< _Tp >::type declval () noexcept
template<typename _InputIterator > iterator_traits
< _InputIterator >
::difference_type distance (_InputIterator __first, _InputIterator __last)
template<typename _Tp , typename _Tp1 > shared_ptr< _Tp > dynamic_pointer_cast (const shared_ptr< _Tp1 > &__r) noexcept
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp> __shared_ptr< _Tp, _Lp > dynamic_pointer_cast (const __shared_ptr< _Tp1, _Lp > &__r) noexcept
template<class _Container > auto end (_Container &__cont)-> decltype(__cont.end())
template<class _Container > auto end (const _Container &__cont)-> decltype(__cont.end())
template<class _Tp , size_t _Nm> _Tp * end (_Tp(&__arr)[_Nm])
template<class _Tp > constexpr const _Tp * end (initializer_list< _Tp > __ils) noexcept
template<class _Tp > _Tp * end (valarray< _Tp > &__va)
template<class _Tp > const _Tp * end (const valarray< _Tp > &__va)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & endl (basic_ostream< _CharT, _Traits > &__os)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & ends (basic_ostream< _CharT, _Traits > &__os)
template<typename _IIter1 , typename _IIter2 > bool equal (_IIter1, _IIter1, _IIter2)
template<typename _IIter1 , typename _IIter2 , typename _BinaryPredicate > bool equal (_IIter1 __first1, _IIter1 __last1, _IIter2 __first2, _BinaryPredicate __binary_pred)
template<typename _II1 , typename _II2 > bool equal (_II1 __first1, _II1 __last1, _II2 __first2)
template<typename _FIter , typename _Tp > pair< _FIter, _FIter > equal_range (_FIter, _FIter, const _Tp &)
template<typename _FIter , typename _Tp , typename _Compare > pair< _FIter, _FIter > equal_range (_FIter, _FIter, const _Tp &, _Compare)
template<typename _ForwardIterator , typename _Tp > pair< _ForwardIterator,
_ForwardIterator > equal_range (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val)
template<typename _ForwardIterator , typename _Tp , typename _Compare > pair< _ForwardIterator,
_ForwardIterator > equal_range (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
void exit (int) throw ()
template<typename _Tp > complex< _Tp > exp (const complex< _Tp > &)
constexpr float exp (float __x)
constexpr long double exp (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type exp (_Tp __x)
template<class _Dom > _Expr< _UnClos< _Exp, _Expr,
_Dom >, typename
_Dom::value_type > exp (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _UnClos< _Exp,
_ValArray, _Tp >, _Tp > exp (const valarray< _Tp > &__v)
constexpr float fabs (float __x)
constexpr long double fabs (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type fabs (_Tp __x)
template<typename _Tp > _Tp fabs (const std::complex< _Tp > &__z)
template<typename _FIter , typename _Tp > void fill (_FIter, _FIter, const _Tp &)
void fill (_Bit_iterator __first, _Bit_iterator __last, const bool &__x)
template<typename _ForwardIterator , typename _Tp > void fill (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _Tp > void fill (const _Deque_iterator< _Tp, _Tp &, _Tp * > &__first, const _Deque_iterator< _Tp, _Tp &, _Tp * > &__last, const _Tp &__value)
template<typename _OIter , typename _Size , typename _Tp > _OIter fill_n (_OIter, _Size, const _Tp &)
template<typename _OI , typename _Size , typename _Tp > _OI fill_n (_OI __first, _Size __n, const _Tp &__value)
template<typename _CharT > __gnu_cxx::__enable_if
< __is_char< _CharT >::__value,
istreambuf_iterator< _CharT >
>::__type find (istreambuf_iterator< _CharT > __first, istreambuf_iterator< _CharT > __last, const _CharT &__val)
template<typename _IIter , typename _Tp > _IIter find (_IIter, _IIter, const _Tp &)
template<typename _InputIterator , typename _Tp > _InputIterator find (_InputIterator __first, _InputIterator __last, const _Tp &__val)
template<typename _FIter1 , typename _FIter2 > _FIter1 find_end (_FIter1, _FIter1, _FIter2, _FIter2)
template<typename _FIter1 , typename _FIter2 , typename _BinaryPredicate > _FIter1 find_end (_FIter1, _FIter1, _FIter2, _FIter2, _BinaryPredicate)
template<typename _ForwardIterator1 , typename _ForwardIterator2 > _ForwardIterator1 find_end (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate > _ForwardIterator1 find_end (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, _BinaryPredicate __comp)
template<typename _FIter1 , typename _FIter2 > _FIter1 find_first_of (_FIter1, _FIter1, _FIter2, _FIter2)
template<typename _FIter1 , typename _FIter2 , typename _BinaryPredicate > _FIter1 find_first_of (_FIter1, _FIter1, _FIter2, _FIter2, _BinaryPredicate)
template<typename _InputIterator , typename _ForwardIterator > _InputIterator find_first_of (_InputIterator __first1, _InputIterator __last1, _ForwardIterator __first2, _ForwardIterator __last2)
template<typename _InputIterator , typename _ForwardIterator , typename _BinaryPredicate > _InputIterator find_first_of (_InputIterator __first1, _InputIterator __last1, _ForwardIterator __first2, _ForwardIterator __last2, _BinaryPredicate __comp)
template<typename _IIter , typename _Predicate > _IIter find_if (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate > _InputIterator find_if (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _IIter , typename _Predicate > _IIter find_if_not (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate > _InputIterator find_if_not (_InputIterator __first, _InputIterator __last, _Predicate __pred)
ios_base & fixed (ios_base &__base)
bitset< _Nb > & flip () _GLIBCXX_NOEXCEPT
bitset< _Nb > & flip (size_t __position)
constexpr float floor (float __x)
constexpr long double floor (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type floor (_Tp __x)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & flush (basic_ostream< _CharT, _Traits > &__os)
constexpr float fmod (float __x, float __y)
constexpr long double fmod (long double __x, long double __y)
template<typename _Tp , typename _Up > constexpr
__gnu_cxx::__promote_2< _Tp,
_Up >::__type fmod (_Tp __x, _Up __y)
template<typename _IIter , typename _Funct > _Funct for_each (_IIter, _IIter, _Funct)
template<typename _InputIterator , typename _Function > _Function for_each (_InputIterator __first, _InputIterator __last, _Function __f)
template<typename _Tp > constexpr _Tp && forward (typename std::remove_reference< _Tp >::type &__t) noexcept
template<typename _Tp > constexpr _Tp && forward (typename std::remove_reference< _Tp >::type &&__t) noexcept
template<typename... _Elements> constexpr tuple< _Elements &&...> forward_as_tuple (_Elements &&...__args) noexcept
float frexp (float __x, int *__exp)
long double frexp (long double __x, int *__exp)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type frexp (_Tp __x, int *__exp)
template<typename _Container > front_insert_iterator< _Container > front_inserter (_Container &__x)
const error_category & future_category () noexcept
template<typename _FIter , typename _Generator > void generate (_FIter, _FIter, _Generator)
template<typename _ForwardIterator , typename _Generator > void generate (_ForwardIterator __first, _ForwardIterator __last, _Generator __gen)
template<typename _RealType , size_t __bits, typename _UniformRandomNumberGenerator > _RealType generate_canonical (_UniformRandomNumberGenerator &__g)
template<typename _OIter , typename _Size , typename _Generator > _OIter generate_n (_OIter, _Size, _Generator)
template<typename _OutputIterator , typename _Size , typename _Generator > _OutputIterator generate_n (_OutputIterator __first, _Size __n, _Generator __gen)
const error_category & generic_category () noexcept
template<std::size_t _Int, class _Tp1 , class _Tp2 > constexpr tuple_element< _Int,
std::pair< _Tp1, _Tp2 >
>::type & get (std::pair< _Tp1, _Tp2 > &__in) noexcept
template<std::size_t _Int, class _Tp1 , class _Tp2 > constexpr tuple_element< _Int,
std::pair< _Tp1, _Tp2 >
>::type && get (std::pair< _Tp1, _Tp2 > &&__in) noexcept
template<std::size_t _Int, class _Tp1 , class _Tp2 > constexpr const tuple_element
< _Int, std::pair< _Tp1, _Tp2 >
>::type & get (const std::pair< _Tp1, _Tp2 > &__in) noexcept
template<std::size_t _Int, typename _Tp , std::size_t _Nm> constexpr _Tp & get (array< _Tp, _Nm > &__arr) noexcept
template<std::size_t _Int, typename _Tp , std::size_t _Nm> constexpr _Tp && get (array< _Tp, _Nm > &&__arr) noexcept
template<std::size_t _Int, typename _Tp , std::size_t _Nm> constexpr const _Tp & get (const array< _Tp, _Nm > &__arr) noexcept
template<std::size_t __i, typename... _Elements> constexpr __add_ref< typename
tuple_element< __i, tuple
< _Elements...> >::type >
::type get (tuple< _Elements...> &__t) noexcept
template<std::size_t __i, typename... _Elements> constexpr __add_c_ref
< typename tuple_element< __i,
tuple< _Elements...> >::type >
::type get (const tuple< _Elements...> &__t) noexcept
template<std::size_t __i, typename... _Elements> constexpr __add_r_ref
< typename tuple_element< __i,
tuple< _Elements...> >::type >
::type get (tuple< _Elements...> &&__t) noexcept
template<typename _Del , typename _Tp , _Lock_policy _Lp> _Del * get_deleter (const __shared_ptr< _Tp, _Lp > &__p) noexcept
template<typename _MoneyT > _Get_money< _MoneyT > get_money (_MoneyT &__mon, bool __intl=false)
template<typename _Tp > pair< _Tp *, ptrdiff_t > get_temporary_buffer (ptrdiff_t __len) _GLIBCXX_NOEXCEPT
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &__is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > &__str, _CharT __delim)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &__is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > &__str)
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Alloc > &__str, _CharT __delim)
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Alloc > &__str)
template<> basic_istream< char > & getline (basic_istream< char > &__in, basic_string< char > &__str, char __delim)
template<> basic_istream< wchar_t > & getline (basic_istream< wchar_t > &__in, basic_string< wchar_t > &__str, wchar_t __delim)
template<typename _Facet > bool has_facet (const locale &__loc) throw ()
ios_base & hex (ios_base &__base)
template<typename _Tp > constexpr _Tp imag (const complex< _Tp > &__z)
template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type imag (_Tp)
template<typename _IIter1 , typename _IIter2 > bool includes (_IIter1, _IIter1, _IIter2, _IIter2)
template<typename _IIter1 , typename _IIter2 , typename _Compare > bool includes (_IIter1, _IIter1, _IIter2, _IIter2, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 > bool includes (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Compare > bool includes (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Tp > _Tp inner_product (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _Tp __init)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Tp , typename _BinaryOperation1 , typename _BinaryOperation2 > _Tp inner_product (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _Tp __init, _BinaryOperation1 __binary_op1, _BinaryOperation2 __binary_op2)
template<typename _BIter > void inplace_merge (_BIter, _BIter, _BIter)
template<typename _BIter , typename _Compare > void inplace_merge (_BIter, _BIter, _BIter, _Compare)
template<typename _BidirectionalIterator > void inplace_merge (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last)
template<typename _BidirectionalIterator , typename _Compare > void inplace_merge (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Compare __comp)
template<typename _Container , typename _Iterator > insert_iterator< _Container > inserter (_Container &__x, _Iterator __i)
ios_base & internal (ios_base &__base)
template<typename _ForwardIterator , typename _Tp > void iota (_ForwardIterator __first, _ForwardIterator __last, _Tp __value)
template<typename _RAIter > bool is_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare > bool is_heap (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator > bool is_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > bool is_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RAIter > _RAIter is_heap_until (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare > _RAIter is_heap_until (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator > _RandomAccessIterator is_heap_until (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > _RandomAccessIterator is_heap_until (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _IIter , typename _Predicate > bool is_partitioned (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate > bool is_partitioned (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _FIter1 , typename _FIter2 > bool is_permutation (_FIter1, _FIter1, _FIter2)
template<typename _FIter1 , typename _FIter2 , typename _BinaryPredicate > bool is_permutation (_FIter1, _FIter1, _FIter2, _BinaryPredicate)
template<typename _ForwardIterator1 , typename _ForwardIterator2 > bool is_permutation (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate > bool is_permutation (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _BinaryPredicate __pred)
template<typename _FIter > bool is_sorted (_FIter, _FIter)
template<typename _FIter , typename _Compare > bool is_sorted (_FIter, _FIter, _Compare)
template<typename _ForwardIterator > bool is_sorted (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare > bool is_sorted (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _FIter > _FIter is_sorted_until (_FIter, _FIter)
template<typename _FIter , typename _Compare > _FIter is_sorted_until (_FIter, _FIter, _Compare)
template<typename _ForwardIterator > _ForwardIterator is_sorted_until (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare > _ForwardIterator is_sorted_until (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _CharT > bool isalnum (_CharT __c, const locale &__loc)
template<typename _CharT > bool isalpha (_CharT __c, const locale &__loc)
template<typename _CharT > bool iscntrl (_CharT __c, const locale &__loc)
template<typename _CharT > bool isdigit (_CharT __c, const locale &__loc)
template<typename _CharT > bool isgraph (_CharT __c, const locale &__loc)
template<typename _CharT > bool islower (_CharT __c, const locale &__loc)
template<typename _CharT > bool isprint (_CharT __c, const locale &__loc)
template<typename _CharT > bool ispunct (_CharT __c, const locale &__loc)
template<typename _CharT > bool isspace (_CharT __c, const locale &__loc)
template<typename _CharT > bool isupper (_CharT __c, const locale &__loc)
template<typename _CharT > bool isxdigit (_CharT __c, const locale &__loc)
template<typename _ForwardIterator1 , typename _ForwardIterator2 > void iter_swap (_ForwardIterator1 __a, _ForwardIterator2 __b)
template<typename _FIter1 , typename _FIter2 > void iter_swap (_FIter1, _FIter2)
template<typename _Tp > _Tp kill_dependency (_Tp __y) noexcept
constexpr float ldexp (float __x, int __exp)
constexpr long double ldexp (long double __x, int __exp)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type ldexp (_Tp __x, int __exp)
ios_base & left (ios_base &__base)
template<typename _IIter1 , typename _IIter2 > bool lexicographical_compare (_IIter1, _IIter1, _IIter2, _IIter2)
template<typename _IIter1 , typename _IIter2 , typename _Compare > bool lexicographical_compare (_IIter1, _IIter1, _IIter2, _IIter2, _Compare)
template<typename _II1 , typename _II2 > bool lexicographical_compare (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2)
template<typename _II1 , typename _II2 , typename _Compare > bool lexicographical_compare (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2, _Compare __comp)
template<typename _L1 , typename _L2 , typename... _L3> void lock (_L1 &__l1, _L2 &__l2, _L3 &...__l3)
template<typename _Tp > complex< _Tp > log (const complex< _Tp > &)
constexpr float log (float __x)
constexpr long double log (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type log (_Tp __x)
template<class _Dom > _Expr< _UnClos< _Log, _Expr,
_Dom >, typename
_Dom::value_type > log (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _UnClos< _Log,
_ValArray, _Tp >, _Tp > log (const valarray< _Tp > &__v)
template<typename _Tp > complex< _Tp > log10 (const complex< _Tp > &)
constexpr float log10 (float __x)
constexpr long double log10 (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type log10 (_Tp __x)
template<typename _Tp > _Expr< _UnClos< _Log10,
_ValArray, _Tp >, _Tp > log10 (const valarray< _Tp > &__v)
template<class _Dom > _Expr< _UnClos< _Log10, _Expr,
_Dom >, typename
_Dom::value_type > log10 (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _FIter , typename _Tp > _FIter lower_bound (_FIter, _FIter, const _Tp &)
template<typename _FIter , typename _Tp , typename _Compare > _FIter lower_bound (_FIter, _FIter, const _Tp &, _Compare)
template<typename _ForwardIterator , typename _Tp > _ForwardIterator lower_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val)
template<typename _ForwardIterator , typename _Tp , typename _Compare > _ForwardIterator lower_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
error_code make_error_code (future_errc __errc) noexcept
error_code make_error_code (errc __e) noexcept
error_condition make_error_condition (future_errc __errc) noexcept
error_condition make_error_condition (errc __e) noexcept
template<typename _Ex > exception_ptr make_exception_ptr (_Ex __ex) _GLIBCXX_USE_NOEXCEPT
template<typename _RAIter > void make_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare > void make_heap (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator > void make_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void make_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _Iterator > move_iterator< _Iterator > make_move_iterator (_Iterator __i)
template<class _T1 , class _T2 > constexpr pair< typename
__decay_and_strip< _T1 >
::__type, typename
__decay_and_strip< _T2 >
::__type > make_pair (_T1 &&__x, _T2 &&__y)
template<typename _Tp , typename... _Args> shared_ptr< _Tp > make_shared (_Args &&...__args)
template<typename... _Elements> constexpr tuple< typename
__decay_and_strip< _Elements >
::__type...> make_tuple (_Elements &&...__args)
template<typename _Tp > const _Tp & max (const _Tp &__a, const _Tp &__b)
template<typename _Tp , typename _Compare > const _Tp & max (const _Tp &__a, const _Tp &__b, _Compare __comp)
template<typename _Tp > _Tp max (initializer_list< _Tp >)
template<typename _Tp , typename _Compare > _Tp max (initializer_list< _Tp >, _Compare)
template<typename _FIter > _FIter max_element (_FIter, _FIter)
template<typename _FIter , typename _Compare > _FIter max_element (_FIter, _FIter, _Compare)
template<typename _ForwardIterator > _ForwardIterator max_element (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare > _ForwardIterator max_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _Tp , typename _Class > _Mem_fn< _Tp _Class::* > mem_fn (_Tp _Class::*__pm)
template<typename _Ret , typename _Tp > mem_fun_t< _Ret, _Tp > mem_fun (_Ret(_Tp::*__f)())
template<typename _Ret , typename _Tp , typename _Arg > mem_fun1_t< _Ret, _Tp, _Arg > mem_fun (_Ret(_Tp::*__f)(_Arg))
template<typename _Ret , typename _Tp > mem_fun_ref_t< _Ret, _Tp > mem_fun_ref (_Ret(_Tp::*__f)())
template<typename _Ret , typename _Tp , typename _Arg > mem_fun1_ref_t< _Ret, _Tp, _Arg > mem_fun_ref (_Ret(_Tp::*__f)(_Arg))
void * memchr (void *__s, int __c, size_t __n)
template<typename _IIter1 , typename _IIter2 , typename _OIter > _OIter merge (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare > _OIter merge (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator > _OutputIterator merge (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare > _OutputIterator merge (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _Tp > const _Tp & min (const _Tp &__a, const _Tp &__b)
template<typename _Tp , typename _Compare > const _Tp & min (const _Tp &__a, const _Tp &__b, _Compare __comp)
template<typename _Tp > _Tp min (initializer_list< _Tp >)
template<typename _Tp , typename _Compare > _Tp min (initializer_list< _Tp >, _Compare)
template<typename _FIter > _FIter min_element (_FIter, _FIter)
template<typename _FIter , typename _Compare > _FIter min_element (_FIter, _FIter, _Compare)
template<typename _ForwardIterator > _ForwardIterator min_element (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare > _ForwardIterator min_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _Tp > pair< const _Tp &, const _Tp & > minmax (const _Tp &__a, const _Tp &__b)
template<typename _Tp , typename _Compare > pair< const _Tp &, const _Tp & > minmax (const _Tp &__a, const _Tp &__b, _Compare __comp)
template<typename _Tp > pair< _Tp, _Tp > minmax (initializer_list< _Tp >)
template<typename _Tp , typename _Compare > pair< _Tp, _Tp > minmax (initializer_list< _Tp >, _Compare)
template<typename _FIter > pair< _FIter, _FIter > minmax_element (_FIter, _FIter)
template<typename _FIter , typename _Compare > pair< _FIter, _FIter > minmax_element (_FIter, _FIter, _Compare)
template<typename _ForwardIterator > pair< _ForwardIterator,
_ForwardIterator > minmax_element (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare > pair< _ForwardIterator,
_ForwardIterator > minmax_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _IIter1 , typename _IIter2 > pair< _IIter1, _IIter2 > mismatch (_IIter1, _IIter1, _IIter2)
template<typename _IIter1 , typename _IIter2 , typename _BinaryPredicate > pair< _IIter1, _IIter2 > mismatch (_IIter1, _IIter1, _IIter2, _BinaryPredicate)
template<typename _InputIterator1 , typename _InputIterator2 > pair< _InputIterator1,
_InputIterator2 > mismatch (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2)
template<typename _InputIterator1 , typename _InputIterator2 , typename _BinaryPredicate > pair< _InputIterator1,
_InputIterator2 > mismatch (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _BinaryPredicate __binary_pred)
float modf (float __x, float *__iptr)
long double modf (long double __x, long double *__iptr)
template<typename _Tp > constexpr
std::remove_reference< _Tp >
::type && move (_Tp &&__t) noexcept
template<typename _Tp > _Deque_iterator< _Tp, _Tp
&, _Tp * > move (_Deque_iterator< _Tp, _Tp &, _Tp * > __first, _Deque_iterator< _Tp, _Tp &, _Tp * > __last, _Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<typename _II , typename _OI > _OI move (_II __first, _II __last, _OI __result)
template<typename _Tp > _Deque_iterator< _Tp, _Tp
&, _Tp * > move (_Deque_iterator< _Tp, const _Tp &, const _Tp * > __first, _Deque_iterator< _Tp, const _Tp &, const _Tp * > __last, _Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<typename _Tp > _Deque_iterator< _Tp, _Tp
&, _Tp * > move_backward (_Deque_iterator< _Tp, _Tp &, _Tp * > __first, _Deque_iterator< _Tp, _Tp &, _Tp * > __last, _Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<typename _BI1 , typename _BI2 > _BI2 move_backward (_BI1 __first, _BI1 __last, _BI2 __result)
template<typename _Tp > _Deque_iterator< _Tp, _Tp
&, _Tp * > move_backward (_Deque_iterator< _Tp, const _Tp &, const _Tp * > __first, _Deque_iterator< _Tp, const _Tp &, const _Tp * > __last, _Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<typename _Tp > conditional
< __move_if_noexcept_cond< _Tp >
::value, const _Tp &, _Tp && >
::type move_if_noexcept (_Tp &__x) noexcept
template<typename _ForwardIterator > _ForwardIterator next (_ForwardIterator __x, typename iterator_traits< _ForwardIterator >::difference_type __n=1)
template<typename _BIter > bool next_permutation (_BIter, _BIter)
template<typename _BIter , typename _Compare > bool next_permutation (_BIter, _BIter, _Compare)
template<typename _BidirectionalIterator > bool next_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last)
template<typename _BidirectionalIterator , typename _Compare > bool next_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last, _Compare __comp)
ios_base & noboolalpha (ios_base &__base)
bool none () const _GLIBCXX_NOEXCEPT
template<typename _IIter , typename _Predicate > bool none_of (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate > bool none_of (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _Tp > _Tp norm (const complex< _Tp > &)
template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type norm (_Tp __x)
ios_base & noshowbase (ios_base &__base)
ios_base & noshowpoint (ios_base &__base)
ios_base & noshowpos (ios_base &__base)
ios_base & noskipws (ios_base &__base)
template<typename _Predicate > unary_negate< _Predicate > not1 (const _Predicate &__pred)
template<typename _Predicate > binary_negate< _Predicate > not2 (const _Predicate &__pred)
ios_base & nounitbuf (ios_base &__base)
ios_base & nouppercase (ios_base &__base)
template<typename _RAIter > void nth_element (_RAIter, _RAIter, _RAIter)
template<typename _RAIter , typename _Compare > void nth_element (_RAIter, _RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator > void nth_element (_RandomAccessIterator __first, _RandomAccessIterator __nth, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void nth_element (_RandomAccessIterator __first, _RandomAccessIterator __nth, _RandomAccessIterator __last, _Compare __comp)
ios_base & oct (ios_base &__base)
template<typename _T1 , typename _T2 > bool operator!= (const allocator< _T1 > &, const allocator< _T2 > &)
template<typename _Tp > bool operator!= (const allocator< _Tp > &, const allocator< _Tp > &)
template<class _Tp , class _CharT , class _Traits , class _Dist > bool operator!= (const istream_iterator< _Tp, _CharT, _Traits, _Dist > &__x, const istream_iterator< _Tp, _CharT, _Traits, _Dist > &__y)
bool operator!= (thread::id __x, thread::id __y) noexcept
template<typename _Tp , std::size_t _Nm> bool operator!= (const array< _Tp, _Nm > &__one, const array< _Tp, _Nm > &__two)
template<typename _CharT , typename _Traits > bool operator!= (const istreambuf_iterator< _CharT, _Traits > &__a, const istreambuf_iterator< _CharT, _Traits > &__b)
template<class _T1 , class _T2 > constexpr bool operator!= (const pair< _T1, _T2 > &__x, const pair< _T1, _T2 > &__y)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc , bool __cache_hash_code> bool operator!= (const __unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc, __cache_hash_code > &__x, const __unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc, __cache_hash_code > &__y)
template<typename _StateT > bool operator!= (const fpos< _StateT > &__lhs, const fpos< _StateT > &__rhs)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc , bool __cache_hash_code> bool operator!= (const __unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc, __cache_hash_code > &__x, const __unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc, __cache_hash_code > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc , bool __cache_hash_code> bool operator!= (const __unordered_set< _Value, _Hash, _Pred, _Alloc, __cache_hash_code > &__x, const __unordered_set< _Value, _Hash, _Pred, _Alloc, __cache_hash_code > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc , bool __cache_hash_code> bool operator!= (const __unordered_multiset< _Value, _Hash, _Pred, _Alloc, __cache_hash_code > &__x, const __unordered_multiset< _Value, _Hash, _Pred, _Alloc, __cache_hash_code > &__y)
template<typename _Tp > bool operator!= (const _Fwd_list_iterator< _Tp > &__x, const _Fwd_list_const_iterator< _Tp > &__y)
template<typename _Tp , typename _Ref , typename _Ptr > bool operator!= (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y)
template<typename _Tp , typename _Seq > bool operator!= (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR > bool operator!= (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y)
template<typename _Val > bool operator!= (const _List_iterator< _Val > &__x, const _List_const_iterator< _Val > &__y)
bool operator!= (const error_code &__lhs, const error_code &__rhs) noexcept
template<typename _Tp , typename _Seq > bool operator!= (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
bool operator!= (const error_code &__lhs, const error_condition &__rhs) noexcept
bool operator!= (const error_condition &__lhs, const error_code &__rhs) noexcept
bool operator!= (const error_condition &__lhs, const error_condition &__rhs) noexcept
template<typename _Iterator > bool operator!= (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _Val > bool operator!= (const _Rb_tree_iterator< _Val > &__x, const _Rb_tree_const_iterator< _Val > &__y)
template<typename _Tp1 , typename _Tp2 > bool operator!= (const shared_ptr< _Tp1 > &__a, const shared_ptr< _Tp2 > &__b) noexcept
template<typename _UIntType , _UIntType __a, _UIntType __c, _UIntType __m> bool operator!= (const std::linear_congruential_engine< _UIntType, __a, __c, __m > &__lhs, const std::linear_congruential_engine< _UIntType, __a, __c, __m > &__rhs)
template<typename _Tp > bool operator!= (const shared_ptr< _Tp > &__a, nullptr_t) noexcept
template<typename _Tp > bool operator!= (nullptr_t, const shared_ptr< _Tp > &__a) noexcept
template<typename _IteratorL , typename _IteratorR > bool operator!= (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<typename _OutA1 , typename _OutA2 , typename... _InA> bool operator!= (const scoped_allocator_adaptor< _OutA1, _InA...> &__a, const scoped_allocator_adaptor< _OutA2, _InA...> &__b) noexcept
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc > bool operator!= (const unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, const unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc > bool operator!= (const unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, const unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc > bool operator!= (const unordered_set< _Value, _Hash, _Pred, _Alloc > &__x, const unordered_set< _Value, _Hash, _Pred, _Alloc > &__y)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos
< __not_equal_to, _Expr, _Expr,
_Dom1, _Dom2 >, typename __fun
< __not_equal_to, typename
_Dom1::value_type >
::result_type > operator!= (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos
< __not_equal_to, _Constant,
_Expr, typename
_Dom::value_type, _Dom >
, typename __fun
< __not_equal_to, typename
_Dom::value_type >
::result_type > operator!= (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos
< __not_equal_to, _Expr,
_ValArray, _Dom, typename
_Dom::value_type >, typename
__fun< __not_equal_to,
typename _Dom::value_type >
::result_type > operator!= (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos
< __not_equal_to, _ValArray,
_Expr, typename
_Dom::value_type, _Dom >
, typename __fun
< __not_equal_to, typename
_Dom::value_type >
::result_type > operator!= (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom > _Expr< _BinClos
< __not_equal_to, _Expr,
_Constant, _Dom, typename
_Dom::value_type >, typename
__fun< __not_equal_to,
typename _Dom::value_type >
::result_type > operator!= (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Value , class _Hash , class _Pred , class _Alloc > bool operator!= (const unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__x, const unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__y)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep > bool operator!= (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp > bool operator!= (const unique_ptr< _Tp, _Dp > &__x, nullptr_t) noexcept
template<typename _Tp , typename _Dp > bool operator!= (nullptr_t, const unique_ptr< _Tp, _Dp > &__x) noexcept
template<typename _UIntType , size_t __w, size_t __n, size_t __m, size_t __r, _UIntType __a, size_t __u, _UIntType __d, size_t __s, _UIntType __b, size_t __t, _UIntType __c, size_t __l, _UIntType __f> bool operator!= (const std::mersenne_twister_engine< _UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f > &__lhs, const std::mersenne_twister_engine< _UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f > &__rhs)
template<typename _Key , typename _Compare , typename _Alloc > bool operator!= (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc > bool operator!= (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _UIntType , size_t __w, size_t __s, size_t __r> bool operator!= (const std::subtract_with_carry_engine< _UIntType, __w, __s, __r > &__lhs, const std::subtract_with_carry_engine< _UIntType, __w, __s, __r > &__rhs)
template<typename... _TElements, typename... _UElements> bool operator!= (const tuple< _TElements...> &__t, const tuple< _UElements...> &__u)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool operator!= (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc > bool operator!= (const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _BiIter > bool operator!= (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool operator!= (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool operator!= (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _RandomNumberEngine , size_t __p, size_t __r> bool operator!= (const std::discard_block_engine< _RandomNumberEngine, __p, __r > &__lhs, const std::discard_block_engine< _RandomNumberEngine, __p, __r > &__rhs)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool operator!= (const sub_match< _Bi_iter > &__lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _IteratorL , typename _IteratorR > bool operator!= (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Iterator > bool operator!= (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp> bool operator!= (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp> bool operator!= (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp , _Lock_policy _Lp> bool operator!= (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Bi_iter > bool operator!= (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp > _Expr< _BinClos
< __not_equal_to, _ValArray,
_ValArray, _Tp, _Tp >
, typename __fun
< __not_equal_to, _Tp >
::result_type > operator!= (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos
< __not_equal_to, _ValArray,
_Constant, _Tp, _Tp >
, typename __fun
< __not_equal_to, _Tp >
::result_type > operator!= (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > _Expr< _BinClos
< __not_equal_to, _Constant,
_ValArray, _Tp, _Tp >
, typename __fun
< __not_equal_to, _Tp >
::result_type > operator!= (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _RandomNumberEngine , size_t __w, typename _UIntType > bool operator!= (const std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType > &__lhs, const std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType > &__rhs)
template<typename _Bi_iter > bool operator!= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Bi_iter > bool operator!= (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp , typename _Alloc > bool operator!= (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Bi_iter > bool operator!= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Tp , typename _Alloc > bool operator!= (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
template<typename _RandomNumberEngine , size_t __k> bool operator!= (const std::shuffle_order_engine< _RandomNumberEngine, __k > &__lhs, const std::shuffle_order_engine< _RandomNumberEngine, __k > &__rhs)
template<typename _Tp , typename _Alloc > bool operator!= (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _IntType > bool operator!= (const std::uniform_int_distribution< _IntType > &__d1, const std::uniform_int_distribution< _IntType > &__d2)
template<typename _Bi_iter , class _Allocator > bool operator!= (const match_results< _Bi_iter, _Allocator > &__m1, const match_results< _Bi_iter, _Allocator > &__m2)
template<typename _IntType > bool operator!= (const std::uniform_real_distribution< _IntType > &__d1, const std::uniform_real_distribution< _IntType > &__d2)
template<typename _Tp , typename _Alloc > bool operator!= (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _RealType > bool operator!= (const std::normal_distribution< _RealType > &__d1, const std::normal_distribution< _RealType > &__d2)
template<typename _RealType > bool operator!= (const std::lognormal_distribution< _RealType > &__d1, const std::lognormal_distribution< _RealType > &__d2)
template<typename _Res , typename... _Args> bool operator!= (const function< _Res(_Args...)> &__f, nullptr_t) noexcept
template<typename _Res , typename... _Args> bool operator!= (nullptr_t, const function< _Res(_Args...)> &__f) noexcept
template<typename _RealType > bool operator!= (const std::gamma_distribution< _RealType > &__d1, const std::gamma_distribution< _RealType > &__d2)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator!= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator!= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator!= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _RealType > bool operator!= (const std::chi_squared_distribution< _RealType > &__d1, const std::chi_squared_distribution< _RealType > &__d2)
template<typename _RealType > bool operator!= (const std::cauchy_distribution< _RealType > &__d1, const std::cauchy_distribution< _RealType > &__d2)
template<typename _RealType > bool operator!= (const std::fisher_f_distribution< _RealType > &__d1, const std::fisher_f_distribution< _RealType > &__d2)
template<typename _RealType > bool operator!= (const std::student_t_distribution< _RealType > &__d1, const std::student_t_distribution< _RealType > &__d2)
bool operator!= (const std::bernoulli_distribution &__d1, const std::bernoulli_distribution &__d2)
template<typename _IntType > bool operator!= (const std::binomial_distribution< _IntType > &__d1, const std::binomial_distribution< _IntType > &__d2)
template<typename _IntType > bool operator!= (const std::geometric_distribution< _IntType > &__d1, const std::geometric_distribution< _IntType > &__d2)
template<typename _IntType > bool operator!= (const std::negative_binomial_distribution< _IntType > &__d1, const std::negative_binomial_distribution< _IntType > &__d2)
template<typename _IntType > bool operator!= (const std::poisson_distribution< _IntType > &__d1, const std::poisson_distribution< _IntType > &__d2)
template<typename _RealType > bool operator!= (const std::exponential_distribution< _RealType > &__d1, const std::exponential_distribution< _RealType > &__d2)
template<typename _RealType > bool operator!= (const std::weibull_distribution< _RealType > &__d1, const std::weibull_distribution< _RealType > &__d2)
template<typename _RealType > bool operator!= (const std::extreme_value_distribution< _RealType > &__d1, const std::extreme_value_distribution< _RealType > &__d2)
template<typename _IntType > bool operator!= (const std::discrete_distribution< _IntType > &__d1, const std::discrete_distribution< _IntType > &__d2)
template<typename _RealType > bool operator!= (const std::piecewise_constant_distribution< _RealType > &__d1, const std::piecewise_constant_distribution< _RealType > &__d2)
template<typename _RealType > bool operator!= (const std::piecewise_linear_distribution< _RealType > &__d1, const std::piecewise_linear_distribution< _RealType > &__d2)
template<class _Dom > _Expr< _BinClos< __modulus,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun< __modulus,
typename _Dom::value_type >
::result_type > operator% (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __modulus,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun< __modulus,
typename _Dom::value_type >
::result_type > operator% (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __modulus,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __modulus,
typename _Dom::value_type >
::result_type > operator% (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __modulus,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __modulus,
typename _Dom::value_type >
::result_type > operator% (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __modulus,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun< __modulus,
typename _Dom1::value_type >
::result_type > operator% (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<typename _Tp > _Expr< _BinClos< __modulus,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun< __modulus,
_Tp >::result_type > operator% (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __modulus,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun< __modulus,
_Tp >::result_type > operator% (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > _Expr< _BinClos< __modulus,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun< __modulus,
_Tp >::result_type > operator% (const _Tp &__t, const valarray< _Tp > &__v)
constexpr _Ios_Fmtflags operator& (_Ios_Fmtflags __a, _Ios_Fmtflags __b)
constexpr _Ios_Openmode operator& (_Ios_Openmode __a, _Ios_Openmode __b)
constexpr launch operator& (launch __x, launch __y)
constexpr _Ios_Iostate operator& (_Ios_Iostate __a, _Ios_Iostate __b)
template<class _Dom > _Expr< _BinClos< __bitwise_and,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun
< __bitwise_and, typename
_Dom::value_type >
::result_type > operator& (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __bitwise_and,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun
< __bitwise_and, typename
_Dom1::value_type >
::result_type > operator& (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __bitwise_and,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun
< __bitwise_and, typename
_Dom::value_type >
::result_type > operator& (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __bitwise_and,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun
< __bitwise_and, typename
_Dom::value_type >
::result_type > operator& (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __bitwise_and,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun
< __bitwise_and, typename
_Dom::value_type >
::result_type > operator& (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<typename _Tp > _Expr< _BinClos< __bitwise_and,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun
< __bitwise_and, _Tp >
::result_type > operator& (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __bitwise_and,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun
< __bitwise_and, _Tp >
::result_type > operator& (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > _Expr< _BinClos< __bitwise_and,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun
< __bitwise_and, _Tp >
::result_type > operator& (const _Tp &__t, const valarray< _Tp > &__v)
template<class _Dom > _Expr< _BinClos< __logical_and,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun
< __logical_and, typename
_Dom::value_type >
::result_type > operator&& (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __logical_and,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun
< __logical_and, typename
_Dom::value_type >
::result_type > operator&& (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __logical_and,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun
< __logical_and, typename
_Dom1::value_type >
::result_type > operator&& (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __logical_and,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun
< __logical_and, typename
_Dom::value_type >
::result_type > operator&& (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __logical_and,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun
< __logical_and, typename
_Dom::value_type >
::result_type > operator&& (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _BinClos< __logical_and,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun
< __logical_and, _Tp >
::result_type > operator&& (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __logical_and,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun
< __logical_and, _Tp >
::result_type > operator&& (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > _Expr< _BinClos< __logical_and,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun
< __logical_and, _Tp >
::result_type > operator&& (const _Tp &__t, const valarray< _Tp > &__v)
const _Ios_Fmtflags & operator&= (_Ios_Fmtflags &__a, _Ios_Fmtflags __b)
const _Ios_Openmode & operator&= (_Ios_Openmode &__a, _Ios_Openmode __b)
launch & operator&= (launch &__x, launch __y)
const _Ios_Iostate & operator&= (_Ios_Iostate &__a, _Ios_Iostate __b)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __multiplies,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun< __multiplies,
typename _Dom1::value_type >
::result_type > operator* (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __multiplies,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun< __multiplies,
typename _Dom::value_type >
::result_type > operator* (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __multiplies,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __multiplies,
typename _Dom::value_type >
::result_type > operator* (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __multiplies,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun< __multiplies,
typename _Dom::value_type >
::result_type > operator* (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __multiplies,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __multiplies,
typename _Dom::value_type >
::result_type > operator* (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _BinClos< __multiplies,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun< __multiplies,
_Tp >::result_type > operator* (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __multiplies,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun< __multiplies,
_Tp >::result_type > operator* (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > _Expr< _BinClos< __multiplies,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun< __multiplies,
_Tp >::result_type > operator* (const _Tp &__t, const valarray< _Tp > &__v)
_Bit_iterator operator+ (ptrdiff_t __n, const _Bit_iterator &__x)
template<typename _Iterator > reverse_iterator< _Iterator > operator+ (typename reverse_iterator< _Iterator >::difference_type __n, const reverse_iterator< _Iterator > &__x)
_Bit_const_iterator operator+ (ptrdiff_t __n, const _Bit_const_iterator &__x)
template<typename _Tp , typename _Ref , typename _Ptr > _Deque_iterator< _Tp, _Ref, _Ptr > operator+ (ptrdiff_t __n, const _Deque_iterator< _Tp, _Ref, _Ptr > &__x)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __plus, _Expr,
_Expr, _Dom1, _Dom2 >
, typename __fun< __plus,
typename _Dom1::value_type >
::result_type > operator+ (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __plus, _Expr,
_ValArray, _Dom, typename
_Dom::value_type >, typename
__fun< __plus, typename
_Dom::value_type >
::result_type > operator+ (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __plus,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __plus,
typename _Dom::value_type >
::result_type > operator+ (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom > _Expr< _BinClos< __plus, _Expr,
_Constant, _Dom, typename
_Dom::value_type >, typename
__fun< __plus, typename
_Dom::value_type >
::result_type > operator+ (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __plus,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __plus,
typename _Dom::value_type >
::result_type > operator+ (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp > complex< _Tp > operator+ (const complex< _Tp > &__x)
template<typename _Iterator > move_iterator< _Iterator > operator+ (typename move_iterator< _Iterator >::difference_type __n, const move_iterator< _Iterator > &__x)
template<typename _Tp > _Expr< _BinClos< __plus,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun< __plus, _Tp >
::result_type > operator+ (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __plus,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun< __plus, _Tp >
::result_type > operator+ (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > _Expr< _BinClos< __plus,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun< __plus, _Tp >
::result_type > operator+ (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits,
_Alloc > operator+ (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits,
_Alloc > operator+ (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits,
_Alloc > operator+ (_CharT __lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits,
_Alloc > operator+ (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits,
_Alloc > operator+ (const basic_string< _CharT, _Traits, _Alloc > &__lhs, _CharT __rhs)
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits,
_Alloc > operator+ (basic_string< _CharT, _Traits, _Alloc > &&__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits,
_Alloc > operator+ (const basic_string< _CharT, _Traits, _Alloc > &__lhs, basic_string< _CharT, _Traits, _Alloc > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits,
_Alloc > operator+ (basic_string< _CharT, _Traits, _Alloc > &&__lhs, basic_string< _CharT, _Traits, _Alloc > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits,
_Alloc > operator+ (const _CharT *__lhs, basic_string< _CharT, _Traits, _Alloc > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits,
_Alloc > operator+ (_CharT __lhs, basic_string< _CharT, _Traits, _Alloc > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits,
_Alloc > operator+ (basic_string< _CharT, _Traits, _Alloc > &&__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits,
_Alloc > operator+ (basic_string< _CharT, _Traits, _Alloc > &&__lhs, _CharT __rhs)
ptrdiff_t operator- (const _Bit_iterator_base &__x, const _Bit_iterator_base &__y)
template<typename _Iterator > reverse_iterator< _Iterator >
::difference_type operator- (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _Tp , typename _Ref , typename _Ptr > _Deque_iterator< _Tp, _Ref,
_Ptr >::difference_type operator- (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y)
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR > _Deque_iterator< _Tp, _RefL,
_PtrL >::difference_type operator- (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y)
template<typename _IteratorL , typename _IteratorR > auto operator- (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)-> decltype(__y.base()-__x.base())
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __minus,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun< __minus,
typename _Dom1::value_type >
::result_type > operator- (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __minus,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun< __minus,
typename _Dom::value_type >
::result_type > operator- (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __minus,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun< __minus,
typename _Dom::value_type >
::result_type > operator- (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __minus,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __minus,
typename _Dom::value_type >
::result_type > operator- (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom > _Expr< _BinClos< __minus,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __minus,
typename _Dom::value_type >
::result_type > operator- (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp > complex< _Tp > operator- (const complex< _Tp > &__x)
template<typename _IteratorL , typename _IteratorR > auto operator- (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)-> decltype(__x.base()-__y.base())
template<typename _Iterator > auto operator- (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)-> decltype(__x.base()-__y.base())
template<typename _Tp > _Expr< _BinClos< __minus,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun< __minus, _Tp >
::result_type > operator- (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > _Expr< _BinClos< __minus,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun< __minus, _Tp >
::result_type > operator- (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __minus,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun< __minus, _Tp >
::result_type > operator- (const _Tp &__t, const valarray< _Tp > &__v)
template<class _Dom > _Expr< _BinClos< __divides,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __divides,
typename _Dom::value_type >
::result_type > operator/ (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __divides,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun< __divides,
typename _Dom::value_type >
::result_type > operator/ (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __divides,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun< __divides,
typename _Dom::value_type >
::result_type > operator/ (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __divides,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __divides,
typename _Dom::value_type >
::result_type > operator/ (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __divides,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun< __divides,
typename _Dom1::value_type >
::result_type > operator/ (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<typename _Tp > _Expr< _BinClos< __divides,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun< __divides,
_Tp >::result_type > operator/ (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Tp > _Expr< _BinClos< __divides,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun< __divides,
_Tp >::result_type > operator/ (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __divides,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun< __divides,
_Tp >::result_type > operator/ (const valarray< _Tp > &__v, const _Tp &__t)
bool operator< (const error_code &__lhs, const error_code &__rhs) noexcept
template<class _T1 , class _T2 > constexpr bool operator< (const pair< _T1, _T2 > &__x, const pair< _T1, _T2 > &__y)
template<typename _Tp , std::size_t _Nm> bool operator< (const array< _Tp, _Nm > &__a, const array< _Tp, _Nm > &__b)
bool operator< (const error_condition &__lhs, const error_condition &__rhs) noexcept
template<typename _Tp , typename _Seq > bool operator< (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _Tp , typename _Ref , typename _Ptr > bool operator< (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y)
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR > bool operator< (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y)
template<typename _Tp , typename _Seq > bool operator< (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _Iterator > bool operator< (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _IteratorL , typename _IteratorR > bool operator< (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<typename _Tp1 , typename _Tp2 > bool operator< (const shared_ptr< _Tp1 > &__a, const shared_ptr< _Tp2 > &__b) noexcept
template<typename _Tp > bool operator< (const shared_ptr< _Tp > &__a, nullptr_t) noexcept
template<typename _Tp > bool operator< (nullptr_t, const shared_ptr< _Tp > &__a) noexcept
template<class _Dom > _Expr< _BinClos< __less, _Expr,
_Constant, _Dom, typename
_Dom::value_type >, typename
__fun< __less, typename
_Dom::value_type >
::result_type > operator< (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __less, _Expr,
_ValArray, _Dom, typename
_Dom::value_type >, typename
__fun< __less, typename
_Dom::value_type >
::result_type > operator< (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __less,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __less,
typename _Dom::value_type >
::result_type > operator< (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __less, _Expr,
_Expr, _Dom1, _Dom2 >
, typename __fun< __less,
typename _Dom1::value_type >
::result_type > operator< (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __less,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __less,
typename _Dom::value_type >
::result_type > operator< (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep > bool operator< (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp > bool operator< (const unique_ptr< _Tp, _Dp > &__x, nullptr_t)
template<typename _Tp , typename _Dp > bool operator< (nullptr_t, const unique_ptr< _Tp, _Dp > &__x)
template<typename _Key , typename _Compare , typename _Alloc > bool operator< (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc > bool operator< (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename... _TElements, typename... _UElements> bool operator< (const tuple< _TElements...> &__t, const tuple< _UElements...> &__u)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool operator< (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc > bool operator< (const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _BiIter > bool operator< (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool operator< (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool operator< (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _IteratorL , typename _IteratorR > bool operator< (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc > bool operator< (const sub_match< _Bi_iter > &__lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Iterator > bool operator< (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp> bool operator< (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp> bool operator< (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp , _Lock_policy _Lp> bool operator< (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Bi_iter > bool operator< (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp > _Expr< _BinClos< __less,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun< __less, _Tp >
::result_type > operator< (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __less,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun< __less, _Tp >
::result_type > operator< (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > _Expr< _BinClos< __less,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun< __less, _Tp >
::result_type > operator< (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Bi_iter > bool operator< (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Tp , typename _Alloc > bool operator< (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Bi_iter > bool operator< (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool operator< (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Tp , typename _Alloc > bool operator< (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc > bool operator< (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc > bool operator< (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator< (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator< (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator< (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _Ch , typename _Tr , typename _Tp , _Lock_policy _Lp> std::basic_ostream< _Ch, _Tr > & operator<< (std::basic_ostream< _Ch, _Tr > &__os, const __shared_ptr< _Tp, _Lp > &__p)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Resetiosflags __f)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Setiosflags __f)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Setbase __f)
template<typename _UIntType , _UIntType __a, _UIntType __c, _UIntType __m, typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const linear_congruential_engine< _UIntType, __a, __c, __m > &__lcr)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Setfill< _CharT > __f)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, const error_code &__e)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Setprecision __f)
template<class _CharT , class _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__out, thread::id __id)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Setw __f)
template<typename _CharT , typename _Traits , typename _MoneyT > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Put_money< _MoneyT > __f)
template<class _Dom > _Expr< _BinClos< __shift_left,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun< __shift_left,
typename _Dom::value_type >
::result_type > operator<< (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __shift_left,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun< __shift_left,
typename _Dom::value_type >
::result_type > operator<< (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __shift_left,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun< __shift_left,
typename _Dom1::value_type >
::result_type > operator<< (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __shift_left,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __shift_left,
typename _Dom::value_type >
::result_type > operator<< (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom > _Expr< _BinClos< __shift_left,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __shift_left,
typename _Dom::value_type >
::result_type > operator<< (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _UIntType , size_t __w, size_t __n, size_t __m, size_t __r, _UIntType __a, size_t __u, _UIntType __d, size_t __s, _UIntType __b, size_t __t, _UIntType __c, size_t __l, _UIntType __f, typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const mersenne_twister_engine< _UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f > &__x)
template<typename _Tp , typename _CharT , class _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, const complex< _Tp > &__x)
template<typename _CharT , typename _Traits , typename _Tp > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &&__os, const _Tp &__x)
template<typename _UIntType , size_t __w, size_t __s, size_t __r, typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const subtract_with_carry_engine< _UIntType, __w, __s, __r > &__x)
template<typename _RandomNumberEngine , size_t __p, size_t __r, typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const discard_block_engine< _RandomNumberEngine, __p, __r > &__x)
template<typename _RandomNumberEngine , size_t __k, typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const shuffle_order_engine< _RandomNumberEngine, __k > &__x)
template<typename _IntType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const negative_binomial_distribution< _IntType > &__x)
template<typename _Tp > _Expr< _BinClos< __shift_left,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun< __shift_left,
_Tp >::result_type > operator<< (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Tp > _Expr< _BinClos< __shift_left,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun< __shift_left,
_Tp >::result_type > operator<< (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __shift_left,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun< __shift_left,
_Tp >::result_type > operator<< (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _RandomNumberEngine , size_t __w, typename _UIntType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType > &__x)
template<typename _IntType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const poisson_distribution< _IntType > &__x)
template<typename _Ch_type , typename _Ch_traits , typename _Bi_iter > basic_ostream< _Ch_type,
_Ch_traits > & operator<< (basic_ostream< _Ch_type, _Ch_traits > &__os, const sub_match< _Bi_iter > &__m)
template<typename _IntType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const binomial_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const normal_distribution< _RealType > &__x)
template<typename _IntType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &, const std::uniform_int_distribution< _IntType > &)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const lognormal_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const chi_squared_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const fisher_f_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &, const std::uniform_real_distribution< _RealType > &)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const student_t_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const gamma_distribution< _RealType > &__x)
template<typename _IntType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const discrete_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const piecewise_constant_distribution< _RealType > &__x)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, const __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > &__str)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const piecewise_linear_distribution< _RealType > &__x)
template<typename _CharT , typename _Traits , typename _Alloc > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, const basic_string< _CharT, _Traits, _Alloc > &__str)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::cauchy_distribution< _RealType > &__x)
template<typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::bernoulli_distribution &__x)
template<typename _IntType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::geometric_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::exponential_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::weibull_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::extreme_value_distribution< _RealType > &__x)
bool operator<= (thread::id __x, thread::id __y) noexcept
template<typename _Tp , std::size_t _Nm> bool operator<= (const array< _Tp, _Nm > &__one, const array< _Tp, _Nm > &__two)
template<class _T1 , class _T2 > constexpr bool operator<= (const pair< _T1, _T2 > &__x, const pair< _T1, _T2 > &__y)
template<typename _Tp , typename _Seq > bool operator<= (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _Tp , typename _Ref , typename _Ptr > bool operator<= (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y)
template<typename _Tp , typename _Seq > bool operator<= (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR > bool operator<= (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y)
template<typename _Iterator > bool operator<= (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _IteratorL , typename _IteratorR > bool operator<= (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<typename _Tp1 , typename _Tp2 > bool operator<= (const shared_ptr< _Tp1 > &__a, const shared_ptr< _Tp2 > &__b) noexcept
template<typename _Tp > bool operator<= (const shared_ptr< _Tp > &__a, nullptr_t) noexcept
template<typename _Tp > bool operator<= (nullptr_t, const shared_ptr< _Tp > &__a) noexcept
template<class _Dom > _Expr< _BinClos< __less_equal,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun< __less_equal,
typename _Dom::value_type >
::result_type > operator<= (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __less_equal,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __less_equal,
typename _Dom::value_type >
::result_type > operator<= (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __less_equal,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun< __less_equal,
typename _Dom1::value_type >
::result_type > operator<= (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __less_equal,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun< __less_equal,
typename _Dom::value_type >
::result_type > operator<= (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __less_equal,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __less_equal,
typename _Dom::value_type >
::result_type > operator<= (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep > bool operator<= (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp > bool operator<= (const unique_ptr< _Tp, _Dp > &__x, nullptr_t)
template<typename _Tp , typename _Dp > bool operator<= (nullptr_t, const unique_ptr< _Tp, _Dp > &__x)
template<typename _Key , typename _Compare , typename _Alloc > bool operator<= (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc > bool operator<= (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename... _TElements, typename... _UElements> bool operator<= (const tuple< _TElements...> &__t, const tuple< _UElements...> &__u)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool operator<= (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc > bool operator<= (const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _BiIter > bool operator<= (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool operator<= (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool operator<= (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _IteratorL , typename _IteratorR > bool operator<= (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Iterator > bool operator<= (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc > bool operator<= (const sub_match< _Bi_iter > &__lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp> bool operator<= (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp> bool operator<= (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp , _Lock_policy _Lp> bool operator<= (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Tp > _Expr< _BinClos< __less_equal,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun< __less_equal,
_Tp >::result_type > operator<= (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __less_equal,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun< __less_equal,
_Tp >::result_type > operator<= (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Tp > _Expr< _BinClos< __less_equal,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun< __less_equal,
_Tp >::result_type > operator<= (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Bi_iter > bool operator<= (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool operator<= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Tp , typename _Alloc > bool operator<= (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Bi_iter > bool operator<= (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp , typename _Alloc > bool operator<= (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
template<typename _Bi_iter > bool operator<= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Tp , typename _Alloc > bool operator<= (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc > bool operator<= (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator<= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator<= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator<= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _T1 , typename _T2 > bool operator== (const allocator< _T1 > &, const allocator< _T2 > &)
template<typename _Tp > bool operator== (const allocator< _Tp > &, const allocator< _Tp > &)
template<typename _Tp , typename _CharT , typename _Traits , typename _Dist > bool operator== (const istream_iterator< _Tp, _CharT, _Traits, _Dist > &__x, const istream_iterator< _Tp, _CharT, _Traits, _Dist > &__y)
template<typename _Tp , std::size_t _Nm> bool operator== (const array< _Tp, _Nm > &__one, const array< _Tp, _Nm > &__two)
template<class _T1 , class _T2 > constexpr bool operator== (const pair< _T1, _T2 > &__x, const pair< _T1, _T2 > &__y)
template<typename _CharT , typename _Traits > bool operator== (const istreambuf_iterator< _CharT, _Traits > &__a, const istreambuf_iterator< _CharT, _Traits > &__b)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc , bool __cache_hash_code> bool operator== (const __unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc, __cache_hash_code > &__x, const __unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc, __cache_hash_code > &__y)
template<typename _StateT > bool operator== (const fpos< _StateT > &__lhs, const fpos< _StateT > &__rhs)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc , bool __cache_hash_code> bool operator== (const __unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc, __cache_hash_code > &__x, const __unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc, __cache_hash_code > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc , bool __cache_hash_code> bool operator== (const __unordered_set< _Value, _Hash, _Pred, _Alloc, __cache_hash_code > &__x, const __unordered_set< _Value, _Hash, _Pred, _Alloc, __cache_hash_code > &__y)
template<typename _Tp , typename _Seq > bool operator== (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _Tp , typename _Ref , typename _Ptr > bool operator== (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y)
template<typename _Tp > bool operator== (const _Fwd_list_iterator< _Tp > &__x, const _Fwd_list_const_iterator< _Tp > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc , bool __cache_hash_code> bool operator== (const __unordered_multiset< _Value, _Hash, _Pred, _Alloc, __cache_hash_code > &__x, const __unordered_multiset< _Value, _Hash, _Pred, _Alloc, __cache_hash_code > &__y)
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR > bool operator== (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y)
bool operator== (const error_code &__lhs, const error_code &__rhs) noexcept
bool operator== (const error_code &__lhs, const error_condition &__rhs) noexcept
template<typename _Tp , typename _Seq > bool operator== (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
bool operator== (const error_condition &__lhs, const error_code &__rhs) noexcept
template<typename _Val > bool operator== (const _List_iterator< _Val > &__x, const _List_const_iterator< _Val > &__y)
bool operator== (const error_condition &__lhs, const error_condition &__rhs) noexcept
template<typename _Iterator > bool operator== (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _Val > bool operator== (const _Rb_tree_iterator< _Val > &__x, const _Rb_tree_const_iterator< _Val > &__y)
template<typename _Tp1 , typename _Tp2 > bool operator== (const shared_ptr< _Tp1 > &__a, const shared_ptr< _Tp2 > &__b) noexcept
template<typename _Tp > bool operator== (const shared_ptr< _Tp > &__a, nullptr_t) noexcept
template<typename _Tp > bool operator== (nullptr_t, const shared_ptr< _Tp > &__a) noexcept
template<typename _IteratorL , typename _IteratorR > bool operator== (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<typename _OutA1 , typename _OutA2 , typename... _InA> bool operator== (const scoped_allocator_adaptor< _OutA1, _InA...> &__a, const scoped_allocator_adaptor< _OutA2, _InA...> &__b) noexcept
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc > bool operator== (const unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, const unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc > bool operator== (const unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, const unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc > bool operator== (const unordered_set< _Value, _Hash, _Pred, _Alloc > &__x, const unordered_set< _Value, _Hash, _Pred, _Alloc > &__y)
template<class _Dom > _Expr< _BinClos< __equal_to,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __equal_to,
typename _Dom::value_type >
::result_type > operator== (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __equal_to,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun< __equal_to,
typename _Dom1::value_type >
::result_type > operator== (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __equal_to,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun< __equal_to,
typename _Dom::value_type >
::result_type > operator== (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __equal_to,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __equal_to,
typename _Dom::value_type >
::result_type > operator== (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __equal_to,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun< __equal_to,
typename _Dom::value_type >
::result_type > operator== (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Value , class _Hash , class _Pred , class _Alloc > bool operator== (const unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__x, const unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__y)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep > bool operator== (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp > bool operator== (const unique_ptr< _Tp, _Dp > &__x, nullptr_t) noexcept
template<typename _Tp , typename _Dp > bool operator== (nullptr_t, const unique_ptr< _Tp, _Dp > &__x) noexcept
template<typename _Key , typename _Compare , typename _Alloc > bool operator== (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc > bool operator== (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename... _TElements, typename... _UElements> bool operator== (const tuple< _TElements...> &__t, const tuple< _UElements...> &__u)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool operator== (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc > bool operator== (const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _BiIter > bool operator== (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool operator== (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool operator== (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool operator== (const sub_match< _Bi_iter > &__lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _IteratorL , typename _IteratorR > bool operator== (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Iterator > bool operator== (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp> bool operator== (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp> bool operator== (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp , _Lock_policy _Lp> bool operator== (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Bi_iter > bool operator== (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp > _Expr< _BinClos< __equal_to,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun< __equal_to,
_Tp >::result_type > operator== (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Tp > _Expr< _BinClos< __equal_to,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun< __equal_to,
_Tp >::result_type > operator== (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > _Expr< _BinClos< __equal_to,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun< __equal_to,
_Tp >::result_type > operator== (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Bi_iter > bool operator== (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Tp , typename _Alloc > bool operator== (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Bi_iter > bool operator== (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool operator== (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Tp , typename _Alloc > bool operator== (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc > bool operator== (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _RealType > bool operator== (const std::normal_distribution< _RealType > &__d1, const std::normal_distribution< _RealType > &__d2)
template<typename _Bi_iter , typename _Allocator > bool operator== (const match_results< _Bi_iter, _Allocator > &__m1, const match_results< _Bi_iter, _Allocator > &__m2)
template<typename _Tp , typename _Alloc > bool operator== (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _Res , typename... _Args> bool operator== (const function< _Res(_Args...)> &__f, nullptr_t) noexcept
template<typename _Res , typename... _Args> bool operator== (nullptr_t, const function< _Res(_Args...)> &__f) noexcept
template<typename _CharT , typename _Traits , typename _Alloc > bool operator== (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT > __gnu_cxx::__enable_if
< __is_char< _CharT >::__value,
bool >::__type operator== (const basic_string< _CharT > &__lhs, const basic_string< _CharT > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator== (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator== (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
bool operator> (thread::id __x, thread::id __y) noexcept
template<typename _Tp , std::size_t _Nm> bool operator> (const array< _Tp, _Nm > &__one, const array< _Tp, _Nm > &__two)
template<class _T1 , class _T2 > constexpr bool operator> (const pair< _T1, _T2 > &__x, const pair< _T1, _T2 > &__y)
template<typename _Tp , typename _Seq > bool operator> (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _Tp , typename _Ref , typename _Ptr > bool operator> (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y)
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR > bool operator> (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y)
template<typename _Tp , typename _Seq > bool operator> (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _Iterator > bool operator> (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _IteratorL , typename _IteratorR > bool operator> (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<typename _Tp1 , typename _Tp2 > bool operator> (const shared_ptr< _Tp1 > &__a, const shared_ptr< _Tp2 > &__b) noexcept
template<typename _Tp > bool operator> (const shared_ptr< _Tp > &__a, nullptr_t) noexcept
template<typename _Tp > bool operator> (nullptr_t, const shared_ptr< _Tp > &__a) noexcept
template<class _Dom > _Expr< _BinClos< __greater,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __greater,
typename _Dom::value_type >
::result_type > operator> (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __greater,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun< __greater,
typename _Dom1::value_type >
::result_type > operator> (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __greater,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun< __greater,
typename _Dom::value_type >
::result_type > operator> (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __greater,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __greater,
typename _Dom::value_type >
::result_type > operator> (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __greater,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun< __greater,
typename _Dom::value_type >
::result_type > operator> (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep > bool operator> (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp > bool operator> (const unique_ptr< _Tp, _Dp > &__x, nullptr_t)
template<typename _Tp , typename _Dp > bool operator> (nullptr_t, const unique_ptr< _Tp, _Dp > &__x)
template<typename _Key , typename _Compare , typename _Alloc > bool operator> (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc > bool operator> (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename... _TElements, typename... _UElements> bool operator> (const tuple< _TElements...> &__t, const tuple< _UElements...> &__u)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool operator> (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc > bool operator> (const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool operator> (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _BiIter > bool operator> (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool operator> (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc > bool operator> (const sub_match< _Bi_iter > &__lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _IteratorL , typename _IteratorR > bool operator> (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Iterator > bool operator> (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp> bool operator> (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp> bool operator> (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp , _Lock_policy _Lp> bool operator> (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Bi_iter > bool operator> (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp > _Expr< _BinClos< __greater,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun< __greater,
_Tp >::result_type > operator> (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Tp > _Expr< _BinClos< __greater,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun< __greater,
_Tp >::result_type > operator> (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __greater,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun< __greater,
_Tp >::result_type > operator> (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Bi_iter > bool operator> (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Tp , typename _Alloc > bool operator> (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Bi_iter > bool operator> (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool operator> (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Tp , typename _Alloc > bool operator> (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc > bool operator> (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc > bool operator> (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator> (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator> (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator> (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
bool operator>= (thread::id __x, thread::id __y) noexcept
template<typename _Tp , std::size_t _Nm> bool operator>= (const array< _Tp, _Nm > &__one, const array< _Tp, _Nm > &__two)
template<class _T1 , class _T2 > constexpr bool operator>= (const pair< _T1, _T2 > &__x, const pair< _T1, _T2 > &__y)
template<typename _Tp , typename _Seq > bool operator>= (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _Tp , typename _Seq > bool operator>= (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _Tp , typename _Ref , typename _Ptr > bool operator>= (const _Deque_iterator< _Tp, _Ref, _Ptr > &__x, const _Deque_iterator< _Tp, _Ref, _Ptr > &__y)
template<typename _Tp , typename _RefL , typename _PtrL , typename _RefR , typename _PtrR > bool operator>= (const _Deque_iterator< _Tp, _RefL, _PtrL > &__x, const _Deque_iterator< _Tp, _RefR, _PtrR > &__y)
template<typename _Iterator > bool operator>= (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _IteratorL , typename _IteratorR > bool operator>= (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<typename _Tp1 , typename _Tp2 > bool operator>= (const shared_ptr< _Tp1 > &__a, const shared_ptr< _Tp2 > &__b) noexcept
template<typename _Tp > bool operator>= (const shared_ptr< _Tp > &__a, nullptr_t) noexcept
template<class _Dom > _Expr< _BinClos
< __greater_equal, _Expr,
_ValArray, _Dom, typename
_Dom::value_type >, typename
__fun< __greater_equal,
typename _Dom::value_type >
::result_type > operator>= (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos
< __greater_equal, _ValArray,
_Expr, typename
_Dom::value_type, _Dom >
, typename __fun
< __greater_equal, typename
_Dom::value_type >
::result_type > operator>= (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos
< __greater_equal, _Expr,
_Expr, _Dom1, _Dom2 >
, typename __fun
< __greater_equal, typename
_Dom1::value_type >
::result_type > operator>= (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos
< __greater_equal, _Constant,
_Expr, typename
_Dom::value_type, _Dom >
, typename __fun
< __greater_equal, typename
_Dom::value_type >
::result_type > operator>= (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos
< __greater_equal, _Expr,
_Constant, _Dom, typename
_Dom::value_type >, typename
__fun< __greater_equal,
typename _Dom::value_type >
::result_type > operator>= (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<typename _Tp > bool operator>= (nullptr_t, const shared_ptr< _Tp > &__a) noexcept
template<typename _Tp , typename _Dp , typename _Up , typename _Ep > bool operator>= (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp > bool operator>= (const unique_ptr< _Tp, _Dp > &__x, nullptr_t)
template<typename _Tp , typename _Dp > bool operator>= (nullptr_t, const unique_ptr< _Tp, _Dp > &__x)
template<typename _Key , typename _Compare , typename _Alloc > bool operator>= (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc > bool operator>= (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename... _TElements, typename... _UElements> bool operator>= (const tuple< _TElements...> &__t, const tuple< _UElements...> &__u)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool operator>= (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc > bool operator>= (const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, const _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _BiIter > bool operator>= (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool operator>= (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool operator>= (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc > bool operator>= (const sub_match< _Bi_iter > &__lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _IteratorL , typename _IteratorR > bool operator>= (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Iterator > bool operator>= (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp> bool operator>= (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp> bool operator>= (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Bi_iter > bool operator>= (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Tp , _Lock_policy _Lp> bool operator>= (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Tp > _Expr< _BinClos
< __greater_equal, _ValArray,
_Constant, _Tp, _Tp >
, typename __fun
< __greater_equal, _Tp >
::result_type > operator>= (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > _Expr< _BinClos
< __greater_equal, _ValArray,
_ValArray, _Tp, _Tp >
, typename __fun
< __greater_equal, _Tp >
::result_type > operator>= (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos
< __greater_equal, _Constant,
_ValArray, _Tp, _Tp >
, typename __fun
< __greater_equal, _Tp >
::result_type > operator>= (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Bi_iter > bool operator>= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Tp , typename _Alloc > bool operator>= (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Bi_iter > bool operator>= (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool operator>= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Tp , typename _Alloc > bool operator>= (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc > bool operator>= (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc > bool operator>= (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator>= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator>= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc > bool operator>= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Resetiosflags __f)
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Setiosflags __f)
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Setbase __f)
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Setfill< _CharT > __f)
template<typename _UIntType , _UIntType __a, _UIntType __c, _UIntType __m, typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, linear_congruential_engine< _UIntType, __a, __c, __m > &__lcr)
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Setprecision __f)
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Setw __f)
template<typename _CharT , typename _Traits , typename _MoneyT > basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Get_money< _MoneyT > __f)
template<class _Dom > _Expr< _BinClos< __shift_right,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun
< __shift_right, typename
_Dom::value_type >
::result_type > operator>> (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __shift_right,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun
< __shift_right, typename
_Dom1::value_type >
::result_type > operator>> (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __shift_right,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun
< __shift_right, typename
_Dom::value_type >
::result_type > operator>> (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __shift_right,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun
< __shift_right, typename
_Dom::value_type >
::result_type > operator>> (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom > _Expr< _BinClos< __shift_right,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun
< __shift_right, typename
_Dom::value_type >
::result_type > operator>> (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp , typename _CharT , class _Traits > basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, complex< _Tp > &__x)
template<typename _UIntType , size_t __w, size_t __n, size_t __m, size_t __r, _UIntType __a, size_t __u, _UIntType __d, size_t __s, _UIntType __b, size_t __t, _UIntType __c, size_t __l, _UIntType __f, typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, mersenne_twister_engine< _UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f > &__x)
template<typename _UIntType , size_t __w, size_t __s, size_t __r, typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, subtract_with_carry_engine< _UIntType, __w, __s, __r > &__x)
template<typename _RandomNumberEngine , size_t __p, size_t __r, typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, discard_block_engine< _RandomNumberEngine, __p, __r > &__x)
template<typename _RandomNumberEngine , size_t __k, typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, shuffle_order_engine< _RandomNumberEngine, __k > &__x)
template<typename _CharT , typename _Traits , typename _Tp > basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &&__is, _Tp &__x)
template<typename _Tp > _Expr< _BinClos< __shift_right,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun
< __shift_right, _Tp >
::result_type > operator>> (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __shift_right,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun
< __shift_right, _Tp >
::result_type > operator>> (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > _Expr< _BinClos< __shift_right,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun
< __shift_right, _Tp >
::result_type > operator>> (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _IntType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, negative_binomial_distribution< _IntType > &__x)
template<typename _IntType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, poisson_distribution< _IntType > &__x)
template<typename _IntType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, binomial_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, normal_distribution< _RealType > &__x)
template<typename _IntType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &, std::uniform_int_distribution< _IntType > &)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, lognormal_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, chi_squared_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &, std::uniform_real_distribution< _RealType > &)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, fisher_f_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, student_t_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, gamma_distribution< _RealType > &__x)
template<typename _IntType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, discrete_distribution< _IntType > &__x)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > &__str)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, piecewise_constant_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, piecewise_linear_distribution< _RealType > &__x)
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Alloc > &__str)
template<> basic_istream< char > & operator>> (basic_istream< char > &__is, basic_string< char > &__str)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::cauchy_distribution< _RealType > &__x)
template<typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::bernoulli_distribution &__x)
template<typename _IntType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::geometric_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::exponential_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::weibull_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::extreme_value_distribution< _RealType > &__x)
constexpr _Ios_Fmtflags operator^ (_Ios_Fmtflags __a, _Ios_Fmtflags __b)
constexpr _Ios_Openmode operator^ (_Ios_Openmode __a, _Ios_Openmode __b)
constexpr launch operator^ (launch __x, launch __y)
constexpr _Ios_Iostate operator^ (_Ios_Iostate __a, _Ios_Iostate __b)
template<class _Dom > _Expr< _BinClos< __bitwise_xor,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun
< __bitwise_xor, typename
_Dom::value_type >
::result_type > operator^ (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __bitwise_xor,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun
< __bitwise_xor, typename
_Dom1::value_type >
::result_type > operator^ (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __bitwise_xor,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun
< __bitwise_xor, typename
_Dom::value_type >
::result_type > operator^ (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __bitwise_xor,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun
< __bitwise_xor, typename
_Dom::value_type >
::result_type > operator^ (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __bitwise_xor,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun
< __bitwise_xor, typename
_Dom::value_type >
::result_type > operator^ (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<typename _Tp > _Expr< _BinClos< __bitwise_xor,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun
< __bitwise_xor, _Tp >
::result_type > operator^ (const valarray< _Tp > &__v, const _Tp &__t)
template<typename _Tp > _Expr< _BinClos< __bitwise_xor,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun
< __bitwise_xor, _Tp >
::result_type > operator^ (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Tp > _Expr< _BinClos< __bitwise_xor,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun
< __bitwise_xor, _Tp >
::result_type > operator^ (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
const _Ios_Fmtflags & operator^= (_Ios_Fmtflags &__a, _Ios_Fmtflags __b)
const _Ios_Openmode & operator^= (_Ios_Openmode &__a, _Ios_Openmode __b)
launch & operator^= (launch &__x, launch __y)
const _Ios_Iostate & operator^= (_Ios_Iostate &__a, _Ios_Iostate __b)
bitset< _Nb > & operator^= (const bitset< _Nb > &__rhs) _GLIBCXX_NOEXCEPT
constexpr _Ios_Fmtflags operator| (_Ios_Fmtflags __a, _Ios_Fmtflags __b)
constexpr _Ios_Openmode operator| (_Ios_Openmode __a, _Ios_Openmode __b)
constexpr launch operator| (launch __x, launch __y)
constexpr _Ios_Iostate operator| (_Ios_Iostate __a, _Ios_Iostate __b)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __bitwise_or,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun< __bitwise_or,
typename _Dom1::value_type >
::result_type > operator| (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __bitwise_or,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __bitwise_or,
typename _Dom::value_type >
::result_type > operator| (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __bitwise_or,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __bitwise_or,
typename _Dom::value_type >
::result_type > operator| (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom > _Expr< _BinClos< __bitwise_or,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun< __bitwise_or,
typename _Dom::value_type >
::result_type > operator| (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom > _Expr< _BinClos< __bitwise_or,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun< __bitwise_or,
typename _Dom::value_type >
::result_type > operator| (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<typename _Tp > _Expr< _BinClos< __bitwise_or,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun< __bitwise_or,
_Tp >::result_type > operator| (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Tp > _Expr< _BinClos< __bitwise_or,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun< __bitwise_or,
_Tp >::result_type > operator| (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __bitwise_or,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun< __bitwise_or,
_Tp >::result_type > operator| (const valarray< _Tp > &__v, const _Tp &__t)
const _Ios_Fmtflags & operator|= (_Ios_Fmtflags &__a, _Ios_Fmtflags __b)
const _Ios_Openmode & operator|= (_Ios_Openmode &__a, _Ios_Openmode __b)
launch & operator|= (launch &__x, launch __y)
const _Ios_Iostate & operator|= (_Ios_Iostate &__a, _Ios_Iostate __b)
bitset< _Nb > & operator|= (const bitset< _Nb > &__rhs) _GLIBCXX_NOEXCEPT
template<class _Dom > _Expr< _BinClos< __logical_or,
_Expr, _Constant, _Dom,
typename _Dom::value_type >
, typename __fun< __logical_or,
typename _Dom::value_type >
::result_type > operator|| (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< __logical_or,
_Expr, _Expr, _Dom1, _Dom2 >
, typename __fun< __logical_or,
typename _Dom1::value_type >
::result_type > operator|| (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom > _Expr< _BinClos< __logical_or,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __logical_or,
typename _Dom::value_type >
::result_type > operator|| (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom > _Expr< _BinClos< __logical_or,
_Expr, _ValArray, _Dom,
typename _Dom::value_type >
, typename __fun< __logical_or,
typename _Dom::value_type >
::result_type > operator|| (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom > _Expr< _BinClos< __logical_or,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename __fun< __logical_or,
typename _Dom::value_type >
::result_type > operator|| (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp > _Expr< _BinClos< __logical_or,
_Constant, _ValArray, _Tp, _Tp >
, typename __fun< __logical_or,
_Tp >::result_type > operator|| (const _Tp &__t, const valarray< _Tp > &__v)
template<typename _Tp > _Expr< _BinClos< __logical_or,
_ValArray, _ValArray, _Tp, _Tp >
, typename __fun< __logical_or,
_Tp >::result_type > operator|| (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< __logical_or,
_ValArray, _Constant, _Tp, _Tp >
, typename __fun< __logical_or,
_Tp >::result_type > operator|| (const valarray< _Tp > &__v, const _Tp &__t)
constexpr _Ios_Fmtflags operator~ (_Ios_Fmtflags __a)
constexpr _Ios_Openmode operator~ (_Ios_Openmode __a)
constexpr launch operator~ (launch __x)
constexpr _Ios_Iostate operator~ (_Ios_Iostate __a)
bitset< _Nb > operator~ () const _GLIBCXX_NOEXCEPT
template<typename _RAIter > void partial_sort (_RAIter, _RAIter, _RAIter)
template<typename _RAIter , typename _Compare > void partial_sort (_RAIter, _RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator > void partial_sort (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void partial_sort (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, _Compare __comp)
template<typename _IIter , typename _RAIter > _RAIter partial_sort_copy (_IIter, _IIter, _RAIter, _RAIter)
template<typename _IIter , typename _RAIter , typename _Compare > _RAIter partial_sort_copy (_IIter, _IIter, _RAIter, _RAIter, _Compare)
template<typename _InputIterator , typename _RandomAccessIterator > _RandomAccessIterator partial_sort_copy (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __result_first, _RandomAccessIterator __result_last)
template<typename _InputIterator , typename _RandomAccessIterator , typename _Compare > _RandomAccessIterator partial_sort_copy (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __result_first, _RandomAccessIterator __result_last, _Compare __comp)
template<typename _InputIterator , typename _OutputIterator > _OutputIterator partial_sum (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation > _OutputIterator partial_sum (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op)
template<typename _BIter , typename _Predicate > _BIter partition (_BIter, _BIter, _Predicate)
template<typename _ForwardIterator , typename _Predicate > _ForwardIterator partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _IIter , typename _OIter1 , typename _OIter2 , typename _Predicate > pair< _OIter1, _OIter2 > partition_copy (_IIter, _IIter, _OIter1, _OIter2, _Predicate)
template<typename _InputIterator , typename _OutputIterator1 , typename _OutputIterator2 , typename _Predicate > pair< _OutputIterator1,
_OutputIterator2 > partition_copy (_InputIterator __first, _InputIterator __last, _OutputIterator1 __out_true, _OutputIterator2 __out_false, _Predicate __pred)
template<typename _FIter , typename _Predicate > _FIter partition_point (_FIter, _FIter, _Predicate)
template<typename _ForwardIterator , typename _Predicate > _ForwardIterator partition_point (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _Tp > complex< _Tp > polar (const _Tp &, const _Tp &=0)
template<typename _RandomAccessIterator > void pop_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void pop_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RAIter > void pop_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare > void pop_heap (_RAIter, _RAIter, _Compare)
template<typename _Tp > complex< _Tp > pow (const complex< _Tp > &, const _Tp &)
template<typename _Tp > complex< _Tp > pow (const complex< _Tp > &, const complex< _Tp > &)
template<typename _Tp > complex< _Tp > pow (const _Tp &, const complex< _Tp > &)
constexpr float pow (float __x, float __y)
constexpr long double pow (long double __x, long double __y)
template<typename _Tp , typename _Up > constexpr
__gnu_cxx::__promote_2< _Tp,
_Up >::__type pow (_Tp __x, _Up __y)
template<class _Dom > _Expr< _BinClos< _Pow, _Expr,
_Constant, _Dom, typename
_Dom::value_type >, typename
_Dom::value_type > pow (const _Expr< _Dom, typename _Dom::value_type > &__e, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 > _Expr< _BinClos< _Pow, _Expr,
_Expr, _Dom1, _Dom2 >
, typename _Dom1::value_type > pow (const _Expr< _Dom1, typename _Dom1::value_type > &__e1, const _Expr< _Dom2, typename _Dom2::value_type > &__e2)
template<class _Dom > _Expr< _BinClos< _Pow,
_Constant, _Expr, typename
_Dom::value_type, _Dom >
, typename _Dom::value_type > pow (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _BinClos< _Pow,
_ValArray, _Constant, _Tp, _Tp >
, _Tp > pow (const valarray< _Tp > &__v, const _Tp &__t)
template<class _Dom > _Expr< _BinClos< _Pow, _Expr,
_ValArray, _Dom, typename
_Dom::value_type >, typename
_Dom::value_type > pow (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<typename _Tp > _Expr< _BinClos< _Pow,
_ValArray, _ValArray, _Tp, _Tp >
, _Tp > pow (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp > _Expr< _BinClos< _Pow,
_Constant, _ValArray, _Tp, _Tp >
, _Tp > pow (const _Tp &__t, const valarray< _Tp > &__v)
template<class _Dom > _Expr< _BinClos< _Pow,
_ValArray, _Expr, typename
_Dom::value_type, _Dom >
, typename _Dom::value_type > pow (const valarray< typename _Dom::valarray > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp , typename _Up > std::complex< typename
__gnu_cxx::__promote_2< _Tp,
_Up >::__type > pow (const std::complex< _Tp > &__x, const _Up &__y)
template<typename _Tp , typename _Up > std::complex< typename
__gnu_cxx::__promote_2< _Tp,
_Up >::__type > pow (const _Tp &__x, const std::complex< _Up > &__y)
template<typename _Tp , typename _Up > std::complex< typename
__gnu_cxx::__promote_2< _Tp,
_Up >::__type > pow (const std::complex< _Tp > &__x, const std::complex< _Up > &__y)
template<typename _BidirectionalIterator > _BidirectionalIterator prev (_BidirectionalIterator __x, typename iterator_traits< _BidirectionalIterator >::difference_type __n=1)
template<typename _BIter > bool prev_permutation (_BIter, _BIter)
template<typename _BIter , typename _Compare > bool prev_permutation (_BIter, _BIter, _Compare)
template<typename _BidirectionalIterator > bool prev_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last)
template<typename _BidirectionalIterator , typename _Compare > bool prev_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last, _Compare __comp)
template<typename _Tp > std::complex< _Tp > proj (const std::complex< _Tp > &)
template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type proj (_Tp __x)
template<typename _Arg , typename _Result > pointer_to_unary_function
< _Arg, _Result > ptr_fun (_Result(*__x)(_Arg))
template<typename _Arg1 , typename _Arg2 , typename _Result > pointer_to_binary_function
< _Arg1, _Arg2, _Result > ptr_fun (_Result(*__x)(_Arg1, _Arg2))
template<typename _RandomAccessIterator > void push_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void push_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RAIter > void push_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare > void push_heap (_RAIter, _RAIter, _Compare)
template<typename _MoneyT > _Put_money< _MoneyT > put_money (const _MoneyT &__mon, bool __intl=false)
template<typename _RAIter > void random_shuffle (_RAIter, _RAIter)
template<typename _RAIter , typename _Generator > void random_shuffle (_RAIter, _RAIter, _Generator &&)
template<typename _RandomAccessIterator > void random_shuffle (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _RandomNumberGenerator > void random_shuffle (_RandomAccessIterator __first, _RandomAccessIterator __last, _RandomNumberGenerator &&__rand)
template<typename _Tp > constexpr _Tp real (const complex< _Tp > &__z)
template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type real (_Tp __x)
template<typename _FIter , typename _Tp > _FIter remove (_FIter, _FIter, const _Tp &)
template<typename _ForwardIterator , typename _Tp > _ForwardIterator remove (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _IIter , typename _OIter , typename _Tp > _OIter remove_copy (_IIter, _IIter, _OIter, const _Tp &)
template<typename _InputIterator , typename _OutputIterator , typename _Tp > _OutputIterator remove_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, const _Tp &__value)
template<typename _IIter , typename _OIter , typename _Predicate > _OIter remove_copy_if (_IIter, _IIter, _OIter, _Predicate)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate > _OutputIterator remove_copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred)
template<typename _FIter , typename _Predicate > _FIter remove_if (_FIter, _FIter, _Predicate)
template<typename _ForwardIterator , typename _Predicate > _ForwardIterator remove_if (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _FIter , typename _Tp > void replace (_FIter, _FIter, const _Tp &, const _Tp &)
template<typename _ForwardIterator , typename _Tp > void replace (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__old_value, const _Tp &__new_value)
template<typename _IIter , typename _OIter , typename _Tp > _OIter replace_copy (_IIter, _IIter, _OIter, const _Tp &, const _Tp &)
template<typename _InputIterator , typename _OutputIterator , typename _Tp > _OutputIterator replace_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, const _Tp &__old_value, const _Tp &__new_value)
template<typename _Iter , typename _OIter , typename _Predicate , typename _Tp > _OIter replace_copy_if (_Iter, _Iter, _OIter, _Predicate, const _Tp &)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate , typename _Tp > _OutputIterator replace_copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred, const _Tp &__new_value)
template<typename _FIter , typename _Predicate , typename _Tp > void replace_if (_FIter, _FIter, _Predicate, const _Tp &)
template<typename _ForwardIterator , typename _Predicate , typename _Tp > void replace_if (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, const _Tp &__new_value)
bitset< _Nb > & reset () _GLIBCXX_NOEXCEPT
bitset< _Nb > & reset (size_t __position)
_Resetiosflags resetiosflags (ios_base::fmtflags __mask)
void rethrow_exception (exception_ptr) __attribute__((__noreturn__))
template<typename _Ex > void rethrow_if_nested (const _Ex &__ex)
void rethrow_if_nested (const nested_exception &__ex)
template<typename _Tp > void return_temporary_buffer (_Tp *__p)
template<typename _BIter > void reverse (_BIter, _BIter)
template<typename _BidirectionalIterator > void reverse (_BidirectionalIterator __first, _BidirectionalIterator __last)
template<typename _BIter , typename _OIter > _OIter reverse_copy (_BIter, _BIter, _OIter)
template<typename _BidirectionalIterator , typename _OutputIterator > _OutputIterator reverse_copy (_BidirectionalIterator __first, _BidirectionalIterator __last, _OutputIterator __result)
ios_base & right (ios_base &__base)
template<typename _FIter > void rotate (_FIter, _FIter, _FIter)
template<typename _ForwardIterator > void rotate (_ForwardIterator __first, _ForwardIterator __middle, _ForwardIterator __last)
template<typename _FIter , typename _OIter > _OIter rotate_copy (_FIter, _FIter, _FIter, _OIter)
template<typename _ForwardIterator , typename _OutputIterator > _OutputIterator rotate_copy (_ForwardIterator __first, _ForwardIterator __middle, _ForwardIterator __last, _OutputIterator __result)
ios_base & scientific (ios_base &__base)
template<typename _FIter1 , typename _FIter2 > _FIter1 search (_FIter1, _FIter1, _FIter2, _FIter2)
template<typename _FIter1 , typename _FIter2 , typename _BinaryPredicate > _FIter1 search (_FIter1, _FIter1, _FIter2, _FIter2, _BinaryPredicate)
template<typename _ForwardIterator1 , typename _ForwardIterator2 > _ForwardIterator1 search (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate > _ForwardIterator1 search (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, _BinaryPredicate __predicate)
template<typename _FIter , typename _Size , typename _Tp > _FIter search_n (_FIter, _FIter, _Size, const _Tp &)
template<typename _FIter , typename _Size , typename _Tp , typename _BinaryPredicate > _FIter search_n (_FIter, _FIter, _Size, const _Tp &, _BinaryPredicate)
template<typename _ForwardIterator , typename _Integer , typename _Tp > _ForwardIterator search_n (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, const _Tp &__val)
template<typename _ForwardIterator , typename _Integer , typename _Tp , typename _BinaryPredicate > _ForwardIterator search_n (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, const _Tp &__val, _BinaryPredicate __binary_pred)
bitset< _Nb > & set () _GLIBCXX_NOEXCEPT
bitset< _Nb > & set (size_t __position, bool __val=true)
template<typename _IIter1 , typename _IIter2 , typename _OIter > _OIter set_difference (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare > _OIter set_difference (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator > _OutputIterator set_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare > _OutputIterator set_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _IIter1 , typename _IIter2 , typename _OIter > _OIter set_intersection (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare > _OIter set_intersection (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator > _OutputIterator set_intersection (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare > _OutputIterator set_intersection (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
new_handler set_new_handler (new_handler) throw ()
template<typename _IIter1 , typename _IIter2 , typename _OIter > _OIter set_symmetric_difference (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare > _OIter set_symmetric_difference (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator > _OutputIterator set_symmetric_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare > _OutputIterator set_symmetric_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
terminate_handler set_terminate (terminate_handler) _GLIBCXX_USE_NOEXCEPT
unexpected_handler set_unexpected (unexpected_handler) _GLIBCXX_USE_NOEXCEPT
template<typename _IIter1 , typename _IIter2 , typename _OIter > _OIter set_union (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare > _OIter set_union (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator > _OutputIterator set_union (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare > _OutputIterator set_union (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
_Setbase setbase (int __base)
template<typename _CharT > _Setfill< _CharT > setfill (_CharT __c)
_Setiosflags setiosflags (ios_base::fmtflags __mask)
_Setprecision setprecision (int __n)
_Setw setw (int __n)
ios_base & showbase (ios_base &__base)
ios_base & showpoint (ios_base &__base)
ios_base & showpos (ios_base &__base)
template<typename _RAIter , typename _UGenerator > void shuffle (_RAIter, _RAIter, _UGenerator &&)
template<typename _RandomAccessIterator , typename _UniformRandomNumberGenerator > void shuffle (_RandomAccessIterator __first, _RandomAccessIterator __last, _UniformRandomNumberGenerator &&__g)
template<typename _Tp > complex< _Tp > sin (const complex< _Tp > &)
template<typename _Tp > _Expr< _UnClos< _Sin,
_ValArray, _Tp >, _Tp > sin (const valarray< _Tp > &__v)
template<class _Dom > _Expr< _UnClos< _Sin, _Expr,
_Dom >, typename
_Dom::value_type > sin (const _Expr< _Dom, typename _Dom::value_type > &__e)
constexpr float sin (float __x)
constexpr long double sin (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type sin (_Tp __x)
template<typename _Tp > complex< _Tp > sinh (const complex< _Tp > &)
template<class _Dom > _Expr< _UnClos< _Sinh, _Expr,
_Dom >, typename
_Dom::value_type > sinh (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _UnClos< _Sinh,
_ValArray, _Tp >, _Tp > sinh (const valarray< _Tp > &__v)
constexpr float sinh (float __x)
constexpr long double sinh (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type sinh (_Tp __x)
constexpr size_t size () const _GLIBCXX_NOEXCEPT
ios_base & skipws (ios_base &__base)
template<typename _RAIter > void sort (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare > void sort (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator > void sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator > void sort_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void sort_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RAIter > void sort_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare > void sort_heap (_RAIter, _RAIter, _Compare)
template<typename _Tp > complex< _Tp > sqrt (const complex< _Tp > &)
template<class _Dom > _Expr< _UnClos< _Sqrt, _Expr,
_Dom >, typename
_Dom::value_type > sqrt (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _UnClos< _Sqrt,
_ValArray, _Tp >, _Tp > sqrt (const valarray< _Tp > &__v)
constexpr float sqrt (float __x)
constexpr long double sqrt (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type sqrt (_Tp __x)
template<typename _BIter , typename _Predicate > _BIter stable_partition (_BIter, _BIter, _Predicate)
template<typename _ForwardIterator , typename _Predicate > _ForwardIterator stable_partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _RAIter > void stable_sort (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare > void stable_sort (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator > void stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare > void stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _Tp , typename _Tp1 > shared_ptr< _Tp > static_pointer_cast (const shared_ptr< _Tp1 > &__r) noexcept
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp> __shared_ptr< _Tp, _Lp > static_pointer_cast (const __shared_ptr< _Tp1, _Lp > &__r) noexcept
char * strchr (char *__s, int __n)
char * strpbrk (char *__s1, const char *__s2)
char * strrchr (char *__s, int __n)
char * strstr (char *__s1, const char *__s2)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc , bool __cache_hash_code> void swap (__unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc, __cache_hash_code > &__x, __unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc, __cache_hash_code > &__y)
void swap (thread &__x, thread &__y) noexcept
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc , bool __cache_hash_code> void swap (__unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc, __cache_hash_code > &__x, __unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc, __cache_hash_code > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc , bool __cache_hash_code> void swap (__unordered_set< _Value, _Hash, _Pred, _Alloc, __cache_hash_code > &__x, __unordered_set< _Value, _Hash, _Pred, _Alloc, __cache_hash_code > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc , bool __cache_hash_code> void swap (__unordered_multiset< _Value, _Hash, _Pred, _Alloc, __cache_hash_code > &__x, __unordered_multiset< _Value, _Hash, _Pred, _Alloc, __cache_hash_code > &__y)
template<typename _Tp , std::size_t _Nm> void swap (array< _Tp, _Nm > &__one, array< _Tp, _Nm > &__two) noexcept(noexcept(__one.swap(__two)))
template<class _T1 , class _T2 > void swap (pair< _T1, _T2 > &__x, pair< _T1, _T2 > &__y) noexcept(noexcept(__x.swap(__y)))
template<typename _Tp , typename _Seq > void swap (stack< _Tp, _Seq > &__x, stack< _Tp, _Seq > &__y) noexcept(noexcept(__x.swap(__y)))
template<typename _Tp , typename _Seq > void swap (queue< _Tp, _Seq > &__x, queue< _Tp, _Seq > &__y) noexcept(noexcept(__x.swap(__y)))
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc > void swap (unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc > void swap (unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc > void swap (unordered_set< _Value, _Hash, _Pred, _Alloc > &__x, unordered_set< _Value, _Hash, _Pred, _Alloc > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc > void swap (unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__x, unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__y)
template<typename _Tp > void swap (shared_ptr< _Tp > &__a, shared_ptr< _Tp > &__b) noexcept
template<typename _Tp , typename _Dp > void swap (unique_ptr< _Tp, _Dp > &__x, unique_ptr< _Tp, _Dp > &__y) noexcept
template<typename _Tp > void swap (weak_ptr< _Tp > &__a, weak_ptr< _Tp > &__b) noexcept
template<typename _Tp , typename _Sequence , typename _Compare > void swap (priority_queue< _Tp, _Sequence, _Compare > &__x, priority_queue< _Tp, _Sequence, _Compare > &__y) noexcept(noexcept(__x.swap(__y)))
template<typename _Tp > void swap (_Tp &__a, _Tp &__b) noexcept(__and_< is_nothrow_move_constructible< _Tp >
template<typename _Tp , size_t _Nm> void swap (_Tp(&__a)[_Nm], _Tp(&__b)[_Nm]) noexcept(noexcept(swap(*__a
template<typename _Mutex > void swap (unique_lock< _Mutex > &__x, unique_lock< _Mutex > &__y) noexcept
template<typename _Key , typename _Compare , typename _Alloc > void swap (multiset< _Key, _Compare, _Alloc > &__x, multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Ch_type , typename _Rx_traits > void swap (basic_regex< _Ch_type, _Rx_traits > &__lhs, basic_regex< _Ch_type, _Rx_traits > &__rhs)
template<typename _Key , typename _Compare , typename _Alloc > void swap (set< _Key, _Compare, _Alloc > &__x, set< _Key, _Compare, _Alloc > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > void swap (multimap< _Key, _Tp, _Compare, _Alloc > &__x, multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc > void swap (_Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > void swap (map< _Key, _Tp, _Compare, _Alloc > &__x, map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename... _Elements> void swap (tuple< _Elements...> &__x, tuple< _Elements...> &__y) noexcept(noexcept(__x.swap(__y)))
template<typename _Tp , _Lock_policy _Lp> void swap (__shared_ptr< _Tp, _Lp > &__a, __shared_ptr< _Tp, _Lp > &__b) noexcept
template<typename _Tp , typename _Alloc > void swap (forward_list< _Tp, _Alloc > &__lx, forward_list< _Tp, _Alloc > &__ly)
template<typename _Tp , _Lock_policy _Lp> void swap (__weak_ptr< _Tp, _Lp > &__a, __weak_ptr< _Tp, _Lp > &__b) noexcept
template<typename _Tp , typename _Alloc > void swap (vector< _Tp, _Alloc > &__x, vector< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc > void swap (list< _Tp, _Alloc > &__x, list< _Tp, _Alloc > &__y)
template<typename _Bi_iter , typename _Allocator > void swap (match_results< _Bi_iter, _Allocator > &__lhs, match_results< _Bi_iter, _Allocator > &__rhs)
template<typename _Tp , typename _Alloc > void swap (deque< _Tp, _Alloc > &__x, deque< _Tp, _Alloc > &__y)
template<typename _Res , typename... _Args> void swap (function< _Res(_Args...)> &__x, function< _Res(_Args...)> &__y)
template<typename _CharT , typename _Traits , typename _Alloc > void swap (basic_string< _CharT, _Traits, _Alloc > &__lhs, basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _ForwardIterator1 , typename _ForwardIterator2 > _ForwardIterator2 swap_ranges (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2)
template<typename _FIter1 , typename _FIter2 > _FIter2 swap_ranges (_FIter1, _FIter1, _FIter2)
const error_category & system_category () noexcept
template<typename _Tp > complex< _Tp > tan (const complex< _Tp > &)
template<class _Dom > _Expr< _UnClos< _Tan, _Expr,
_Dom >, typename
_Dom::value_type > tan (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp > _Expr< _UnClos< _Tan,
_ValArray, _Tp >, _Tp > tan (const valarray< _Tp > &__v)
constexpr float tan (float __x)
constexpr long double tan (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type tan (_Tp __x)
template<typename _Tp > complex< _Tp > tanh (const complex< _Tp > &)
template<typename _Tp > _Expr< _UnClos< _Tanh,
_ValArray, _Tp >, _Tp > tanh (const valarray< _Tp > &__v)
template<class _Dom > _Expr< _UnClos< _Tanh, _Expr,
_Dom >, typename
_Dom::value_type > tanh (const _Expr< _Dom, typename _Dom::value_type > &__e)
constexpr float tanh (float __x)
constexpr long double tanh (long double __x)
template<typename _Tp > constexpr
__gnu_cxx::__enable_if
< __is_integer< _Tp >::__value,
double >::__type tanh (_Tp __x)
void terminate () _GLIBCXX_USE_NOEXCEPT __attribute__((__noreturn__))
bool test (size_t __position) const
template<typename _Ex > void throw_with_nested (_Ex __ex)
template<typename... _Elements> tuple< _Elements &...> tie (_Elements &...__args) noexcept
template<class _CharT , class _Traits , class _Alloc > std::basic_string< _CharT,
_Traits, _Alloc > to_string () const
template<class _CharT , class _Traits , class _Alloc > std::basic_string< _CharT,
_Traits, _Alloc > to_string (_CharT __zero, _CharT __one=_CharT('1')) const
template<class _CharT , class _Traits > std::basic_string< _CharT,
_Traits, std::allocator
< _CharT > > to_string () const
template<class _CharT , class _Traits > std::basic_string< _CharT,
_Traits, std::allocator
< _CharT > > to_string (_CharT __zero, _CharT __one=_CharT('1')) const
template<class _CharT > std::basic_string< _CharT,
std::char_traits< _CharT >
, std::allocator< _CharT > > to_string () const
template<class _CharT > std::basic_string< _CharT,
std::char_traits< _CharT >
, std::allocator< _CharT > > to_string (_CharT __zero, _CharT __one=_CharT('1')) const
std::basic_string< char,
std::char_traits< char >
, std::allocator< char > > to_string (char __zero, char __one= '1') const
unsigned long long to_ullong () const
unsigned long to_ulong () const
template<typename _CharT > _CharT tolower (_CharT __c, const locale &__loc)
template<typename _CharT > _CharT toupper (_CharT __c, const locale &__loc)
template<typename _IIter , typename _OIter , typename _UnaryOperation > _OIter transform (_IIter, _IIter, _OIter, _UnaryOperation)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _BinaryOperation > _OIter transform (_IIter1, _IIter1, _IIter2, _OIter, _BinaryOperation)
template<typename _InputIterator , typename _OutputIterator , typename _UnaryOperation > _OutputIterator transform (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _UnaryOperation __unary_op)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _BinaryOperation > _OutputIterator transform (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _OutputIterator __result, _BinaryOperation __binary_op)
template<typename _Lock1 , typename _Lock2 , typename... _Lock3> int try_lock (_Lock1 &__l1, _Lock2 &__l2, _Lock3 &...__l3)
template<typename... _Tpls, typename = typename enable_if<__and_<__is_tuple_like<_Tpls>...>::value>::type> constexpr auto tuple_cat (_Tpls &&...__tpls)-> typename __tuple_cat_result< _Tpls...>
bool uncaught_exception () _GLIBCXX_USE_NOEXCEPT __attribute__((__pure__))
void unexpected () __attribute__((__noreturn__))
template<typename _InputIterator , typename _ForwardIterator > _ForwardIterator uninitialized_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result)
template<typename _InputIterator , typename _Size , typename _ForwardIterator > _ForwardIterator uninitialized_copy_n (_InputIterator __first, _Size __n, _ForwardIterator __result)
template<typename _ForwardIterator , typename _Tp > void uninitialized_fill (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__x)
template<typename _ForwardIterator , typename _Size , typename _Tp > void uninitialized_fill_n (_ForwardIterator __first, _Size __n, const _Tp &__x)
template<typename _FIter > _FIter unique (_FIter, _FIter)
template<typename _FIter , typename _BinaryPredicate > _FIter unique (_FIter, _FIter, _BinaryPredicate)
template<typename _ForwardIterator > _ForwardIterator unique (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _BinaryPredicate > _ForwardIterator unique (_ForwardIterator __first, _ForwardIterator __last, _BinaryPredicate __binary_pred)
template<typename _IIter , typename _OIter > _OIter unique_copy (_IIter, _IIter, _OIter)
template<typename _IIter , typename _OIter , typename _BinaryPredicate > _OIter unique_copy (_IIter, _IIter, _OIter, _BinaryPredicate)
template<typename _InputIterator , typename _OutputIterator > _OutputIterator unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryPredicate > _OutputIterator unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred)
ios_base & unitbuf (ios_base &__base)
template<typename _FIter , typename _Tp > _FIter upper_bound (_FIter, _FIter, const _Tp &)
template<typename _FIter , typename _Tp , typename _Compare > _FIter upper_bound (_FIter, _FIter, const _Tp &, _Compare)
template<typename _ForwardIterator , typename _Tp > _ForwardIterator upper_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val)
template<typename _ForwardIterator , typename _Tp , typename _Compare > _ForwardIterator upper_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
ios_base & uppercase (ios_base &__base)
template<typename _Facet > const _Facet & use_facet (const locale &__loc)
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & ws (basic_istream< _CharT, _Traits > &__is)
bitset< _Nb > & operator<<= (size_t __position) _GLIBCXX_NOEXCEPT
bitset< _Nb > & operator>>= (size_t __position) _GLIBCXX_NOEXCEPT
bitset< _Nb > & _Unchecked_set (size_t __pos) _GLIBCXX_NOEXCEPT
bitset< _Nb > & _Unchecked_set (size_t __pos, int __val) _GLIBCXX_NOEXCEPT
bitset< _Nb > & _Unchecked_reset (size_t __pos) _GLIBCXX_NOEXCEPT
bitset< _Nb > & _Unchecked_flip (size_t __pos) _GLIBCXX_NOEXCEPT
constexpr bool _Unchecked_test (size_t __pos) const _GLIBCXX_NOEXCEPT
reference operator[] (size_t __position)
bool operator== (const bitset< _Nb > &__rhs) const _GLIBCXX_NOEXCEPT
bool operator!= (const bitset< _Nb > &__rhs) const _GLIBCXX_NOEXCEPT
bitset< _Nb > operator<< (size_t __position) const _GLIBCXX_NOEXCEPT
bitset< _Nb > operator>> (size_t __position) const _GLIBCXX_NOEXCEPT
template<size_t _Nb> bitset< _Nb > operator& (const bitset< _Nb > &__x, const bitset< _Nb > &__y) _GLIBCXX_NOEXCEPT
template<size_t _Nb> bitset< _Nb > operator| (const bitset< _Nb > &__x, const bitset< _Nb > &__y) _GLIBCXX_NOEXCEPT
template<size_t _Nb> bitset< _Nb > operator^ (const bitset< _Nb > &__x, const bitset< _Nb > &__y) _GLIBCXX_NOEXCEPT
template<class _CharT , class _Traits , size_t _Nb> std::basic_istream< _CharT,
_Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, bitset< _Nb > &__x)
template<class _CharT , class _Traits , size_t _Nb> std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const bitset< _Nb > &__x)
template<typename _Tp > complex< _Tp > operator+ (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > operator+ (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp > complex< _Tp > operator+ (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > operator- (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > operator- (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp > complex< _Tp > operator- (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > operator* (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > operator* (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp > complex< _Tp > operator* (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > operator/ (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > operator/ (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp > complex< _Tp > operator/ (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp > constexpr bool operator== (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > constexpr bool operator== (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp > constexpr bool operator== (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp > constexpr bool operator!= (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > constexpr bool operator!= (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp > constexpr bool operator!= (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp > reference_wrapper< _Tp > ref (_Tp &__t) noexcept
template<typename _Tp > reference_wrapper< const _Tp > cref (const _Tp &__t) noexcept
template<typename _Tp > void ref (const _Tp &&)
template<typename _Tp > void cref (const _Tp &&)
template<typename _Tp > reference_wrapper< _Tp > ref (reference_wrapper< _Tp > __t) noexcept
template<typename _Tp > reference_wrapper< const _Tp > cref (reference_wrapper< _Tp > __t) noexcept
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__in, _CharT &__c)
template<class _Traits > basic_istream< char, _Traits > & operator>> (basic_istream< char, _Traits > &__in, unsigned char &__c)
template<class _Traits > basic_istream< char, _Traits > & operator>> (basic_istream< char, _Traits > &__in, signed char &__c)
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__in, _CharT *__s)
template<> basic_istream< char > & operator>> (basic_istream< char > &__in, char *__s)
template<class _Traits > basic_istream< char, _Traits > & operator>> (basic_istream< char, _Traits > &__in, unsigned char *__s)
template<class _Traits > basic_istream< char, _Traits > & operator>> (basic_istream< char, _Traits > &__in, signed char *__s)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__out, _CharT __c)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__out, char __c)
template<class _Traits > basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &__out, char __c)
template<class _Traits > basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &__out, signed char __c)
template<class _Traits > basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &__out, unsigned char __c)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__out, const _CharT *__s)
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__out, const char *__s)
template<class _Traits > basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &__out, const char *__s)
template<class _Traits > basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &__out, const signed char *__s)
template<class _Traits > basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &__out, const unsigned char *__s)
Matching, Searching, and Replacing
template<typename _Bi_iter , typename _Allocator , typename _Ch_type , typename _Rx_traits > bool regex_match (_Bi_iter __s, _Bi_iter __e, match_results< _Bi_iter, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Bi_iter , typename _Ch_type , typename _Rx_traits > bool regex_match (_Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_type , typename _Allocator , typename _Rx_traits > bool regex_match (const _Ch_type *__s, match_results< const _Ch_type *, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _Ch_alloc , typename _Allocator , typename _Ch_type , typename _Rx_traits > bool regex_match (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &__s, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_type , class _Rx_traits > bool regex_match (const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _Str_allocator , typename _Ch_type , typename _Rx_traits > bool regex_match (const basic_string< _Ch_type, _Ch_traits, _Str_allocator > &__s, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Bi_iter , typename _Allocator , typename _Ch_type , typename _Rx_traits > bool regex_search (_Bi_iter __first, _Bi_iter __last, match_results< _Bi_iter, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Bi_iter , typename _Ch_type , typename _Rx_traits > bool regex_search (_Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_type , class _Allocator , class _Rx_traits > bool regex_search (const _Ch_type *__s, match_results< const _Ch_type *, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_type , typename _Rx_traits > bool regex_search (const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _String_allocator , typename _Ch_type , typename _Rx_traits > bool regex_search (const basic_string< _Ch_type, _Ch_traits, _String_allocator > &__s, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_traits , typename _Ch_alloc , typename _Allocator , typename _Ch_type , typename _Rx_traits > bool regex_search (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &__s, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Out_iter , typename _Bi_iter , typename _Rx_traits , typename _Ch_type > _Out_iter regex_replace (_Out_iter __out, _Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type > &__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Rx_traits , typename _Ch_type > basic_string< _Ch_type > regex_replace (const basic_string< _Ch_type > &__s, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type > &__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
Variables
__a
void * __b
enable_if< (!is_member_pointer
< _Functor >::value
&&!is_function< _Functor >
::value &&!is_function
< typename remove_pointer
< _Functor >::type >::value),
typename result_of< _Functor(_Args &&...)>
::type >::type __invoke (_Functor &__f, _Args &&...__args)
static ios_base::Init __ioinit
function< void()> __once_functor
void
is_nothrow_move_assignable
< _Tp >::value _Tp __tmp
constexpr allocator_arg_t allocator_arg
error_code make_error_code (errc) noexcept
error_condition make_error_condition (errc) noexcept
const nothrow_t nothrow
constexpr piecewise_construct_t piecewise_construct
return * this
Standard Stream Objects
The <iostream> header declares the eight standard stream objects. For other declarations, see http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt11ch24.html and the I/O forward declarations
They are required by default to cooperate with the global C library's FILE streams, and to be available during program startup and termination. For more information, see the HOWTO linked to above.
istream cin
ostream cout
ostream cerr
ostream clog
wistream wcin
wostream wcout
wostream wcerr
wostream wclog
Detailed Description
ISO C++ entities toplevel namespace is std.
Typedef Documentation
typedef void(* std::new_handler)()
If you write your own error handler to be called by new, it must be of this type.
Definition at line 75 of file new.
typedef long long std::streamoff
Type used by fpos, char_traits<char>, and char_traits<wchar_t>.
In clauses 21.1.3.1 and 27.4.1 streamoff is described as an implementation defined type. Note: In versions of GCC up to and including GCC 3.3, streamoff was typedef long.
Definition at line 96 of file postypes.h.
typedef fpos<mbstate_t> std::streampos
File position for char streams.
Definition at line 230 of file postypes.h.
typedef ptrdiff_t std::streamsize
Integral type for I/O operation counts and buffer sizes.
Definition at line 100 of file postypes.h.
typedef fpos<mbstate_t> std::u16streampos
File position for char16_t streams.
Definition at line 236 of file postypes.h.
typedef fpos<mbstate_t> std::u32streampos
File position for char32_t streams.
Definition at line 238 of file postypes.h.
typedef fpos<mbstate_t> std::wstreampos
File position for wchar_t streams.
Definition at line 232 of file postypes.h.
Enumeration Type Documentation
anonymous enum
Todo:
Needs documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html This controls some aspect of the sort routines.
Definition at line 2227 of file stl_algo.h.
enum std::float_denorm_style
Describes the denormalization for floating-point types.
These values represent the presence or absence of a variable number of exponent bits. This type is used in the std::numeric_limits class.
Enumerator:
denorm_indeterminate
Indeterminate at compile time whether denormalized values are allowed.
denorm_absent
The type does not allow denormalized values.
denorm_present
The type allows denormalized values.
Definition at line 172 of file limits.
enum std::float_round_style
Describes the rounding style for floating-point types.
This is used in the std::numeric_limits class.
Enumerator:
round_toward_zero
Intermediate.
round_to_nearest
To zero.
round_toward_infinity
To the nearest representable value.
round_toward_neg_infinity
To infinity.
Definition at line 157 of file limits.
Function Documentation
size_t std::__deque_buf_size (size_t __size) [inline]
This function controls the size of memory nodes.
Parameters:
__size The size of an element.
Returns:
The number (not byte size) of elements per node.
This function started off as a compiler kludge from SGI, but seems to be a useful wrapper around a repeated constant expression. The 512 is tunable (and no other code needs to change), but no investigation has been done since inheriting the SGI code. Touch _GLIBCXX_DEQUE_BUF_SIZE only if you know what you are doing, however: changing it breaks the binary compatibility!!
Definition at line 90 of file stl_deque.h.
Referenced by std::_Deque_base< _Tp, _Alloc >::_M_initialize_map().
template<typename _RandomAccessIterator > void std::__final_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
This is a helper function for the sort routine.
Definition at line 2232 of file stl_algo.h.
References __insertion_sort(), and __unguarded_insertion_sort().
Referenced by sort().
template<typename _RandomAccessIterator , typename _Compare > void std::__final_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
This is a helper function for the sort routine.
Definition at line 2247 of file stl_algo.h.
References __insertion_sort(), and __unguarded_insertion_sort().
template<typename _InputIterator , typename _Tp > _InputIterator std::__find (_InputIterator __first, _InputIterator __last, const _Tp & __val, input_iterator_tag) [inline]
This is an overload used by find() for the Input Iterator case.
Definition at line 132 of file stl_algo.h.
Referenced by find().
template<typename _RandomAccessIterator , typename _Tp > _RandomAccessIterator std::__find (_RandomAccessIterator __first, _RandomAccessIterator __last, const _Tp & __val, random_access_iterator_tag)
This is an overload used by find() for the RAI case.
Definition at line 154 of file stl_algo.h.
template<typename _InputIterator , typename _Predicate > _InputIterator std::__find_if (_InputIterator __first, _InputIterator __last, _Predicate __pred, input_iterator_tag) [inline]
This is an overload used by find_if() for the Input Iterator case.
Definition at line 143 of file stl_algo.h.
Referenced by find_if().
template<typename _RandomAccessIterator , typename _Predicate > _RandomAccessIterator std::__find_if (_RandomAccessIterator __first, _RandomAccessIterator __last, _Predicate __pred, random_access_iterator_tag)
This is an overload used by find_if() for the RAI case.
Definition at line 202 of file stl_algo.h.
template<typename _InputIterator , typename _Predicate > _InputIterator std::__find_if_not (_InputIterator __first, _InputIterator __last, _Predicate __pred, input_iterator_tag) [inline]
This is an overload used by find_if_not() for the Input Iterator case.
Definition at line 250 of file stl_algo.h.
Referenced by __find_if_not(), find_if_not(), and stable_partition().
template<typename _RandomAccessIterator , typename _Predicate > _RandomAccessIterator std::__find_if_not (_RandomAccessIterator __first, _RandomAccessIterator __last, _Predicate __pred, random_access_iterator_tag)
This is an overload used by find_if_not() for the RAI case.
Definition at line 261 of file stl_algo.h.
template<typename _InputIterator , typename _Predicate > _InputIterator std::__find_if_not (_InputIterator __first, _InputIterator __last, _Predicate __pred) [inline]
Provided for stable_partition to use.
Definition at line 309 of file stl_algo.h.
References __find_if_not(), and __iterator_category().
template<typename _InputIterator , typename _Predicate , typename _Distance > _InputIterator std::__find_if_not_n (_InputIterator __first, _Distance & __len, _Predicate __pred)
Like find_if_not(), but uses and updates a count of the remaining range length instead of comparing against an end iterator.
Definition at line 321 of file stl_algo.h.
Referenced by __inplace_stable_partition(), and __stable_partition_adaptive().
template<typename _EuclideanRingElement > _EuclideanRingElement std::__gcd (_EuclideanRingElement __m, _EuclideanRingElement __n)
This is a helper function for the rotate algorithm specialized on RAIs. It returns the greatest common divisor of two integer values.
Definition at line 1520 of file stl_algo.h.
template<typename _RandomAccessIterator > void std::__heap_select (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last)
This is a helper function for the sort routines.
Definition at line 1955 of file stl_algo.h.
References make_heap().
Referenced by partial_sort().
template<typename _RandomAccessIterator , typename _Compare > void std::__heap_select (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, _Compare __comp)
This is a helper function for the sort routines.
Definition at line 1968 of file stl_algo.h.
References make_heap().
template<typename _ForwardIterator , typename _Predicate , typename _Distance > _ForwardIterator std::__inplace_stable_partition (_ForwardIterator __first, _Predicate __pred, _Distance __len)
This is a helper function... Requires __len != 0 and !__pred(*__first), same as __stable_partition_adaptive.
Definition at line 1811 of file stl_algo.h.
References __find_if_not_n(), advance(), distance(), and rotate().
Referenced by stable_partition().
template<typename _RandomAccessIterator > void std::__inplace_stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
This is a helper function for the stable sorting routines.
Definition at line 3511 of file stl_algo.h.
References __insertion_sort(), and __merge_without_buffer().
Referenced by __inplace_stable_sort(), and stable_sort().
template<typename _RandomAccessIterator , typename _Compare > void std::__inplace_stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
This is a helper function for the stable sorting routines.
Definition at line 3530 of file stl_algo.h.
References __inplace_stable_sort(), __insertion_sort(), and __merge_without_buffer().
template<typename _RandomAccessIterator > void std::__insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
This is a helper function for the sort routine.
Definition at line 2155 of file stl_algo.h.
References __unguarded_linear_insert().
Referenced by __final_insertion_sort(), and __inplace_stable_sort().
template<typename _RandomAccessIterator , typename _Compare > void std::__insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
This is a helper function for the sort routine.
Definition at line 2178 of file stl_algo.h.
References __unguarded_linear_insert().
template<typename _RandomAccessIterator , typename _Size > void std::__introsort_loop (_RandomAccessIterator __first, _RandomAccessIterator __last, _Size __depth_limit)
This is a helper function for the sort routine.
Definition at line 2327 of file stl_algo.h.
References __unguarded_partition_pivot().
Referenced by __introsort_loop(), and sort().
template<typename _RandomAccessIterator , typename _Size , typename _Compare > void std::__introsort_loop (_RandomAccessIterator __first, _RandomAccessIterator __last, _Size __depth_limit, _Compare __comp)
This is a helper function for the sort routine.
Definition at line 2349 of file stl_algo.h.
References __introsort_loop(), and __unguarded_partition_pivot().
template<typename _Size > _Size std::__lg (_Size __n) [inline]
This is a helper function for the sort routines and for random.tcc.
Definition at line 973 of file stl_algobase.h.
Referenced by nth_element(), std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType >::operator()(), std::linear_congruential_engine< _UIntType, __a, __c, __m >::seed(), and sort().
template<typename _BidirectionalIterator , typename _Distance , typename _Pointer > void std::__merge_adaptive (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Pointer __buffer, _Distance __buffer_size)
This is a helper function for the merge routines.
Definition at line 2959 of file stl_algo.h.
References __move_merge_adaptive(), __move_merge_adaptive_backward(), __rotate_adaptive(), advance(), distance(), lower_bound(), and upper_bound().
Referenced by __merge_adaptive(), and inplace_merge().
template<typename _BidirectionalIterator , typename _Distance , typename _Pointer , typename _Compare > void std::__merge_adaptive (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Pointer __buffer, _Distance __buffer_size, _Compare __comp)
This is a helper function for the merge routines.
Definition at line 3015 of file stl_algo.h.
References __merge_adaptive(), __move_merge_adaptive(), __move_merge_adaptive_backward(), __rotate_adaptive(), advance(), distance(), lower_bound(), and upper_bound().
template<typename _BidirectionalIterator , typename _Distance > void std::__merge_without_buffer (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2)
This is a helper function for the merge routines.
Definition at line 3072 of file stl_algo.h.
References advance(), distance(), iter_swap(), lower_bound(), rotate(), and upper_bound().
Referenced by __inplace_stable_sort(), __merge_without_buffer(), and inplace_merge().
template<typename _BidirectionalIterator , typename _Distance , typename _Compare > void std::__merge_without_buffer (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Compare __comp)
This is a helper function for the merge routines.
Definition at line 3116 of file stl_algo.h.
References __merge_without_buffer(), advance(), distance(), iter_swap(), lower_bound(), rotate(), and upper_bound().
template<typename _Iterator > void std::__move_median_first (_Iterator __a, _Iterator __b, _Iterator __c)
Swaps the median value of *__a, *__b and *__c to *__a.
Definition at line 80 of file stl_algo.h.
References iter_swap().
Referenced by __unguarded_partition_pivot().
template<typename _Iterator , typename _Compare > void std::__move_median_first (_Iterator __a, _Iterator __b, _Iterator __c, _Compare __comp)
Swaps the median value of *__a, *__b and *__c under __comp to *__a.
Definition at line 104 of file stl_algo.h.
References iter_swap().
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator > _OutputIterator std::__move_merge (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
This is a helper function for the __merge_sort_loop routines.
Definition at line 3274 of file stl_algo.h.
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare > _OutputIterator std::__move_merge (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
This is a helper function for the __merge_sort_loop routines.
Definition at line 3301 of file stl_algo.h.
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator > void std::__move_merge_adaptive (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
This is a helper function for the __merge_adaptive routines.
Definition at line 2780 of file stl_algo.h.
Referenced by __merge_adaptive().
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare > void std::__move_merge_adaptive (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
This is a helper function for the __merge_adaptive routines.
Definition at line 2806 of file stl_algo.h.
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _BidirectionalIterator3 > void std::__move_merge_adaptive_backward (_BidirectionalIterator1 __first1, _BidirectionalIterator1 __last1, _BidirectionalIterator2 __first2, _BidirectionalIterator2 __last2, _BidirectionalIterator3 __result)
This is a helper function for the __merge_adaptive routines.
Definition at line 2832 of file stl_algo.h.
Referenced by __merge_adaptive().
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _BidirectionalIterator3 , typename _Compare > void std::__move_merge_adaptive_backward (_BidirectionalIterator1 __first1, _BidirectionalIterator1 __last1, _BidirectionalIterator2 __first2, _BidirectionalIterator2 __last2, _BidirectionalIterator3 __result, _Compare __comp)
This is a helper function for the __merge_adaptive routines.
Definition at line 2874 of file stl_algo.h.
template<typename _ForwardIterator , typename _Predicate > _ForwardIterator std::__partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, forward_iterator_tag)
This is a helper function...
Definition at line 1754 of file stl_algo.h.
References iter_swap().
Referenced by partition().
template<typename _BidirectionalIterator , typename _Predicate > _BidirectionalIterator std::__partition (_BidirectionalIterator __first, _BidirectionalIterator __last, _Predicate __pred, bidirectional_iterator_tag)
This is a helper function...
Definition at line 1779 of file stl_algo.h.
References iter_swap().
template<typename _BidirectionalIterator > void std::__reverse (_BidirectionalIterator __first, _BidirectionalIterator __last, bidirectional_iterator_tag)
This is an uglified reverse(_BidirectionalIterator, _BidirectionalIterator) overloaded for bidirectional iterators.
Definition at line 1420 of file stl_algo.h.
References iter_swap().
Referenced by __rotate(), and reverse().
template<typename _RandomAccessIterator > void std::__reverse (_RandomAccessIterator __first, _RandomAccessIterator __last, random_access_iterator_tag)
This is an uglified reverse(_BidirectionalIterator, _BidirectionalIterator) overloaded for random access iterators.
Definition at line 1440 of file stl_algo.h.
References iter_swap().
template<typename _ForwardIterator > void std::__rotate (_ForwardIterator __first, _ForwardIterator __middle, _ForwardIterator __last, forward_iterator_tag)
This is a helper function for the rotate algorithm.
Definition at line 1534 of file stl_algo.h.
References iter_swap().
Referenced by __gnu_cxx::bitmap_allocator< _Tp >::_M_deallocate_single_object(), and rotate().
template<typename _BidirectionalIterator > void std::__rotate (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, bidirectional_iterator_tag)
This is a helper function for the rotate algorithm.
Definition at line 1570 of file stl_algo.h.
References __reverse(), and iter_swap().
template<typename _RandomAccessIterator > void std::__rotate (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, random_access_iterator_tag)
This is a helper function for the rotate algorithm.
Definition at line 1600 of file stl_algo.h.
References iter_swap(), and swap_ranges().
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _Distance > _BidirectionalIterator1 std::__rotate_adaptive (_BidirectionalIterator1 __first, _BidirectionalIterator1 __middle, _BidirectionalIterator1 __last, _Distance __len1, _Distance __len2, _BidirectionalIterator2 __buffer, _Distance __buffer_size)
This is a helper function for the merge routines.
Definition at line 2917 of file stl_algo.h.
References advance(), distance(), and rotate().
Referenced by __merge_adaptive().
template<typename _ForwardIterator , typename _Integer , typename _Tp > _ForwardIterator std::__search_n (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, const _Tp & __val, std::forward_iterator_tag)
This is an uglified search_n(_ForwardIterator, _ForwardIterator, _Integer, const _Tp&) overloaded for forward iterators.
Definition at line 349 of file stl_algo.h.
Referenced by search_n().
template<typename _RandomAccessIter , typename _Integer , typename _Tp > _RandomAccessIter std::__search_n (_RandomAccessIter __first, _RandomAccessIter __last, _Integer __count, const _Tp & __val, std::random_access_iterator_tag)
This is an uglified search_n(_ForwardIterator, _ForwardIterator, _Integer, const _Tp&) overloaded for random access iterators.
Definition at line 381 of file stl_algo.h.
template<typename _ForwardIterator , typename _Integer , typename _Tp , typename _BinaryPredicate > _ForwardIterator std::__search_n (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, const _Tp & __val, _BinaryPredicate __binary_pred, std::forward_iterator_tag)
This is an uglified search_n(_ForwardIterator, _ForwardIterator, _Integer, const _Tp&, _BinaryPredicate) overloaded for forward iterators.
Definition at line 435 of file stl_algo.h.
template<typename _RandomAccessIter , typename _Integer , typename _Tp , typename _BinaryPredicate > _RandomAccessIter std::__search_n (_RandomAccessIter __first, _RandomAccessIter __last, _Integer __count, const _Tp & __val, _BinaryPredicate __binary_pred, std::random_access_iterator_tag)
This is an uglified search_n(_ForwardIterator, _ForwardIterator, _Integer, const _Tp&, _BinaryPredicate) overloaded for random access iterators.
Definition at line 474 of file stl_algo.h.
template<typename _ForwardIterator , typename _Pointer , typename _Predicate , typename _Distance > _ForwardIterator std::__stable_partition_adaptive (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, _Distance __len, _Pointer __buffer, _Distance __buffer_size)
This is a helper function... Requires __first != __last and !__pred(*__first) and __len == distance(__first, __last).
!__pred(*__first) allows us to guarantee that we don't move-assign an element onto itself.
Definition at line 1843 of file stl_algo.h.
References __find_if_not_n(), advance(), distance(), and rotate().
Referenced by stable_partition().
template<typename _RandomAccessIterator > void std::__unguarded_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last) [inline]
This is a helper function for the sort routine.
Definition at line 2200 of file stl_algo.h.
References __unguarded_linear_insert().
Referenced by __final_insertion_sort().
template<typename _RandomAccessIterator , typename _Compare > void std::__unguarded_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp) [inline]
This is a helper function for the sort routine.
Definition at line 2213 of file stl_algo.h.
References __unguarded_linear_insert().
template<typename _RandomAccessIterator > void std::__unguarded_linear_insert (_RandomAccessIterator __last)
This is a helper function for the sort routine.
Definition at line 2118 of file stl_algo.h.
Referenced by __insertion_sort(), and __unguarded_insertion_sort().
template<typename _RandomAccessIterator , typename _Compare > void std::__unguarded_linear_insert (_RandomAccessIterator __last, _Compare __comp)
This is a helper function for the sort routine.
Definition at line 2136 of file stl_algo.h.
template<typename _RandomAccessIterator , typename _Tp > _RandomAccessIterator std::__unguarded_partition (_RandomAccessIterator __first, _RandomAccessIterator __last, const _Tp & __pivot)
This is a helper function...
Definition at line 2263 of file stl_algo.h.
References iter_swap().
Referenced by __unguarded_partition_pivot().
template<typename _RandomAccessIterator , typename _Tp , typename _Compare > _RandomAccessIterator std::__unguarded_partition (_RandomAccessIterator __first, _RandomAccessIterator __last, const _Tp & __pivot, _Compare __comp)
This is a helper function...
Definition at line 2283 of file stl_algo.h.
References iter_swap().
template<typename _RandomAccessIterator > _RandomAccessIterator std::__unguarded_partition_pivot (_RandomAccessIterator __first, _RandomAccessIterator __last) [inline]
This is a helper function...
Definition at line 2304 of file stl_algo.h.
References __move_median_first(), and __unguarded_partition().
Referenced by __introsort_loop().
template<typename _RandomAccessIterator , typename _Compare > _RandomAccessIterator std::__unguarded_partition_pivot (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp) [inline]
This is a helper function...
Definition at line 2316 of file stl_algo.h.
References __move_median_first(), and __unguarded_partition().
template<typename _ForwardIterator , typename _OutputIterator > _OutputIterator std::__unique_copy (_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __result, forward_iterator_tag , output_iterator_tag)
This is an uglified unique_copy(_InputIterator, _InputIterator, _OutputIterator) overloaded for forward iterators and output iterator as result.
Definition at line 1272 of file stl_algo.h.
Referenced by unique_copy().
template<typename _InputIterator , typename _OutputIterator > _OutputIterator std::__unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, input_iterator_tag , output_iterator_tag)
This is an uglified unique_copy(_InputIterator, _InputIterator, _OutputIterator) overloaded for input iterators and output iterator as result.
Definition at line 1295 of file stl_algo.h.
template<typename _InputIterator , typename _ForwardIterator > _ForwardIterator std::__unique_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, input_iterator_tag , forward_iterator_tag)
This is an uglified unique_copy(_InputIterator, _InputIterator, _OutputIterator) overloaded for input iterators and forward iterator as result.
Definition at line 1318 of file stl_algo.h.
template<typename _ForwardIterator , typename _OutputIterator , typename _BinaryPredicate > _OutputIterator std::__unique_copy (_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred, forward_iterator_tag , output_iterator_tag)
This is an uglified unique_copy(_InputIterator, _InputIterator, _OutputIterator, _BinaryPredicate) overloaded for forward iterators and output iterator as result.
Definition at line 1339 of file stl_algo.h.
template<typename _InputIterator , typename _OutputIterator , typename _BinaryPredicate > _OutputIterator std::__unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred, input_iterator_tag , output_iterator_tag)
This is an uglified unique_copy(_InputIterator, _InputIterator, _OutputIterator, _BinaryPredicate) overloaded for input iterators and output iterator as result.
Definition at line 1368 of file stl_algo.h.
template<typename _InputIterator , typename _ForwardIterator , typename _BinaryPredicate > _ForwardIterator std::__unique_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, _BinaryPredicate __binary_pred, input_iterator_tag , forward_iterator_tag)
This is an uglified unique_copy(_InputIterator, _InputIterator, _OutputIterator, _BinaryPredicate) overloaded for input iterators and forward iterator as result.
Definition at line 1397 of file stl_algo.h.
template<typename _T1 , typename... _Args> void std::_Construct (_T1 * __p, _Args &&... __args) [inline]
Constructs an object in existing memory by invoking an allocated object's constructor with an initializer.
Definition at line 76 of file stl_construct.h.
template<typename _Tp > void std::_Destroy (_Tp * __pointer) [inline]
Destroy the object pointed to by a pointer type.
Definition at line 94 of file stl_construct.h.
Referenced by std::deque< _Tp, _Alloc >::_M_fill_initialize(), std::deque< _Tp, _Alloc >::_M_range_initialize(), std::vector< _Tp, _Alloc >::operator=(), std::vector< _Tp, _Alloc >::reserve(), and std::vector< sub_match< _Bi_iter >, allocator< sub_match< _Bi_iter > > >::~vector().
template<typename _ForwardIterator > void std::_Destroy (_ForwardIterator __first, _ForwardIterator __last) [inline]
Destroy a range of objects. If the value_type of the object has a trivial destructor, the compiler should optimize all of this away, otherwise the objects' destructors must be invoked.
Definition at line 124 of file stl_construct.h.
template<typename _InputIterator , typename _Tp > _Tp std::accumulate (_InputIterator __first, _InputIterator __last, _Tp __init) [inline]
Accumulate values in a range.
Accumulates the values in the range [first,last) using operator+(). The initial value is init. The values are processed in order.
Parameters:
__first Start of range.
__last End of range.
__init Starting value to add other values to.
Returns:
The final sum.
Definition at line 121 of file stl_numeric.h.
Referenced by __gnu_parallel::__parallel_partial_sum_linear().
template<typename _InputIterator , typename _Tp , typename _BinaryOperation > _Tp std::accumulate (_InputIterator __first, _InputIterator __last, _Tp __init, _BinaryOperation __binary_op) [inline]
Accumulate values in a range with operation.
Accumulates the values in the range [first,last) using the function object __binary_op. The initial value is __init. The values are processed in order.
Parameters:
__first Start of range.
__last End of range.
__init Starting value to add other values to.
__binary_op Function object to accumulate with.
Returns:
The final sum.
Definition at line 147 of file stl_numeric.h.
template<typename _Tp > std::complex< _Tp > std::acos (const std::complex< _Tp > & __z) [inline]
acos(__z) [8.1.2].
Definition at line 1599 of file complex.
template<typename _Tp > std::complex< _Tp > std::acosh (const std::complex< _Tp > & __z) [inline]
acosh(__z) [8.1.5].
Definition at line 1715 of file complex.
template<typename _InputIterator , typename _OutputIterator > _OutputIterator std::adjacent_difference (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
Return differences between adjacent values.
Computes the difference between adjacent values in the range [first,last) using operator-() and writes the result to __result.
Parameters:
__first Start of input range.
__last End of input range.
__result Output sums.
Returns:
Iterator pointing just beyond the values written to result.
_GLIBCXX_RESOLVE_LIB_DEFECTS DR 539. partial_sum and adjacent_difference should mention requirements
Definition at line 318 of file stl_numeric.h.
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation > _OutputIterator std::adjacent_difference (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op)
Return differences between adjacent values.
Computes the difference between adjacent values in the range [__first,__last) using the function object __binary_op and writes the result to __result.
Parameters:
__first Start of input range.
__last End of input range.
__result Output sum.
__binary_op Function object.
Returns:
Iterator pointing just beyond the values written to result.
_GLIBCXX_RESOLVE_LIB_DEFECTS DR 539. partial_sum and adjacent_difference should mention requirements
Definition at line 361 of file stl_numeric.h.
template<typename _InputIterator , typename _Distance > void std::advance (_InputIterator & __i, _Distance __n) [inline]
A generalization of pointer arithmetic.
Parameters:
__i An input iterator.
__n The delta by which to change __i.
Returns:
Nothing.
This increments i by n. For bidirectional and random access iterators, __n may be negative, in which case __i is decremented.
For random access iterators, this uses their + and - operations and are constant time. For other iterator classes they are linear time.
Definition at line 172 of file stl_iterator_base_funcs.h.
References __iterator_category().
Referenced by __inplace_stable_partition(), __merge_adaptive(), __merge_without_buffer(), __rotate_adaptive(), __stable_partition_adaptive(), std::deque< _Tp, _Alloc >::_M_range_initialize(), equal_range(), __gnu_pbds::detail::pat_trie_base::_Node_citer< Node, Leaf, Head, Inode, _CIterator, Iterator, _Alloc >::get_child(), __gnu_pbds::detail::pat_trie_base::_Node_iter< Node, Leaf, Head, Inode, _CIterator, Iterator, _Alloc >::get_child(), is_permutation(), lower_bound(), partition_point(), and upper_bound().
bool std::all () const
Tests whether all the bits are on.
Returns:
True if all the bits are set.
Definition at line 1319 of file bitset.
bool std::any () const
Tests whether any of the bits are on.
Returns:
True if at least one bit is set.
Definition at line 1327 of file bitset.
template<typename _Tp > __gnu_cxx::__promote<_Tp>::__type std::arg (_Tp __x) [inline]
Additional overloads [8.1.9].
Definition at line 1813 of file complex.
References arg().
template<typename _Tp > std::complex< _Tp > std::asin (const std::complex< _Tp > & __z) [inline]
asin(__z) [8.1.3].
Definition at line 1635 of file complex.
template<typename _Tp > std::complex< _Tp > std::asinh (const std::complex< _Tp > & __z) [inline]
asinh(__z) [8.1.6].
Definition at line 1754 of file complex.
template<typename _Tp > std::complex< _Tp > std::atan (const std::complex< _Tp > & __z) [inline]
atan(__z) [8.1.4].
Definition at line 1679 of file complex.
template<typename _Tp > std::complex< _Tp > std::atanh (const std::complex< _Tp > & __z) [inline]
atanh(__z) [8.1.7].
Definition at line 1798 of file complex.
template<class _Container > auto std::begin (_Container & __cont) [inline]
Return an iterator pointing to the first element of the container.
Parameters:
__cont Container.
Definition at line 48 of file range_access.h.
template<class _Container > auto std::begin (const _Container & __cont) [inline]
Return an iterator pointing to the first element of the const container.
Parameters:
__cont Container.
Definition at line 58 of file range_access.h.
template<class _Tp , size_t _Nm> _Tp* std::begin (_Tp(&) __arr[_Nm]) [inline]
Return an iterator pointing to the first element of the array.
Parameters:
__arr Array.
Definition at line 87 of file range_access.h.
template<class _Tp > constexpr const _Tp* std::begin (initializer_list< _Tp > __ils)
Return an iterator pointing to the first element of the initilizer_list.
Parameters:
__ils Initializer list.
Definition at line 89 of file initializer_list.
Referenced by std::vector< _Tp, _Alloc >::emplace(), std::deque< _Tp, _Alloc >::erase(), __gnu_pbds::detail::pat_trie_base::_Node_iter< Node, Leaf, Head, Inode, _CIterator, Iterator, _Alloc >::get_child(), std::vector< _Tp, _Alloc >::insert(), std::list< _Tp, _Alloc >::merge(), std::vector< _Tp, _Alloc >::operator=(), std::forward_list< _Tp, _Alloc >::operator=(), std::list< _Tp, _Alloc >::operator=(), std::list< _Tp, _Alloc >::remove(), std::list< _Tp, _Alloc >::remove_if(), std::list< _Tp, _Alloc >::resize(), std::list< _Tp, _Alloc >::sort(), std::forward_list< _Tp, _Alloc >::unique(), and std::list< _Tp, _Alloc >::unique().
ios_base& std::boolalpha (ios_base & __base) [inline]
Calls base.setf(ios_base::boolalpha).
Definition at line 797 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::boolalpha.
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp> __shared_ptr<_Tp, _Lp> std::const_pointer_cast (const __shared_ptr< _Tp1, _Lp > & __r) [inline]
const_pointer_cast
Definition at line 1207 of file shared_ptr_base.h.
size_t std::count () const
Returns the number of bits which are set.
Definition at line 1279 of file bitset.
Referenced by is_permutation().
template<typename _Tp > reference_wrapper<const _Tp> std::cref (const _Tp & __t) [inline]
Denotes a const reference should be taken to a variable.
Definition at line 482 of file functional.
Referenced by cref().
template<typename _Tp > void std::cref (const _Tp &&)
Denotes a reference should be taken to a variable.
template<typename _Tp > reference_wrapper<const _Tp> std::cref (reference_wrapper< _Tp > __t) [inline]
Partial specialization.
Definition at line 500 of file functional.
References cref().
ios_base& std::dec (ios_base & __base) [inline]
Calls base.setf(ios_base::dec, ios_base::basefield).
Definition at line 935 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::basefield, std::ios_base::dec, and std::ios_base::setf().
Referenced by operator>>().
template<typename _InputIterator > iterator_traits<_InputIterator>::difference_type std::distance (_InputIterator __first, _InputIterator __last) [inline]
A generalization of pointer arithmetic.
Parameters:
__first An input iterator.
__last An input iterator.
Returns:
The distance between them.
Returns n such that __first + n == __last. This requires that __last must be reachable from __first. Note that n may be negative.
For random access iterators, this uses their + and - operations and are constant time. For other iterator classes they are linear time.
Definition at line 114 of file stl_iterator_base_funcs.h.
References __iterator_category().
Referenced by __inplace_stable_partition(), __merge_adaptive(), __merge_without_buffer(), __rotate_adaptive(), __stable_partition_adaptive(), std::deque< _Tp, _Alloc >::_M_range_initialize(), equal_range(), inplace_merge(), is_heap_until(), is_permutation(), std::sub_match< _Bi_iter >::length(), lower_bound(), __gnu_parallel::multiseq_partition(), __gnu_parallel::multiseq_selection(), __gnu_pbds::detail::pat_trie_base::_Node_citer< Node, Leaf, Head, Inode, _CIterator, Iterator, _Alloc >::num_children(), partition_point(), std::match_results< _FwdIterT, _Alloc >::position(), std::list< __inp, __rebind_inp >::size(), and upper_bound().
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp> __shared_ptr<_Tp, _Lp> std::dynamic_pointer_cast (const __shared_ptr< _Tp1, _Lp > & __r) [inline]
dynamic_pointer_cast
Definition at line 1217 of file shared_ptr_base.h.
template<class _Container > auto std::end (_Container & __cont) [inline]
Return an iterator pointing to one past the last element of the container.
Parameters:
__cont Container.
Definition at line 68 of file range_access.h.
template<class _Container > auto std::end (const _Container & __cont) [inline]
Return an iterator pointing to one past the last element of the const container.
Parameters:
__cont Container.
Definition at line 78 of file range_access.h.
template<class _Tp , size_t _Nm> _Tp* std::end (_Tp(&) __arr[_Nm]) [inline]
Return an iterator pointing to one past the last element of the array.
Parameters:
__arr Array.
Definition at line 97 of file range_access.h.
template<class _Tp > constexpr const _Tp* std::end (initializer_list< _Tp > __ils)
Return an iterator pointing to one past the last element of the initilizer_list.
Parameters:
__ils Initializer list.
Definition at line 99 of file initializer_list.
Referenced by std::vector< _Tp, _Alloc >::emplace(), std::vector< _Tp, _Alloc >::erase(), std::deque< _Tp, _Alloc >::erase(), std::vector< _Tp, _Alloc >::insert(), std::list< _Tp, _Alloc >::merge(), std::vector< _Tp, _Alloc >::operator=(), std::forward_list< _Tp, _Alloc >::operator=(), std::list< _Tp, _Alloc >::operator=(), std::list< _Tp, _Alloc >::remove(), std::list< _Tp, _Alloc >::remove_if(), std::list< _Tp, _Alloc >::resize(), std::forward_list< _Tp, _Alloc >::resize(), std::forward_list< _Tp, _Alloc >::unique(), and std::list< _Tp, _Alloc >::unique().
template<typename _CharT , typename _Traits > basic_ostream<_CharT, _Traits>& std::endl (basic_ostream< _CharT, _Traits > & __os) [inline]
Write a newline and flush the stream.
This manipulator is often mistakenly used when a simple newline is desired, leading to poor buffering performance. See http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt11ch25s02.html for more on this subject.
Definition at line 562 of file ostream.
References flush(), std::basic_ostream< _CharT, _Traits >::put(), and std::basic_ios< _CharT, _Traits >::widen().
template<typename _CharT , typename _Traits > basic_ostream<_CharT, _Traits>& std::ends (basic_ostream< _CharT, _Traits > & __os) [inline]
Write a null character into the output sequence.
Null character is CharT() by definition. For CharT of char, this correctly writes the ASCII NUL character string terminator.
Definition at line 574 of file ostream.
References std::basic_ostream< _CharT, _Traits >::put().
template<typename _Tp > _Tp std::fabs (const std::complex< _Tp > & __z) [inline]
fabs(__z) [8.1.8].
Definition at line 1807 of file complex.
References abs().
ios_base& std::fixed (ios_base & __base) [inline]
Calls base.setf(ios_base::fixed, ios_base::floatfield).
Definition at line 960 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::fixed, std::ios_base::floatfield, and std::ios_base::setf().
bitset<_Nb>& std::flip ()
Toggles every bit to its opposite value.
Definition at line 1106 of file bitset.
bitset<_Nb>& std::flip (size_t __position)
Toggles a given bit to its opposite value.
Parameters:
__position The index of the bit.
Exceptions:
std::out_of_range If pos is bigger the size of the set.
Definition at line 1119 of file bitset.
References _Unchecked_flip().
template<typename _CharT , typename _Traits > basic_ostream<_CharT, _Traits>& std::flush (basic_ostream< _CharT, _Traits > & __os) [inline]
Flushes the output stream.
This manipulator simply calls the stream's flush() member function.
Definition at line 584 of file ostream.
References std::basic_ostream< _CharT, _Traits >::flush().
Referenced by endl().
template<typename _MoneyT > _Get_money<_MoneyT> std::get_money (_MoneyT & __mon, bool __intl = false) [inline]
Extended manipulator for extracting money.
Parameters:
__mon Either long double or a specialization of basic_string.
__intl A bool indicating whether international format is to be used.
Sent to a stream object, this manipulator extracts __mon.
Definition at line 258 of file iomanip.
template<typename _Tp > pair<_Tp*, ptrdiff_t> std::get_temporary_buffer (ptrdiff_t __len)
Allocates a temporary buffer.
Parameters:
__len The number of objects of type Tp.
Returns:
See full description.
Reinventing the wheel, but this time with prettier spokes!
This function tries to obtain storage for __len adjacent Tp objects. The objects themselves are not constructed, of course. A pair<> is returned containing the buffer s address and capacity (in the units of sizeof(_Tp)), or a pair of 0 values if no storage can be obtained. Note that the capacity obtained may be less than that requested if the memory is unavailable; you should compare len with the .second return value.
Provides the nothrow exception guarantee.
Definition at line 87 of file stl_tempbuf.h.
Referenced by std::_Temporary_buffer< _ForwardIterator, _Tp >::_Temporary_buffer().
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_istream< _CharT, _Traits > & std::getline (basic_istream< _CharT, _Traits > & __is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > & __str, _CharT __delim)
Read a line from stream into a string.
Parameters:
__is Input stream.
__str Buffer to store into.
__delim Character marking end of line.
Returns:
Reference to the input stream.
Stores characters from __is into __str until __delim is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased. If delim was encountered, it is extracted but not stored into __str.
Definition at line 627 of file vstring.tcc.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::append(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::erase(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::max_size(), std::basic_ios< _CharT, _Traits >::rdbuf(), and std::basic_ios< _CharT, _Traits >::setstate().
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_istream<_CharT, _Traits>& std::getline (basic_istream< _CharT, _Traits > & __is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > & __str) [inline]
Read a line from stream into a string.
Parameters:
__is Input stream.
__str Buffer to store into.
Returns:
Reference to the input stream.
Stores characters from is into __str until '
' is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased. If end of line was encountered, it is extracted but not stored into __str.
Definition at line 2533 of file vstring.h.
References getline(), and std::basic_ios< _CharT, _Traits >::widen().
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream< _CharT, _Traits > & std::getline (basic_istream< _CharT, _Traits > & __is, basic_string< _CharT, _Traits, _Alloc > & __str, _CharT __delim)
Read a line from stream into a string.
Parameters:
__is Input stream.
__str Buffer to store into.
__delim Character marking end of line.
Returns:
Reference to the input stream.
Stores characters from __is into __str until __delim is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased. If __delim was encountered, it is extracted but not stored into __str.
Definition at line 1070 of file basic_string.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::erase(), std::basic_string< _CharT, _Traits, _Alloc >::max_size(), std::basic_ios< _CharT, _Traits >::rdbuf(), and std::basic_ios< _CharT, _Traits >::setstate().
Referenced by getline().
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream<_CharT, _Traits>& std::getline (basic_istream< _CharT, _Traits > & __is, basic_string< _CharT, _Traits, _Alloc > & __str) [inline]
Read a line from stream into a string.
Parameters:
__is Input stream.
__str Buffer to store into.
Returns:
Reference to the input stream.
Stores characters from is into __str until '
' is found, the end of the stream is encountered, or str.max_size() is reached. If __is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased. If end of line was encountered, it is extracted but not stored into __str.
Definition at line 2792 of file basic_string.h.
References getline(), and std::basic_ios< _CharT, _Traits >::widen().
template<typename _Facet > bool std::has_facet (const locale & __loc) throw ()
Test for the presence of a facet.
has_facet tests the locale argument for the presence of the facet type provided as the template parameter. Facets derived from the facet parameter will also return true.
Template Parameters:
_Facet The facet type to test the presence of.
Parameters:
__loc The locale to test.
Returns:
true if __loc contains a facet of type _Facet, else false.
Definition at line 103 of file locale_classes.tcc.
ios_base& std::hex (ios_base & __base) [inline]
Calls base.setf(ios_base::hex, ios_base::basefield).
Definition at line 943 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::basefield, std::ios_base::hex, and std::ios_base::setf().
Referenced by std::regex_traits< _Ch_type >::value().
template<typename _InputIterator1 , typename _InputIterator2 , typename _Tp > _Tp std::inner_product (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _Tp __init) [inline]
Compute inner product of two ranges.
Starting with an initial value of __init, multiplies successive elements from the two ranges and adds each product into the accumulated value using operator+(). The values in the ranges are processed in order.
Parameters:
__first1 Start of range 1.
__last1 End of range 1.
__first2 Start of range 2.
__init Starting value to add other values to.
Returns:
The final inner product.
Definition at line 175 of file stl_numeric.h.
template<typename _InputIterator1 , typename _InputIterator2 , typename _Tp , typename _BinaryOperation1 , typename _BinaryOperation2 > _Tp std::inner_product (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _Tp __init, _BinaryOperation1 __binary_op1, _BinaryOperation2 __binary_op2) [inline]
Compute inner product of two ranges.
Starting with an initial value of __init, applies __binary_op2 to successive elements from the two ranges and accumulates each result into the accumulated value using __binary_op1. The values in the ranges are processed in order.
Parameters:
__first1 Start of range 1.
__last1 End of range 1.
__first2 Start of range 2.
__init Starting value to add other values to.
__binary_op1 Function object to accumulate with.
__binary_op2 Function object to apply to pairs of input values.
Returns:
The final inner product.
Definition at line 207 of file stl_numeric.h.
ios_base& std::internal (ios_base & __base) [inline]
Calls base.setf(ios_base::internal, ios_base::adjustfield).
Definition at line 910 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::adjustfield, and std::ios_base::internal.
template<typename _ForwardIterator , typename _Tp > void std::iota (_ForwardIterator __first, _ForwardIterator __last, _Tp __value)
Create a range of sequentially increasing values.
For each element in the range [first,last) assigns value and increments value as if by ++value.
Parameters:
__first Start of range.
__last End of range.
__value Starting value.
Returns:
Nothing.
Definition at line 83 of file stl_numeric.h.
template<typename _CharT > bool std::isalnum (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.is(ctype_base::alnum, __c).
Definition at line 2583 of file locale_facets.h.
template<typename _CharT > bool std::isalpha (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.is(ctype_base::alpha, __c).
Definition at line 2559 of file locale_facets.h.
template<typename _CharT > bool std::iscntrl (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.is(ctype_base::cntrl, __c).
Definition at line 2541 of file locale_facets.h.
template<typename _CharT > bool std::isdigit (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.is(ctype_base::digit, __c).
Definition at line 2565 of file locale_facets.h.
template<typename _CharT > bool std::isgraph (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.is(ctype_base::graph, __c).
Definition at line 2589 of file locale_facets.h.
template<typename _CharT > bool std::islower (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.is(ctype_base::lower, __c).
Definition at line 2553 of file locale_facets.h.
template<typename _CharT > bool std::isprint (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.is(ctype_base::print, __c).
Definition at line 2535 of file locale_facets.h.
template<typename _CharT > bool std::ispunct (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.is(ctype_base::punct, __c).
Definition at line 2571 of file locale_facets.h.
template<typename _CharT > bool std::isspace (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.is(ctype_base::space, __c).
Definition at line 2529 of file locale_facets.h.
template<typename _CharT > bool std::isupper (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.is(ctype_base::upper, __c).
Definition at line 2547 of file locale_facets.h.
template<typename _CharT > bool std::isxdigit (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.is(ctype_base::xdigit, __c).
Definition at line 2577 of file locale_facets.h.
ios_base& std::left (ios_base & __base) [inline]
Calls base.setf(ios_base::left, ios_base::adjustfield).
Definition at line 918 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::adjustfield, std::ios_base::left, and std::ios_base::setf().
Referenced by operator<<().
template<class _T1 , class _T2 > constexpr pair<typename __decay_and_strip<_T1>::__type, typename __decay_and_strip<_T2>::__type> std::make_pair (_T1 && __x, _T2 && __y)
A convenience wrapper for creating a pair from two objects.
Parameters:
__x The first object.
__y The second object.
Returns:
A newly-constructed pair<> object of the appropriate type.
The standard requires that the objects be passed by reference-to-const, but LWG issue #181 says they should be passed by const value. We follow the LWG by default.
Definition at line 268 of file stl_pair.h.
Referenced by __gnu_parallel::__find_template(), __gnu_debug::__get_distance(), __gnu_parallel::__parallel_merge_advance(), __gnu_parallel::__parallel_sort_qsb(), __gnu_parallel::__qsb_local_sort_with_helping(), __gnu_parallel::__find_if_selector::_M_sequential_algorithm(), __gnu_parallel::__adjacent_find_selector::_M_sequential_algorithm(), __gnu_parallel::__find_first_of_selector< _FIterator >::_M_sequential_algorithm(), minmax_element(), __gnu_parallel::multiseq_partition(), __gnu_parallel::multiseq_selection(), __gnu_parallel::parallel_multiway_merge(), __gnu_parallel::parallel_sort_mwms_pu(), and __gnu_pbds::detail::pat_trie_base::_Node_citer< Node, Leaf, Head, Inode, _CIterator, Iterator, _Alloc >::valid_prefix().
ios_base& std::noboolalpha (ios_base & __base) [inline]
Calls base.unsetf(ios_base::boolalpha).
Definition at line 805 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::boolalpha, and std::ios_base::unsetf().
bool std::none () const
Tests whether any of the bits are on.
Returns:
True if none of the bits are set.
Definition at line 1335 of file bitset.
ios_base& std::noshowbase (ios_base & __base) [inline]
Calls base.unsetf(ios_base::showbase).
Definition at line 821 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::showbase, and std::ios_base::unsetf().
ios_base& std::noshowpoint (ios_base & __base) [inline]
Calls base.unsetf(ios_base::showpoint).
Definition at line 837 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::showpoint, and std::ios_base::unsetf().
ios_base& std::noshowpos (ios_base & __base) [inline]
Calls base.unsetf(ios_base::showpos).
Definition at line 853 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::showpos, and std::ios_base::unsetf().
ios_base& std::noskipws (ios_base & __base) [inline]
Calls base.unsetf(ios_base::skipws).
Definition at line 869 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::skipws, and std::ios_base::unsetf().
ios_base& std::nounitbuf (ios_base & __base) [inline]
Calls base.unsetf(ios_base::unitbuf).
Definition at line 901 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::unitbuf, and std::ios_base::unsetf().
ios_base& std::nouppercase (ios_base & __base) [inline]
Calls base.unsetf(ios_base::uppercase).
Definition at line 885 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::unsetf(), and std::ios_base::uppercase.
ios_base& std::oct (ios_base & __base) [inline]
Calls base.setf(ios_base::oct, ios_base::basefield).
Definition at line 951 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::basefield, std::ios_base::oct, and std::ios_base::setf().
Referenced by std::regex_traits< _Ch_type >::value().
template<class _T1 , class _T2 > constexpr bool std::operator!= (const pair< _T1, _T2 > & __x, const pair< _T1, _T2 > & __y) [inline]
Uses operator== to find the result.
Definition at line 219 of file stl_pair.h.
template<typename _Tp > bool std::operator!= (const _Fwd_list_iterator< _Tp > & __x, const _Fwd_list_const_iterator< _Tp > & __y) [inline]
Forward list iterator inequality comparison.
Definition at line 258 of file forward_list.h.
template<typename _Tp , typename _Seq > bool std::operator!= (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) [inline]
Based on operator==.
Definition at line 266 of file stl_stack.h.
template<typename _Tp , typename _Seq > bool std::operator!= (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) [inline]
Based on operator==.
Definition at line 291 of file stl_queue.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator!= (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) [inline]
Returns !(x == y).
Definition at line 709 of file stl_multiset.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator!= (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) [inline]
Returns !(x == y).
Definition at line 728 of file stl_set.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator!= (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
Based on operator==.
Definition at line 829 of file stl_multimap.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator!= (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
Based on operator==.
Definition at line 913 of file stl_map.h.
template<typename _Tp , typename _Alloc > bool std::operator!= (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) [inline]
Based on operator==.
Definition at line 1285 of file forward_list.h.
bool std::operator!= (const bitset< _Nb > & __rhs) const
These comparisons for equality/inequality are, well, bitwise.
Definition at line 1294 of file bitset.
template<typename _Tp , typename _Alloc > bool std::operator!= (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) [inline]
Based on operator==.
Definition at line 1394 of file stl_vector.h.
template<typename _Tp , typename _Alloc > bool std::operator!= (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) [inline]
Based on operator==.
Definition at line 1610 of file stl_list.h.
template<typename _Tp , typename _Alloc > bool std::operator!= (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) [inline]
Based on operator==.
Definition at line 1955 of file stl_deque.h.
template<typename _Res , typename... _Args> bool std::operator!= (const function< _Res(_Args...)> & __f, nullptr_t) [inline]
Compares a polymorphic function object wrapper against 0 (the NULL pointer).
Returns:
false if the wrapper has no target, true otherwise
This function will not throw an exception.
Definition at line 2394 of file functional.
template<typename _Res , typename... _Args> bool std::operator!= (nullptr_t , const function< _Res(_Args...)> & __f) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2400 of file functional.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator!= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Test difference of two strings.
Parameters:
__lhs First string.
__rhs Second string.
Returns:
True if __lhs.compare(__rhs) != 0. False otherwise.
Definition at line 2529 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator!= (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Test difference of C string and string.
Parameters:
__lhs C string.
__rhs String.
Returns:
True if __rhs.compare(__lhs) != 0. False otherwise.
Definition at line 2541 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator!= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) [inline]
Test difference of string and C string.
Parameters:
__lhs String.
__rhs C string.
Returns:
True if __lhs.compare(__rhs) != 0. False otherwise.
Definition at line 2553 of file basic_string.h.
template<size_t _Nb> bitset<_Nb> std::operator& (const bitset< _Nb > & __x, const bitset< _Nb > & __y) [inline]
Global bitwise operations on bitsets.
Parameters:
__x A bitset.
__y A bitset of the same size as __x.
Returns:
A new bitset.
These should be self-explanatory.
Definition at line 1418 of file bitset.
template<typename _CharT , typename _Traits , typename _Alloc > basic_string<_CharT, _Traits, _Alloc> std::operator+ (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs)
Concatenate two strings.
Parameters:
__lhs First string.
__rhs Last string.
Returns:
New string with value of __lhs followed by __rhs.
Definition at line 2362 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::append().
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > std::operator+ (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs)
Concatenate C string and string.
Parameters:
__lhs First string.
__rhs Last string.
Returns:
New string with value of __lhs followed by __rhs.
Definition at line 694 of file basic_string.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::size().
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > std::operator+ (_CharT __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs)
Concatenate character and string.
Parameters:
__lhs First string.
__rhs Last string.
Returns:
New string with __lhs followed by __rhs.
Definition at line 710 of file basic_string.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::size().
template<typename _CharT , typename _Traits , typename _Alloc > basic_string<_CharT, _Traits, _Alloc> std::operator+ (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) [inline]
Concatenate string and C string.
Parameters:
__lhs First string.
__rhs Last string.
Returns:
New string with __lhs followed by __rhs.
Definition at line 2399 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::append().
template<typename _CharT , typename _Traits , typename _Alloc > basic_string<_CharT, _Traits, _Alloc> std::operator+ (const basic_string< _CharT, _Traits, _Alloc > & __lhs, _CharT __rhs) [inline]
Concatenate string and character.
Parameters:
__lhs First string.
__rhs Last string.
Returns:
New string with __lhs followed by __rhs.
Definition at line 2415 of file basic_string.h.
template<class _T1 , class _T2 > constexpr bool std::operator< (const pair< _T1, _T2 > & __x, const pair< _T1, _T2 > & __y) [inline]
<http://gcc.gnu.org/onlinedocs/libstdc++/manual/utilities.html>
Definition at line 212 of file stl_pair.h.
References std::pair< _T1, _T2 >::first.
template<typename _Tp , typename _Seq > bool std::operator< (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) [inline]
Stack ordering relation.
Parameters:
__x A stack.
__y A stack of the same type as x.
Returns:
True iff x is lexicographically less than __y.
This is an total ordering relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, the elements must be comparable with <, and std::lexicographical_compare() is usually used to make the determination.
Definition at line 260 of file stl_stack.h.
template<typename _Tp , typename _Seq > bool std::operator< (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) [inline]
Queue ordering relation.
Parameters:
__x A queue.
__y A queue of the same type as x.
Returns:
True iff __x is lexicographically less than __y.
This is an total ordering relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, the elements must be comparable with <, and std::lexicographical_compare() is usually used to make the determination.
Definition at line 285 of file stl_queue.h.
References std::queue< _Tp, _Sequence >::c.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator< (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) [inline]
Multiset ordering relation.
Parameters:
__x A multiset.
__y A multiset of the same type as __x.
Returns:
True iff __x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the maps. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 702 of file stl_multiset.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator< (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) [inline]
Set ordering relation.
Parameters:
__x A set.
__y A set of the same type as x.
Returns:
True iff __x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the maps. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 721 of file stl_set.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator< (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
Multimap ordering relation.
Parameters:
__x A multimap.
__y A multimap of the same type as __x.
Returns:
True iff x is lexicographically less than y.
This is a total ordering relation. It is linear in the size of the multimaps. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 822 of file stl_multimap.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator< (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
Map ordering relation.
Parameters:
__x A map.
__y A map of the same type as x.
Returns:
True iff x is lexicographically less than y.
This is a total ordering relation. It is linear in the size of the maps. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 906 of file stl_map.h.
template<typename _Tp , typename _Alloc > bool std::operator< (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) [inline]
Forward list ordering relation.
Parameters:
__lx A forward_list.
__ly A forward_list of the same type as __lx.
Returns:
True iff __lx is lexicographically less than __ly.
This is a total ordering relation. It is linear in the number of elements of the forward lists. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1277 of file forward_list.h.
References lexicographical_compare().
template<typename _Tp , typename _Alloc > bool std::operator< (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) [inline]
Vector ordering relation.
Parameters:
__x A vector.
__y A vector of the same type as __x.
Returns:
True iff __x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the vectors. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1387 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::begin(), std::vector< _Tp, _Alloc >::end(), and lexicographical_compare().
template<typename _Tp , typename _Alloc > bool std::operator< (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) [inline]
List ordering relation.
Parameters:
__x A list.
__y A list of the same type as __x.
Returns:
True iff __x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the lists. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1603 of file stl_list.h.
References lexicographical_compare().
template<typename _Tp , typename _Alloc > bool std::operator< (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) [inline]
Deque ordering relation.
Parameters:
__x A deque.
__y A deque of the same type as __x.
Returns:
True iff x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the deques. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1947 of file stl_deque.h.
References lexicographical_compare().
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator< (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Test if string precedes string.
Parameters:
__lhs First string.
__rhs Second string.
Returns:
True if __lhs precedes __rhs. False otherwise.
Definition at line 2566 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator< (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) [inline]
Test if string precedes C string.
Parameters:
__lhs String.
__rhs C string.
Returns:
True if __lhs precedes __rhs. False otherwise.
Definition at line 2578 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator< (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Test if C string precedes string.
Parameters:
__lhs C string.
__rhs String.
Returns:
True if __lhs precedes __rhs. False otherwise.
Definition at line 2590 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<typename _CharT , typename _Traits > basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __out, _CharT __c) [inline]
Character inserters.
Parameters:
__out An output stream.
__c A character.
Returns:
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
Definition at line 469 of file ostream.
template<typename _CharT , typename _Traits > basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __out, char __c) [inline]
Character inserters.
Parameters:
__out An output stream.
__c A character.
Returns:
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
Definition at line 474 of file ostream.
template<class _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & __out, char __c) [inline]
Character inserters.
Parameters:
__out An output stream.
__c A character.
Returns:
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
Definition at line 480 of file ostream.
template<class _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & __out, signed char __c) [inline]
Character inserters.
Parameters:
__out An output stream.
__c A character.
Returns:
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
Definition at line 486 of file ostream.
template<class _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & __out, unsigned char __c) [inline]
Character inserters.
Parameters:
__out An output stream.
__c A character.
Returns:
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
Definition at line 491 of file ostream.
template<typename _CharT , typename _Traits > basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __out, const _CharT * __s) [inline]
String inserters.
Parameters:
__out An output stream.
__s A character string.
Returns:
out
Precondition:
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
Definition at line 511 of file ostream.
References std::ios_base::badbit.
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & std::operator<< (basic_ostream< _CharT, _Traits > & __out, const char * __s)
String inserters.
Parameters:
__out An output stream.
__s A character string.
Returns:
out
Precondition:
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
Definition at line 323 of file ostream.tcc.
References std::ios_base::badbit, and std::basic_ios< _CharT, _Traits >::setstate().
template<class _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & __out, const char * __s) [inline]
String inserters.
Parameters:
__out An output stream.
__s A character string.
Returns:
out
Precondition:
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
Definition at line 528 of file ostream.
References std::ios_base::badbit.
template<class _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & __out, const signed char * __s) [inline]
String inserters.
Parameters:
__out An output stream.
__s A character string.
Returns:
out
Precondition:
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
Definition at line 541 of file ostream.
template<class _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & __out, const unsigned char * __s) [inline]
String inserters.
Parameters:
__out An output stream.
__s A character string.
Returns:
out
Precondition:
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
Definition at line 546 of file ostream.
template<typename _CharT , typename _Traits , typename _Tp > basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > && __os, const _Tp & __x) [inline]
Generic inserter for rvalue stream.
Parameters:
__os An input stream.
__x A reference to the object being inserted.
Returns:
os
This is just a forwarding function to allow insertion to rvalue streams since they won't bind to the inserter functions that take an lvalue reference.
Definition at line 600 of file ostream.
bitset<_Nb> std::operator<< (size_t __position) const
Self-explanatory.
Definition at line 1341 of file bitset.
template<class _CharT , class _Traits , size_t _Nb> std::basic_ostream<_CharT, _Traits>& std::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const bitset< _Nb > & __x)
Global I/O operators for bitsets.
Direct I/O between streams and bitsets is supported. Output is straightforward. Input will skip whitespace, only accept 0 and 1 characters, and will only extract as many digits as the bitset will hold.
Definition at line 1523 of file bitset.
References std::__ctype_abstract_base< _CharT >::widen().
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __os, const __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > & __str) [inline]
Write string to a stream.
Parameters:
__os Output stream.
__str String to write out.
Returns:
Reference to the output stream.
Output characters of __str into os following the same rules as for writing a C string.
Definition at line 2487 of file vstring.h.
template<typename _CharT , typename _Traits , typename _Alloc > basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __os, const basic_string< _CharT, _Traits, _Alloc > & __str) [inline]
Write string to a stream.
Parameters:
__os Output stream.
__str String to write out.
Returns:
Reference to the output stream.
Output characters of __str into os following the same rules as for writing a C string.
Definition at line 2750 of file basic_string.h.
bitset<_Nb>& std::operator<<= (size_t __position)
Operations on bitsets.
Parameters:
__position The number of places to shift.
These should be self-explanatory.
Definition at line 982 of file bitset.
template<class _T1 , class _T2 > constexpr bool std::operator<= (const pair< _T1, _T2 > & __x, const pair< _T1, _T2 > & __y) [inline]
Uses operator< to find the result.
Definition at line 231 of file stl_pair.h.
template<typename _Tp , typename _Seq > bool std::operator<= (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) [inline]
Based on operator<.
Definition at line 278 of file stl_stack.h.
template<typename _Tp , typename _Seq > bool std::operator<= (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) [inline]
Based on operator<.
Definition at line 303 of file stl_queue.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator<= (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) [inline]
Returns !(y < x)
Definition at line 723 of file stl_multiset.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator<= (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) [inline]
Returns !(y < x)
Definition at line 742 of file stl_set.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator<= (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 843 of file stl_multimap.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator<= (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 927 of file stl_map.h.
template<typename _Tp , typename _Alloc > bool std::operator<= (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) [inline]
Based on operator<.
Definition at line 1306 of file forward_list.h.
template<typename _Tp , typename _Alloc > bool std::operator<= (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 1406 of file stl_vector.h.
template<typename _Tp , typename _Alloc > bool std::operator<= (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 1622 of file stl_list.h.
template<typename _Tp , typename _Alloc > bool std::operator<= (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 1969 of file stl_deque.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator<= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Test if string doesn't follow string.
Parameters:
__lhs First string.
__rhs Second string.
Returns:
True if __lhs doesn't follow __rhs. False otherwise.
Definition at line 2640 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator<= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) [inline]
Test if string doesn't follow C string.
Parameters:
__lhs String.
__rhs C string.
Returns:
True if __lhs doesn't follow __rhs. False otherwise.
Definition at line 2652 of file basic_string.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator<= (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Test if C string doesn't follow string.
Parameters:
__lhs C string.
__rhs String.
Returns:
True if __lhs doesn't follow __rhs. False otherwise.
Definition at line 2664 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<class _T1 , class _T2 > constexpr bool std::operator== (const pair< _T1, _T2 > & __x, const pair< _T1, _T2 > & __y) [inline]
Two pairs of the same type are equal iff their members are equal.
Definition at line 206 of file stl_pair.h.
References std::pair< _T1, _T2 >::first, and std::pair< _T1, _T2 >::second.
template<typename _StateT > bool std::operator== (const fpos< _StateT > & __lhs, const fpos< _StateT > & __rhs) [inline]
Test if equivalent to another position.
Definition at line 218 of file postypes.h.
template<typename _Tp , typename _Seq > bool std::operator== (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) [inline]
Stack equality comparison.
Parameters:
__x A stack.
__y A stack of the same type as __x.
Returns:
True iff the size and elements of the stacks are equal.
This is an equivalence relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, and stacks are considered equivalent if their sequences compare equal.
Definition at line 242 of file stl_stack.h.
template<typename _Tp > bool std::operator== (const _Fwd_list_iterator< _Tp > & __x, const _Fwd_list_const_iterator< _Tp > & __y) [inline]
Forward list iterator equality comparison.
Definition at line 249 of file forward_list.h.
template<typename _Tp , typename _Seq > bool std::operator== (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) [inline]
Queue equality comparison.
Parameters:
__x A queue.
__y A queue of the same type as __x.
Returns:
True iff the size and elements of the queues are equal.
This is an equivalence relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, and queues are considered equivalent if their sequences compare equal.
Definition at line 267 of file stl_queue.h.
References std::queue< _Tp, _Sequence >::c.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator== (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) [inline]
Multiset equality comparison.
Parameters:
__x A multiset.
__y A multiset of the same type as __x.
Returns:
True iff the size and elements of the multisets are equal.
This is an equivalence relation. It is linear in the size of the multisets. Multisets are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 685 of file stl_multiset.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator== (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) [inline]
Set equality comparison.
Parameters:
__x A set.
__y A set of the same type as x.
Returns:
True iff the size and elements of the sets are equal.
This is an equivalence relation. It is linear in the size of the sets. Sets are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 704 of file stl_set.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator== (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
Multimap equality comparison.
Parameters:
__x A multimap.
__y A multimap of the same type as __x.
Returns:
True iff the size and elements of the maps are equal.
This is an equivalence relation. It is linear in the size of the multimaps. Multimaps are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 805 of file stl_multimap.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator== (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
Map equality comparison.
Parameters:
__x A map.
__y A map of the same type as x.
Returns:
True iff the size and elements of the maps are equal.
This is an equivalence relation. It is linear in the size of the maps. Maps are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 889 of file stl_map.h.
template<typename _Tp , typename _Alloc > bool std::operator== (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly)
Forward list equality comparison.
Parameters:
__lx A forward_list
__ly A forward_list of the same type as __lx.
Returns:
True iff the elements of the forward lists are equal.
This is an equivalence relation. It is linear in the number of elements of the forward lists. Deques are considered equivalent if corresponding elements compare equal.
Definition at line 380 of file forward_list.tcc.
References std::forward_list< _Tp, _Alloc >::cbegin(), and std::forward_list< _Tp, _Alloc >::cend().
bool std::operator== (const bitset< _Nb > & __rhs) const
These comparisons for equality/inequality are, well, bitwise.
Definition at line 1290 of file bitset.
template<typename _Tp , typename _Alloc > bool std::operator== (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) [inline]
Vector equality comparison.
Parameters:
__x A vector.
__y A vector of the same type as __x.
Returns:
True iff the size and elements of the vectors are equal.
This is an equivalence relation. It is linear in the size of the vectors. Vectors are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 1370 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::begin(), std::vector< _Tp, _Alloc >::end(), equal(), and std::vector< _Tp, _Alloc >::size().
template<typename _Tp , typename _Alloc > bool std::operator== (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) [inline]
List equality comparison.
Parameters:
__x A list.
__y A list of the same type as __x.
Returns:
True iff the size and elements of the lists are equal.
This is an equivalence relation. It is linear in the size of the lists. Lists are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 1574 of file stl_list.h.
References std::list< _Tp, _Alloc >::begin(), and std::list< _Tp, _Alloc >::end().
template<typename _Tp , typename _Alloc > bool std::operator== (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) [inline]
Deque equality comparison.
Parameters:
__x A deque.
__y A deque of the same type as __x.
Returns:
True iff the size and elements of the deques are equal.
This is an equivalence relation. It is linear in the size of the deques. Deques are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 1929 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::begin(), std::deque< _Tp, _Alloc >::end(), equal(), and std::deque< _Tp, _Alloc >::size().
template<typename _Res , typename... _Args> bool std::operator== (const function< _Res(_Args...)> & __f, nullptr_t) [inline]
Compares a polymorphic function object wrapper against 0 (the NULL pointer).
Returns:
true if the wrapper has no target, false otherwise
This function will not throw an exception.
Definition at line 2376 of file functional.
template<typename _Res , typename... _Args> bool std::operator== (nullptr_t , const function< _Res(_Args...)> & __f) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2382 of file functional.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator== (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Test equivalence of two strings.
Parameters:
__lhs First string.
__rhs Second string.
Returns:
True if __lhs.compare(__rhs) == 0. False otherwise.
Definition at line 2483 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator== (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Test equivalence of C string and string.
Parameters:
__lhs C string.
__rhs String.
Returns:
True if __rhs.compare(__lhs) == 0. False otherwise.
Definition at line 2504 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator== (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) [inline]
Test equivalence of string and C string.
Parameters:
__lhs String.
__rhs C string.
Returns:
True if __lhs.compare(__rhs) == 0. False otherwise.
Definition at line 2516 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<class _T1 , class _T2 > constexpr bool std::operator> (const pair< _T1, _T2 > & __x, const pair< _T1, _T2 > & __y) [inline]
Uses operator< to find the result.
Definition at line 225 of file stl_pair.h.
template<typename _Tp , typename _Seq > bool std::operator> (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) [inline]
Based on operator<.
Definition at line 272 of file stl_stack.h.
template<typename _Tp , typename _Seq > bool std::operator> (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) [inline]
Based on operator<.
Definition at line 297 of file stl_queue.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator> (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) [inline]
Returns y < x.
Definition at line 716 of file stl_multiset.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator> (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) [inline]
Returns y < x.
Definition at line 735 of file stl_set.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator> (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 836 of file stl_multimap.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator> (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 920 of file stl_map.h.
template<typename _Tp , typename _Alloc > bool std::operator> (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) [inline]
Based on operator<.
Definition at line 1292 of file forward_list.h.
template<typename _Tp , typename _Alloc > bool std::operator> (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 1400 of file stl_vector.h.
template<typename _Tp , typename _Alloc > bool std::operator> (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 1616 of file stl_list.h.
template<typename _Tp , typename _Alloc > bool std::operator> (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 1962 of file stl_deque.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator> (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Test if string follows string.
Parameters:
__lhs First string.
__rhs Second string.
Returns:
True if __lhs follows __rhs. False otherwise.
Definition at line 2603 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator> (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) [inline]
Test if string follows C string.
Parameters:
__lhs String.
__rhs C string.
Returns:
True if __lhs follows __rhs. False otherwise.
Definition at line 2615 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator> (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Test if C string follows string.
Parameters:
__lhs C string.
__rhs String.
Returns:
True if __lhs follows __rhs. False otherwise.
Definition at line 2627 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<class _T1 , class _T2 > constexpr bool std::operator>= (const pair< _T1, _T2 > & __x, const pair< _T1, _T2 > & __y) [inline]
Uses operator< to find the result.
Definition at line 237 of file stl_pair.h.
template<typename _Tp , typename _Seq > bool std::operator>= (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) [inline]
Based on operator<.
Definition at line 284 of file stl_stack.h.
template<typename _Tp , typename _Seq > bool std::operator>= (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) [inline]
Based on operator<.
Definition at line 309 of file stl_queue.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator>= (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) [inline]
Returns !(x < y)
Definition at line 730 of file stl_multiset.h.
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator>= (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) [inline]
Returns !(x < y)
Definition at line 749 of file stl_set.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator>= (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 850 of file stl_multimap.h.
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator>= (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 934 of file stl_map.h.
template<typename _Tp , typename _Alloc > bool std::operator>= (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) [inline]
Based on operator<.
Definition at line 1299 of file forward_list.h.
template<typename _Tp , typename _Alloc > bool std::operator>= (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 1412 of file stl_vector.h.
template<typename _Tp , typename _Alloc > bool std::operator>= (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 1628 of file stl_list.h.
template<typename _Tp , typename _Alloc > bool std::operator>= (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) [inline]
Based on operator<.
Definition at line 1976 of file stl_deque.h.
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator>= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Test if string doesn't precede string.
Parameters:
__lhs First string.
__rhs Second string.
Returns:
True if __lhs doesn't precede __rhs. False otherwise.
Definition at line 2677 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator>= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) [inline]
Test if string doesn't precede C string.
Parameters:
__lhs String.
__rhs C string.
Returns:
True if __lhs doesn't precede __rhs. False otherwise.
Definition at line 2689 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator>= (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Test if C string doesn't precede string.
Parameters:
__lhs C string.
__rhs String.
Returns:
True if __lhs doesn't precede __rhs. False otherwise.
Definition at line 2701 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & std::operator>> (basic_istream< _CharT, _Traits > & __in, _CharT & __c)
Character extractors.
Parameters:
__in An input stream.
__c A character reference.
Returns:
in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts a character (if one is available) and stores it in __c. Otherwise, sets failbit in the input stream.
Definition at line 925 of file istream.tcc.
References std::ios_base::badbit, std::ios_base::eofbit, std::ios_base::failbit, std::ios_base::goodbit, std::basic_ios< _CharT, _Traits >::rdbuf(), and std::basic_ios< _CharT, _Traits >::setstate().
template<class _Traits > basic_istream<char, _Traits>& std::operator>> (basic_istream< char, _Traits > & __in, unsigned char & __c) [inline]
Character extractors.
Parameters:
__in An input stream.
__c A character reference.
Returns:
in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts a character (if one is available) and stores it in __c. Otherwise, sets failbit in the input stream.
Definition at line 725 of file istream.
template<class _Traits > basic_istream<char, _Traits>& std::operator>> (basic_istream< char, _Traits > & __in, signed char & __c) [inline]
Character extractors.
Parameters:
__in An input stream.
__c A character reference.
Returns:
in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts a character (if one is available) and stores it in __c. Otherwise, sets failbit in the input stream.
Definition at line 730 of file istream.
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & std::operator>> (basic_istream< _CharT, _Traits > & __in, _CharT * __s)
Character string extractors.
Parameters:
__in An input stream.
__s A pointer to a character array.
Returns:
__in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts up to n characters and stores them into the array starting at __s. n is defined as:
if width() is greater than zero, n is width() otherwise
n is the number of elements of the largest array of *
char_type that can store a terminating eos.
[27.6.1.2.3]/6
Characters are extracted and stored until one of the following happens:
n-1 characters are stored
EOF is reached
the next character is whitespace according to the current locale
the next character is a null byte (i.e., charT())
width(0) is then called for the input stream.
If no characters are extracted, sets failbit.
Definition at line 957 of file istream.tcc.
References std::ios_base::badbit, std::basic_ios< _CharT, _Traits >::eof(), std::ios_base::eofbit, std::ios_base::failbit, std::ios_base::getloc(), std::ios_base::goodbit, std::basic_ios< _CharT, _Traits >::rdbuf(), std::basic_ios< _CharT, _Traits >::setstate(), and std::ios_base::width().
template<> basic_istream<char>& std::operator>> (basic_istream< char > & __in, char * __s)
Character string extractors.
Parameters:
__in An input stream.
__s A pointer to a character array.
Returns:
__in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts up to n characters and stores them into the array starting at __s. n is defined as:
if width() is greater than zero, n is width() otherwise
n is the number of elements of the largest array of *
char_type that can store a terminating eos.
[27.6.1.2.3]/6
Characters are extracted and stored until one of the following happens:
n-1 characters are stored
EOF is reached
the next character is whitespace according to the current locale
the next character is a null byte (i.e., charT())
width(0) is then called for the input stream.
If no characters are extracted, sets failbit.
template<class _Traits > basic_istream<char, _Traits>& std::operator>> (basic_istream< char, _Traits > & __in, unsigned char * __s) [inline]
Character string extractors.
Parameters:
__in An input stream.
__s A pointer to a character array.
Returns:
__in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts up to n characters and stores them into the array starting at __s. n is defined as:
if width() is greater than zero, n is width() otherwise
n is the number of elements of the largest array of *
char_type that can store a terminating eos.
[27.6.1.2.3]/6
Characters are extracted and stored until one of the following happens:
n-1 characters are stored
EOF is reached
the next character is whitespace according to the current locale
the next character is a null byte (i.e., charT())
width(0) is then called for the input stream.
If no characters are extracted, sets failbit.
Definition at line 772 of file istream.
template<class _Traits > basic_istream<char, _Traits>& std::operator>> (basic_istream< char, _Traits > & __in, signed char * __s) [inline]
Character string extractors.
Parameters:
__in An input stream.
__s A pointer to a character array.
Returns:
__in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts up to n characters and stores them into the array starting at __s. n is defined as:
if width() is greater than zero, n is width() otherwise
n is the number of elements of the largest array of *
char_type that can store a terminating eos.
[27.6.1.2.3]/6
Characters are extracted and stored until one of the following happens:
n-1 characters are stored
EOF is reached
the next character is whitespace according to the current locale
the next character is a null byte (i.e., charT())
width(0) is then called for the input stream.
If no characters are extracted, sets failbit.
Definition at line 777 of file istream.
template<typename _CharT , typename _Traits , typename _Tp > basic_istream<_CharT, _Traits>& std::operator>> (basic_istream< _CharT, _Traits > && __is, _Tp & __x) [inline]
Generic extractor for rvalue stream.
Parameters:
__is An input stream.
__x A reference to the extraction target.
Returns:
is
This is just a forwarding function to allow extraction from rvalue streams since they won't bind to the extractor functions that take an lvalue reference.
Definition at line 866 of file istream.
bitset<_Nb> std::operator>> (size_t __position) const
Self-explanatory.
Definition at line 1345 of file bitset.
template<class _CharT , class _Traits , size_t _Nb> std::basic_istream<_CharT, _Traits>& std::operator>> (std::basic_istream< _CharT, _Traits > & __is, bitset< _Nb > & __x)
Global I/O operators for bitsets.
Direct I/O between streams and bitsets is supported. Output is straightforward. Input will skip whitespace, only accept 0 and 1 characters, and will only extract as many digits as the bitset will hold.
Definition at line 1455 of file bitset.
References std::basic_string< _CharT, _Traits, _Alloc >::empty(), std::basic_string< _CharT, _Traits, _Alloc >::push_back(), std::basic_ios< _CharT, _Traits >::rdbuf(), std::basic_string< _CharT, _Traits, _Alloc >::reserve(), std::basic_ios< _CharT, _Traits >::setstate(), and std::basic_ios< _CharT, _Traits >::widen().
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_istream< _CharT, _Traits > & std::operator>> (basic_istream< _CharT, _Traits > & __is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > & __str)
Read stream into a string.
Parameters:
__is Input stream.
__str Buffer to store into.
Returns:
Reference to the input stream.
Stores characters from __is into __str until whitespace is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased.
Definition at line 552 of file vstring.tcc.
References std::ios_base::getloc(), std::basic_ios< _CharT, _Traits >::rdbuf(), std::basic_ios< _CharT, _Traits >::setstate(), and std::ios_base::width().
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream< _CharT, _Traits > & std::operator>> (basic_istream< _CharT, _Traits > & __is, basic_string< _CharT, _Traits, _Alloc > & __str)
Read stream into a string.
Parameters:
__is Input stream.
__str Buffer to store into.
Returns:
Reference to the input stream.
Stores characters from __is into __str until whitespace is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased.
Definition at line 998 of file basic_string.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::append(), std::basic_string< _CharT, _Traits, _Alloc >::erase(), std::ios_base::getloc(), std::basic_string< _CharT, _Traits, _Alloc >::max_size(), std::basic_ios< _CharT, _Traits >::rdbuf(), std::basic_ios< _CharT, _Traits >::setstate(), and std::ios_base::width().
bitset<_Nb>& std::operator>>= (size_t __position)
Operations on bitsets.
Parameters:
__position The number of places to shift.
These should be self-explanatory.
Definition at line 995 of file bitset.
constexpr bool std::operator[] (size_t __position)
Array-indexing support.
Parameters:
__position Index into the bitset.
Returns:
A bool for a const bitset. For non-const bitsets, an instance of the reference proxy class.
Note:
These operators do no range checking and throw no exceptions, as required by DR 11 to the standard.
_GLIBCXX_RESOLVE_LIB_DEFECTS Note that this implementation already resolves DR 11 (items 1 and 2), but does not do the range-checking required by that DR's resolution. -pme The DR has since been changed: range-checking is a precondition (users' responsibility), and these functions must not throw. -pme
Definition at line 1147 of file bitset.
template<size_t _Nb> bitset<_Nb> std::operator^ (const bitset< _Nb > & __x, const bitset< _Nb > & __y) [inline]
Global bitwise operations on bitsets.
Parameters:
__x A bitset.
__y A bitset of the same size as __x.
Returns:
A new bitset.
These should be self-explanatory.
Definition at line 1436 of file bitset.
template<size_t _Nb> bitset<_Nb> std::operator| (const bitset< _Nb > & __x, const bitset< _Nb > & __y) [inline]
Global bitwise operations on bitsets.
Parameters:
__x A bitset.
__y A bitset of the same size as __x.
Returns:
A new bitset.
These should be self-explanatory.
Definition at line 1427 of file bitset.
bitset<_Nb> std::operator~ () const
See the no-argument flip().
Definition at line 1128 of file bitset.
template<typename _InputIterator , typename _OutputIterator > _OutputIterator std::partial_sum (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
Return list of partial sums.
Accumulates the values in the range [first,last) using the + operator. As each successive input value is added into the total, that partial sum is written to __result. Therefore, the first value in __result is the first value of the input, the second value in __result is the sum of the first and second input values, and so on.
Parameters:
__first Start of input range.
__last End of input range.
__result Output sum.
Returns:
Iterator pointing just beyond the values written to __result.
Definition at line 238 of file stl_numeric.h.
Referenced by __gnu_parallel::__parallel_random_shuffle_drs_pu(), and __gnu_parallel::__sequential_random_shuffle().
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation > _OutputIterator std::partial_sum (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op)
Return list of partial sums.
Accumulates the values in the range [first,last) using __binary_op. As each successive input value is added into the total, that partial sum is written to __result. Therefore, the first value in __result is the first value of the input, the second value in __result is the sum of the first and second input values, and so on.
Parameters:
__first Start of input range.
__last End of input range.
__result Output sum.
__binary_op Function object.
Returns:
Iterator pointing just beyond the values written to __result.
Definition at line 279 of file stl_numeric.h.
template<typename _MoneyT > _Put_money<_MoneyT> std::put_money (const _MoneyT & __mon, bool __intl = false) [inline]
Extended manipulator for inserting money.
Parameters:
__mon Either long double or a specialization of basic_string.
__intl A bool indicating whether international format is to be used.
Sent to a stream object, this manipulator inserts __mon.
Definition at line 305 of file iomanip.
template<typename _Tp > reference_wrapper<_Tp> std::ref (_Tp & __t) [inline]
Denotes a reference should be taken to a variable.
Definition at line 476 of file functional.
Referenced by ref().
template<typename _Tp > void std::ref (const _Tp &&)
Denotes a reference should be taken to a variable.
template<typename _Tp > reference_wrapper<_Tp> std::ref (reference_wrapper< _Tp > __t) [inline]
Partial specialization.
Definition at line 494 of file functional.
References ref().
template<typename _InputIterator , typename _OutputIterator , typename _Tp > _OutputIterator std::replace_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, const _Tp & __old_value, const _Tp & __new_value)
Copy a sequence, replacing each element of one value with another value.
Parameters:
__first An input iterator.
__last An input iterator.
__result An output iterator.
__old_value The value to be replaced.
__new_value The replacement value.
Returns:
The end of the output sequence, result+(last-first).
Copies each element in the input range [__first,__last) to the output range [__result,__result+(__last-__first)) replacing elements equal to __old_value with __new_value.
Definition at line 3909 of file stl_algo.h.
bitset<_Nb>& std::reset ()
Sets every bit to false.
Definition at line 1081 of file bitset.
bitset<_Nb>& std::reset (size_t __position)
Sets a given bit to false.
Parameters:
__position The index of the bit.
Exceptions:
std::out_of_range If pos is bigger the size of the set.
Same as writing set(pos,false).
Definition at line 1095 of file bitset.
References _Unchecked_reset().
_Resetiosflags std::resetiosflags (ios_base::fmtflags __mask) [inline]
Manipulator for setf.
Parameters:
__mask A format flags mask.
Sent to a stream object, this manipulator resets the specified flags, via stream.setf(0,__mask).
Definition at line 65 of file iomanip.
template<typename _Tp > void std::return_temporary_buffer (_Tp * __p) [inline]
The companion to get_temporary_buffer().
Parameters:
__p A buffer previously allocated by get_temporary_buffer.
Returns:
None.
Frees the memory pointed to by __p.
Definition at line 114 of file stl_tempbuf.h.
Referenced by std::_Temporary_buffer< _ForwardIterator, _Tp >::_Temporary_buffer().
ios_base& std::right (ios_base & __base) [inline]
Calls base.setf(ios_base::right, ios_base::adjustfield).
Definition at line 926 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::adjustfield, std::ios_base::right, and std::ios_base::setf().
ios_base& std::scientific (ios_base & __base) [inline]
Calls base.setf(ios_base::scientific, ios_base::floatfield).
Definition at line 968 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::floatfield, std::ios_base::scientific, and std::ios_base::setf().
Referenced by operator<<().
bitset<_Nb>& std::set ()
Sets every bit to true.
Definition at line 1056 of file bitset.
bitset<_Nb>& std::set (size_t __position, bool __val = true)
Sets a given bit to a particular value.
Parameters:
__position The index of the bit.
__val Either true or false, defaults to true.
Exceptions:
std::out_of_range If pos is bigger the size of the set.
Definition at line 1070 of file bitset.
References _Unchecked_set().
new_handler std::set_new_handler (new_handler) throw ()
Takes a replacement handler as the argument, returns the previous handler.
_Setbase std::setbase (int __base) [inline]
Manipulator for setf.
Parameters:
__base A numeric base.
Sent to a stream object, this manipulator changes the ios_base::basefield flags to oct, dec, or hex when base is 8, 10, or 16, accordingly, and to 0 if __base is any other value.
Definition at line 126 of file iomanip.
template<typename _CharT > _Setfill<_CharT> std::setfill (_CharT __c) [inline]
Manipulator for fill.
Parameters:
__c The new fill character.
Sent to a stream object, this manipulator calls fill(__c) for that object.
Definition at line 164 of file iomanip.
_Setiosflags std::setiosflags (ios_base::fmtflags __mask) [inline]
Manipulator for setf.
Parameters:
__mask A format flags mask.
Sent to a stream object, this manipulator sets the format flags to __mask.
Definition at line 95 of file iomanip.
_Setprecision std::setprecision (int __n) [inline]
Manipulator for precision.
Parameters:
__n The new precision.
Sent to a stream object, this manipulator calls precision(__n) for that object.
Definition at line 194 of file iomanip.
_Setw std::setw (int __n) [inline]
Manipulator for width.
Parameters:
__n The new width.
Sent to a stream object, this manipulator calls width(__n) for that object.
Definition at line 224 of file iomanip.
ios_base& std::showbase (ios_base & __base) [inline]
Calls base.setf(ios_base::showbase).
Definition at line 813 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::setf(), and std::ios_base::showbase.
ios_base& std::showpoint (ios_base & __base) [inline]
Calls base.setf(ios_base::showpoint).
Definition at line 829 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::setf(), and std::ios_base::showpoint.
ios_base& std::showpos (ios_base & __base) [inline]
Calls base.setf(ios_base::showpos).
Definition at line 845 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::setf(), and std::ios_base::showpos.
constexpr size_t std::size () const
Returns the total number of bits.
Definition at line 1284 of file bitset.
Referenced by std::deque< _Tp, _Alloc >::_M_new_elements_at_back(), std::deque< _Tp, _Alloc >::_M_new_elements_at_front(), std::basic_string< _CharT, _Traits, _Alloc >::append(), std::basic_string< _CharT, _Traits, _Alloc >::assign(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare(), std::basic_string< _CharT, _Traits, _Alloc >::compare(), std::deque< _Tp, _Alloc >::erase(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::find(), std::basic_string< _CharT, _Traits, _Alloc >::find(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::find_first_not_of(), std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::find_first_of(), std::basic_string< _CharT, _Traits, _Alloc >::find_first_of(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::find_last_not_of(), std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::find_last_of(), std::basic_string< _CharT, _Traits, _Alloc >::find_last_of(), std::vector< _Tp, _Alloc >::operator=(), std::deque< _Tp, _Alloc >::operator=(), std::vector< _Tp, _Alloc >::reserve(), std::basic_string< _CharT, _Traits, _Alloc >::reserve(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::resize(), std::basic_string< _CharT, _Traits, _Alloc >::resize(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::rfind(), and std::basic_string< _CharT, _Traits, _Alloc >::rfind().
ios_base& std::skipws (ios_base & __base) [inline]
Calls base.setf(ios_base::skipws).
Definition at line 861 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::setf(), and std::ios_base::skipws.
Referenced by operator>>().
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp> __shared_ptr<_Tp, _Lp> std::static_pointer_cast (const __shared_ptr< _Tp1, _Lp > & __r) [inline]
static_pointer_cast
Definition at line 1197 of file shared_ptr_base.h.
template<class _T1 , class _T2 > void std::swap (pair< _T1, _T2 > & __x, pair< _T1, _T2 > & __y) [inline]
See std::pair::swap().
Definition at line 246 of file stl_pair.h.
template<typename _Key , typename _Compare , typename _Alloc > void std::swap (multiset< _Key, _Compare, _Alloc > & __x, multiset< _Key, _Compare, _Alloc > & __y) [inline]
See std::multiset::swap().
Definition at line 737 of file stl_multiset.h.
References std::multiset< _Key, _Compare, _Alloc >::swap().
template<typename _Key , typename _Compare , typename _Alloc > void std::swap (set< _Key, _Compare, _Alloc > & __x, set< _Key, _Compare, _Alloc > & __y) [inline]
See std::set::swap().
Definition at line 756 of file stl_set.h.
References std::set< _Key, _Compare, _Alloc >::swap().
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > void std::swap (multimap< _Key, _Tp, _Compare, _Alloc > & __x, multimap< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
See std::multimap::swap().
Definition at line 857 of file stl_multimap.h.
References std::multimap< _Key, _Tp, _Compare, _Alloc >::swap().
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > void std::swap (map< _Key, _Tp, _Compare, _Alloc > & __x, map< _Key, _Tp, _Compare, _Alloc > & __y) [inline]
See std::map::swap().
Definition at line 941 of file stl_map.h.
References std::map< _Key, _Tp, _Compare, _Alloc >::swap().
template<typename _Tp , typename _Alloc > void std::swap (forward_list< _Tp, _Alloc > & __lx, forward_list< _Tp, _Alloc > & __ly) [inline]
See std::forward_list::swap().
Definition at line 1313 of file forward_list.h.
References std::forward_list< _Tp, _Alloc >::swap().
template<typename _Tp , typename _Alloc > void std::swap (vector< _Tp, _Alloc > & __x, vector< _Tp, _Alloc > & __y) [inline]
See std::vector::swap().
Definition at line 1418 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::swap().
template<typename _Tp , typename _Alloc > void std::swap (list< _Tp, _Alloc > & __x, list< _Tp, _Alloc > & __y) [inline]
See std::list::swap().
Definition at line 1634 of file stl_list.h.
References std::list< _Tp, _Alloc >::swap().
template<typename _Tp , typename _Alloc > void std::swap (deque< _Tp, _Alloc > & __x, deque< _Tp, _Alloc > & __y) [inline]
See std::deque::swap().
Definition at line 1983 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::swap().
template<typename _Res , typename... _Args> void std::swap (function< _Res(_Args...)> & __x, function< _Res(_Args...)> & __y) [inline]
Swap the targets of two polymorphic function object wrappers.
This function will not throw an exception.
Definition at line 2412 of file functional.
template<typename _CharT , typename _Traits , typename _Alloc > void std::swap (basic_string< _CharT, _Traits, _Alloc > & __lhs, basic_string< _CharT, _Traits, _Alloc > & __rhs) [inline]
Swap contents of two strings.
Parameters:
__lhs First string.
__rhs Second string.
Exchanges the contents of __lhs and __rhs in constant time.
Definition at line 2714 of file basic_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::swap().
bool std::test (size_t __position) const
Tests the value of a bit.
Parameters:
__position The index of a bit.
Returns:
The value at pos.
Exceptions:
std::out_of_range If pos is bigger the size of the set.
Definition at line 1305 of file bitset.
References _Unchecked_test().
template<class _CharT , class _Traits , class _Alloc > std::basic_string< char, std::char_traits< char >, std::allocator< char > > std::to_string () const
Returns a character interpretation of the bitset.
Returns:
The string equivalent of the bits.
Note the ordering of the bits: decreasing character positions correspond to increasing bit positions (see the main class notes for an example).
Definition at line 1181 of file bitset.
unsigned long std::to_ulong () const
Returns a numerical interpretation of the bitset.
Returns:
The integral equivalent of the bits.
Exceptions:
std::overflow_error If there are too many bits to be represented in an unsigned long.
Definition at line 1162 of file bitset.
template<typename _CharT > _CharT std::tolower (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.tolower(__c).
Definition at line 2601 of file locale_facets.h.
Referenced by std::regex_traits< _Ch_type >::translate_nocase().
template<typename _CharT > _CharT std::toupper (_CharT __c, const locale & __loc) [inline]
Convenience interface to ctype.toupper(__c).
Definition at line 2595 of file locale_facets.h.
template<typename _InputIterator , typename _ForwardIterator > _ForwardIterator std::uninitialized_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result) [inline]
Copies the range [first,last) into result.
Parameters:
__first An input iterator.
__last An input iterator.
__result An output iterator.
Returns:
__result + (__first - __last)
Like copy(), but does not require an initialized output range.
Definition at line 109 of file stl_uninitialized.h.
Referenced by __gnu_parallel::parallel_sort_mwms_pu().
template<typename _InputIterator , typename _Size , typename _ForwardIterator > _ForwardIterator std::uninitialized_copy_n (_InputIterator __first, _Size __n, _ForwardIterator __result) [inline]
Copies the range [first,first+n) into result.
Parameters:
__first An input iterator.
__n The number of elements to copy.
__result An output iterator.
Returns:
__result + __n
Like copy_n(), but does not require an initialized output range.
Definition at line 649 of file stl_uninitialized.h.
References __iterator_category().
template<typename _ForwardIterator , typename _Tp > void std::uninitialized_fill (_ForwardIterator __first, _ForwardIterator __last, const _Tp & __x) [inline]
Copies the value x into the range [first,last).
Parameters:
__first An input iterator.
__last An input iterator.
__x The source value.
Returns:
Nothing.
Like fill(), but does not require an initialized output range.
Definition at line 166 of file stl_uninitialized.h.
template<typename _ForwardIterator , typename _Size , typename _Tp > void std::uninitialized_fill_n (_ForwardIterator __first, _Size __n, const _Tp & __x) [inline]
Copies the value x into the range [first,first+n).
Parameters:
__first An input iterator.
__n The number of copies to make.
__x The source value.
Returns:
Nothing.
Like fill_n(), but does not require an initialized output range.
Definition at line 220 of file stl_uninitialized.h.
ios_base& std::unitbuf (ios_base & __base) [inline]
Calls base.setf(ios_base::unitbuf).
Definition at line 893 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::setf(), and std::ios_base::unitbuf.
ios_base& std::uppercase (ios_base & __base) [inline]
Calls base.setf(ios_base::uppercase).
Definition at line 877 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::setf(), and std::ios_base::uppercase.
template<typename _Facet > const _Facet & std::use_facet (const locale & __loc)
Return a facet.
use_facet looks for and returns a reference to a facet of type Facet where Facet is the template parameter. If has_facet(locale) is true, there is a suitable facet to return. It throws std::bad_cast if the locale doesn't contain a facet of type Facet.
Template Parameters:
_Facet The facet type to access.
Parameters:
__loc The locale to use.
Returns:
Reference to facet of type Facet.
Exceptions:
std::bad_cast if __loc doesn't contain a facet of type _Facet.
Definition at line 130 of file locale_classes.tcc.
Referenced by std::regex_traits< _Ch_type >::isctype(), std::regex_traits< _Ch_type >::transform(), and std::regex_traits< _Ch_type >::translate_nocase().
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & std::ws (basic_istream< _CharT, _Traits > & __is)
Quick and easy way to eat whitespace.
This manipulator extracts whitespace characters, stopping when the next character is non-whitespace, or when the input sequence is empty. If the sequence is empty, eofbit is set in the stream, but not failbit.
The current locale is used to distinguish whitespace characters.
Example:
     MyClass   mc;
     std::cin >> std::ws >> mc;
will skip leading whitespace before calling operator>> on cin and your object. Note that the same effect can be achieved by creating a std::basic_istream::sentry inside your definition of operator>>.
Definition at line 1018 of file istream.tcc.
References std::basic_ios< _CharT, _Traits >::eof(), std::ios_base::eofbit, std::ios_base::getloc(), std::basic_ios< _CharT, _Traits >::rdbuf(), and std::basic_ios< _CharT, _Traits >::setstate().
Variable Documentation
enable_if< (is_pointer< _Functor >::value &&is_function< typename remove_pointer< _Functor >::type >::value), typename result_of< _Functor(_Args &&...)>::type >::type std::__invoke [inline]
Invoke a function object, which may be either a member pointer or a function object. The first parameter will tell which.
Definition at line 233 of file functional.
ios_base::Init std::__ioinit [static]
Linked to standard error (buffered)
Definition at line 75 of file iostream.
ostream std::cerr
Linked to standard output.
istream std::cin
Linked to standard input.
ostream std::clog
Linked to standard error (unbuffered)
ostream std::cout
Linked to standard input.
constexpr piecewise_construct_t std::piecewise_construct
piecewise_construct
Definition at line 76 of file stl_pair.h.
wostream std::wcerr
Linked to standard output.
wistream std::wcin
Linked to standard error (buffered)
wostream std::wclog
Linked to standard error (unbuffered)
wostream std::wcout
Linked to standard input.