libstdc++: Regular Expressions
Regular Expressions
Classes
class std::basic_regex< _Ch_type, _Rx_traits >
class std::match_results< _Bi_iter, _Allocator >
The results of a match or search operation.
class std::regex_iterator< _Bi_iter, _Ch_type, _Rx_traits >
class std::regex_token_iterator< _Bi_iter, _Ch_type, _Rx_traits >
struct std::regex_traits< _Ch_type >
Describes aspects of a regular expression.
class std::sub_match< _BiIter >
Typedefs
typedef match_results< const
char * > std::cmatch
typedef regex_iterator< const
char * > std::cregex_iterator
typedef regex_token_iterator
< const char * > std::cregex_token_iterator
typedef sub_match< const char * > std::csub_match
typedef basic_regex< char > std::regex
typedef match_results
< string::const_iterator > std::smatch
typedef regex_iterator
< string::const_iterator > std::sregex_iterator
typedef regex_token_iterator
< string::const_iterator > std::sregex_token_iterator
typedef sub_match
< string::const_iterator > std::ssub_match
typedef match_results< const
wchar_t * > std::wcmatch
typedef regex_iterator< const
wchar_t * > std::wcregex_iterator
typedef regex_token_iterator
< const wchar_t * > std::wcregex_token_iterator
typedef sub_match< const
wchar_t * > std::wcsub_match
typedef basic_regex< wchar_t > std::wregex
typedef match_results
< wstring::const_iterator > std::wsmatch
typedef regex_iterator
< wstring::const_iterator > std::wsregex_iterator
typedef regex_token_iterator
< wstring::const_iterator > std::wsregex_token_iterator
typedef sub_match
< wstring::const_iterator > std::wssub_match
Functions
template<typename _Bi_iter > const sub_match< _Bi_iter > & std::__unmatched_sub ()
bool std::regex_traits< _Ch_type >::isctype (_Ch_type __c, char_class_type __f) const
template<typename _BiIter > bool std::operator!= (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator!= (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator!= (const sub_match< _Bi_iter > &__lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Bi_iter > bool std::operator!= (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool std::operator!= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Bi_iter > bool std::operator!= (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool std::operator!= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Bi_iter , class _Allocator > bool std::operator!= (const match_results< _Bi_iter, _Allocator > &__m1, const match_results< _Bi_iter, _Allocator > &__m2)
template<typename _BiIter > bool std::operator< (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator< (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc > bool std::operator< (const sub_match< _Bi_iter > &__lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Bi_iter > bool std::operator< (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool std::operator< (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Bi_iter > bool std::operator< (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool std::operator< (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Ch_type , typename _Ch_traits , typename _Bi_iter > basic_ostream< _Ch_type,
_Ch_traits > & std::operator<< (basic_ostream< _Ch_type, _Ch_traits > &__os, const sub_match< _Bi_iter > &__m)
template<typename _BiIter > bool std::operator<= (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator<= (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc > bool std::operator<= (const sub_match< _Bi_iter > &__lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Bi_iter > bool std::operator<= (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool std::operator<= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Bi_iter > bool std::operator<= (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool std::operator<= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _BiIter > bool std::operator== (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator== (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator== (const sub_match< _Bi_iter > &__lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Bi_iter > bool std::operator== (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool std::operator== (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Bi_iter > bool std::operator== (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool std::operator== (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Bi_iter , typename _Allocator > bool std::operator== (const match_results< _Bi_iter, _Allocator > &__m1, const match_results< _Bi_iter, _Allocator > &__m2)
template<typename _BiIter > bool std::operator> (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator> (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc > bool std::operator> (const sub_match< _Bi_iter > &__lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Bi_iter > bool std::operator> (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool std::operator> (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Bi_iter > bool std::operator> (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool std::operator> (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _BiIter > bool std::operator>= (const sub_match< _BiIter > &__lhs, const sub_match< _BiIter > &__rhs)
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator>= (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc > bool std::operator>= (const sub_match< _Bi_iter > &__lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > &__rhs)
template<typename _Bi_iter > bool std::operator>= (typename iterator_traits< _Bi_iter >::value_type const *__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool std::operator>= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const *__rhs)
template<typename _Bi_iter > bool std::operator>= (typename iterator_traits< _Bi_iter >::value_type const &__lhs, const sub_match< _Bi_iter > &__rhs)
template<typename _Bi_iter > bool std::operator>= (const sub_match< _Bi_iter > &__lhs, typename iterator_traits< _Bi_iter >::value_type const &__rhs)
template<typename _Ch_type , typename _Rx_traits > void std::swap (basic_regex< _Ch_type, _Rx_traits > &__lhs, basic_regex< _Ch_type, _Rx_traits > &__rhs)
template<typename _Bi_iter , typename _Allocator > void std::swap (match_results< _Bi_iter, _Allocator > &__lhs, match_results< _Bi_iter, _Allocator > &__rhs)
int std::regex_traits< _Ch_type >::value (_Ch_type __ch, int __radix) const
Matching, Searching, and Replacing
template<typename _Bi_iter , typename _Allocator , typename _Ch_type , typename _Rx_traits > bool std::regex_match (_Bi_iter __s, _Bi_iter __e, match_results< _Bi_iter, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Bi_iter , typename _Ch_type , typename _Rx_traits > bool std::regex_match (_Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_type , typename _Allocator , typename _Rx_traits > bool std::regex_match (const _Ch_type *__s, match_results< const _Ch_type *, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _Ch_alloc , typename _Allocator , typename _Ch_type , typename _Rx_traits > bool std::regex_match (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &__s, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_type , class _Rx_traits > bool std::regex_match (const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _Str_allocator , typename _Ch_type , typename _Rx_traits > bool std::regex_match (const basic_string< _Ch_type, _Ch_traits, _Str_allocator > &__s, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Bi_iter , typename _Allocator , typename _Ch_type , typename _Rx_traits > bool std::regex_search (_Bi_iter __first, _Bi_iter __last, match_results< _Bi_iter, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Bi_iter , typename _Ch_type , typename _Rx_traits > bool std::regex_search (_Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_type , class _Allocator , class _Rx_traits > bool std::regex_search (const _Ch_type *__s, match_results< const _Ch_type *, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_type , typename _Rx_traits > bool std::regex_search (const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _String_allocator , typename _Ch_type , typename _Rx_traits > bool std::regex_search (const basic_string< _Ch_type, _Ch_traits, _String_allocator > &__s, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_traits , typename _Ch_alloc , typename _Allocator , typename _Ch_type , typename _Rx_traits > bool std::regex_search (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &__s, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Out_iter , typename _Bi_iter , typename _Rx_traits , typename _Ch_type > _Out_iter std::regex_replace (_Out_iter __out, _Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type > &__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Rx_traits , typename _Ch_type > basic_string< _Ch_type > std::regex_replace (const basic_string< _Ch_type > &__s, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type > &__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
Detailed Description
A facility for performing regular expression pattern matching.
Typedef Documentation
typedef regex_token_iterator<const char*> std::cregex_token_iterator
Token iterator for C-style NULL-terminated strings.
Definition at line 2508 of file regex.h.
typedef sub_match<const char*> std::csub_match
Standard regex submatch over a C-style null-terminated string.
Definition at line 853 of file regex.h.
typedef basic_regex<char> std::regex
Standard regular expressions.
Definition at line 726 of file regex.h.
typedef regex_token_iterator<string::const_iterator> std::sregex_token_iterator
Token iterator for standard strings.
Definition at line 2510 of file regex.h.
typedef sub_match<string::const_iterator> std::ssub_match
Standard regex submatch over a standard string.
Definition at line 855 of file regex.h.
typedef regex_token_iterator<const wchar_t*> std::wcregex_token_iterator
Token iterator for C-style NULL-terminated wide strings.
Definition at line 2513 of file regex.h.
typedef sub_match<const wchar_t*> std::wcsub_match
Regex submatch over a C-style null-terminated wide string.
Definition at line 858 of file regex.h.
typedef basic_regex<wchar_t> std::wregex
Standard wide-character regular expressions.
Definition at line 729 of file regex.h.
typedef regex_token_iterator<wstring::const_iterator> std::wsregex_token_iterator
Token iterator for standard wide-character strings.
Definition at line 2515 of file regex.h.
typedef sub_match<wstring::const_iterator> std::wssub_match
Regex submatch over a standard wide string.
Definition at line 860 of file regex.h.
Function Documentation
template<typename _Ch_type > bool std::regex_traits< _Ch_type >::isctype (_Ch_type __c, char_class_type __f) const
Determines if c is a member of an identified class.
Parameters:
__c a character.
__f a class type (as returned from lookup_classname).
Returns:
true if the character __c is a member of the classification represented by __f, false otherwise.
Exceptions:
std::bad_cast if the current locale does not have a ctype facet.
Definition at line 285 of file regex.h.
References std::__ctype_abstract_base< _CharT >::is(), std::use_facet(), and std::__ctype_abstract_base< _CharT >::widen().
template<typename _BiIter > bool std::operator!= (const sub_match< _BiIter > & __lhs, const sub_match< _BiIter > & __rhs) [inline]
Tests the inequivalence of two regular expression submatches.
Parameters:
__lhs First regular expression submatch.
__rhs Second regular expression submatch.
Returns:
true if __lhs is not equivalent to __rhs, false otherwise.
Definition at line 885 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator!= (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > & __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the inequivalence of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs is not equivalent to __rhs, false otherwise.
Definition at line 961 of file regex.h.
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator!= (const sub_match< _Bi_iter > & __lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > & __rhs) [inline]
Tests the inequivalence of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A string.
Returns:
true if __lhs is not equivalent to __rhs, false otherwise.
Definition at line 1042 of file regex.h.
template<typename _Bi_iter > bool std::operator!= (typename iterator_traits< _Bi_iter >::value_type const * __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the inequivalence of an iterator value and a regular expression submatch.
Parameters:
__lhs A regular expression submatch.
__rhs A string.
Returns:
true if __lhs is not equivalent to __rhs, false otherwise.
Definition at line 1126 of file regex.h.
template<typename _Bi_iter > bool std::operator!= (const sub_match< _Bi_iter > & __lhs, typename iterator_traits< _Bi_iter >::value_type const * __rhs) [inline]
Tests the inequivalence of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A pointer to a string.
Returns:
true if __lhs is not equivalent to __rhs, false otherwise.
Definition at line 1200 of file regex.h.
template<typename _Bi_iter > bool std::operator!= (typename iterator_traits< _Bi_iter >::value_type const & __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the inequivalence of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs is not equivalent to __rhs, false otherwise.
Definition at line 1277 of file regex.h.
template<typename _Bi_iter > bool std::operator!= (const sub_match< _Bi_iter > & __lhs, typename iterator_traits< _Bi_iter >::value_type const & __rhs) [inline]
Tests the inequivalence of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A const string reference.
Returns:
true if __lhs is not equivalent to __rhs, false otherwise.
Definition at line 1357 of file regex.h.
template<typename _Bi_iter , class _Allocator > bool std::operator!= (const match_results< _Bi_iter, _Allocator > & __m1, const match_results< _Bi_iter, _Allocator > & __m2) [inline]
Compares two match_results for inequality.
Returns:
true if the two objects do not refer to the same match, false otherwise.
Definition at line 1872 of file regex.h.
template<typename _BiIter > bool std::operator< (const sub_match< _BiIter > & __lhs, const sub_match< _BiIter > & __rhs) [inline]
Tests the ordering of two regular expression submatches.
Parameters:
__lhs First regular expression submatch.
__rhs Second regular expression submatch.
Returns:
true if __lhs precedes __rhs, false otherwise.
Definition at line 897 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator< (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > & __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the ordering of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs precedes __rhs, false otherwise.
Definition at line 974 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc > bool std::operator< (const sub_match< _Bi_iter > & __lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > & __rhs) [inline]
Tests the ordering of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A string.
Returns:
true if __lhs precedes __rhs, false otherwise.
Definition at line 1056 of file regex.h.
References std::basic_string< _CharT, _Traits, _Alloc >::compare().
template<typename _Bi_iter > bool std::operator< (typename iterator_traits< _Bi_iter >::value_type const * __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the ordering of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs precedes __rhs, false otherwise.
Definition at line 1138 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter > bool std::operator< (const sub_match< _Bi_iter > & __lhs, typename iterator_traits< _Bi_iter >::value_type const * __rhs) [inline]
Tests the ordering of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A string.
Returns:
true if __lhs precedes __rhs, false otherwise.
Definition at line 1212 of file regex.h.
template<typename _Bi_iter > bool std::operator< (typename iterator_traits< _Bi_iter >::value_type const & __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the ordering of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs precedes __rhs, false otherwise.
Definition at line 1289 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter > bool std::operator< (const sub_match< _Bi_iter > & __lhs, typename iterator_traits< _Bi_iter >::value_type const & __rhs) [inline]
Tests the ordering of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A const string reference.
Returns:
true if __lhs precedes __rhs, false otherwise.
Definition at line 1369 of file regex.h.
template<typename _Ch_type , typename _Ch_traits , typename _Bi_iter > basic_ostream<_Ch_type, _Ch_traits>& std::operator<< (basic_ostream< _Ch_type, _Ch_traits > & __os, const sub_match< _Bi_iter > & __m) [inline]
Inserts a matched string into an output stream.
Parameters:
__os The output stream.
__m A submatch string.
Returns:
the output stream with the submatch string inserted.
Definition at line 1423 of file regex.h.
References std::sub_match< _BiIter >::str().
template<typename _BiIter > bool std::operator<= (const sub_match< _BiIter > & __lhs, const sub_match< _BiIter > & __rhs) [inline]
Tests the ordering of two regular expression submatches.
Parameters:
__lhs First regular expression submatch.
__rhs Second regular expression submatch.
Returns:
true if __lhs does not succeed __rhs, false otherwise.
Definition at line 909 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator<= (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > & __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the ordering of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs does not succeed __rhs, false otherwise.
Definition at line 1013 of file regex.h.
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc > bool std::operator<= (const sub_match< _Bi_iter > & __lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > & __rhs) [inline]
Tests the ordering of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A string.
Returns:
true if __lhs does not succeed __rhs, false otherwise.
Definition at line 1098 of file regex.h.
template<typename _Bi_iter > bool std::operator<= (typename iterator_traits< _Bi_iter >::value_type const * __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the ordering of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs does not succeed __rhs, false otherwise.
Definition at line 1174 of file regex.h.
template<typename _Bi_iter > bool std::operator<= (const sub_match< _Bi_iter > & __lhs, typename iterator_traits< _Bi_iter >::value_type const * __rhs) [inline]
Tests the ordering of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A string.
Returns:
true if __lhs does not succeed __rhs, false otherwise.
Definition at line 1248 of file regex.h.
template<typename _Bi_iter > bool std::operator<= (typename iterator_traits< _Bi_iter >::value_type const & __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the ordering of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs does not succeed __rhs, false otherwise.
Definition at line 1328 of file regex.h.
template<typename _Bi_iter > bool std::operator<= (const sub_match< _Bi_iter > & __lhs, typename iterator_traits< _Bi_iter >::value_type const & __rhs) [inline]
Tests the ordering of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A const string reference.
Returns:
true if __lhs does not succeed __rhs, false otherwise.
Definition at line 1408 of file regex.h.
template<typename _BiIter > bool std::operator== (const sub_match< _BiIter > & __lhs, const sub_match< _BiIter > & __rhs) [inline]
Tests the equivalence of two regular expression submatches.
Parameters:
__lhs First regular expression submatch.
__rhs Second regular expression submatch.
Returns:
true if __lhs is equivalent to __rhs, false otherwise.
Definition at line 873 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator== (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > & __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the equivalence of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs is equivalent to __rhs, false otherwise.
Definition at line 946 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator== (const sub_match< _Bi_iter > & __lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > & __rhs) [inline]
Tests the equivalence of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A string.
Returns:
true if __lhs is equivalent to __rhs, false otherwise.
Definition at line 1027 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter > bool std::operator== (typename iterator_traits< _Bi_iter >::value_type const * __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the equivalence of a C string and a regular expression submatch.
Parameters:
__lhs A C string.
__rhs A regular expression submatch.
Returns:
true if __lhs is equivalent to __rhs, false otherwise.
Definition at line 1113 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter > bool std::operator== (const sub_match< _Bi_iter > & __lhs, typename iterator_traits< _Bi_iter >::value_type const * __rhs) [inline]
Tests the equivalence of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A pointer to a string?
Returns:
true if __lhs is equivalent to __rhs, false otherwise.
Definition at line 1187 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter > bool std::operator== (typename iterator_traits< _Bi_iter >::value_type const & __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the equivalence of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs is equivalent to __rhs, false otherwise.
Definition at line 1261 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter > bool std::operator== (const sub_match< _Bi_iter > & __lhs, typename iterator_traits< _Bi_iter >::value_type const & __rhs) [inline]
Tests the equivalence of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A const string reference.
Returns:
true if __lhs is equivalent to __rhs, false otherwise.
Definition at line 1341 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter , typename _Allocator > bool std::operator== (const match_results< _Bi_iter, _Allocator > & __m1, const match_results< _Bi_iter, _Allocator > & __m2) [inline]
Compares two match_results for equality.
Returns:
true if the two objects refer to the same match, false otherwise.
Definition at line 1848 of file regex.h.
References std::match_results< _Bi_iter, _Allocator >::begin(), std::match_results< _Bi_iter, _Allocator >::empty(), std::match_results< _Bi_iter, _Allocator >::end(), std::equal(), std::match_results< _Bi_iter, _Allocator >::prefix(), std::match_results< _Bi_iter, _Allocator >::ready(), std::match_results< _Bi_iter, _Allocator >::size(), and std::match_results< _Bi_iter, _Allocator >::suffix().
template<typename _BiIter > bool std::operator> (const sub_match< _BiIter > & __lhs, const sub_match< _BiIter > & __rhs) [inline]
Tests the ordering of two regular expression submatches.
Parameters:
__lhs First regular expression submatch.
__rhs Second regular expression submatch.
Returns:
true if __lhs succeeds __rhs, false otherwise.
Definition at line 933 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator> (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > & __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the ordering of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs succeeds __rhs, false otherwise.
Definition at line 987 of file regex.h.
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc > bool std::operator> (const sub_match< _Bi_iter > & __lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > & __rhs) [inline]
Tests the ordering of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A string.
Returns:
true if __lhs succeeds __rhs, false otherwise.
Definition at line 1070 of file regex.h.
template<typename _Bi_iter > bool std::operator> (typename iterator_traits< _Bi_iter >::value_type const * __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the ordering of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs succeeds __rhs, false otherwise.
Definition at line 1150 of file regex.h.
template<typename _Bi_iter > bool std::operator> (const sub_match< _Bi_iter > & __lhs, typename iterator_traits< _Bi_iter >::value_type const * __rhs) [inline]
Tests the ordering of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A string.
Returns:
true if __lhs succeeds __rhs, false otherwise.
Definition at line 1224 of file regex.h.
template<typename _Bi_iter > bool std::operator> (typename iterator_traits< _Bi_iter >::value_type const & __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the ordering of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs succeeds __rhs, false otherwise.
Definition at line 1304 of file regex.h.
template<typename _Bi_iter > bool std::operator> (const sub_match< _Bi_iter > & __lhs, typename iterator_traits< _Bi_iter >::value_type const & __rhs) [inline]
Tests the ordering of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A const string reference.
Returns:
true if __lhs succeeds __rhs, false otherwise.
Definition at line 1384 of file regex.h.
template<typename _BiIter > bool std::operator>= (const sub_match< _BiIter > & __lhs, const sub_match< _BiIter > & __rhs) [inline]
Tests the ordering of two regular expression submatches.
Parameters:
__lhs First regular expression submatch.
__rhs Second regular expression submatch.
Returns:
true if __lhs does not precede __rhs, false otherwise.
Definition at line 921 of file regex.h.
References std::sub_match< _BiIter >::compare().
template<typename _Bi_iter , typename _Ch_traits , typename _Ch_alloc > bool std::operator>= (const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > & __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the ordering of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs does not precede __rhs, false otherwise.
Definition at line 1000 of file regex.h.
template<typename _Bi_iter , class _Ch_traits , class _Ch_alloc > bool std::operator>= (const sub_match< _Bi_iter > & __lhs, const basic_string< typename iterator_traits< _Bi_iter >::value_type, _Ch_traits, _Ch_alloc > & __rhs) [inline]
Tests the ordering of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A string.
Returns:
true if __lhs does not precede __rhs, false otherwise.
Definition at line 1084 of file regex.h.
template<typename _Bi_iter > bool std::operator>= (typename iterator_traits< _Bi_iter >::value_type const * __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the ordering of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs does not precede __rhs, false otherwise.
Definition at line 1162 of file regex.h.
template<typename _Bi_iter > bool std::operator>= (const sub_match< _Bi_iter > & __lhs, typename iterator_traits< _Bi_iter >::value_type const * __rhs) [inline]
Tests the ordering of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A string.
Returns:
true if __lhs does not precede __rhs, false otherwise.
Definition at line 1236 of file regex.h.
template<typename _Bi_iter > bool std::operator>= (typename iterator_traits< _Bi_iter >::value_type const & __lhs, const sub_match< _Bi_iter > & __rhs) [inline]
Tests the ordering of a string and a regular expression submatch.
Parameters:
__lhs A string.
__rhs A regular expression submatch.
Returns:
true if __lhs does not precede __rhs, false otherwise.
Definition at line 1316 of file regex.h.
template<typename _Bi_iter > bool std::operator>= (const sub_match< _Bi_iter > & __lhs, typename iterator_traits< _Bi_iter >::value_type const & __rhs) [inline]
Tests the ordering of a regular expression submatch and a string.
Parameters:
__lhs A regular expression submatch.
__rhs A const string reference.
Returns:
true if __lhs does not precede __rhs, false otherwise.
Definition at line 1396 of file regex.h.
template<typename _Bi_iter , typename _Allocator , typename _Ch_type , typename _Rx_traits > bool std::regex_match (_Bi_iter __s, _Bi_iter __e, match_results< _Bi_iter, _Allocator > & __m, const basic_regex< _Ch_type, _Rx_traits > & __re, regex_constants::match_flag_type __flags = regex_constants::match_default)
Determines if there is a match between the regular expression e and all of the character sequence [first, last).
Parameters:
__s Start of the character sequence to match.
__e One-past-the-end of the character sequence to match.
__m The match results.
__re The regular expression.
__flags Controls how the regular expression is matched.
Return values:
true A match exists.
false Otherwise.
Exceptions:
an exception of type regex_error.
Todo:
Implement this function.
Definition at line 1916 of file regex.h.
Referenced by std::regex_match().
template<typename _Bi_iter , typename _Ch_type , typename _Rx_traits > bool std::regex_match (_Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > & __re, regex_constants::match_flag_type __flags = regex_constants::match_default)
Indicates if there is a match between the regular expression e and all of the character sequence [first, last).
Parameters:
__first Beginning of the character sequence to match.
__last One-past-the-end of the character sequence to match.
__re The regular expression.
__flags Controls how the regular expression is matched.
Return values:
true A match exists.
false Otherwise.
Exceptions:
an exception of type regex_error.
Definition at line 1947 of file regex.h.
References std::regex_match().
template<typename _Ch_type , typename _Allocator , typename _Rx_traits > bool std::regex_match (const _Ch_type * __s, match_results< const _Ch_type *, _Allocator > & __m, const basic_regex< _Ch_type, _Rx_traits > & __re, regex_constants::match_flag_type __f = regex_constants::match_default) [inline]
Determines if there is a match between the regular expression e and a C-style null-terminated string.
Parameters:
__s The C-style null-terminated string to match.
__m The match results.
__re The regular expression.
__f Controls how the regular expression is matched.
Return values:
true A match exists.
false Otherwise.
Exceptions:
an exception of type regex_error.
Definition at line 1972 of file regex.h.
References std::regex_match().
template<typename _Ch_traits , typename _Ch_alloc , typename _Allocator , typename _Ch_type , typename _Rx_traits > bool std::regex_match (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > & __s, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Allocator > & __m, const basic_regex< _Ch_type, _Rx_traits > & __re, regex_constants::match_flag_type __flags = regex_constants::match_default) [inline]
Determines if there is a match between the regular expression e and a string.
Parameters:
__s The string to match.
__m The match results.
__re The regular expression.
__flags Controls how the regular expression is matched.
Return values:
true A match exists.
false Otherwise.
Exceptions:
an exception of type regex_error.
Definition at line 1996 of file regex.h.
References std::basic_string< _CharT, _Traits, _Alloc >::begin(), std::basic_string< _CharT, _Traits, _Alloc >::end(), and std::regex_match().
template<typename _Ch_type , class _Rx_traits > bool std::regex_match (const _Ch_type * __s, const basic_regex< _Ch_type, _Rx_traits > & __re, regex_constants::match_flag_type __f = regex_constants::match_default) [inline]
Indicates if there is a match between the regular expression e and a C-style null-terminated string.
Parameters:
__s The C-style null-terminated string to match.
__re The regular expression.
__f Controls how the regular expression is matched.
Return values:
true A match exists.
false Otherwise.
Exceptions:
an exception of type regex_error.
Definition at line 2019 of file regex.h.
References std::regex_match().
template<typename _Ch_traits , typename _Str_allocator , typename _Ch_type , typename _Rx_traits > bool std::regex_match (const basic_string< _Ch_type, _Ch_traits, _Str_allocator > & __s, const basic_regex< _Ch_type, _Rx_traits > & __re, regex_constants::match_flag_type __flags = regex_constants::match_default) [inline]
Indicates if there is a match between the regular expression e and a string.
Parameters:
__s [IN] The string to match.
__re [IN] The regular expression.
__flags [IN] Controls how the regular expression is matched.
Return values:
true A match exists.
false Otherwise.
Exceptions:
an exception of type regex_error.
Definition at line 2041 of file regex.h.
References std::basic_string< _CharT, _Traits, _Alloc >::begin(), std::basic_string< _CharT, _Traits, _Alloc >::end(), and std::regex_match().
template<typename _Out_iter , typename _Bi_iter , typename _Rx_traits , typename _Ch_type > _Out_iter std::regex_replace (_Out_iter __out, _Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > & __e, const basic_string< _Ch_type > & __fmt, regex_constants::match_flag_type __flags = regex_constants::match_default) [inline]
Todo:
Needs documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Parameters:
__out
__first
__last
__e
__fmt
__flags
Returns:
out
Exceptions:
an exception of type regex_error.
Todo:
Implement this function.
Definition at line 2200 of file regex.h.
Referenced by std::regex_replace().
template<typename _Rx_traits , typename _Ch_type > basic_string<_Ch_type> std::regex_replace (const basic_string< _Ch_type > & __s, const basic_regex< _Ch_type, _Rx_traits > & __e, const basic_string< _Ch_type > & __fmt, regex_constants::match_flag_type __flags = regex_constants::match_default) [inline]
Todo:
Needs documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Parameters:
__s
__e
__fmt
__flags
Returns:
a copy of string s with replacements.
Exceptions:
an exception of type regex_error.
Definition at line 2220 of file regex.h.
References std::back_inserter(), std::basic_string< _CharT, _Traits, _Alloc >::begin(), std::basic_string< _CharT, _Traits, _Alloc >::end(), and std::regex_replace().
template<typename _Bi_iter , typename _Allocator , typename _Ch_type , typename _Rx_traits > bool std::regex_search (_Bi_iter __first, _Bi_iter __last, match_results< _Bi_iter, _Allocator > & __m, const basic_regex< _Ch_type, _Rx_traits > & __re, regex_constants::match_flag_type __flags = regex_constants::match_default) [inline]
Searches for a regular expression within a range.
Parameters:
__first [IN] The start of the string to search.
__last [IN] One-past-the-end of the string to search.
__m [OUT] The match results.
__re [IN] The regular expression to search for.
__flags [IN] Search policy flags.
Return values:
true A match was found within the string.
false No match was found within the string, the content of m is undefined.
Exceptions:
an exception of type regex_error.
Todo:
Implement this function.
Definition at line 2066 of file regex.h.
Referenced by std::regex_search().
template<typename _Bi_iter , typename _Ch_type , typename _Rx_traits > bool std::regex_search (_Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > & __re, regex_constants::match_flag_type __flags = regex_constants::match_default) [inline]
Searches for a regular expression within a range.
Parameters:
__first [IN] The start of the string to search.
__last [IN] One-past-the-end of the string to search.
__re [IN] The regular expression to search for.
__flags [IN] Search policy flags.
Return values:
true A match was found within the string.
false No match was found within the string.
Todo:
Needs documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Exceptions:
an exception of type regex_error.
Definition at line 2087 of file regex.h.
References std::regex_search().
template<typename _Ch_type , class _Allocator , class _Rx_traits > bool std::regex_search (const _Ch_type * __s, match_results< const _Ch_type *, _Allocator > & __m, const basic_regex< _Ch_type, _Rx_traits > & __e, regex_constants::match_flag_type __f = regex_constants::match_default) [inline]
Searches for a regular expression within a C-string.
Parameters:
__s [IN] A C-string to search for the regex.
__m [OUT] The set of regex matches.
__e [IN] The regex to search for in s.
__f [IN] The search flags.
Return values:
true A match was found within the string.
false No match was found within the string, the content of m is undefined.
Todo:
Needs documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Exceptions:
an exception of type regex_error.
Definition at line 2111 of file regex.h.
References std::regex_search().
template<typename _Ch_type , typename _Rx_traits > bool std::regex_search (const _Ch_type * __s, const basic_regex< _Ch_type, _Rx_traits > & __e, regex_constants::match_flag_type __f = regex_constants::match_default) [inline]
Searches for a regular expression within a C-string.
Parameters:
__s [IN] The C-string to search.
__e [IN] The regular expression to search for.
__f [IN] Search policy flags.
Return values:
true A match was found within the string.
false No match was found within the string.
Todo:
Needs documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Exceptions:
an exception of type regex_error.
Definition at line 2131 of file regex.h.
References std::regex_search().
template<typename _Ch_traits , typename _String_allocator , typename _Ch_type , typename _Rx_traits > bool std::regex_search (const basic_string< _Ch_type, _Ch_traits, _String_allocator > & __s, const basic_regex< _Ch_type, _Rx_traits > & __e, regex_constants::match_flag_type __flags = regex_constants::match_default) [inline]
Searches for a regular expression within a string.
Parameters:
__s [IN] The string to search.
__e [IN] The regular expression to search for.
__flags [IN] Search policy flags.
Return values:
true A match was found within the string.
false No match was found within the string.
Todo:
Needs documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Exceptions:
an exception of type regex_error.
Definition at line 2151 of file regex.h.
References std::regex_search().
template<typename _Ch_traits , typename _Ch_alloc , typename _Allocator , typename _Ch_type , typename _Rx_traits > bool std::regex_search (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > & __s, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Allocator > & __m, const basic_regex< _Ch_type, _Rx_traits > & __e, regex_constants::match_flag_type __f = regex_constants::match_default) [inline]
Searches for a regular expression within a string.
Parameters:
__s [IN] A C++ string to search for the regex.
__m [OUT] The set of regex matches.
__e [IN] The regex to search for in s.
__f [IN] The search flags.
Return values:
true A match was found within the string.
false No match was found within the string, the content of m is undefined.
Exceptions:
an exception of type regex_error.
Definition at line 2174 of file regex.h.
References std::basic_string< _CharT, _Traits, _Alloc >::begin(), std::basic_string< _CharT, _Traits, _Alloc >::end(), and std::regex_search().
template<typename _Ch_type , typename _Rx_traits > void std::swap (basic_regex< _Ch_type, _Rx_traits > & __lhs, basic_regex< _Ch_type, _Rx_traits > & __rhs) [inline]
Swaps the contents of two regular expression objects.
Parameters:
__lhs First regular expression.
__rhs Second regular expression.
Definition at line 741 of file regex.h.
References std::basic_regex< _Ch_type, _Rx_traits >::swap().
template<typename _Bi_iter , typename _Allocator > void std::swap (match_results< _Bi_iter, _Allocator > & __lhs, match_results< _Bi_iter, _Allocator > & __rhs) [inline]
Swaps two match results.
Parameters:
__lhs A match result.
__rhs A match result.
The contents of the two match_results objects are swapped.
Definition at line 1886 of file regex.h.
References std::match_results< _Bi_iter, _Allocator >::swap().
template<typename _Ch_type > int std::regex_traits< _Ch_type >::value (_Ch_type __ch, int __radix) const
Converts a digit to an int.
Parameters:
__ch a character representing a digit.
__radix the radix if the numeric conversion (limited to 8, 10, or 16).
Returns:
the value represented by the digit __ch in base radix if the character __ch is a valid digit in base radix; otherwise returns -1.
Definition at line 321 of file regex.h.
References std::basic_ios< _CharT, _Traits >::fail(), std::hex(), and std::oct().